Released SPN*2*21 SEQ #21
Extracted from mail message
**KIDS**:SPN*2.0*21^

**INSTALL NAME**
SPN*2.0*21
"BLD",4730,0)
SPN*2.0*21^SPINAL CORD DYSFUNCTION^0^3031022^y
"BLD",4730,4,0)
^9.64PA^^0
"BLD",4730,"INI")
SPNPRI21
"BLD",4730,"KRN",0)
^9.67PA^8989.52^19
"BLD",4730,"KRN",.4,0)
.4
"BLD",4730,"KRN",.4,"NM",0)
^9.68A^^
"BLD",4730,"KRN",.401,0)
.401
"BLD",4730,"KRN",.402,0)
.402
"BLD",4730,"KRN",.403,0)
.403
"BLD",4730,"KRN",.5,0)
.5
"BLD",4730,"KRN",.84,0)
.84
"BLD",4730,"KRN",3.6,0)
3.6
"BLD",4730,"KRN",3.8,0)
3.8
"BLD",4730,"KRN",9.2,0)
9.2
"BLD",4730,"KRN",9.8,0)
9.8
"BLD",4730,"KRN",9.8,"NM",0)
^9.68A^14^14
"BLD",4730,"KRN",9.8,"NM",1,0)
SPNFMENU^^0^B9208049
"BLD",4730,"KRN",9.8,"NM",2,0)
SPNPRT13^^0^B22128448
"BLD",4730,"KRN",9.8,"NM",3,0)
SPNCTINB^^0^B11500024
"BLD",4730,"KRN",9.8,"NM",4,0)
SPNCTOUB^^0^B11481281
"BLD",4730,"KRN",9.8,"NM",5,0)
SPN21E^^0^B1529030
"BLD",4730,"KRN",9.8,"NM",6,0)
SPNPRI21^^0^B118828
"BLD",4730,"KRN",9.8,"NM",7,0)
SPNAGGE^^0^B40608516
"BLD",4730,"KRN",9.8,"NM",8,0)
SPNAGGPE^^0^B23872212
"BLD",4730,"KRN",9.8,"NM",9,0)
SPNAGGEU^^0^B7949619
"BLD",4730,"KRN",9.8,"NM",10,0)
SPNAGGC^^0^B80356092
"BLD",4730,"KRN",9.8,"NM",11,0)
SPNAGGPC^^0^B26838227
"BLD",4730,"KRN",9.8,"NM",12,0)
SPNCTSHO^^0^B13517194
"BLD",4730,"KRN",9.8,"NM",13,0)
SPNAGGI^^0^B62554694
"BLD",4730,"KRN",9.8,"NM",14,0)
SPNAGGU^^0^B39243002
"BLD",4730,"KRN",9.8,"NM","B","SPN21E",5)

"BLD",4730,"KRN",9.8,"NM","B","SPNAGGC",10)

"BLD",4730,"KRN",9.8,"NM","B","SPNAGGE",7)

"BLD",4730,"KRN",9.8,"NM","B","SPNAGGEU",9)

"BLD",4730,"KRN",9.8,"NM","B","SPNAGGI",13)

"BLD",4730,"KRN",9.8,"NM","B","SPNAGGPC",11)

"BLD",4730,"KRN",9.8,"NM","B","SPNAGGPE",8)

"BLD",4730,"KRN",9.8,"NM","B","SPNAGGU",14)

"BLD",4730,"KRN",9.8,"NM","B","SPNCTINB",3)

"BLD",4730,"KRN",9.8,"NM","B","SPNCTOUB",4)

"BLD",4730,"KRN",9.8,"NM","B","SPNCTSHO",12)

"BLD",4730,"KRN",9.8,"NM","B","SPNFMENU",1)

"BLD",4730,"KRN",9.8,"NM","B","SPNPRI21",6)

"BLD",4730,"KRN",9.8,"NM","B","SPNPRT13",2)

"BLD",4730,"KRN",19,0)
19
"BLD",4730,"KRN",19,"NM",0)
^9.68A^2^2
"BLD",4730,"KRN",19,"NM",1,0)
SPN REG INQ^^0
"BLD",4730,"KRN",19,"NM",2,0)
SPNL COORDINATOR^^2
"BLD",4730,"KRN",19,"NM","B","SPN REG INQ",1)

"BLD",4730,"KRN",19,"NM","B","SPNL COORDINATOR",2)

"BLD",4730,"KRN",19.1,0)
19.1
"BLD",4730,"KRN",101,0)
101
"BLD",4730,"KRN",409.61,0)
409.61
"BLD",4730,"KRN",771,0)
771
"BLD",4730,"KRN",870,0)
870
"BLD",4730,"KRN",8989.51,0)
8989.51
"BLD",4730,"KRN",8989.52,0)
8989.52
"BLD",4730,"KRN",8994,0)
8994
"BLD",4730,"KRN","B",.4,.4)

"BLD",4730,"KRN","B",.401,.401)

"BLD",4730,"KRN","B",.402,.402)

"BLD",4730,"KRN","B",.403,.403)

"BLD",4730,"KRN","B",.5,.5)

"BLD",4730,"KRN","B",.84,.84)

"BLD",4730,"KRN","B",3.6,3.6)

"BLD",4730,"KRN","B",3.8,3.8)

"BLD",4730,"KRN","B",9.2,9.2)

"BLD",4730,"KRN","B",9.8,9.8)

"BLD",4730,"KRN","B",19,19)

"BLD",4730,"KRN","B",19.1,19.1)

"BLD",4730,"KRN","B",101,101)

"BLD",4730,"KRN","B",409.61,409.61)

"BLD",4730,"KRN","B",771,771)

"BLD",4730,"KRN","B",870,870)

"BLD",4730,"KRN","B",8989.51,8989.51)

"BLD",4730,"KRN","B",8989.52,8989.52)

"BLD",4730,"KRN","B",8994,8994)

"BLD",4730,"PRE")
SPN21E
"BLD",4730,"QUES",0)
^9.62^^
"INI")
SPNPRI21
"KRN",19,2932262,-1)
2^2
"KRN",19,2932262,0)
SPNL COORDINATOR^SCD Coordinator Menu^^M^12748^^^^^^^^^1^
"KRN",19,2932262,10,0)
^19.01IP^12^12
"KRN",19,2932262,10,12,0)
2937884^INQR^11
"KRN",19,2932262,10,12,"^")
SPN REG INQ
"KRN",19,2932262,"U")
SCD COORDINATOR MENU
"KRN",19,2937884,-1)
0^1
"KRN",19,2937884,0)
SPN REG INQ^Inquire to a Registry Patient^^I^^^^^^^n^SPINAL CORD DYSFUNCTION
"KRN",19,2937884,1,0)
^^2^2^3031008^
"KRN",19,2937884,1,1,0)
This is a read-only (inquire) option providing a view of completed fields
"KRN",19,2937884,1,2,0)
in the SCD Registry for a particular patient.
"KRN",19,2937884,30)
SPNL(154,
"KRN",19,2937884,31)
AEMQ
"KRN",19,2937884,80)
SPNL(154,
"KRN",19,2937884,"U")
INQUIRE TO A REGISTRY PATIENT
"MBREQ")
0
"ORD",18,19)
19;18;;;OPT^XPDTA;OPTF1^XPDIA;OPTE1^XPDIA;OPTF2^XPDIA;;OPTDEL^XPDIA
"ORD",18,19,0)
OPTION
"PKG",418,-1)
1^1
"PKG",418,0)
SPINAL CORD DYSFUNCTION^SPN^SPINAL CORD DYSFUNCTION, FIELD COMPONENT
"PKG",418,20,0)
^9.402P^^
"PKG",418,22,0)
^9.49I^1^1
"PKG",418,22,1,0)
2.0^2961206^2970131^13722
"PKG",418,22,1,"PAH",1,0)
21^3031022
"PRE")
SPN21E
"QUES","XPF1",0)
Y
"QUES","XPF1","??")
^D REP^XPDH
"QUES","XPF1","A")
Shall I write over your |FLAG| File
"QUES","XPF1","B")
YES
"QUES","XPF1","M")
D XPF1^XPDIQ
"QUES","XPF2",0)
Y
"QUES","XPF2","??")
^D DTA^XPDH
"QUES","XPF2","A")
Want my data |FLAG| yours
"QUES","XPF2","B")
YES
"QUES","XPF2","M")
D XPF2^XPDIQ
"QUES","XPI1",0)
YO
"QUES","XPI1","??")
^D INHIBIT^XPDH
"QUES","XPI1","A")
Want KIDS to INHIBIT LOGONs during the install
"QUES","XPI1","B")
YES
"QUES","XPI1","M")
D XPI1^XPDIQ
"QUES","XPM1",0)
PO^VA(200,:EM
"QUES","XPM1","??")
^D MG^XPDH
"QUES","XPM1","A")
Enter the Coordinator for Mail Group '|FLAG|'
"QUES","XPM1","B")

"QUES","XPM1","M")
D XPM1^XPDIQ
"QUES","XPO1",0)
Y
"QUES","XPO1","??")
^D MENU^XPDH
"QUES","XPO1","A")
Want KIDS to Rebuild Menu Trees Upon Completion of Install
"QUES","XPO1","B")
YES
"QUES","XPO1","M")
D XPO1^XPDIQ
"QUES","XPZ1",0)
Y
"QUES","XPZ1","??")
^D OPT^XPDH
"QUES","XPZ1","A")
Want to DISABLE Scheduled Options, Menu Options, and Protocols
"QUES","XPZ1","B")
YES
"QUES","XPZ1","M")
D XPZ1^XPDIQ
"QUES","XPZ2",0)
Y
"QUES","XPZ2","??")
^D RTN^XPDH
"QUES","XPZ2","A")
Want to MOVE routines to other CPUs
"QUES","XPZ2","B")
NO
"QUES","XPZ2","M")
D XPZ2^XPDIQ
"RTN")
14
"RTN","SPN21E")
0^5^B1529030
"RTN","SPN21E",1,0)
SPN21E ;SD/CM- ENVIRONMENT CHECK FOR SPN*2.0*21;8/20/2003
"RTN","SPN21E",2,0)
 ;;2.0;Spinal Cord Dysfunction;**21**;01/02/97
"RTN","SPN21E",3,0)
 ;
"RTN","SPN21E",4,0)
EN ;ENTRY
"RTN","SPN21E",5,0)
 N ROU,TEST,VER,X,ZAP,P20
"RTN","SPN21E",6,0)
 S ROU="SPNFMENU"
"RTN","SPN21E",7,0)
 D CHK
"RTN","SPN21E",8,0)
 I $G(ZAP)=1 S XPDABORT=2 W !,"***SPN*2.0*21 ABORTED***",! D EXIT Q
"RTN","SPN21E",9,0)
 I $G(ZAP)=1 S XPDABORT=2 W !,"***SPN*2.0*21 ABORTED***",! D EXIT Q
"RTN","SPN21E",10,0)
 W !,"***Environment is fine***",!
"RTN","SPN21E",11,0)
 K ROU,TEST,VER,ZAP,P20
"RTN","SPN21E",12,0)
 Q
"RTN","SPN21E",13,0)
CHK ;CHECK FOR PATCH SPN*2*20
"RTN","SPN21E",14,0)
 S X="S TEST=$T(+2^"_ROU_")" X X
"RTN","SPN21E",15,0)
 S VER=$P(TEST,";",3),P20=$P(TEST,";",5)
"RTN","SPN21E",16,0)
 I VER="" W !,"This account is missing some SPN routines!" S ZAP=1 Q
"RTN","SPN21E",17,0)
 I VER'[2 W !,"This is not the current version of Spinal Cord!" S ZAP=1 Q
"RTN","SPN21E",18,0)
 I P20'[20 W !,"Routine: ",ROU," is missing patch SPN*2*20" S ZAP=1
"RTN","SPN21E",19,0)
 Q
"RTN","SPN21E",20,0)
EXIT ;
"RTN","SPN21E",21,0)
 K ROU,TEST,VER,ZAP,P20
"RTN","SPN21E",22,0)
 Q
"RTN","SPNAGGC")
0^10^B80356092
"RTN","SPNAGGC",1,0)
SPNAGGC ;SD/CM- AGGREGATE CONT OF CARE OUTCOMES REPORT; 9-17-2003
"RTN","SPNAGGC",2,0)
 ;;2.0;Spinal Cord Dysfunction;**20,21**;01/02/97
"RTN","SPNAGGC",3,0)
 ;
"RTN","SPNAGGC",4,0)
EN ;
"RTN","SPNAGGC",5,0)
 S U="^"
"RTN","SPNAGGC",6,0)
 D INPT^SPNAGGU
"RTN","SPNAGGC",7,0)
 S (LDATE,TDATE,LORCALL,MAX1,MAX2)=0
"RTN","SPNAGGC",8,0)
PARAMS ;
"RTN","SPNAGGC",9,0)
 D CED
"RTN","SPNAGGC",10,0)
 G:SPNLEXIT=1 EXIT
"RTN","SPNAGGC",11,0)
DEVICE ;
"RTN","SPNAGGC",12,0)
 S ZTSAVE("SPN*")="",ZTSAVE("B*")="",ZTSAVE("AGE*")="",ZTSAVE("MIN*")=""
"RTN","SPNAGGC",13,0)
 S ZTSAVE("MAX*")="",ZTSAVE("LOR*")="",ZTSAVE("TF*")="",ZTSAVE("SEX*")=""
"RTN","SPNAGGC",14,0)
 S ZTSAVE("SL*")="",ZTSAVE("COMD*")="",ZTSAVE("CARETYP")=""
"RTN","SPNAGGC",15,0)
 S ZTSAVE("EDATE")="",ZTSAVE("BDATE")="",ZTSAVE("LINE")="",ZTSAVE("I")=""
"RTN","SPNAGGC",16,0)
 S ZTSAVE("ASIA*")="",ZTSAVE("LDATE")="",ZTSAVE("TDATE")=""
"RTN","SPNAGGC",17,0)
 W !
"RTN","SPNAGGC",18,0)
 D DEVICE^SPNPRTMT("PRINT^SPNAGGPC","Continuum of Care Outcomes",.ZTSAVE) Q:SPNLEXIT
"RTN","SPNAGGC",19,0)
 I SPNIO="Q" D EXIT Q  ; Print was queued
"RTN","SPNAGGC",20,0)
 I IO'="" D PRINT^SPNAGGPC D EXIT Q  ; Print not queued
"RTN","SPNAGGC",21,0)
 D EXIT
"RTN","SPNAGGC",22,0)
 Q
"RTN","SPNAGGC",23,0)
CED ;
"RTN","SPNAGGC",24,0)
 D DATE^SPNAGGA
"RTN","SPNAGGC",25,0)
 Q
"RTN","SPNAGGC",26,0)
OIEN ;
"RTN","SPNAGGC",27,0)
 S SPNPD1=0 F  S SPNPD1=$O(^SPNL(154.1,"B",SPNPD0,SPNPD1)) Q:'+SPNPD1  D DIAGCAT
"RTN","SPNAGGC",28,0)
 Q
"RTN","SPNAGGC",29,0)
DIAGCAT ;
"RTN","SPNAGGC",30,0)
 S SPNDCS=0,SPNDCM=0,SPNDCP=0,SPNDCL=0
"RTN","SPNAGGC",31,0)
 Q:'$D(^SPNL(154.1,SPNPD1,0))
"RTN","SPNAGGC",32,0)
 Q:'$D(^SPNL(154.1,SPNPD1,"ASIA"))
"RTN","SPNAGGC",33,0)
 Q:'$D(^SPNL(154.1,SPNPD1,8))
"RTN","SPNAGGC",34,0)
 Q:$P(^SPNL(154.1,SPNPD1,0),U,2)'=3
"RTN","SPNAGGC",35,0)
 Q:$P(^SPNL(154.1,SPNPD1,8),U,3)'=CARETYP
"RTN","SPNAGGC",36,0)
 Q:$P($G(^SPNL(154.1,SPNPD1,0)),U,4)<BDATE!($P($G(^SPNL(154.1,SPNPD1,0)),U,4)>EDATE)
"RTN","SPNAGGC",37,0)
 Q:$P($G(^SPNL(154.1,SPNPD1,0)),U,1)=SPNNODUP
"RTN","SPNAGGC",38,0)
 S SPNNODUP=$P($G(^SPNL(154.1,SPNPD1,0)),U,1)
"RTN","SPNAGGC",39,0)
 S ASIAONE=$P($G(^SPNL(154.1,SPNPD1,"ASIA")),U,1),ASIAFRTN=$P($G(^SPNL(154.1,SPNPD1,"ASIA")),U,14)
"RTN","SPNAGGC",40,0)
 I "ABC"[ASIAONE,ASIAFRTN<5 S SPNDCS=1
"RTN","SPNAGGC",41,0)
 I "ABC"[ASIAONE,ASIAFRTN<5 S SPNLSTDT="S"
"RTN","SPNAGGC",42,0)
 I "ABC"[ASIAONE&(ASIAFRTN>4)&(ASIAFRTN<9) S SPNDCM=1
"RTN","SPNAGGC",43,0)
 I "ABC"[ASIAONE&(ASIAFRTN>4)&(ASIAFRTN<9) S SPNLSTDT="M"
"RTN","SPNAGGC",44,0)
 I "ABC"[ASIAONE,ASIAFRTN>8 S SPNDCP=1
"RTN","SPNAGGC",45,0)
 I "ABC"[ASIAONE,ASIAFRTN>8 S SPNLSTDT="P"
"RTN","SPNAGGC",46,0)
 I ASIAONE="D",ASIAFRTN<31 S SPNDCL=1
"RTN","SPNAGGC",47,0)
 I ASIAONE="D",ASIAFRTN<31 S SPNLSTDT="L"
"RTN","SPNAGGC",48,0)
 I SPNLSTDT="S" S SPNSEVC=SPNSEVC+1
"RTN","SPNAGGC",49,0)
 I SPNLSTDT="M" S SPNMODC=SPNMODC+1
"RTN","SPNAGGC",50,0)
 I SPNLSTDT="P" S SPNPARC=SPNPARC+1
"RTN","SPNAGGC",51,0)
 I SPNLSTDT="L" S SPNLOWC=SPNLOWC+1
"RTN","SPNAGGC",52,0)
 S SPNDIAGC=SPNDIAGC+1
"RTN","SPNAGGC",53,0)
 ;
"RTN","SPNAGGC",54,0)
AGE ;
"RTN","SPNAGGC",55,0)
 S AGECALL=$$GET1^DIQ(154.1,SPNPD1,999.025)
"RTN","SPNAGGC",56,0)
 I +SPNDCS S SPNAGES=SPNAGES+AGECALL,AGESC=AGESC+1 S:AGESC=1 BMAS=AGECALL S MINAGES=$S(AGECALL<BMAS:AGECALL,1:BMAS)
"RTN","SPNAGGC",57,0)
 I +SPNDCS S:AGESC=1 BHAS=AGECALL S MAXAGES=$S(AGECALL>BHAS:AGECALL,1:BHAS)
"RTN","SPNAGGC",58,0)
 I +SPNDCM S SPNAGEM=SPNAGEM+AGECALL,AGEMC=AGEMC+1 S:AGEMC=1 BMAM=AGECALL S MINAGEM=$S(AGECALL<BMAM:AGECALL,1:BMAM)
"RTN","SPNAGGC",59,0)
 I +SPNDCM S:AGEMC=1 BHAM=AGECALL S MAXAGEM=$S(AGECALL>BHAM:AGECALL,1:BHAM)
"RTN","SPNAGGC",60,0)
 I +SPNDCP S SPNAGEP=SPNAGEP+AGECALL,AGEPC=AGEPC+1 S:AGEPC=1 BMAP=AGECALL S MINAGEP=$S(AGECALL<BMAP:AGECALL,1:BMAP)
"RTN","SPNAGGC",61,0)
 I +SPNDCP S:AGEPC=1 BHAP=AGECALL S MAXAGEP=$S(AGECALL>BHAP:AGECALL,1:BHAP)
"RTN","SPNAGGC",62,0)
 I +SPNDCL S SPNAGEL=SPNAGEL+AGECALL,AGELC=AGELC+1 S:AGELC=1 BMAL=AGECALL S MINAGEL=$S(AGECALL<BMAL:AGECALL,1:BMAL)
"RTN","SPNAGGC",63,0)
 I +SPNDCL S:AGELC=1 BHAL=AGECALL S MAXAGEL=$S(AGECALL>BHAL:AGECALL,1:BHAL)
"RTN","SPNAGGC",64,0)
 S AGEL=$S((MINAGES<MINAGEM)&(MINAGES<MINAGEP)&(MINAGES<MINAGEL):MINAGES,(MINAGEM<MINAGEP)&(MINAGEM<MINAGEL):MINAGEM,MINAGEP<MINAGEL:MINAGEP,1:MINAGEL)
"RTN","SPNAGGC",65,0)
 S AGEH=$S((MAXAGES>MAXAGEM)&(MAXAGES>MAXAGEP)&(MAXAGES>MAXAGEL):MAXAGES,(MAXAGEM>MAXAGEP)&(MAXAGEM>MAXAGEL):MAXAGEM,MAXAGEP>MAXAGEL:MAXAGEP,1:MAXAGEL)
"RTN","SPNAGGC",66,0)
 ;
"RTN","SPNAGGC",67,0)
SEX ;
"RTN","SPNAGGC",68,0)
 S SEXCALL=$P(^DPT($P(^SPNL(154.1,SPNPD1,0),U,1),0),U,2)
"RTN","SPNAGGC",69,0)
 I +SPNDCS,SEXCALL="M" S SPNSEXS=SPNSEXS+1
"RTN","SPNAGGC",70,0)
 I +SPNDCM,SEXCALL="M" S SPNSEXM=SPNSEXM+1
"RTN","SPNAGGC",71,0)
 I +SPNDCP,SEXCALL="M" S SPNSEXP=SPNSEXP+1
"RTN","SPNAGGC",72,0)
 I +SPNDCL,SEXCALL="M" S SPNSEXL=SPNSEXL+1
"RTN","SPNAGGC",73,0)
LOR ;
"RTN","SPNAGGC",74,0)
 I +SPNDCS D STATS I +LORRN S SPNLORS=SPNLORS+LORCALL,LORSC=LORSC+1
"RTN","SPNAGGC",75,0)
 I +SPNDCS S ^TMP($J,"SPNLSNS",SPNPD1)=LORCALL S MINLORS=$$MINLOS(SPNPD1)
"RTN","SPNAGGC",76,0)
 I +SPNDCS S ^TMP($J,"SPNLSXS",SPNPD1)=LORCALL S MAXLORS=$$MAXLOS(SPNPD1)
"RTN","SPNAGGC",77,0)
 I +SPNDCS&(+LORRN)&(+TFSRN) S TFS=TFSCALL,TFF=LOR5CALL,TFCUMS=TFCUMS+(TFF-TFS),TFCS=TFCS+1
"RTN","SPNAGGC",78,0)
 I +SPNDCS&(+LORRN)&(+TFGRN) S TFG=TFGCALL,TFF=LOR5CALL,TFGCUMS=TFGCUMS+(TFF-TFG),TFGCS=TFGCS+1
"RTN","SPNAGGC",79,0)
CDSEV I +SPNDCS&(+LORRN)&($P($G(^SPNL(154.1,LORRN,0)),U,24)<5) S COMDISS=COMDISS+1
"RTN","SPNAGGC",80,0)
FRETSEV I +SPNDCS&(+LORRN)&(+TFURN) S TFU=TFUCALL,TFF=LOR5CALL,TFUCUMS=TFUCUMS+(TFU-TFF),TFUCS=TFUCS+1
"RTN","SPNAGGC",81,0)
SLSEV I +SPNDCS&(+SLSRN)&(+SLFRN) S SLS=SLSCALL,SLF=SLFCALL,SLCUMS=SLCUMS+(SLF-SLS),SLCS=SLCS+1
"RTN","SPNAGGC",82,0)
SLUSEV I +SPNDCS&(+SLFRN)&(+SLURN) S SLU=SLUCALL,SLF=SLFCALL,SLUCUMS=SLUCUMS+(SLU-SLF),SLUCS=SLUCS+1
"RTN","SPNAGGC",83,0)
 I +SPNDCM D STATS I +LORRN S SPNLORM=SPNLORM+LORCALL,LORMC=LORMC+1
"RTN","SPNAGGC",84,0)
 I +SPNDCM S ^TMP($J,"SPNLSNM",SPNPD1)=LORCALL S MINLORM=$$MINLOM(SPNPD1)
"RTN","SPNAGGC",85,0)
 I +SPNDCM S ^TMP($J,"SPNLSXM",SPNPD1)=LORCALL S MAXLORM=$$MAXLOM(SPNPD1)
"RTN","SPNAGGC",86,0)
 I +SPNDCM&(+LORRN)&(+TFSRN) S TFS=TFSCALL,TFF=LOR5CALL,TFCUMM=TFCUMM+(TFF-TFS),TFCM=TFCM+1
"RTN","SPNAGGC",87,0)
 I +SPNDCM&(+LORRN)&(+TFGRN) S TFG=TFGCALL,TFF=LOR5CALL,TFGCUMM=TFGCUMM+(TFF-TFG),TFGCM=TFGCM+1
"RTN","SPNAGGC",88,0)
CDMOD I +SPNDCM&(+LORRN)&($P($G(^SPNL(154.1,LORRN,0)),U,24)<5) S COMDISM=COMDISM+1
"RTN","SPNAGGC",89,0)
FRETMOD I +SPNDCM&(+LORRN)&(+TFURN) S TFU=TFUCALL,TFF=LOR5CALL,TFUCUMM=TFUCUMM+(TFU-TFF),TFUCM=TFUCM+1
"RTN","SPNAGGC",90,0)
SLMOD I +SPNDCM&(+SLSRN)&(+SLFRN) S SLS=SLSCALL,SLF=SLFCALL,SLCUMM=SLCUMM+(SLF-SLS),SLCM=SLCM+1
"RTN","SPNAGGC",91,0)
SLUMOD I +SPNDCM&(+SLFRN)&(+SLURN) S SLU=SLUCALL,SLF=SLFCALL,SLUCUMM=SLUCUMM+(SLU-SLF),SLUCM=SLUCM+1
"RTN","SPNAGGC",92,0)
 I +SPNDCP D STATS I +LORRN S SPNLORP=SPNLORP+LORCALL,LORPC=LORPC+1
"RTN","SPNAGGC",93,0)
 I +SPNDCP S ^TMP($J,"SPNLSNP",SPNPD1)=LORCALL S MINLORP=$$MINLOP(SPNPD1)
"RTN","SPNAGGC",94,0)
 I +SPNDCP S ^TMP($J,"SPNLSXP",SPNPD1)=LORCALL S MAXLORP=$$MAXLOP(SPNPD1)
"RTN","SPNAGGC",95,0)
 I +SPNDCP&(+LORRN)&(+TFSRN) S TFS=TFSCALL,TFF=LOR5CALL,TFCUMP=TFCUMP+(TFF-TFS),TFCP=TFCP+1
"RTN","SPNAGGC",96,0)
 I +SPNDCP&(+LORRN)&(+TFGRN) S TFG=TFGCALL,TFF=LOR5CALL,TFGCUMP=TFGCUMP+(TFF-TFG),TFGCP=TFGCP+1
"RTN","SPNAGGC",97,0)
CDPARA I +SPNDCP&(+LORRN)&($P($G(^SPNL(154.1,LORRN,0)),U,24)<5) S COMDISP=COMDISP+1
"RTN","SPNAGGC",98,0)
FRETPAR I +SPNDCP&(+LORRN)&(+TFURN) S TFU=TFUCALL,TFF=LOR5CALL,TFUCUMP=TFUCUMP+(TFU-TFF),TFUCP=TFUCP+1
"RTN","SPNAGGC",99,0)
SLPAR I +SPNDCP&(+SLSRN)&(+SLFRN) S SLS=SLSCALL,SLF=SLFCALL,SLCUMP=SLCUMP+(SLF-SLS),SLCP=SLCP+1
"RTN","SPNAGGC",100,0)
SLUPAR I +SPNDCP&(+SLFRN)&(+SLURN) S SLU=SLUCALL,SLF=SLFCALL,SLUCUMP=SLUCUMP+(SLU-SLF),SLUCP=SLUCP+1
"RTN","SPNAGGC",101,0)
 I +SPNDCL D STATS I +LORRN S SPNLORL=SPNLORL+LORCALL,LORLC=LORLC+1
"RTN","SPNAGGC",102,0)
 I +SPNDCL S ^TMP($J,"SPNLSNL",SPNPD1)=LORCALL S MINLORL=$$MINLOL(SPNPD1)
"RTN","SPNAGGC",103,0)
 I +SPNDCL S ^TMP($J,"SPNLSXL",SPNPD1)=LORCALL S MAXLORL=$$MAXLOL(SPNPD1)
"RTN","SPNAGGC",104,0)
 I +SPNDCL&(+LORRN)&(+TFSRN) S TFS=TFSCALL,TFF=LOR5CALL,TFCUML=TFCUML+(TFF-TFS),TFCL=TFCL+1
"RTN","SPNAGGC",105,0)
 I +SPNDCL&(+LORRN)&(+TFGRN) S TFG=TFGCALL,TFF=LOR5CALL,TFGCUML=TFGCUML+(TFF-TFG),TFGCL=TFGCL+1
"RTN","SPNAGGC",106,0)
CDLOW I +SPNDCL&(+LORRN)&($P($G(^SPNL(154.1,LORRN,0)),U,24)<5) S COMDISL=COMDISL+1
"RTN","SPNAGGC",107,0)
FRETLOW I +SPNDCL&(+LORRN)&(+TFURN) S TFU=TFUCALL,TFF=LOR5CALL,TFUCUML=TFUCUML+(TFU-TFF),TFUCL=TFUCL+1
"RTN","SPNAGGC",108,0)
SLLOW I +SPNDCL&(+SLSRN)&(+SLFRN) S SLS=SLSCALL,SLF=SLFCALL,SLCUML=SLCUML+(SLF-SLS),SLCL=SLCL+1
"RTN","SPNAGGC",109,0)
SLULOW I +SPNDCL&(+SLFRN)&(+SLURN) S SLU=SLUCALL,SLF=SLFCALL,SLUCUML=SLUCUML+(SLU-SLF),SLUCL=SLUCL+1
"RTN","SPNAGGC",110,0)
 S LORL=$S((MINLORS<MINLORM)&(MINLORS<MINLORP)&(MINLORS<MINLORL):MINLORS,(MINLORM<MINLORP)&(MINLORM<MINLORL):MINLORM,MINLORP<MINLORL:MINLORP,1:MINLORL)
"RTN","SPNAGGC",111,0)
 S LORH=$S((MAXLORS>MAXLORM)&(MAXLORS>MAXLORP)&(MAXLORS>MAXLORL):MAXLORS,(MAXLORM>MAXLORP)&(MAXLORM>MAXLORL):MAXLORM,MAXLORP>MAXLORL:MAXLORP,1:MAXLORL)
"RTN","SPNAGGC",112,0)
 Q
"RTN","SPNAGGC",113,0)
 ;
"RTN","SPNAGGC",114,0)
STATS ;
"RTN","SPNAGGC",115,0)
 S LORRN=0,TFSRN=0,TFGRN=0,TFURN=0,SLSRN=0,SLFRN=0,SLURN=0,LDATE=0,TDATE=0,LORCALL=0
"RTN","SPNAGGC",116,0)
 S V=SPNPD1 F  S V=$O(^SPNL(154.1,"B",SPNPD0,V)) Q:'+V  D GETLOR
"RTN","SPNAGGC",117,0)
 S LDATE=$P($G(^SPNL(154.1,LORRN,0)),U,4),TDATE=$P($G(^SPNL(154.1,TFSRN,0)),U,4)
"RTN","SPNAGGC",118,0)
 I +LDATE,(+TDATE) S LORCALL=$$FMDIFF^XLFDT(LDATE,TDATE)
"RTN","SPNAGGC",119,0)
 S LOR5CALL=$$GET1^DIQ(154.1,LORRN,999.05)
"RTN","SPNAGGC",120,0)
 S TFSCALL=$$GET1^DIQ(154.1,TFSRN,999.05)
"RTN","SPNAGGC",121,0)
 S TFGCALL=$$GET1^DIQ(154.1,TFGRN,999.05)
"RTN","SPNAGGC",122,0)
 S TFUCALL=$$GET1^DIQ(154.1,TFURN,999.05)
"RTN","SPNAGGC",123,0)
 S SLSCALL=$P($G(^SPNL(154.1,SLSRN,"SCORE")),U,1)
"RTN","SPNAGGC",124,0)
 S SLFCALL=$P($G(^SPNL(154.1,SLFRN,"SCORE")),U,1)
"RTN","SPNAGGC",125,0)
 S SLUCALL=$P($G(^SPNL(154.1,SLURN,"SCORE")),U,1)
"RTN","SPNAGGC",126,0)
 Q
"RTN","SPNAGGC",127,0)
GETLOR ;get Rec No. for LOR,TFS (TFF same RN as LOR), etc
"RTN","SPNAGGC",128,0)
 ;LORRN is ~TFDRN
"RTN","SPNAGGC",129,0)
 Q:'$D(^SPNL(154.1,V,0))
"RTN","SPNAGGC",130,0)
 Q:'+$P($G(^SPNL(154.1,V,2)),U,17)
"RTN","SPNAGGC",131,0)
 Q:$P($G(^SPNL(154.1,V,8)),U,3)'=CARETYP
"RTN","SPNAGGC",132,0)
 Q:$P($G(^SPNL(154.1,V,0)),U,4)<BDATE!($P($G(^SPNL(154.1,V,0)),U,4)>EDATE)
"RTN","SPNAGGC",133,0)
 I $P(^SPNL(154.1,V,2),U,17)=12,($P(^SPNL(154.1,V,0),U,2)=2) S TFSRN=V
"RTN","SPNAGGC",134,0)
 I $P(^SPNL(154.1,V,2),U,17)=13,($P(^SPNL(154.1,V,0),U,2)=2) S TFGRN=V
"RTN","SPNAGGC",135,0)
 I $P(^SPNL(154.1,V,2),U,17)=15,($P(^SPNL(154.1,V,0),U,2)=2) S LORRN=V
"RTN","SPNAGGC",136,0)
 I $P(^SPNL(154.1,V,2),U,17)=16,($P(^SPNL(154.1,V,0),U,2)=2) S TFURN=V
"RTN","SPNAGGC",137,0)
 I $P(^SPNL(154.1,V,2),U,17)=12,($P(^SPNL(154.1,V,0),U,2)=6) S SLSRN=V
"RTN","SPNAGGC",138,0)
 I $P(^SPNL(154.1,V,2),U,17)=15,($P(^SPNL(154.1,V,0),U,2)=6) S SLFRN=V
"RTN","SPNAGGC",139,0)
 I $P(^SPNL(154.1,V,2),U,17)=16,($P(^SPNL(154.1,V,0),U,2)=6) S SLURN=V
"RTN","SPNAGGC",140,0)
 Q
"RTN","SPNAGGC",141,0)
MAXLOS(SPNPD1) ;
"RTN","SPNAGGC",142,0)
 S MAX1=0
"RTN","SPNAGGC",143,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLSXS",X)) Q:'+X  D
"RTN","SPNAGGC",144,0)
 .Q:'$D(^TMP($J,"SPNLSXS",X))
"RTN","SPNAGGC",145,0)
 .S MAX2=$P(^TMP($J,"SPNLSXS",X),U,1)
"RTN","SPNAGGC",146,0)
 .I MAX2>MAX1 S MAX1=MAX2
"RTN","SPNAGGC",147,0)
 .Q
"RTN","SPNAGGC",148,0)
 Q MAX1
"RTN","SPNAGGC",149,0)
MAXLOM(SPNPD1) ;
"RTN","SPNAGGC",150,0)
 S MAX1=0
"RTN","SPNAGGC",151,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLSXM",X)) Q:'+X  D
"RTN","SPNAGGC",152,0)
 .Q:'$D(^TMP($J,"SPNLSXM",X))
"RTN","SPNAGGC",153,0)
 .S MAX2=$P(^TMP($J,"SPNLSXM",X),U,1)
"RTN","SPNAGGC",154,0)
 .I MAX2>MAX1 S MAX1=MAX2
"RTN","SPNAGGC",155,0)
 .Q
"RTN","SPNAGGC",156,0)
 Q MAX1
"RTN","SPNAGGC",157,0)
MAXLOP(SPNPD1) ;
"RTN","SPNAGGC",158,0)
 S MAX1=0
"RTN","SPNAGGC",159,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLSXP",X)) Q:'+X  D
"RTN","SPNAGGC",160,0)
 .Q:'$D(^TMP($J,"SPNLSXP",X))
"RTN","SPNAGGC",161,0)
 .S MAX2=$P(^TMP($J,"SPNLSXP",X),U,1)
"RTN","SPNAGGC",162,0)
 .I MAX2>MAX1 S MAX1=MAX2
"RTN","SPNAGGC",163,0)
 .Q
"RTN","SPNAGGC",164,0)
 Q MAX1
"RTN","SPNAGGC",165,0)
MAXLOL(SPNPD1) ;
"RTN","SPNAGGC",166,0)
 S MAX1=0
"RTN","SPNAGGC",167,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLSXL",X)) Q:'+X  D
"RTN","SPNAGGC",168,0)
 .Q:'$D(^TMP($J,"SPNLSXL",X))
"RTN","SPNAGGC",169,0)
 .S MAX2=$P(^TMP($J,"SPNLSXL",X),U,1)
"RTN","SPNAGGC",170,0)
 .I MAX2>MAX1 S MAX1=MAX2
"RTN","SPNAGGC",171,0)
 .Q
"RTN","SPNAGGC",172,0)
 Q MAX1
"RTN","SPNAGGC",173,0)
MINLOS(SPNPD1) ;
"RTN","SPNAGGC",174,0)
 S MAX1=LORCALL
"RTN","SPNAGGC",175,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLSNS",X)) Q:'+X  D
"RTN","SPNAGGC",176,0)
 .Q:'$D(^TMP($J,"SPNLSNS",X))
"RTN","SPNAGGC",177,0)
 .S MAX2=$P(^TMP($J,"SPNLSNS",X),U,1)
"RTN","SPNAGGC",178,0)
 .I MAX2<MAX1 S MAX1=MAX2
"RTN","SPNAGGC",179,0)
 .Q
"RTN","SPNAGGC",180,0)
 Q MAX1
"RTN","SPNAGGC",181,0)
MINLOM(SPNPD1) ;
"RTN","SPNAGGC",182,0)
 S MAX1=LORCALL
"RTN","SPNAGGC",183,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLSNM",X)) Q:'+X  D
"RTN","SPNAGGC",184,0)
 .Q:'$D(^TMP($J,"SPNLSNM",X))
"RTN","SPNAGGC",185,0)
 .S MAX2=$P(^TMP($J,"SPNLSNM",X),U,1)
"RTN","SPNAGGC",186,0)
 .I MAX2<MAX1 S MAX1=MAX2
"RTN","SPNAGGC",187,0)
 .Q
"RTN","SPNAGGC",188,0)
 Q MAX1
"RTN","SPNAGGC",189,0)
MINLOP(SPNPD1) ;
"RTN","SPNAGGC",190,0)
 S MAX1=LORCALL
"RTN","SPNAGGC",191,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLSNP",X)) Q:'+X  D
"RTN","SPNAGGC",192,0)
 .Q:'$D(^TMP($J,"SPNLSNP",X))
"RTN","SPNAGGC",193,0)
 .S MAX2=$P(^TMP($J,"SPNLSNP",X),U,1)
"RTN","SPNAGGC",194,0)
 .I MAX2<MAX1 S MAX1=MAX2
"RTN","SPNAGGC",195,0)
 .Q
"RTN","SPNAGGC",196,0)
 Q MAX1
"RTN","SPNAGGC",197,0)
MINLOL(SPNPD1) ;
"RTN","SPNAGGC",198,0)
 S MAX1=LORCALL
"RTN","SPNAGGC",199,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLSNL",X)) Q:'+X  D
"RTN","SPNAGGC",200,0)
 .Q:'$D(^TMP($J,"SPNLSNL",X))
"RTN","SPNAGGC",201,0)
 .S MAX2=$P(^TMP($J,"SPNLSNL",X),U,1)
"RTN","SPNAGGC",202,0)
 .I MAX2<MAX1 S MAX1=MAX2
"RTN","SPNAGGC",203,0)
 .Q
"RTN","SPNAGGC",204,0)
 Q MAX1
"RTN","SPNAGGC",205,0)
EXIT ;
"RTN","SPNAGGC",206,0)
 D EXIT^SPNAGGU
"RTN","SPNAGGC",207,0)
 K LDATE,TDATE,MAX1,MAX2
"RTN","SPNAGGC",208,0)
 K ^TMP($J,"SPNLSXS"),^TMP($J,"SPNLSXM"),^TMP($J,"SPNLSXP"),^TMP($J,"SPNLSXL")
"RTN","SPNAGGC",209,0)
 K ^TMP($J,"SPNLSNS"),^TMP($J,"SPNLSNM"),^TMP($J,"SPNLSNP"),^TMP($J,"SPNLSNL")
"RTN","SPNAGGC",210,0)
 Q
"RTN","SPNAGGE")
0^7^B40608516
"RTN","SPNAGGE",1,0)
SPNAGGE ;SD/CM- AGGREGATE ANUAL EVAL OUTCOMES REPORT; 2-21-2003
"RTN","SPNAGGE",2,0)
 ;;2.0;Spinal Cord Dysfunction;**20,21**;01/02/97
"RTN","SPNAGGE",3,0)
 ;
"RTN","SPNAGGE",4,0)
EN ;
"RTN","SPNAGGE",5,0)
 S U="^"
"RTN","SPNAGGE",6,0)
 D SET^SPNAGGEU
"RTN","SPNAGGE",7,0)
PARAMS ;
"RTN","SPNAGGE",8,0)
 D CED
"RTN","SPNAGGE",9,0)
 G:SPNLEXIT=1 EXIT
"RTN","SPNAGGE",10,0)
DEVICE ;
"RTN","SPNAGGE",11,0)
 S ZTSAVE("SPN*")="",ZTSAVE("B*")="",ZTSAVE("AGE*")="",ZTSAVE("MIN*")=""
"RTN","SPNAGGE",12,0)
 S ZTSAVE("MAX*")="",ZTSAVE("LOR*")="",ZTSAVE("TF*")="",ZTSAVE("SEX*")=""
"RTN","SPNAGGE",13,0)
 S ZTSAVE("SL*")="",ZTSAVE("CARETYP")="",ZTSAVE("MF*")=""
"RTN","SPNAGGE",14,0)
 S ZTSAVE("EDATE")="",ZTSAVE("BDATE")="",ZTSAVE("LINE")="",ZTSAVE("I")=""
"RTN","SPNAGGE",15,0)
 S ZTSAVE("ASIA*")="",ZTSAVE("C*")=""
"RTN","SPNAGGE",16,0)
 W !
"RTN","SPNAGGE",17,0)
 D DEVICE^SPNPRTMT("PRINT^SPNAGGPE","Annual Eval Outcomes",.ZTSAVE) Q:SPNLEXIT
"RTN","SPNAGGE",18,0)
 I SPNIO="Q" D EXIT Q  ; Print was queued
"RTN","SPNAGGE",19,0)
 I IO'="" D PRINT^SPNAGGPE D EXIT Q  ; Print was not queued
"RTN","SPNAGGE",20,0)
 D EXIT
"RTN","SPNAGGE",21,0)
 Q
"RTN","SPNAGGE",22,0)
CED ;date range for Record Date
"RTN","SPNAGGE",23,0)
 D DATE^SPNAGGA
"RTN","SPNAGGE",24,0)
 Q
"RTN","SPNAGGE",25,0)
OIEN ;
"RTN","SPNAGGE",26,0)
 S SPNPD1=0 F  S SPNPD1=$O(^SPNL(154.1,"B",SPNPD0,SPNPD1)) Q:'+SPNPD1  D DIAGCAT
"RTN","SPNAGGE",27,0)
 Q
"RTN","SPNAGGE",28,0)
DIAGCAT ;get ASIA Highest Neuro Level and ASIA Imp Scale
"RTN","SPNAGGE",29,0)
 S SPNDCS=0,SPNDCM=0,SPNDCP=0,SPNDCL=0
"RTN","SPNAGGE",30,0)
 Q:'$D(^SPNL(154.1,SPNPD1,0))
"RTN","SPNAGGE",31,0)
 Q:'$D(^SPNL(154.1,SPNPD1,"ASIA"))
"RTN","SPNAGGE",32,0)
 Q:'$D(^SPNL(154.1,SPNPD1,8))
"RTN","SPNAGGE",33,0)
 Q:$P(^SPNL(154.1,SPNPD1,0),U,2)'=3
"RTN","SPNAGGE",34,0)
 Q:$P(^SPNL(154.1,SPNPD1,8),U,3)'=CARETYP
"RTN","SPNAGGE",35,0)
 Q:$P($G(^SPNL(154.1,SPNPD1,0)),U,4)<BDATE!($P($G(^SPNL(154.1,SPNPD1,0)),U,4)>EDATE)
"RTN","SPNAGGE",36,0)
 Q:$P($G(^SPNL(154.1,SPNPD1,0)),U,1)=SPNNODUP
"RTN","SPNAGGE",37,0)
 S SPNNODUP=$P($G(^SPNL(154.1,SPNPD1,0)),U,1)
"RTN","SPNAGGE",38,0)
 S ASIAONE=$P($G(^SPNL(154.1,SPNPD1,"ASIA")),U,1),ASIAFRTN=$P($G(^SPNL(154.1,SPNPD1,"ASIA")),U,14)
"RTN","SPNAGGE",39,0)
 I "ABC"[ASIAONE,ASIAFRTN<5 S SPNDCS=1
"RTN","SPNAGGE",40,0)
 I "ABC"[ASIAONE,ASIAFRTN<5 S SPNLSTDT="S"
"RTN","SPNAGGE",41,0)
 I "ABC"[ASIAONE&(ASIAFRTN>4)&(ASIAFRTN<9) S SPNDCM=1
"RTN","SPNAGGE",42,0)
 I "ABC"[ASIAONE&(ASIAFRTN>4)&(ASIAFRTN<9) S SPNLSTDT="M"
"RTN","SPNAGGE",43,0)
 I "ABC"[ASIAONE,ASIAFRTN>8 S SPNDCP=1
"RTN","SPNAGGE",44,0)
 I "ABC"[ASIAONE,ASIAFRTN>8 S SPNLSTDT="P"
"RTN","SPNAGGE",45,0)
 I ASIAONE="D",ASIAFRTN<31 S SPNDCL=1
"RTN","SPNAGGE",46,0)
 I ASIAONE="D",ASIAFRTN<31 S SPNLSTDT="L"
"RTN","SPNAGGE",47,0)
 I SPNLSTDT="S" S SPNSEVC=SPNSEVC+1
"RTN","SPNAGGE",48,0)
 I SPNLSTDT="M" S SPNMODC=SPNMODC+1
"RTN","SPNAGGE",49,0)
 I SPNLSTDT="P" S SPNPARC=SPNPARC+1
"RTN","SPNAGGE",50,0)
 I SPNLSTDT="L" S SPNLOWC=SPNLOWC+1
"RTN","SPNAGGE",51,0)
 S SPNDIAGC=SPNDIAGC+1
"RTN","SPNAGGE",52,0)
 ;
"RTN","SPNAGGE",53,0)
AGE ;
"RTN","SPNAGGE",54,0)
 S AGECALL=$$GET1^DIQ(154.1,SPNPD1,999.025)
"RTN","SPNAGGE",55,0)
 I +SPNDCS S SPNAGES=SPNAGES+AGECALL,AGESC=AGESC+1 S:AGESC=1 BMAS=AGECALL S MINAGES=$S(AGECALL<BMAS:AGECALL,1:BMAS)
"RTN","SPNAGGE",56,0)
 I +SPNDCS S:AGESC=1 BHAS=AGECALL S MAXAGES=$S(AGECALL>BHAS:AGECALL,1:BHAS)
"RTN","SPNAGGE",57,0)
 I +SPNDCM S SPNAGEM=SPNAGEM+AGECALL,AGEMC=AGEMC+1 S:AGEMC=1 BMAM=AGECALL S MINAGEM=$S(AGECALL<BMAM:AGECALL,1:BMAM)
"RTN","SPNAGGE",58,0)
 I +SPNDCM S:AGEMC=1 BHAM=AGECALL S MAXAGEM=$S(AGECALL>BHAM:AGECALL,1:BHAM)
"RTN","SPNAGGE",59,0)
 I +SPNDCP S SPNAGEP=SPNAGEP+AGECALL,AGEPC=AGEPC+1 S:AGEPC=1 BMAP=AGECALL S MINAGEP=$S(AGECALL<BMAP:AGECALL,1:BMAP)
"RTN","SPNAGGE",60,0)
 I +SPNDCP S:AGEPC=1 BHAP=AGECALL S MAXAGEP=$S(AGECALL>BHAP:AGECALL,1:BHAP)
"RTN","SPNAGGE",61,0)
 I +SPNDCL S SPNAGEL=SPNAGEL+AGECALL,AGELC=AGELC+1 S:AGELC=1 BMAL=AGECALL S MINAGEL=$S(AGECALL<BMAL:AGECALL,1:BMAL)
"RTN","SPNAGGE",62,0)
 I +SPNDCL S:AGELC=1 BHAL=AGECALL S MAXAGEL=$S(AGECALL>BHAL:AGECALL,1:BHAL)
"RTN","SPNAGGE",63,0)
 S AGEL=$S((MINAGES<MINAGEM)&(MINAGES<MINAGEP)&(MINAGES<MINAGEL):MINAGES,(MINAGEM<MINAGEP)&(MINAGEM<MINAGEL):MINAGEM,MINAGEP<MINAGEL:MINAGEP,1:MINAGEL)
"RTN","SPNAGGE",64,0)
 S AGEH=$S((MAXAGES>MAXAGEM)&(MAXAGES>MAXAGEP)&(MAXAGES>MAXAGEL):MAXAGES,(MAXAGEM>MAXAGEP)&(MAXAGEM>MAXAGEL):MAXAGEM,MAXAGEP>MAXAGEL:MAXAGEP,1:MAXAGEL)
"RTN","SPNAGGE",65,0)
 ;
"RTN","SPNAGGE",66,0)
SEX ;
"RTN","SPNAGGE",67,0)
 S SEXCALL=$P(^DPT($P(^SPNL(154.1,SPNPD1,0),U,1),0),U,2)
"RTN","SPNAGGE",68,0)
 I +SPNDCS,SEXCALL="M" S SPNSEXS=SPNSEXS+1
"RTN","SPNAGGE",69,0)
 I +SPNDCM,SEXCALL="M" S SPNSEXM=SPNSEXM+1
"RTN","SPNAGGE",70,0)
 I +SPNDCP,SEXCALL="M" S SPNSEXP=SPNSEXP+1
"RTN","SPNAGGE",71,0)
 I +SPNDCL,SEXCALL="M" S SPNSEXL=SPNSEXL+1
"RTN","SPNAGGE",72,0)
LOR ;Let's obtain record
"RTN","SPNAGGE",73,0)
 I +SPNDCS D STATS I +TFSRN S TFS=TFS+TFSCALL,TFCS=TFCS+1
"RTN","SPNAGGE",74,0)
 I +SPNDCS&(+MFSRN) S MFS=MFS+MFSCALL,MFCS=MFCS+1
"RTN","SPNAGGE",75,0)
 I +SPNDCS&(+CFSRN) S CFS=CFS+CFSCALL,CFCS=CFCS+1
"RTN","SPNAGGE",76,0)
 I +SPNDCS&(+CPIRN) S CPIS=CPIS+CPICALL,CPICS=CPICS+1
"RTN","SPNAGGE",77,0)
 I +SPNDCS&(+CCIRN) S CCIS=CCIS+CCICALL,CCICS=CCICS+1
"RTN","SPNAGGE",78,0)
 I +SPNDCS&(+CMRN) S CMS=CMS+CMCALL,CMCS=CMCS+1
"RTN","SPNAGGE",79,0)
 I +SPNDCS&(+CORN) S COS=COS+COCALL,COCS=COCS+1
"RTN","SPNAGGE",80,0)
 I +SPNDCS&(+CSIRN) S CSIS=CSIS+CSICALL,CSICS=CSICS+1
"RTN","SPNAGGE",81,0)
 I +SPNDCS&(+CERN) S CES=CES+CECALL,CECS=CECS+1
"RTN","SPNAGGE",82,0)
 I +SPNDCS&(+SLSRN) S SLSS=SLSS+SLSCALL,SLCS=SLCS+1
"RTN","SPNAGGE",83,0)
 ;
"RTN","SPNAGGE",84,0)
 I +SPNDCM D STATS I +TFSRN S TFM=TFM+TFSCALL,TFCM=TFCM+1
"RTN","SPNAGGE",85,0)
 I +SPNDCM&(+MFSRN) S MFM=MFM+MFSCALL,MFCM=MFCM+1
"RTN","SPNAGGE",86,0)
 I +SPNDCM&(+CFSRN) S CFM=CFM+CFSCALL,CFCM=CFCM+1
"RTN","SPNAGGE",87,0)
 I +SPNDCM&(+CPIRN) S CPIM=CPIM+CPICALL,CPICM=CPICM+1
"RTN","SPNAGGE",88,0)
 I +SPNDCM&(+CCIRN) S CCIM=CCIM+CCICALL,CCICM=CCICM+1
"RTN","SPNAGGE",89,0)
 I +SPNDCM&(+CMRN) S CMM=CMM+CMCALL,CMCM=CMCM+1
"RTN","SPNAGGE",90,0)
 I +SPNDCM&(+CORN) S COM=COM+COCALL,COCM=COCM+1
"RTN","SPNAGGE",91,0)
 I +SPNDCM&(+CSIRN) S CSIM=CSIM+CSICALL,CSICM=CSICM+1
"RTN","SPNAGGE",92,0)
 I +SPNDCM&(+CERN) S CEM=CEM+CECALL,CECM=CECM+1
"RTN","SPNAGGE",93,0)
 I +SPNDCM&(+SLSRN) S SLSM=SLSM+SLSCALL,SLCM=SLCM+1
"RTN","SPNAGGE",94,0)
 ;
"RTN","SPNAGGE",95,0)
 I +SPNDCP D STATS I +TFSRN S TFP=TFP+TFSCALL,TFCP=TFCP+1
"RTN","SPNAGGE",96,0)
 I +SPNDCP&(+MFSRN) S MFP=MFP+MFSCALL,MFCP=MFCP+1
"RTN","SPNAGGE",97,0)
 I +SPNDCP&(+CFSRN) S CFP=CFP+CFSCALL,CFCP=CFCP+1
"RTN","SPNAGGE",98,0)
 I +SPNDCP&(+CPIRN) S CPIP=CPIP+CPICALL,CPICP=CPICP+1
"RTN","SPNAGGE",99,0)
 I +SPNDCP&(+CCIRN) S CCIP=CCIP+CCICALL,CCICP=CCICP+1
"RTN","SPNAGGE",100,0)
 I +SPNDCP&(+CMRN) S CMP=CMP+CMCALL,CMCP=CMCP+1
"RTN","SPNAGGE",101,0)
 I +SPNDCP&(+CORN) S COP=COP+COCALL,COCP=COCP+1
"RTN","SPNAGGE",102,0)
 I +SPNDCP&(+CSIRN) S CSIP=CSIP+CSICALL,CSICP=CSICP+1
"RTN","SPNAGGE",103,0)
 I +SPNDCP&(+CERN) S CEP=CEP+CECALL,CECP=CECP+1
"RTN","SPNAGGE",104,0)
 I +SPNDCP&(+SLSRN) S SLSP=SLSP+SLSCALL,SLCP=SLCP+1
"RTN","SPNAGGE",105,0)
 ;
"RTN","SPNAGGE",106,0)
 I +SPNDCL D STATS I +TFSRN S TFL=TFL+TFSCALL,TFCL=TFCL+1
"RTN","SPNAGGE",107,0)
 I +SPNDCL&(+MFSRN) S MFL=MFL+MFSCALL,MFCL=MFCL+1
"RTN","SPNAGGE",108,0)
 I +SPNDCL&(+CFSRN) S CFL=CFL+CFSCALL,CFCL=CFCL+1
"RTN","SPNAGGE",109,0)
 I +SPNDCL&(+CPIRN) S CPIL=CPIL+CPICALL,CPICL=CPICL+1
"RTN","SPNAGGE",110,0)
 I +SPNDCL&(+CCIRN) S CCIL=CCIL+CCICALL,CCICL=CCICL+1
"RTN","SPNAGGE",111,0)
 I +SPNDCL&(+CMRN) S CML=CML+CMCALL,CMCL=CMCL+1
"RTN","SPNAGGE",112,0)
 I +SPNDCL&(+CORN) S COL=COL+COCALL,COCL=COCL+1
"RTN","SPNAGGE",113,0)
 I +SPNDCL&(+CSIRN) S CSIL=CSIL+CSICALL,CSICL=CSICL+1
"RTN","SPNAGGE",114,0)
 I +SPNDCL&(+CERN) S CEL=CEL+CECALL,CECL=CECL+1
"RTN","SPNAGGE",115,0)
 I +SPNDCL&(+SLSRN) S SLSL=SLSL+SLSCALL,SLCL=SLCL+1
"RTN","SPNAGGE",116,0)
 Q
"RTN","SPNAGGE",117,0)
 ;
"RTN","SPNAGGE",118,0)
STATS ;finds record
"RTN","SPNAGGE",119,0)
 S TFSRN=0,MFSRN=0,CFSRN=0,CPIRN=0,CCIRN=0,CMRN=0,CORN=0,CSIRN=0,CERN=0,SLSRN=0
"RTN","SPNAGGE",120,0)
 S V=SPNPD1 F  S V=$O(^SPNL(154.1,"B",SPNPD0,V)) Q:'+V  D GETLOR
"RTN","SPNAGGE",121,0)
 S TFSCALL=$$GET1^DIQ(154.1,TFSRN,999.05)
"RTN","SPNAGGE",122,0)
 S MFSCALL=$$GET1^DIQ(154.1,MFSRN,999.03)
"RTN","SPNAGGE",123,0)
 S CFSCALL=$$GET1^DIQ(154.1,CFSRN,999.04)
"RTN","SPNAGGE",124,0)
 S CPICALL=$P($G(^SPNL(154.1,CPIRN,"CHART")),U,1)
"RTN","SPNAGGE",125,0)
 S CCICALL=$P($G(^SPNL(154.1,CCIRN,"CHART")),U,6)
"RTN","SPNAGGE",126,0)
 S CMCALL=$P($G(^SPNL(154.1,CMRN,"CHART")),U,2)
"RTN","SPNAGGE",127,0)
 S COCALL=$P($G(^SPNL(154.1,CORN,"CHART")),U,3)
"RTN","SPNAGGE",128,0)
 S CSICALL=$P($G(^SPNL(154.1,CSIRN,"CHART")),U,4)
"RTN","SPNAGGE",129,0)
 S CECALL=$P($G(^SPNL(154.1,CERN,"CHART")),U,5)
"RTN","SPNAGGE",130,0)
 S SLSCALL=$P($G(^SPNL(154.1,SLSRN,"SCORE")),U,1)
"RTN","SPNAGGE",131,0)
 Q
"RTN","SPNAGGE",132,0)
GETLOR ;get Rec No. for TFS,MFS,CFS,CPI,SLS, etc
"RTN","SPNAGGE",133,0)
 Q:'$D(^SPNL(154.1,V,0))
"RTN","SPNAGGE",134,0)
 Q:$P($G(^SPNL(154.1,V,8)),U,3)'=CARETYP
"RTN","SPNAGGE",135,0)
 Q:$P($G(^SPNL(154.1,V,0)),U,4)<BDATE!($P($G(^SPNL(154.1,V,0)),U,4)>EDATE)
"RTN","SPNAGGE",136,0)
 I $P(^SPNL(154.1,V,0),U,2)=2 S (TFSRN,MFSRN,CFSRN)=V
"RTN","SPNAGGE",137,0)
 I $P(^SPNL(154.1,V,0),U,2)=4 S (CPIRN,CCIRN,CMRN,CORN,CSIRN,CERN)=V
"RTN","SPNAGGE",138,0)
 I $P(^SPNL(154.1,V,0),U,2)=6 S SLSRN=V
"RTN","SPNAGGE",139,0)
 Q
"RTN","SPNAGGE",140,0)
EXIT ;
"RTN","SPNAGGE",141,0)
 D EXIT^SPNAGGEU
"RTN","SPNAGGE",142,0)
 Q
"RTN","SPNAGGEU")
0^9^B7949619
"RTN","SPNAGGEU",1,0)
SPNAGGEU ;CM/SD- ANN EVAL AGGREGATE OUTCOME REPORT UTILITIES; 9-13-2003
"RTN","SPNAGGEU",2,0)
 ;;2.0;Spinal Cord Dysfunction;**21**;01/02/97
"RTN","SPNAGGEU",3,0)
 ;
"RTN","SPNAGGEU",4,0)
SET S U="^"
"RTN","SPNAGGEU",5,0)
 S SPNDIAGC=0,SPNSEVC=0,SPNMODC=0,SPNPARC=0,SPNLOWC=0
"RTN","SPNAGGEU",6,0)
 S SPNLSTDT="",SPNNODUP=""
"RTN","SPNAGGEU",7,0)
 S SPNSDATE=0,SPNMDATE=0,SPNPDATE=0,SPNLDATE=0
"RTN","SPNAGGEU",8,0)
 S SPNSEXS=0,SPNSEXM=0,SPNSEXP=0,SPNSEXL=0
"RTN","SPNAGGEU",9,0)
 S SPNAGES=0,SPNAGEM=0,SPNAGEP=0,SPNAGEL=0
"RTN","SPNAGGEU",10,0)
 S SPNT1=30,SPNT2=40,SPNT3=50,SPNT4=60,SPNT5=70
"RTN","SPNAGGEU",11,0)
 S MINAGES=0,MINAGEM=0,MINAGEP=0,MINAGEL=0
"RTN","SPNAGGEU",12,0)
 S MAXAGES=0,MAXAGEM=0,MAXAGEP=0,MAXAGEL=0
"RTN","SPNAGGEU",13,0)
 S BMAS=0,BMAM=0,BMAP=0,BMAL=0,AGESC=0,AGEMC=0,AGEPC=0,AGELC=0
"RTN","SPNAGGEU",14,0)
 S BHAS=0,BHAM=0,BHAP=0,BHAL=0
"RTN","SPNAGGEU",15,0)
 S AGEL=0,AGEH=0
"RTN","SPNAGGEU",16,0)
 S TFSRN=0,TFS=0,TFF=0
"RTN","SPNAGGEU",17,0)
 S TFM=0,TFP=0,TFL=0
"RTN","SPNAGGEU",18,0)
 S MFSRN=0,CFSRN=0,MFS=0,CFS=0,MFCS=0,CFCS=0
"RTN","SPNAGGEU",19,0)
 S MFM=0,CFM=0,MFCM=0,CFCM=0,MFP=0,CFP=0,MFCP=0,CFCP=0
"RTN","SPNAGGEU",20,0)
 S MFL=0,CFL=0,MFCL=0,CFCL=0
"RTN","SPNAGGEU",21,0)
 S TFCS=0,TFCM=0,TFCP=0,TFCL=0
"RTN","SPNAGGEU",22,0)
 S CPI=0,CCI=0,CM=0,CO=0,CSI=0,CE=0
"RTN","SPNAGGEU",23,0)
 S CPIS=0,CPIM=0,CPIP=0,CPIL=0,CCIS=0,CCIM=0,CCIP=0,CCIL=0
"RTN","SPNAGGEU",24,0)
 S CMS=0,CMM=0,CMP=0,CML=0,COS=0,COM=0,COP=0,COL=0
"RTN","SPNAGGEU",25,0)
 S CSIS=0,CSIM=0,CSIP=0,CSIL=0,CES=0,CEM=0,CEP=0,CEL=0
"RTN","SPNAGGEU",26,0)
 S CPIRN=0,CCIRN=0,CMRN=0,CORN=0,CSIRN=0,CERN=0
"RTN","SPNAGGEU",27,0)
 S CPICS=0,CPICM=0,CPICP=0,CPICL=0,CCICS=0,CCICM=0,CCICP=0,CCICL=0
"RTN","SPNAGGEU",28,0)
 S CMCS=0,CMCM=0,CMCP=0,CMCL=0,COCS=0,COCM=0,COCP=0,COCL=0
"RTN","SPNAGGEU",29,0)
 S CSICS=0,CSICM=0,CSICP=0,CSICL=0,CECS=0,CECM=0,CECP=0,CECL=0
"RTN","SPNAGGEU",30,0)
 S SLSRN=0,SLS=0
"RTN","SPNAGGEU",31,0)
 S SLSS=0,SLSM=0,SLSP=0,SLSL=0
"RTN","SPNAGGEU",32,0)
 S SLCS=0,SLCM=0,SLCP=0,SLCL=0
"RTN","SPNAGGEU",33,0)
 Q
"RTN","SPNAGGEU",34,0)
EXIT ;
"RTN","SPNAGGEU",35,0)
 K BDATE,EDATE,I,SPNLEXIT,SPNPD0,SPNPD1,SPNLSTDT,SPNDIAGC,SPNSEVC,SPNMODC
"RTN","SPNAGGEU",36,0)
 K SPNPARC,SPNLOWC,SPNSDATE,SPNMDATE,SPNPDATE,SPNLDATE,SPNNODUP,SPNSEXS
"RTN","SPNAGGEU",37,0)
 K SPNSEXM,SPNSEXP,SPNSEXL
"RTN","SPNAGGEU",38,0)
 K SPNT1,SPNT2,SPNT3,SPNT4,SPNT5,SPNDCS,SPNDCM,SPNDCP,SPNDCL,SPNAGROU
"RTN","SPNAGGEU",39,0)
 K SPNAGES,SPNAGEM,SPNAGEP,SPNAGEL
"RTN","SPNAGGEU",40,0)
 K BMAS,BMAM,BMAP,BMAL,BHAS,BHAM,BHAP,BHAL
"RTN","SPNAGGEU",41,0)
 K AGESC,AGEMC,AGEPC,AGELC,MINAGES,MINAGEM,MINAGEP,MINAGEL
"RTN","SPNAGGEU",42,0)
 K LORRN,V,LORL,LORH,AGEL,AGEH,ZTSAVE
"RTN","SPNAGGEU",43,0)
 K TFSRN,TFS,TFM,TFP,TFL,TFF,TFCS,TFCM,TFCP,TFCL
"RTN","SPNAGGEU",44,0)
 K MFSRN,CFSRN,MFS,MFM,MFP,MFL,CFS,CFM,CFP,CFL
"RTN","SPNAGGEU",45,0)
 K MFCS,MFCM,MFCP,MFCL,CFCS,CFCM,CFCP,CFCL
"RTN","SPNAGGEU",46,0)
 K SLSRN,SLS,SLCS,SLCM,SLCP,SLC
"RTN","SPNAGGEU",47,0)
 K SLSS,SLSM,SLSP,SLSL
"RTN","SPNAGGEU",48,0)
 K CCPIS,CPIM,CPIP,CPIL,CCIS,CCIM,CCIP,CCIL
"RTN","SPNAGGEU",49,0)
 K CMS,CMM,CMP,CML,COS,COM,COP,COL
"RTN","SPNAGGEU",50,0)
 K CSIS,CSIM,CSIP,CSIL,CES,CEM,CEP,CEL
"RTN","SPNAGGEU",51,0)
 K CPI,CCI,CM,CO,CSI,CEC
"RTN","SPNAGGEU",52,0)
 K CPICS,CPICM,CPICP,CPICL,CCICS,CCICM,CCICP,CCICL,CMCS,CMCM,CMCP,CMCL
"RTN","SPNAGGEU",53,0)
 K COCS,COCM,COCP,COCL,CSICS,CSICM,CSICP,CSICL,CECS,CECM,CECP,CECL
"RTN","SPNAGGEU",54,0)
 K AGECALL,ASIAONE,ASIAFRTN,SEXCALL
"RTN","SPNAGGEU",55,0)
 K TFSCALL,SLSCALL,CSICALL,CECALLL
"RTN","SPNAGGEU",56,0)
 K MFSCALL,CFSCALL,CPICALL,CCICALL,CMCALL,COCALL
"RTN","SPNAGGEU",57,0)
 Q
"RTN","SPNAGGI")
0^13^B62554694
"RTN","SPNAGGI",1,0)
SPNAGGI ;SD/CM- AGGREGATE INPATIENT OUTCOMES REPORT; 2-21-2003
"RTN","SPNAGGI",2,0)
 ;;2.0;Spinal Cord Dysfunction;**20,21**;01/02/97
"RTN","SPNAGGI",3,0)
 ;
"RTN","SPNAGGI",4,0)
EN ;
"RTN","SPNAGGI",5,0)
 S U="^"
"RTN","SPNAGGI",6,0)
 D INPT^SPNAGGU
"RTN","SPNAGGI",7,0)
 S (LORCALL,MAX1,MAX2)=0
"RTN","SPNAGGI",8,0)
PARAMS ;
"RTN","SPNAGGI",9,0)
 D CED
"RTN","SPNAGGI",10,0)
 G:SPNLEXIT=1 EXIT
"RTN","SPNAGGI",11,0)
DEVICE ;
"RTN","SPNAGGI",12,0)
 S ZTSAVE("SPN*")="",ZTSAVE("B*")="",ZTSAVE("AGE*")="",ZTSAVE("MIN*")=""
"RTN","SPNAGGI",13,0)
 S ZTSAVE("MAX*")="",ZTSAVE("LOR*")="",ZTSAVE("TF*")="",ZTSAVE("SEX*")=""
"RTN","SPNAGGI",14,0)
 S ZTSAVE("SL*")="",ZTSAVE("COMD*")="",ZTSAVE("CARETYP")=""
"RTN","SPNAGGI",15,0)
 S ZTSAVE("EDATE")="",ZTSAVE("BDATE")="",ZTSAVE("LINE")="",ZTSAVE("I")=""
"RTN","SPNAGGI",16,0)
 S ZTSAVE("ASIA*")=""
"RTN","SPNAGGI",17,0)
 W !
"RTN","SPNAGGI",18,0)
 D DEVICE^SPNPRTMT("PRINT^SPNAGGPI","Inpt Rehab Outcomes",.ZTSAVE) Q:SPNLEXIT
"RTN","SPNAGGI",19,0)
 I SPNIO="Q" D EXIT Q  ; Print was queued
"RTN","SPNAGGI",20,0)
 I IO'="" D PRINT^SPNAGGPI D EXIT Q  ; Print was not queued
"RTN","SPNAGGI",21,0)
 D EXIT
"RTN","SPNAGGI",22,0)
 Q
"RTN","SPNAGGI",23,0)
CED ;date range for Care End Date
"RTN","SPNAGGI",24,0)
 D DATE^SPNAGGA
"RTN","SPNAGGI",25,0)
 Q
"RTN","SPNAGGI",26,0)
OIEN ;
"RTN","SPNAGGI",27,0)
 S SPNPD1=0 F  S SPNPD1=$O(^SPNL(154.1,"B",SPNPD0,SPNPD1)) Q:'+SPNPD1  D DIAGCAT
"RTN","SPNAGGI",28,0)
 Q
"RTN","SPNAGGI",29,0)
DIAGCAT ;get ASIA Highest Neuro Level and ASIA Imp Scale
"RTN","SPNAGGI",30,0)
 S SPNDCS=0,SPNDCM=0,SPNDCP=0,SPNDCL=0
"RTN","SPNAGGI",31,0)
 Q:'$D(^SPNL(154.1,SPNPD1,0))
"RTN","SPNAGGI",32,0)
 Q:'$D(^SPNL(154.1,SPNPD1,"ASIA"))
"RTN","SPNAGGI",33,0)
 Q:'$D(^SPNL(154.1,SPNPD1,8))
"RTN","SPNAGGI",34,0)
 Q:$P(^SPNL(154.1,SPNPD1,0),U,2)'=3
"RTN","SPNAGGI",35,0)
 Q:$P(^SPNL(154.1,SPNPD1,8),U,3)'=CARETYP
"RTN","SPNAGGI",36,0)
 Q:$P($G(^SPNL(154.1,SPNPD1,8)),U,2)<BDATE!($P($G(^SPNL(154.1,SPNPD1,8)),U,2)>EDATE)
"RTN","SPNAGGI",37,0)
 Q:$P($G(^SPNL(154.1,SPNPD1,0)),U,1)=SPNNODUP
"RTN","SPNAGGI",38,0)
 S SPNNODUP=$P($G(^SPNL(154.1,SPNPD1,0)),U,1)
"RTN","SPNAGGI",39,0)
 S ASIAONE=$P($G(^SPNL(154.1,SPNPD1,"ASIA")),U,1),ASIAFRTN=$P($G(^SPNL(154.1,SPNPD1,"ASIA")),U,14)
"RTN","SPNAGGI",40,0)
 I "ABC"[ASIAONE,ASIAFRTN<5 S SPNDCS=1
"RTN","SPNAGGI",41,0)
 I "ABC"[ASIAONE,ASIAFRTN<5 S SPNLSTDT="S"
"RTN","SPNAGGI",42,0)
 I "ABC"[ASIAONE&(ASIAFRTN>4)&(ASIAFRTN<9) S SPNDCM=1
"RTN","SPNAGGI",43,0)
 I "ABC"[ASIAONE&(ASIAFRTN>4)&(ASIAFRTN<9) S SPNLSTDT="M"
"RTN","SPNAGGI",44,0)
 I "ABC"[ASIAONE,ASIAFRTN>8 S SPNDCP=1
"RTN","SPNAGGI",45,0)
 I "ABC"[ASIAONE,ASIAFRTN>8 S SPNLSTDT="P"
"RTN","SPNAGGI",46,0)
 I ASIAONE="D",ASIAFRTN<31 S SPNDCL=1
"RTN","SPNAGGI",47,0)
 I ASIAONE="D",ASIAFRTN<31 S SPNLSTDT="L"
"RTN","SPNAGGI",48,0)
 I SPNLSTDT="S" S SPNSEVC=SPNSEVC+1
"RTN","SPNAGGI",49,0)
 I SPNLSTDT="M" S SPNMODC=SPNMODC+1
"RTN","SPNAGGI",50,0)
 I SPNLSTDT="P" S SPNPARC=SPNPARC+1
"RTN","SPNAGGI",51,0)
 I SPNLSTDT="L" S SPNLOWC=SPNLOWC+1
"RTN","SPNAGGI",52,0)
 S SPNDIAGC=SPNDIAGC+1
"RTN","SPNAGGI",53,0)
 ;
"RTN","SPNAGGI",54,0)
AGE ;
"RTN","SPNAGGI",55,0)
 S AGECALL=$$GET1^DIQ(154.1,SPNPD1,999.025)
"RTN","SPNAGGI",56,0)
 I +SPNDCS S SPNAGES=SPNAGES+AGECALL,AGESC=AGESC+1 S:AGESC=1 BMAS=AGECALL S MINAGES=$S(AGECALL<BMAS:AGECALL,1:BMAS)
"RTN","SPNAGGI",57,0)
 I +SPNDCS S:AGESC=1 BHAS=AGECALL S MAXAGES=$S(AGECALL>BHAS:AGECALL,1:BHAS)
"RTN","SPNAGGI",58,0)
 I +SPNDCM S SPNAGEM=SPNAGEM+AGECALL,AGEMC=AGEMC+1 S:AGEMC=1 BMAM=AGECALL S MINAGEM=$S(AGECALL<BMAM:AGECALL,1:BMAM)
"RTN","SPNAGGI",59,0)
 I +SPNDCM S:AGEMC=1 BHAM=AGECALL S MAXAGEM=$S(AGECALL>BHAM:AGECALL,1:BHAM)
"RTN","SPNAGGI",60,0)
 I +SPNDCP S SPNAGEP=SPNAGEP+AGECALL,AGEPC=AGEPC+1 S:AGEPC=1 BMAP=AGECALL S MINAGEP=$S(AGECALL<BMAP:AGECALL,1:BMAP)
"RTN","SPNAGGI",61,0)
 I +SPNDCP S:AGEPC=1 BHAP=AGECALL S MAXAGEP=$S(AGECALL>BHAP:AGECALL,1:BHAP)
"RTN","SPNAGGI",62,0)
 I +SPNDCL S SPNAGEL=SPNAGEL+AGECALL,AGELC=AGELC+1 S:AGELC=1 BMAL=AGECALL S MINAGEL=$S(AGECALL<BMAL:AGECALL,1:BMAL)
"RTN","SPNAGGI",63,0)
 I +SPNDCL S:AGELC=1 BHAL=AGECALL S MAXAGEL=$S(AGECALL>BHAL:AGECALL,1:BHAL)
"RTN","SPNAGGI",64,0)
 S AGEL=$S((MINAGES<MINAGEM)&(MINAGES<MINAGEP)&(MINAGES<MINAGEL):MINAGES,(MINAGEM<MINAGEP)&(MINAGEM<MINAGEL):MINAGEM,MINAGEP<MINAGEL:MINAGEP,1:MINAGEL)
"RTN","SPNAGGI",65,0)
 S AGEH=$S((MAXAGES>MAXAGEM)&(MAXAGES>MAXAGEP)&(MAXAGES>MAXAGEL):MAXAGES,(MAXAGEM>MAXAGEP)&(MAXAGEM>MAXAGEL):MAXAGEM,MAXAGEP>MAXAGEL:MAXAGEP,1:MAXAGEL)
"RTN","SPNAGGI",66,0)
 ;
"RTN","SPNAGGI",67,0)
SEX ;
"RTN","SPNAGGI",68,0)
 S SEXCALL=$P(^DPT($P(^SPNL(154.1,SPNPD1,0),U,1),0),U,2)
"RTN","SPNAGGI",69,0)
 I +SPNDCS,SEXCALL="M" S SPNSEXS=SPNSEXS+1
"RTN","SPNAGGI",70,0)
 I +SPNDCM,SEXCALL="M" S SPNSEXM=SPNSEXM+1
"RTN","SPNAGGI",71,0)
 I +SPNDCP,SEXCALL="M" S SPNSEXP=SPNSEXP+1
"RTN","SPNAGGI",72,0)
 I +SPNDCL,SEXCALL="M" S SPNSEXL=SPNSEXL+1
"RTN","SPNAGGI",73,0)
LOR ;Length of Rehab in Days
"RTN","SPNAGGI",74,0)
 I +SPNDCS D STATS I +LORRN S SPNLORS=SPNLORS+LORCALL,LORSC=LORSC+1
"RTN","SPNAGGI",75,0)
 I +SPNDCS S ^TMP($J,"SPNLRNS",SPNPD1)=LORCALL S MINLORS=$$MINLORS^SPNAGGU(SPNPD1)
"RTN","SPNAGGI",76,0)
 I +SPNDCS S ^TMP($J,"SPNLRXS",SPNPD1)=LORCALL S MAXLORS=$$MAXLORS^SPNAGGU(SPNPD1)
"RTN","SPNAGGI",77,0)
 I +SPNDCS&(+LORRN)&(+TFSRN) S TFS=TFSCALL,TFF=LOR5CALL,TFCUMS=TFCUMS+(TFF-TFS),TFCS=TFCS+1
"RTN","SPNAGGI",78,0)
 I +SPNDCS&(+LORRN)&(+TFGRN) S TFG=TFGCALL,TFF=LOR5CALL,TFGCUMS=TFGCUMS+(TFF-TFG),TFGCS=TFGCS+1
"RTN","SPNAGGI",79,0)
CDSEV I +SPNDCS&(+LORRN)&($P($G(^SPNL(154.1,LORRN,0)),U,24)<5) S COMDISS=COMDISS+1
"RTN","SPNAGGI",80,0)
FRETSEV I +SPNDCS&(+LORRN)&(+TFURN) S TFU=TFUCALL,TFF=LOR5CALL,TFUCUMS=TFUCUMS+(TFU-TFF),TFUCS=TFUCS+1
"RTN","SPNAGGI",81,0)
SLSEV I +SPNDCS&(+SLSRN)&(+SLFRN) S SLS=SLSCALL,SLF=SLFCALL,SLCUMS=SLCUMS+(SLF-SLS),SLCS=SLCS+1
"RTN","SPNAGGI",82,0)
SLUSEV I +SPNDCS&(+SLFRN)&(+SLURN) S SLU=SLUCALL,SLF=SLFCALL,SLUCUMS=SLUCUMS+(SLU-SLF),SLUCS=SLUCS+1
"RTN","SPNAGGI",83,0)
 I +SPNDCM D STATS I +LORRN S SPNLORM=SPNLORM+LORCALL,LORMC=LORMC+1
"RTN","SPNAGGI",84,0)
 I +SPNDCM S ^TMP($J,"SPNLRNM",SPNPD1)=LORCALL S MINLORM=$$MINLORM^SPNAGGU(SPNPD1)
"RTN","SPNAGGI",85,0)
 I +SPNDCM S ^TMP($J,"SPNLRXM",SPNPD1)=LORCALL S MAXLORM=$$MAXLORM^SPNAGGU(SPNPD1)
"RTN","SPNAGGI",86,0)
 I +SPNDCM&(+LORRN)&(+TFSRN) S TFS=TFSCALL,TFF=LOR5CALL,TFCUMM=TFCUMM+(TFF-TFS),TFCM=TFCM+1
"RTN","SPNAGGI",87,0)
 I +SPNDCM&(+LORRN)&(+TFGRN) S TFG=TFGCALL,TFF=LOR5CALL,TFGCUMM=TFGCUMM+(TFF-TFG),TFGCM=TFGCM+1
"RTN","SPNAGGI",88,0)
CDMOD I +SPNDCM&(+LORRN)&($P($G(^SPNL(154.1,LORRN,0)),U,24)<5) S COMDISM=COMDISM+1
"RTN","SPNAGGI",89,0)
FRETMOD I +SPNDCM&(+LORRN)&(+TFURN) S TFU=TFUCALL,TFF=LOR5CALL,TFUCUMM=TFUCUMM+(TFU-TFF),TFUCM=TFUCM+1
"RTN","SPNAGGI",90,0)
SLMOD I +SPNDCM&(+SLSRN)&(+SLFRN) S SLS=SLSCALL,SLF=SLFCALL,SLCUMM=SLCUMM+(SLF-SLS),SLCM=SLCM+1
"RTN","SPNAGGI",91,0)
SLUMOD I +SPNDCM&(+SLFRN)&(+SLURN) S SLU=SLUCALL,SLF=SLFCALL,SLUCUMM=SLUCUMM+(SLU-SLF),SLUCM=SLUCM+1
"RTN","SPNAGGI",92,0)
 I +SPNDCP D STATS I +LORRN S SPNLORP=SPNLORP+LORCALL,LORPC=LORPC+1
"RTN","SPNAGGI",93,0)
 I +SPNDCP S ^TMP($J,"SPNLRNP",SPNPD1)=LORCALL S MINLORP=$$MINLORP^SPNAGGU(SPNPD1)
"RTN","SPNAGGI",94,0)
 I +SPNDCP S ^TMP($J,"SPNLRXP",SPNPD1)=LORCALL S MAXLORP=$$MAXLORP^SPNAGGU(SPNPD1)
"RTN","SPNAGGI",95,0)
 I +SPNDCP&(+LORRN)&(+TFSRN) S TFS=TFSCALL,TFF=LOR5CALL,TFCUMP=TFCUMP+(TFF-TFS),TFCP=TFCP+1
"RTN","SPNAGGI",96,0)
 I +SPNDCP&(+LORRN)&(+TFGRN) S TFG=TFGCALL,TFF=LOR5CALL,TFGCUMP=TFGCUMP+(TFF-TFG),TFGCP=TFGCP+1
"RTN","SPNAGGI",97,0)
CDPARA I +SPNDCP&(+LORRN)&($P($G(^SPNL(154.1,LORRN,0)),U,24)<5) S COMDISP=COMDISP+1
"RTN","SPNAGGI",98,0)
FRETPAR I +SPNDCP&(+LORRN)&(+TFURN) S TFU=TFUCALL,TFF=LOR5CALL,TFUCUMP=TFUCUMP+(TFU-TFF),TFUCP=TFUCP+1
"RTN","SPNAGGI",99,0)
SLPAR I +SPNDCP&(+SLSRN)&(+SLFRN) S SLS=SLSCALL,SLF=SLFCALL,SLCUMP=SLCUMP+(SLF-SLS),SLCP=SLCP+1
"RTN","SPNAGGI",100,0)
SLUPAR I +SPNDCP&(+SLFRN)&(+SLURN) S SLU=SLUCALL,SLF=SLFCALL,SLUCUMP=SLUCUMP+(SLU-SLF),SLUCP=SLUCP+1
"RTN","SPNAGGI",101,0)
 I +SPNDCL D STATS I +LORRN S SPNLORL=SPNLORL+LORCALL,LORLC=LORLC+1
"RTN","SPNAGGI",102,0)
 I +SPNDCL S ^TMP($J,"SPNLRNL",SPNPD1)=LORCALL S MINLORL=$$MINLORL^SPNAGGU(SPNPD1)
"RTN","SPNAGGI",103,0)
 I +SPNDCL S ^TMP($J,"SPNLRXL",SPNPD1)=LORCALL S MAXLORL=$$MAXLORL^SPNAGGU(SPNPD1)
"RTN","SPNAGGI",104,0)
 I +SPNDCL&(+LORRN)&(+TFSRN) S TFS=TFSCALL,TFF=LOR5CALL,TFCUML=TFCUML+(TFF-TFS),TFCL=TFCL+1
"RTN","SPNAGGI",105,0)
 I +SPNDCL&(+LORRN)&(+TFGRN) S TFG=TFGCALL,TFF=LOR5CALL,TFGCUML=TFGCUML+(TFF-TFG),TFGCL=TFGCL+1
"RTN","SPNAGGI",106,0)
CDLOW I +SPNDCL&(+LORRN)&($P($G(^SPNL(154.1,LORRN,0)),U,24)<5) S COMDISL=COMDISL+1
"RTN","SPNAGGI",107,0)
FRETLOW I +SPNDCL&(+LORRN)&(+TFURN) S TFU=TFUCALL,TFF=LOR5CALL,TFUCUML=TFUCUML+(TFU-TFF),TFUCL=TFUCL+1
"RTN","SPNAGGI",108,0)
SLLOW I +SPNDCL&(+SLSRN)&(+SLFRN) S SLS=SLSCALL,SLF=SLFCALL,SLCUML=SLCUML+(SLF-SLS),SLCL=SLCL+1
"RTN","SPNAGGI",109,0)
SLULOW I +SPNDCL&(+SLFRN)&(+SLURN) S SLU=SLUCALL,SLF=SLFCALL,SLUCUML=SLUCUML+(SLU-SLF),SLUCL=SLUCL+1
"RTN","SPNAGGI",110,0)
 S LORL=$S((MINLORS<MINLORM)&(MINLORS<MINLORP)&(MINLORS<MINLORL):MINLORS,(MINLORM<MINLORP)&(MINLORM<MINLORL):MINLORM,MINLORP<MINLORL:MINLORP,1:MINLORL)
"RTN","SPNAGGI",111,0)
 S LORH=$S((MAXLORS>MAXLORM)&(MAXLORS>MAXLORP)&(MAXLORS>MAXLORL):MAXLORS,(MAXLORM>MAXLORP)&(MAXLORM>MAXLORL):MAXLORM,MAXLORP>MAXLORL:MAXLORP,1:MAXLORL)
"RTN","SPNAGGI",112,0)
 Q
"RTN","SPNAGGI",113,0)
 ;
"RTN","SPNAGGI",114,0)
STATS ;finds record with Rehab Finish, so Length of Rehab can be obtained
"RTN","SPNAGGI",115,0)
 S LORRN=0,TFSRN=0,TFGRN=0,TFURN=0,SLSRN=0,SLFRN=0,SLURN=0
"RTN","SPNAGGI",116,0)
 S V=SPNPD1 F  S V=$O(^SPNL(154.1,"B",SPNPD0,V)) Q:'+V  D GETLOR
"RTN","SPNAGGI",117,0)
 S LORCALL=$$GET1^DIQ(154.1,LORRN,999.08)
"RTN","SPNAGGI",118,0)
 S LOR5CALL=$$GET1^DIQ(154.1,LORRN,999.05)
"RTN","SPNAGGI",119,0)
 S TFSCALL=$$GET1^DIQ(154.1,TFSRN,999.05)
"RTN","SPNAGGI",120,0)
 S TFGCALL=$$GET1^DIQ(154.1,TFGRN,999.05)
"RTN","SPNAGGI",121,0)
 S TFUCALL=$$GET1^DIQ(154.1,TFURN,999.05)
"RTN","SPNAGGI",122,0)
 S SLSCALL=$P($G(^SPNL(154.1,SLSRN,"SCORE")),U,1)
"RTN","SPNAGGI",123,0)
 S SLFCALL=$P($G(^SPNL(154.1,SLFRN,"SCORE")),U,1)
"RTN","SPNAGGI",124,0)
 S SLUCALL=$P($G(^SPNL(154.1,SLURN,"SCORE")),U,1)
"RTN","SPNAGGI",125,0)
 Q
"RTN","SPNAGGI",126,0)
GETLOR ;get Rec No. for LOR,TFS (TFF is same RN as LOR),TFU,TFG,SLS,SLF,SLU
"RTN","SPNAGGI",127,0)
 Q:'$D(^SPNL(154.1,V,0))
"RTN","SPNAGGI",128,0)
 Q:'+$P($G(^SPNL(154.1,V,2)),U,17)
"RTN","SPNAGGI",129,0)
 Q:$P($G(^SPNL(154.1,V,8)),U,3)'=CARETYP
"RTN","SPNAGGI",130,0)
 Q:$P($G(^SPNL(154.1,V,8)),U,2)<BDATE!($P($G(^SPNL(154.1,V,8)),U,2)>EDATE)
"RTN","SPNAGGI",131,0)
 I $P(^SPNL(154.1,V,2),U,17)=1,($P(^SPNL(154.1,V,0),U,2)=2) S TFSRN=V
"RTN","SPNAGGI",132,0)
 I $P(^SPNL(154.1,V,2),U,17)=2,($P(^SPNL(154.1,V,0),U,2)=2) S TFGRN=V
"RTN","SPNAGGI",133,0)
 I $P(^SPNL(154.1,V,2),U,17)=5,($P(^SPNL(154.1,V,0),U,2)=2) S TFURN=V
"RTN","SPNAGGI",134,0)
 I $P(^SPNL(154.1,V,2),U,17)=1,($P(^SPNL(154.1,V,0),U,2)=6) S SLSRN=V
"RTN","SPNAGGI",135,0)
 I $P(^SPNL(154.1,V,2),U,17)=4,($P(^SPNL(154.1,V,0),U,2)=6) S SLFRN=V
"RTN","SPNAGGI",136,0)
 I $P(^SPNL(154.1,V,2),U,17)=5,($P(^SPNL(154.1,V,0),U,2)=6) S SLURN=V
"RTN","SPNAGGI",137,0)
 I $P($G(^SPNL(154.1,V,8)),U,4)'="" S LORRN=V
"RTN","SPNAGGI",138,0)
 Q
"RTN","SPNAGGI",139,0)
EXIT ;
"RTN","SPNAGGI",140,0)
 D EXIT^SPNAGGU
"RTN","SPNAGGI",141,0)
 K MAX1,MAX2
"RTN","SPNAGGI",142,0)
 K ^TMP($J,"SPNLRNS"),^TMP($J,"SPNLRXS"),^TMP($J,"SPNLRNM"),^TMP($J,"SPNLRXM"),^TMP($J,"SPNLRNP"),^TMP($J,"SPNLRXP"),^TMP($J,"SPNLRNL"),^TMP($J,"SPNLRXL")
"RTN","SPNAGGI",143,0)
 Q
"RTN","SPNAGGPC")
0^11^B26838227
"RTN","SPNAGGPC",1,0)
SPNAGGPC ;SD/CM- PRINT AGGREGATE CONT OF CARE OUTCOMES; 9-17-2003
"RTN","SPNAGGPC",2,0)
 ;;2.0;Spinal Cord Dysfunction;**21**;01/02/97
"RTN","SPNAGGPC",3,0)
 ;
"RTN","SPNAGGPC",4,0)
PRINT ;
"RTN","SPNAGGPC",5,0)
 S U="^"
"RTN","SPNAGGPC",6,0)
 W !!
"RTN","SPNAGGPC",7,0)
 S SPNPD0=0 F  S SPNPD0=$O(^SPNL(154.1,"B",SPNPD0)) Q:'+SPNPD0  D OIEN^SPNAGGC
"RTN","SPNAGGPC",8,0)
 W !,?20,"CONTINUUM OF CARE Outcomes Report"
"RTN","SPNAGGPC",9,0)
 W !,?24,"Date of Report: ",$$FMTE^XLFDT($$NOW^XLFDT,"5DZP")
"RTN","SPNAGGPC",10,0)
 W !,?13,"Based on Care Dates from ",$$FMTE^XLFDT(BDATE,"5DZP")," to ",$$FMTE^XLFDT(EDATE,"5DZP"),!!
"RTN","SPNAGGPC",11,0)
 S LINE="-" F I=1:1:80 W LINE
"RTN","SPNAGGPC",12,0)
 W !,?SPNT1,"HI TETRA",?SPNT2,"LO TETRA",?SPNT3,"PARA",?SPNT4,"ASIA D",?SPNT5,"ALL",!
"RTN","SPNAGGPC",13,0)
 W !,"# and % of Patients",?SPNT1,SPNSEVC," (",$S(+SPNDIAGC:$J(SPNSEVC/SPNDIAGC*100,2,0),1:0),"%)",?SPNT2,SPNMODC," (",$S(+SPNDIAGC:$J(SPNMODC/SPNDIAGC*100,2,0),1:0),"%)"
"RTN","SPNAGGPC",14,0)
 W ?SPNT3,SPNPARC," (",$S(+SPNDIAGC:$J(SPNPARC/SPNDIAGC*100,2,0),1:0),"%)",?SPNT4,SPNLOWC," (",$S(+SPNDIAGC:$J(SPNLOWC/SPNDIAGC*100,2,0),1:0),"%)",?SPNT5,SPNDIAGC," (100%)"
"RTN","SPNAGGPC",15,0)
 W !,"Age (yrs)",?SPNT1,$S(+SPNSEVC:$J(SPNAGES/SPNSEVC,3,1),1:"N/A"),?SPNT2,$S(+SPNMODC:$J(SPNAGEM/SPNMODC,3,1),1:"N/A"),?SPNT3,$S(+SPNPARC:$J(SPNAGEP/SPNPARC,3,1),1:"N/A"),?SPNT4,$S(+SPNLOWC:$J(SPNAGEL/SPNLOWC,3,1),1:"N/A")
"RTN","SPNAGGPC",16,0)
 W ?SPNT5,$S(SPNDIAGC>0:$J(SPNAGES+SPNAGEM+SPNAGEP+SPNAGEL/SPNDIAGC,3,1),1:"N/A")
"RTN","SPNAGGPC",17,0)
 W !,"Age Range",?SPNT1,MINAGES,"-",MAXAGES,?SPNT2,MINAGEM,"-",MAXAGEM,?SPNT3,MINAGEP,"-",MAXAGEP,?SPNT4,MINAGEL,"-",MAXAGEL,?SPNT5,AGEL,"-",AGEH
"RTN","SPNAGGPC",18,0)
 W !,"Gender (% Male pts)",?SPNT1,$S(+SPNSEVC:$J(SPNSEXS/SPNSEVC*100,2,0)_"%",1:"N/A"),?SPNT2,$S(+SPNMODC:$J(SPNSEXM/SPNMODC*100,2,0)_"%",1:"N/A"),?SPNT3,$S(+SPNPARC:$J(SPNSEXP/SPNPARC*100,2,0)_"%",1:"N/A")
"RTN","SPNAGGPC",19,0)
 W ?SPNT4,$S(+SPNLOWC:$J(SPNSEXL/SPNLOWC*100,2,0)_"%",1:"N/A")
"RTN","SPNAGGPC",20,0)
 W ?SPNT5,$S(+SPNDIAGC:$J(SPNSEXS+SPNSEXM+SPNSEXP+SPNSEXL/SPNDIAGC*100,2,0)_"%",1:"N/A")
"RTN","SPNAGGPC",21,0)
 W !,"Length of Stay (days)",?SPNT1,$S(+LORSC:SPNLORS/LORSC,1:"N/A"),?SPNT2,$S(+LORMC:SPNLORM/LORMC,1:"N/A"),?SPNT3,$S(+LORPC:SPNLORP/LORPC,1:"N/A"),?SPNT4
"RTN","SPNAGGPC",22,0)
 W $S(+LORLC:SPNLORL/LORLC,1:"N/A"),?SPNT5,$S(+(LORSC+LORMC+LORPC+LORLC):$J(SPNLORS+SPNLORM+SPNLORP+SPNLORL/(LORSC+LORMC+LORPC+LORLC),3,0),1:"N/A")
"RTN","SPNAGGPC",23,0)
 W !,"Length of Stay Range",?SPNT1,MINLORS,"-",MAXLORS,?SPNT2,MINLORM,"-",SPNLORM,?SPNT3,MINLORP,"-",MAXLORP,?SPNT4,MINLORL,"-",MAXLORL,?SPNT5,LORL,"-",LORH
"RTN","SPNAGGPC",24,0)
 W !,"Total FIM Change",?SPNT1,$S(+TFCS:TFCUMS/TFCS,1:"N/A"),?SPNT2,$S(+TFCM:TFCUMM/TFCM,1:"N/A"),?SPNT3,$S(+TFCP:TFCUMP/TFCP,1:"N/A"),?SPNT4,$S(+TFCL:TFCUML/TFCL,1:"N/A")
"RTN","SPNAGGPC",25,0)
 W ?SPNT5,$S(TFCS+TFCM+TFCP+TFCL>0:$J(TFCUMS+TFCUMM+TFCUMP+TFCUML/(TFCS+TFCM+TFCP+TFCL),3,1),1:"N/A")
"RTN","SPNAGGPC",26,0)
 W !,"FIM Efficiency",?SPNT1,$S(+SPNLORS:$J(TFCUMS/SPNLORS,3,2),1:"N/A"),?SPNT2,$S(+SPNLORM:$J(TFCUMM/SPNLORM,3,2),1:"N/A"),?SPNT3,$S(+SPNLORP:$J(TFCUMP/SPNLORP,3,2),1:"N/A")
"RTN","SPNAGGPC",27,0)
 W ?SPNT4,$S(+SPNLORL:$J(TFCUML/SPNLORL,3,2),1:"N/A"),?SPNT5,$S(SPNLORS+SPNLORM+SPNLORP+SPNLORL>0:$J(TFCUMS+TFCUMM+TFCUMP+TFCUML/(SPNLORS+SPNLORM+SPNLORP+SPNLORL),3,2),1:"N/A")
"RTN","SPNAGGPC",28,0)
 W !,"FIM Goal Attainment",?SPNT1,$S(+TFGCS:TFGCUMS/TFGCS,1:"N/A"),?SPNT2,$S(+TFGCM:TFGCUMM/TFGCM,1:"N/A"),?SPNT3,$S(+TFGCP:TFGCUMP/TFGCP,1:"N/A"),?SPNT4,$S(+TFGCL:TFGCUML/TFGCL,1:"N/A")
"RTN","SPNAGGPC",29,0)
 W ?SPNT5,$S(TFGCS+TFGCM+TFGCP+TFGCL>0:$J(TFGCUMS+TFGCUMM+TFGCUMP+TFGCUML/(TFGCS+TFGCM+TFGCP+TFGCL),3,1),1:"N/A")
"RTN","SPNAGGPC",30,0)
 W !,"% Discharged to Community",?SPNT1,$S(+COMDISS:COMDISS/LORSC*100_"%",1:"N/A"),?SPNT2,$S(+COMDISM:COMDISM/LORMC*100_"%",1:"N/A"),?SPNT3,$S(+COMDISP:COMDISP/LORPC*100_"%",1:"N/A"),?SPNT4,$S(+COMDISL:COMDISL/LORLC*100_"%",1:"N/A")
"RTN","SPNAGGPC",31,0)
 W ?SPNT5,$S(LORSC+LORMC+LORPC+LORLC>0:$J(COMDISS+COMDISM+COMDISP+COMDISL/(LORSC+LORMC+LORPC+LORLC)*100,2,0)_"%",1:"N/A")
"RTN","SPNAGGPC",32,0)
 W !,"FIM Durability",?SPNT1,$S(+TFUCS:TFUCUMS/TFUCS,1:"N/A"),?SPNT2,$S(+TFUCM:TFUCUMM/TFUCM,1:"N/A"),?SPNT3,$S(+TFUCP:TFUCUMP/TFUCP,1:"N/A"),?SPNT4,$S(+TFUCL:TFUCUML/TFUCL,1:"N/A")
"RTN","SPNAGGPC",33,0)
 W ?SPNT5,$S(TFUCS+TFUCM+TFUCP+TFUCL>0:$J(TFUCUMS+TFUCUMM+TFUCUMP+TFUCUML/(TFUCS+TFUCM+TFUCP+TFUCL),3,1),1:"N/A")
"RTN","SPNAGGPC",34,0)
 W !,"Diener SWLS Change",?SPNT1,$S(+SLCS:SLCUMS/SLCS,1:"N/A"),?SPNT2,$S(+SLCM:SLCUMM/SLCM,1:"N/A"),?SPNT3,$S(+SLCP:SLCUMP/SLCP,1:"N/A"),?SPNT4,$S(+SLCL:SLCUML/SLCL,1:"N/A")
"RTN","SPNAGGPC",35,0)
 W ?SPNT5,$S(SLCS+SLCM+SLCP+SLCL>0:$J(SLCUMS+SLCUMM+SLCUMP+SLCUML/(SLCS+SLCM+SLCP+SLCL),3,1),1:"N/A")
"RTN","SPNAGGPC",36,0)
 W !,"Diener SWLS Durability",?SPNT1,$S(+SLUCS:SLUCUMS/SLUCS,1:"N/A"),?SPNT2,$S(+SLUCM:SLUCUMM/SLUCM,1:"N/A"),?SPNT3,$S(+SLUCP:SLUCUMP/SLUCP,1:"N/A"),?SPNT4,$S(+SLUCL:SLUCUML/SLUCL,1:"N/A")
"RTN","SPNAGGPC",37,0)
 W ?SPNT5,$S(SLUCS+SLUCM+SLUCP+SLUCL>0:$J(SLUCUMS+SLUCUMM+SLUCUMP+SLUCUML/(SLUCS+SLUCM+SLUCP+SLUCL),3,1),1:"N/A")
"RTN","SPNAGGPC",38,0)
 Q
"RTN","SPNAGGPE")
0^8^B23872212
"RTN","SPNAGGPE",1,0)
SPNAGGPE ;SD/CM- PRINT AGGREGATE ANN EVAL OUTCOMES; 2-21-2003
"RTN","SPNAGGPE",2,0)
 ;;2.0;Spinal Cord Dysfunction;**21**;01/02/97
"RTN","SPNAGGPE",3,0)
 ;
"RTN","SPNAGGPE",4,0)
PRINT ;
"RTN","SPNAGGPE",5,0)
 S U="^"
"RTN","SPNAGGPE",6,0)
 W !!
"RTN","SPNAGGPE",7,0)
 S SPNPD0=0 F  S SPNPD0=$O(^SPNL(154.1,"B",SPNPD0)) Q:'+SPNPD0  D OIEN^SPNAGGE
"RTN","SPNAGGPE",8,0)
 W !,?20,"ANNUAL EVALUATION Outcomes Report"
"RTN","SPNAGGPE",9,0)
 W !,?24,"Date of Report: ",$$FMTE^XLFDT($$NOW^XLFDT,"5DZP")
"RTN","SPNAGGPE",10,0)
 W !,?11,"Based on Observations from ",$$FMTE^XLFDT(BDATE,"5DZP")," to ",$$FMTE^XLFDT(EDATE,"5DZP"),!!
"RTN","SPNAGGPE",11,0)
 S LINE="-" F I=1:1:80 W LINE
"RTN","SPNAGGPE",12,0)
 W !,?SPNT1,"HI TETRA",?SPNT2,"LO TETRA",?SPNT3,"PARA",?SPNT4,"ASIA D",?SPNT5,"ALL",!
"RTN","SPNAGGPE",13,0)
 W !,"# and % of Patients",?SPNT1,SPNSEVC," (",$S(+SPNDIAGC:$J(SPNSEVC/SPNDIAGC*100,2,0),1:0),"%)",?SPNT2,SPNMODC," (",$S(+SPNDIAGC:$J(SPNMODC/SPNDIAGC*100,2,0),1:0),"%)"
"RTN","SPNAGGPE",14,0)
 W ?SPNT3,SPNPARC," (",$S(+SPNDIAGC:$J(SPNPARC/SPNDIAGC*100,2,0),1:0),"%)",?SPNT4,SPNLOWC," (",$S(+SPNDIAGC:$J(SPNLOWC/SPNDIAGC*100,2,0),1:0),"%)",?SPNT5,SPNDIAGC," (100%)"
"RTN","SPNAGGPE",15,0)
 W !,"Age (yrs)",?SPNT1,$S(+SPNSEVC:SPNAGES/SPNSEVC,1:"N/A"),?SPNT2,$S(+SPNMODC:SPNAGEM/SPNMODC,1:"N/A"),?SPNT3,$S(+SPNPARC:SPNAGEP/SPNPARC,1:"N/A"),?SPNT4,$S(+SPNLOWC:SPNAGEL/SPNLOWC,1:"N/A")
"RTN","SPNAGGPE",16,0)
 W ?SPNT5,$S(SPNDIAGC>0:$J(SPNAGES+SPNAGEM+SPNAGEP+SPNAGEL/SPNDIAGC,3,1),1:"N/A")
"RTN","SPNAGGPE",17,0)
 W !,"Age Range",?SPNT1,MINAGES,"-",MAXAGES,?SPNT2,MINAGEM,"-",MAXAGEM,?SPNT3,MINAGEP,"-",MAXAGEP,?SPNT4,MINAGEL,"-",MAXAGEL,?SPNT5,AGEL,"-",AGEH
"RTN","SPNAGGPE",18,0)
 W !,"Gender (% Male pts)",?SPNT1,$S(+SPNSEVC:$J(SPNSEXS/SPNSEVC*100,2,0)_"%",1:"N/A"),?SPNT2,$S(+SPNMODC:$J(SPNSEXM/SPNMODC*100,2,0)_"%",1:"N/A"),?SPNT3,$S(+SPNPARC:$J(SPNSEXP/SPNPARC*100,2,0)_"%",1:"N/A")
"RTN","SPNAGGPE",19,0)
 W ?SPNT4,$S(+SPNLOWC:$J(SPNSEXL/SPNLOWC*100,2,0)_"%",1:"N/A")
"RTN","SPNAGGPE",20,0)
 W ?SPNT5,$S(+SPNDIAGC:$J(SPNSEXS+SPNSEXM+SPNSEXP+SPNSEXL/SPNDIAGC*100,2,0)_"%",1:"N/A")
"RTN","SPNAGGPE",21,0)
 W !,"Total FIM Score",?SPNT1,$S(+TFCS:TFS/TFCS,1:"N/A"),?SPNT2,$S(+TFCM:TFM/TFCM,1:"N/A"),?SPNT3,$S(+TFCP:TFP/TFCP,1:"N/A"),?SPNT4,$S(+TFCL:TFL/TFCL,1:"N/A")
"RTN","SPNAGGPE",22,0)
 W ?SPNT5,$S(TFCS+TFCM+TFCP+TFCL>0:$J(TFS+TFM+TFP+TFL/(TFCS+TFCM+TFCP+TFCL),3,1),1:"N/A")
"RTN","SPNAGGPE",23,0)
 W !,"Motor FIM Score",?SPNT1,$S(+MFCS:MFS/MFCS,1:"N/A"),?SPNT2,$S(+MFCM:MFM/MFCM,1:"N/A"),?SPNT3,$S(+MFCP:MFP/MFCP,1:"N/A"),?SPNT4,$S(+MFCL:MFL/MFCL,1:"N/A")
"RTN","SPNAGGPE",24,0)
 W ?SPNT5,$S(MFCS+MFCM+MFCP+MFCL>0:$J(MFS+MFM+MFP+MFL/(MFCS+MFCM+MFCP+MFCL),3,1),1:"N/A")
"RTN","SPNAGGPE",25,0)
 W !,"Cognitive FIM Score",?SPNT1,$S(+CFCS:CFS/CFCS,1:"N/A"),?SPNT2,$S(+CFCM:CFM/CFCM,1:"N/A"),?SPNT3,$S(+CFCP:CFP/CFCP,1:"N/A"),?SPNT4,$S(+CFCL:CFL/CFCL,1:"N/A")
"RTN","SPNAGGPE",26,0)
 W ?SPNT5,$S(CFCS+CFCM+CFCP+CFCL>0:$J(CFS+CFM+CFP+CFL/(CFCS+CFCM+CFCP+CFCL),3,1),1:"N/A")
"RTN","SPNAGGPE",27,0)
 W !,"CHART Physical Indep",?SPNT1,$S(+CPICS:CPIS/CPICS,1:"N/A"),?SPNT2,$S(+CPICM:CPIM/CPICM,1:"N/A"),?SPNT3,$S(+CPICP:CPIP/CPICP,1:"N/A"),?SPNT4,$S(+CPICL:CPIL/CPICL,1:"N/A")
"RTN","SPNAGGPE",28,0)
 W ?SPNT5,$S(CPICS+CPICM+CPICP+CPICL>0:$J(CPIS+CPIM+CPIP+CPIL/(CPICS+CPICM+CPICP+CPICL),3,1),1:"N/A")
"RTN","SPNAGGPE",29,0)
 W !,"CHART Cognitive Indep",?SPNT1,$S(+CCICS:CCIS/CCICS,1:"N/A"),?SPNT2,$S(+CCICM:CCIM/CCICM,1:"N/A"),?SPNT3,$S(+CCICP:CCIP/CCICP,1:"N/A"),?SPNT4,$S(+CCICL:CCIL/CCICL,1:"N/A")
"RTN","SPNAGGPE",30,0)
 W ?SPNT5,$S(CCICS+CCICM+CCICP+CCICL>0:$J(CCIS+CCIM+CCIP+CCIL/(CCICS+CCICM+CCICP+CCICL),3,1),1:"N/A")
"RTN","SPNAGGPE",31,0)
 W !,"CHART Mobility",?SPNT1,$S(+CMCS:CMS/CMCS,1:"N/A"),?SPNT2,$S(+CMCM:CMM/CMCM,1:"N/A"),?SPNT3,$S(+CMCP:CMP/CMCP,1:"N/A"),?SPNT4,$S(+CMCL:CML/CMCL,1:"N/A")
"RTN","SPNAGGPE",32,0)
 W ?SPNT5,$S(CMCS+CMCM+CMCP+CMCL>0:$J(CMS+CMM+CMP+CML/(CMCS+CMCM+CMCP+CMCL),3,1),1:"N/A")
"RTN","SPNAGGPE",33,0)
 W !,"CHART Occupation",?SPNT1,$S(+COCS:COS/COCS,1:"N/A"),?SPNT2,$S(+CMCM:COM/CMCM,1:"N/A"),?SPNT3,$S(+COCP:COP/COCP,1:"N/A"),?SPNT4,$S(+COCL:COL/COCL,1:"N/A")
"RTN","SPNAGGPE",34,0)
 W ?SPNT5,$S(COCS+COCM+COCP+COCL>0:$J(COS+COM+COP+COL/(COCS+COCM+COCP+COCL),3,1),1:"N/A")
"RTN","SPNAGGPE",35,0)
 W !,"CHART Social Interaction",?SPNT1,$S(+CSICS:CSIS/CSICS,1:"N/A"),?SPNT2,$S(+CSICM:CSIM/CSICM,1:"N/A"),?SPNT3,$S(+CSICP:CSIP/CSICP,1:"N/A"),?SPNT4,$S(+CSICL:CSIL/CSICL,1:"N/A")
"RTN","SPNAGGPE",36,0)
 W ?SPNT5,$S(CSICS+CSICM+CSICP+CSICL>0:$J(CSIS+CSIM+CSIP+CSIL/(CSICS+CSICM+CSICP+CSICL),3,1),1:"N/A")
"RTN","SPNAGGPE",37,0)
 W !,"CHART Economic",?SPNT1,$S(+CECS:CES/CECS,1:"N/A"),?SPNT2,$S(+CECM:CEM/CECM,1:"N/A"),?SPNT3,$S(+CECP:CEP/CECP,1:"N/A"),?SPNT4,$S(+CECL:CEL/CECL,1:"N/A")
"RTN","SPNAGGPE",38,0)
 W ?SPNT5,$S(CECS+CECM+CECP+CECL>0:$J(CES+CEM+CEP+CEL/(CECS+CECM+CECP+CECL),3,1),1:"N/A")
"RTN","SPNAGGPE",39,0)
 W !,"Diener SWLS",?SPNT1,$S(+SLCS:SLSS/SLCS,1:"N/A"),?SPNT2,$S(+SLCM:SLSM/SLCM,1:"N/A"),?SPNT3,$S(+SLCP:SLSP/SLCP,1:"N/A"),?SPNT4,$S(+SLCL:SLSL/SLCL,1:"N/A")
"RTN","SPNAGGPE",40,0)
 W ?SPNT5,$S(SLCS+SLCM+SLCP+SLCL>0:$J(SLSS+SLSM+SLSP+SLSL/(SLCS+SLCM+SLCP+SLCL),3,1),1:"N/A")
"RTN","SPNAGGPE",41,0)
 Q
"RTN","SPNAGGU")
0^14^B39243002
"RTN","SPNAGGU",1,0)
SPNAGGU ;SD/CM- AGGREGATE OUTCOME REPORT UTILITIES; 2-21-2003
"RTN","SPNAGGU",2,0)
 ;;2.0;Spinal Cord Dysfunction;**20,21**;01/02/97
"RTN","SPNAGGU",3,0)
 ;
"RTN","SPNAGGU",4,0)
INPT ;SPNLSTDT=Last date of ASIA HIGHEST NEURO LEVEL (most recent)
"RTN","SPNAGGU",5,0)
 ;SPNSEVC =Count of unique pts in diag category of 'severe'
"RTN","SPNAGGU",6,0)
 ;SPNMODC =  "    "   "     "   "  "      "     "  'moderate'
"RTN","SPNAGGU",7,0)
 ;SPNPARC =  "    "   "     "   "  "      "     "  'para'
"RTN","SPNAGGU",8,0)
 ;SPNLOWC =  "    "   "     "   "  "      "     "  'low'
"RTN","SPNAGGU",9,0)
 ;SPNDIAGC=Total count of unique pts over all diag categories
"RTN","SPNAGGU",10,0)
 ;SPNDCS  =Set to 1 if diag category criteria for 'severe' are met
"RTN","SPNAGGU",11,0)
 ;SPNDCM  =Set to 1 if diag category criteria for 'moderate' are met
"RTN","SPNAGGU",12,0)
 ;SPNDCP  =Set to 1 if diag category criteria for 'para' are met
"RTN","SPNAGGU",13,0)
 ;SPNDCL  =Set to 1 if diag category criteria for 'low' are met
"RTN","SPNAGGU",14,0)
 ;SPNAGES =Cumulative Age in Severe, SPNAGEM=Cum. Age in Moderate, etc
"RTN","SPNAGGU",15,0)
 ;BMAS    =Base Minimum Age Severe, BMAM=Base Minimum Age Moderate, etc
"RTN","SPNAGGU",16,0)
 ;AGESC   =Age Range Severe Count, AGEMC=Age Range Moderate Count, etc
"RTN","SPNAGGU",17,0)
 ;MINAGES =Minimum Age Severe, MINAGEM=Minimum Age Moderate, etc
"RTN","SPNAGGU",18,0)
 ;BHAS    =Base Maximum Age Severe, BHAM=Base Maximum Age Moderate, etc
"RTN","SPNAGGU",19,0)
 ;MAXAGES =Maximum Age Severe, MAXAGEM=Maximum Age Moderate, etc
"RTN","SPNAGGU",20,0)
 ;AGEL    =Low value of Age range, AGEH=High value of Age range
"RTN","SPNAGGU",21,0)
 ;SPNSEXS =No. of Male pts in Severe, SPNSEXM=No. Male in Moderate, etc
"RTN","SPNAGGU",22,0)
 ;SPNLORS =Cumulative Length of Rehab Severe, SPNLORM=Cum. LOR Mod, etc
"RTN","SPNAGGU",23,0)
 ;BMLS    =Base Minimum LOR Severe, BMLM=Base Minimum LOR Moderate, etc
"RTN","SPNAGGU",24,0)
 ;LORSC   =Length of Rehab Severe Count, LORMC=LOR Moderate Count, etc
"RTN","SPNAGGU",25,0)
 ;MINLORS =Minimum LOR Severe, MINLORM=Minimum LOR Moderate, etc
"RTN","SPNAGGU",26,0)
 ;BHLS    =Base Maximum LOR Severe, BHLM=Base Maximum LOR Moderate, etc
"RTN","SPNAGGU",27,0)
 ;MAXLORS =Maximum LOR Severe, MAXLORM=Maximum LOR Moderate, etc
"RTN","SPNAGGU",28,0)
 ;LORRN   =Length of Rehab record number (node w/ Rehab Finish data)
"RTN","SPNAGGU",29,0)
 ;LORL    =Low value of LOR range, LORH=High value of LOR range
"RTN","SPNAGGU",30,0)
 ;TFSRN   =Total FIM Start record number
"RTN","SPNAGGU",31,0)
 ;TFS     =Total FIM Start score, TFF=Total FIM Finish score
"RTN","SPNAGGU",32,0)
 ;TFCUMS  =Total FIM cumulative change Severe, TFCUMM=Tot FIM ch Mod,etc
"RTN","SPNAGGU",33,0)
 ;TFCS    =Total FIM Count Severe, TFCM=Total FIM Count Moderate, etc
"RTN","SPNAGGU",34,0)
 ;TFGRN   =Total FIM Goal record number
"RTN","SPNAGGU",35,0)
 ;TFG     =Total FIM Goal score
"RTN","SPNAGGU",36,0)
 ;TFGCUMS =Total FIM Goal cumul change Severe,TFGCUMM=TF Goal ch Mod,etc
"RTN","SPNAGGU",37,0)
 ;TFGCS   =Total FIM Goal Count Severe,TFGCM=Tot FIM Goal Count Mod, etc 
"RTN","SPNAGGU",38,0)
 ;COMDISS =No. of Severe pts w/ DISPOSITION<5, COMDISM=No. Mod pts, etc
"RTN","SPNAGGU",39,0)
 ;TFURN   =Total FIM Follow-Up record number
"RTN","SPNAGGU",40,0)
 ;TFU     =Total FIM Follow-Up score
"RTN","SPNAGGU",41,0)
 ;TFUCUMS =Total FIM F/U cumul change Severe,TFUCUMM=TF F/U ch Mod, etc
"RTN","SPNAGGU",42,0)
 ;TFUCS   =Total FIM F/U Count Severe,TFUCM=Tot FIM F/U Count Mod, etc
"RTN","SPNAGGU",43,0)
 ;SLSRN   =SWLS Start record number, SLFRN=SWLS Finish record number
"RTN","SPNAGGU",44,0)
 ;SLS     =SWLS Start score
"RTN","SPNAGGU",45,0)
 ;SLF     =SWLS Finish score
"RTN","SPNAGGU",46,0)
 ;SLCUMS  =SWLS cumul change Severe,SLCUMM=SWLS cumul change Mod, etc
"RTN","SPNAGGU",47,0)
 ;SLCS    =SWLS Count Severe,SLCM=Count Moderate, etc
"RTN","SPNAGGU",48,0)
 ;SLURN   =SWLS Follow-Up record number
"RTN","SPNAGGU",49,0)
 ;SLU     =SWLS Follow-Up score
"RTN","SPNAGGU",50,0)
 ;SLUCUMS =SWLS F/U cumul change Severe,SLUCUMM=SWLS F/U Chng Mod, etc
"RTN","SPNAGGU",51,0)
 ;SLUCS   =SWLS F/U Count Severe,SLUCM=SWLS F/U Count Mod, etc
"RTN","SPNAGGU",52,0)
 S U="^"
"RTN","SPNAGGU",53,0)
 S SPNDIAGC=0,SPNSEVC=0,SPNMODC=0,SPNPARC=0,SPNLOWC=0
"RTN","SPNAGGU",54,0)
 S SPNLSTDT="",SPNNODUP=""
"RTN","SPNAGGU",55,0)
 S SPNSDATE=0,SPNMDATE=0,SPNPDATE=0,SPNLDATE=0
"RTN","SPNAGGU",56,0)
 S SPNSEXS=0,SPNSEXM=0,SPNSEXP=0,SPNSEXL=0
"RTN","SPNAGGU",57,0)
 S SPNAGES=0,SPNAGEM=0,SPNAGEP=0,SPNAGEL=0
"RTN","SPNAGGU",58,0)
 S SPNT1=30,SPNT2=40,SPNT3=50,SPNT4=60,SPNT5=70
"RTN","SPNAGGU",59,0)
 S BMAS=0,BMAM=0,BMAP=0,BMAL=0,AGESC=0,AGEMC=0,AGEPC=0,AGELC=0
"RTN","SPNAGGU",60,0)
 S MINAGES=0,MINAGEM=0,MINAGEP=0,MINAGEL=0
"RTN","SPNAGGU",61,0)
 S MAXAGES=0,MAXAGEM=0,MAXAGEP=0,MAXAGEL=0
"RTN","SPNAGGU",62,0)
 S BHAS=0,BHAM=0,BHAP=0,BHAL=0
"RTN","SPNAGGU",63,0)
 S SPNLORS=0,SPNLORM=0,SPNLORP=0,SPNLORL=0
"RTN","SPNAGGU",64,0)
 S BMLS=0,BMLM=0,BMLP=0,BMLL=0,LORSC=0,LORMC=0,LORPC=0,LORLC=0
"RTN","SPNAGGU",65,0)
 S MINLORS=0,MINLORM=0,MINLORP=0,MINLORL=0
"RTN","SPNAGGU",66,0)
 S MAXLORS=0,MAXLORM=0,MAXLORP=0,MAXLORL=0
"RTN","SPNAGGU",67,0)
 S BHLS=0,BHLM=0,BHLP=0,BHLL=0,LORRN=0,V=0,LORL=0,LORH=0,AGEL=0,AGEH=0
"RTN","SPNAGGU",68,0)
 S TFSRN=0,TFS=0,TFF=0,TFCUMS=0,TFCUMM=0,TFCUMP=0,TFCUML=0
"RTN","SPNAGGU",69,0)
 S TFCS=0,TFCM=0,TFCP=0,TFCL=0
"RTN","SPNAGGU",70,0)
 S TFGRN=0,TFG=0,TFGCUMS=0,TFGCUMM=0,TFGCUMP=0,TFGCUML=0
"RTN","SPNAGGU",71,0)
 S TFGCS=0,TFGCM=0,TFGCP=0,TFGCL=0
"RTN","SPNAGGU",72,0)
 S COMDISS=0,COMDISM=0,COMDISP=0,COMDISL=0
"RTN","SPNAGGU",73,0)
 S TFURN=0,TFU=0,TFUCUMS=0,TFUCUMM=0,TFUCUMP=0,TFUCUML=0
"RTN","SPNAGGU",74,0)
 S TFUCS=0,TFUCM=0,TFUCP=0,TFUCL=0
"RTN","SPNAGGU",75,0)
 S SLSRN=0,SLFRN=0,SLS=0,SLF=0,SLCUMS=0,SLCUMM=0,SLCUMP=0,SLCUML=0
"RTN","SPNAGGU",76,0)
 S SLCS=0,SLCM=0,SLCP=0,SLCL=0
"RTN","SPNAGGU",77,0)
 S SLU=0,SLURN=0,SLUCUMS=0,SLUCUMM=0,SLUCUMP=0,SLUCUML=0
"RTN","SPNAGGU",78,0)
 S SLUCS=0,SLUCM=0,SLUCP=0,SLUCL=0
"RTN","SPNAGGU",79,0)
 Q
"RTN","SPNAGGU",80,0)
PARAMS ;
"RTN","SPNAGGU",81,0)
CT ;Care Type
"RTN","SPNAGGU",82,0)
CED ;date range for Care End Date
"RTN","SPNAGGU",83,0)
OIEN ;
"RTN","SPNAGGU",84,0)
DIAGCAT ;
"RTN","SPNAGGU",85,0)
 ;
"RTN","SPNAGGU",86,0)
MINLORS(SPNPD1) ;
"RTN","SPNAGGU",87,0)
 S MAX1=LORCALL
"RTN","SPNAGGU",88,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLRNS",X)) Q:'+X  D
"RTN","SPNAGGU",89,0)
 .Q:'$D(^TMP($J,"SPNLRNS",X))
"RTN","SPNAGGU",90,0)
 .S MAX2=$P(^TMP($J,"SPNLRNS",X),U,1)
"RTN","SPNAGGU",91,0)
 .I MAX2<MAX1 S MAX1=MAX2
"RTN","SPNAGGU",92,0)
 .Q
"RTN","SPNAGGU",93,0)
 Q MAX1
"RTN","SPNAGGU",94,0)
MAXLORS(SPNPD1) ;
"RTN","SPNAGGU",95,0)
 S MAX1=0
"RTN","SPNAGGU",96,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLRXS",X)) Q:'+X  D
"RTN","SPNAGGU",97,0)
 .Q:'$D(^TMP($J,"SPNLRXS",X))
"RTN","SPNAGGU",98,0)
 .S MAX2=$P(^TMP($J,"SPNLRXS",X),U,1)
"RTN","SPNAGGU",99,0)
 .I MAX2>MAX1 S MAX1=MAX2
"RTN","SPNAGGU",100,0)
 .Q
"RTN","SPNAGGU",101,0)
 Q MAX1
"RTN","SPNAGGU",102,0)
MINLORM(SPNPD1) ;
"RTN","SPNAGGU",103,0)
 S MAX1=LORCALL
"RTN","SPNAGGU",104,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLRNM",X)) Q:'+X  D
"RTN","SPNAGGU",105,0)
 .Q:'$D(^TMP($J,"SPNLRNM",X))
"RTN","SPNAGGU",106,0)
 .S MAX2=$P(^TMP($J,"SPNLRNM",X),U,1)
"RTN","SPNAGGU",107,0)
 .I MAX2<MAX1 S MAX1=MAX2
"RTN","SPNAGGU",108,0)
 .Q
"RTN","SPNAGGU",109,0)
 Q MAX1
"RTN","SPNAGGU",110,0)
MAXLORM(SPNPD1) ;
"RTN","SPNAGGU",111,0)
 S MAX1=0
"RTN","SPNAGGU",112,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLRXM",X)) Q:'+X  D
"RTN","SPNAGGU",113,0)
 .Q:'$D(^TMP($J,"SPNLRXM",X))
"RTN","SPNAGGU",114,0)
 .S MAX2=$P(^TMP($J,"SPNLRXM",X),U,1)
"RTN","SPNAGGU",115,0)
 .I MAX2>MAX1 S MAX1=MAX2
"RTN","SPNAGGU",116,0)
 .Q
"RTN","SPNAGGU",117,0)
 Q MAX1
"RTN","SPNAGGU",118,0)
MINLORP(SPNPD1) ;
"RTN","SPNAGGU",119,0)
 S MAX1=LORCALL
"RTN","SPNAGGU",120,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLRNP",X)) Q:'+X  D
"RTN","SPNAGGU",121,0)
 .Q:'$D(^TMP($J,"SPNLRNP",X))
"RTN","SPNAGGU",122,0)
 .S MAX2=$P(^TMP($J,"SPNLRNP",X),U,1)
"RTN","SPNAGGU",123,0)
 .I MAX2<MAX1 S MAX1=MAX2
"RTN","SPNAGGU",124,0)
 .Q
"RTN","SPNAGGU",125,0)
 Q MAX1
"RTN","SPNAGGU",126,0)
MAXLORP(SPNPD1) ;
"RTN","SPNAGGU",127,0)
 S MAX1=0
"RTN","SPNAGGU",128,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLRXP",X)) Q:'+X  D
"RTN","SPNAGGU",129,0)
 .Q:'$D(^TMP($J,"SPNLRXP",X))
"RTN","SPNAGGU",130,0)
 .S MAX2=$P(^TMP($J,"SPNLRXP",X),U,1)
"RTN","SPNAGGU",131,0)
 .I MAX2>MAX1 S MAX1=MAX2
"RTN","SPNAGGU",132,0)
 .Q
"RTN","SPNAGGU",133,0)
 Q MAX1
"RTN","SPNAGGU",134,0)
MINLORL(SPNPD1) ;
"RTN","SPNAGGU",135,0)
 S MAX1=LORCALL
"RTN","SPNAGGU",136,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLRNL",X)) Q:'+X  D
"RTN","SPNAGGU",137,0)
 .Q:'$D(^TMP($J,"SPNLRNL",X))
"RTN","SPNAGGU",138,0)
 .S MAX2=$P(^TMP($J,"SPNLRNL",X),U,1)
"RTN","SPNAGGU",139,0)
 .I MAX2<MAX1 S MAX1=MAX2
"RTN","SPNAGGU",140,0)
 .Q
"RTN","SPNAGGU",141,0)
 Q MAX1
"RTN","SPNAGGU",142,0)
MAXLORL(SPNPD1) ;
"RTN","SPNAGGU",143,0)
 S MAX1=0
"RTN","SPNAGGU",144,0)
 S X=0 F  S X=$O(^TMP($J,"SPNLRXL",X)) Q:'+X  D
"RTN","SPNAGGU",145,0)
 .Q:'$D(^TMP($J,"SPNLRXL",X))
"RTN","SPNAGGU",146,0)
 .S MAX2=$P(^TMP($J,"SPNLRXL",X),U,1)
"RTN","SPNAGGU",147,0)
 .I MAX2>MAX1 S MAX1=MAX2
"RTN","SPNAGGU",148,0)
 .Q
"RTN","SPNAGGU",149,0)
 Q MAX1
"RTN","SPNAGGU",150,0)
STATS ;finds record with Rehab Finish, so Length of Rehab can be obtained
"RTN","SPNAGGU",151,0)
 S LORRN=0,TFSRN=0,TFGRN=0
"RTN","SPNAGGU",152,0)
 S V=SPNPD1 F  S V=$O(^SPNL(154.1,"B",SPNPD0,V)) Q:'+V  D GETLOR
"RTN","SPNAGGU",153,0)
 Q
"RTN","SPNAGGU",154,0)
GETLOR ;gets Rec No. for LOR, TFS (TFF is same rec no. as LOR), and TFG
"RTN","SPNAGGU",155,0)
 Q:'$D(^SPNL(154.1,V,0))
"RTN","SPNAGGU",156,0)
 Q:'+$P(^SPNL(154.1,V,2),U,17)
"RTN","SPNAGGU",157,0)
 Q:$P($G(^SPNL(154.1,V,8)),U,3)'=CARETYP
"RTN","SPNAGGU",158,0)
 ;Q:$P($G(^SPNL(154.1,V,8)),U,2)<BDATE!($P($G(^SPNL(154.1,V,8)),U,2)>EDATE)
"RTN","SPNAGGU",159,0)
 I $P(^SPNL(154.1,V,2),U,17)=1,($P(^SPNL(154.1,V,0),U,2)=2) S TFSRN=V
"RTN","SPNAGGU",160,0)
 I $P(^SPNL(154.1,V,2),U,17)=2,($P(^SPNL(154.1,V,0),U,2)=2) S TFGRN=V
"RTN","SPNAGGU",161,0)
 I $P($G(^SPNL(154.1,V,8)),U,4)'="" S LORRN=V
"RTN","SPNAGGU",162,0)
 Q
"RTN","SPNAGGU",163,0)
EXIT ;
"RTN","SPNAGGU",164,0)
 K BDATE,EDATE,I,SPNLEXIT,SPNPD0,SPNPD1,SPNLSTDT,SPNDIAGC,SPNSEVC,SPNMODC,SPNPARC,SPNLOWC,SPNSDATE,SPNMDATE,SPNPDATE,SPNLDATE,SPNNODUP,SPNSEXS,SPNSEXM,SPNSEXP,SPNSEXL
"RTN","SPNAGGU",165,0)
 K SPNT1,SPNT2,SPNT3,SPNT4,SPNT5,SPNDCS,SPNDCM,SPNDCP,SPNDCL,SPNAGROU
"RTN","SPNAGGU",166,0)
 K SPNAGES,SPNAGEM,SPNAGEP,SPNAGEL
"RTN","SPNAGGU",167,0)
 K BMAS,BMAM,BMAP,BMAL,BHAS,BHAM,BHAP,BHAL
"RTN","SPNAGGU",168,0)
 K AGESC,AGEMC,AGEPC,AGELC,MINAGES,MINAGEM,MINAGEP,MINAGEL
"RTN","SPNAGGU",169,0)
 K MAXAGES,MAXAGEM,MAXAGEP,MAXAGEL,CARETYP,LINE
"RTN","SPNAGGU",170,0)
 K SPNLORS,SPNLORM,SPNLORP,SPNLORL
"RTN","SPNAGGU",171,0)
 K BMLS,BMLM,BMLP,BMLL,BHLS,BHLM,BHLP,BHLL
"RTN","SPNAGGU",172,0)
 K LORSC,LORMC,LORPC,LORLC,MINLORS,MINLORM,MINLORP,MINLORL
"RTN","SPNAGGU",173,0)
 K MAXLORS,MAXLORM,MAXLORP,MAXLORL,LORRN,V,LORL,LORH,AGEL,AGEH
"RTN","SPNAGGU",174,0)
 K TFSRN,TFS,TFF,TFCUMS,TFCUMM,TFCUMP,TFCUML,TFCS,TFCM,TFCP,TFCL
"RTN","SPNAGGU",175,0)
 K TFGRN,TFG,TFGCUMS,TFGCUMM,TFGCUMP,TFGCUML,TFGCS,TFGCM,TFGCP,TFGCL
"RTN","SPNAGGU",176,0)
 K COMDISS,COMDISM,COMDISP,COMDISL,ZTSAVE
"RTN","SPNAGGU",177,0)
 K TFURN,TFU,TFUCUMS,TFUCUMM,TFUCUMP,TFUCUML,TFUCS,TFUCM,TFUCP,TFUCL
"RTN","SPNAGGU",178,0)
 K SLSRN,SLFRN,SLS,SLF,SLCUMS,SLCUMM,SLCUMP,SLCUML,SLCS,SLCM,SLCP,SLCL
"RTN","SPNAGGU",179,0)
 K SLURN,SLU,SLUCUMS,SLUCUMM,SLUCUMP,SLUCUML,SLUCS,SLUCM,SLUCP,SLUCL
"RTN","SPNAGGU",180,0)
 K AGECALL,ASIAONE,ASIAFRTN,SEXCALL,LORCALL,LOR5CALL
"RTN","SPNAGGU",181,0)
 K TFSCALL,TFGCALL,TFUCALL,SLSCALL,SLFCALL,SLUCALL
"RTN","SPNAGGU",182,0)
 Q
"RTN","SPNCTINB")
0^3^B11500024
"RTN","SPNCTINB",1,0)
SPNCTINB ;WDE/SD INPATIENT CREATE NEW CARE POINT ;6/27/02  05:15
"RTN","SPNCTINB",2,0)
 ;;2.0;Spinal Cord Dysfunction;**19,21**;01/02/1997
"RTN","SPNCTINB",3,0)
 ;
"RTN","SPNCTINB",4,0)
 ; 
"RTN","SPNCTINB",5,0)
IN ;called when there are no episodes on file and to 
"RTN","SPNCTINB",6,0)
 ;start a new care episode
"RTN","SPNCTINB",7,0)
 ;Q:SPNFEXIT=1
"RTN","SPNCTINB",8,0)
 ;Q:$D(SPNFDFN)=""
"RTN","SPNCTINB",9,0)
 ;S SPNFEXIT=0,SPNEXIT=0
"RTN","SPNCTINB",10,0)
 ;S SPNDFN=SPNFDFN
"RTN","SPNCTINB",11,0)
 ;S SPNCT=1  ;inpatient
"RTN","SPNCTINB",12,0)
 ;        ;^ was entered or they are finished with the group
"RTN","SPNCTINB",13,0)
 ;Q
"RTN","SPNCTINB",14,0)
ZAP ;was used in another version no longer need but left for future use
"RTN","SPNCTINB",15,0)
 ;Q
"RTN","SPNCTINB",16,0)
ADD ; *** Add a record to the OUTCOMES file (#154.1)
"RTN","SPNCTINB",17,0)
 ;I $D(SPNQUIT) I SPNQUIT=1 Q
"RTN","SPNCTINB",18,0)
 I $P($G(^TMP($J,0)),U,2)>1 I $P($G(^TMP($J,0)),U,3)="" S SPNSEL="^" S SPNEXIT=1 D  Q  ;episode is not closed.
"RTN","SPNCTINB",19,0)
 .W !!?10,"You need to add an Outcome to the current episode and select"
"RTN","SPNCTINB",20,0)
 .W !?10,"a Score Type of INPT FOLLOW-UP (END)."
"RTN","SPNCTINB",21,0)
 .R !?15,"Press Return to continue ",SPNZ:DTIME K SPNZ
"RTN","SPNCTINB",22,0)
 .Q
"RTN","SPNCTINB",23,0)
 K DIR,DIC,%
"RTN","SPNCTINB",24,0)
 I $P($G(^TMP($J,0)),U,2)=0 D
"RTN","SPNCTINB",25,0)
 .W !,*7,?10,"There are no INPATIENT episodes of care on file."
"RTN","SPNCTINB",26,0)
 .W !?10,"(An ASIA should be entered first if an episode is created.)"
"RTN","SPNCTINB",27,0)
 .W !?10,"Would you like to create an episode of care"
"RTN","SPNCTINB",28,0)
 I $G(SPNSEL)["C" D
"RTN","SPNCTINB",29,0)
 .W !?10,"Would you like to create a new episode of care"
"RTN","SPNCTINB",30,0)
 S %=1 D YN^DICN
"RTN","SPNCTINB",31,0)
 ;I %Y="^" D ZAP^SPNCTINA G KILL^SPNCTINA:$G(^TMP($J,1))="" G RESTART^SPNCTINA
"RTN","SPNCTINB",32,0)
 I %Y="^" I $D(^TMP($J,1)) D ZAP^SPNCTINA G RESTART^SPNCTINA
"RTN","SPNCTINB",33,0)
 I %Y="^" I $D(^TMP($J,1))=0 D ZAP^SPNCTINA G KILL^SPNCTINA
"RTN","SPNCTINB",34,0)
 I %=2 I $D(^TMP($J,1))=0 G KILL^SPNCTINA
"RTN","SPNCTINB",35,0)
 I %=2 I $D(^TMP($J,1)) D ZAP^SPNCTINA G RESTART^SPNCTINA
"RTN","SPNCTINB",36,0)
 ;I %=2  W !,"zdz" H 2 G ZAP^SPNCTINA:$G(^TMP($J,1))="" G RESTART^SPNCTINA
"RTN","SPNCTINB",37,0)
 I %Y["?" D  G RESTART^SPNCTINA
"RTN","SPNCTINB",38,0)
 .W !!?5,"Enter a Y to create a new INPATIENT episode."
"RTN","SPNCTINB",39,0)
 .W !?5,"Enter a N or just Return to return to the last episode"
"RTN","SPNCTINB",40,0)
 .R !!?10,"Press Return to continue",SPNASK:DTIME K SPNASK W !
"RTN","SPNCTINB",41,0)
 I %'=1 D ZAP^SPNCTINA G RESTART^SPNCTINA Q
"RTN","SPNCTINB",42,0)
 I %'=1 D ZAP S SPNEXIT=1 Q
"RTN","SPNCTINB",43,0)
 ;
"RTN","SPNCTINB",44,0)
 S SPNSCOR=1,SPNXMIT=0,SPNEXIT=0
"RTN","SPNCTINB",45,0)
 I $G(SPNFDFN)="" I +$G(SPNDFN) S SPNFDFN=SPNDFN
"RTN","SPNCTINB",46,0)
 I SPNFDFN="" D ZAP^SPNOGRDA Q
"RTN","SPNCTINB",47,0)
 D REPT^SPNFEDT0(SPNFDFN)
"RTN","SPNCTINB",48,0)
 I $D(SPNFTYPE)=0 G ZAP^SPNCTINA Q
"RTN","SPNCTINB",49,0)
 I SPNFTYPE="" G ZAP^SPNCTINA Q  ;no fim record type selected
"RTN","SPNCTINB",50,0)
 I SPNEXIT=1 D ADD Q
"RTN","SPNCTINB",51,0)
 I '+SPNSCOR D ADD Q
"RTN","SPNCTINB",52,0)
 K DIR S DIR("A")="Enter a New Record Date: "
"RTN","SPNCTINB",53,0)
 D DATES  ;Date range set up of dir(0) set above as saftey
"RTN","SPNCTINB",54,0)
 D ^DIR
"RTN","SPNCTINB",55,0)
 I '+Y K DIR,Y S SPNFEXIT=1 Q
"RTN","SPNCTINB",56,0)
 S SPNDATE=Y
"RTN","SPNCTINB",57,0)
 K DD,DIC,DINUM,DO
"RTN","SPNCTINB",58,0)
 S SPNFD0=-1
"RTN","SPNCTINB",59,0)
 S DIC="^SPNL(154.1,",DIC(0)="L"
"RTN","SPNCTINB",60,0)
 S DLAYGO=154.1,X=SPNFDFN
"RTN","SPNCTINB",61,0)
 D FILE^DICN W ! S SPNFD0=+Y
"RTN","SPNCTINB",62,0)
 K DA,DIE,DR
"RTN","SPNCTINB",63,0)
 K ^TMP($J)  ;CLEAN UP THE LAST TABLE OF CARE
"RTN","SPNCTINB",64,0)
 I $G(SPNSCOR)="" S SPNSCOR=""
"RTN","SPNCTINB",65,0)
 S DIE="^SPNL(154.1,",DA=SPNFD0
"RTN","SPNCTINB",66,0)
 S SPNCDT=SPNDATE
"RTN","SPNCTINB",67,0)
 I SPNCDT="" W !,"No care start date is on file for this patient !" D ZAP Q
"RTN","SPNCTINB",68,0)
 S DR=".02///^S X="_SPNFTYPE_";.04///"_SPNDATE_";.021///"_SPNSCOR_";.023///"_$$EN^SPNMAIN(DUZ)_";1001///"_SPNCDT_";1003////1"
"RTN","SPNCTINB",69,0)
 D ^DIE
"RTN","SPNCTINB",70,0)
 S SPNNEW="YES"
"RTN","SPNCTINB",71,0)
 D EDIT^SPNFEDT0
"RTN","SPNCTINB",72,0)
 D ZAP^SPNCTINA
"RTN","SPNCTINB",73,0)
 S SPNFDFN=SPNDFN
"RTN","SPNCTINB",74,0)
 G RESTART^SPNCTINA
"RTN","SPNCTINB",75,0)
 Q
"RTN","SPNCTINB",76,0)
DATES ;set up upper and lower boundaries for the new record
"RTN","SPNCTINB",77,0)
 ;     If there is a care stop date that will be the upper
"RTN","SPNCTINB",78,0)
 ;     If there is a care start date that will be the lower
"RTN","SPNCTINB",79,0)
 ;     The new episode start date must be greater then any
"RTN","SPNCTINB",80,0)
 ;     other episodes on file 
"RTN","SPNCTINB",81,0)
 ;           
"RTN","SPNCTINB",82,0)
 ;    
"RTN","SPNCTINB",83,0)
 S (SPNX,SPNY)="",DIR(0)=""
"RTN","SPNCTINB",84,0)
 S SPNX=$P($G(^TMP($J,0)),U,2)
"RTN","SPNCTINB",85,0)
 S SPNY=$P($G(^TMP($J,0)),U,3)
"RTN","SPNCTINB",86,0)
 I SPNY'=""  S DIR(0)="DAO^"_SPNY_":"_DT_":EX" Q
"RTN","SPNCTINB",87,0)
 ;spny = close date
"RTN","SPNCTINB",88,0)
 I SPNX=0 I SPNY="" S DIR(0)="DAO^:NOW" Q
"RTN","SPNCTOUB")
0^4^B11481281
"RTN","SPNCTOUB",1,0)
SPNCTOUB ;WDE/SD OUTPATIENT CREATE NEW EPISODE ;6/27/02  05:15
"RTN","SPNCTOUB",2,0)
 ;;2.0;Spinal Cord Dysfunction;**19,21**;01/02/1997
"RTN","SPNCTOUB",3,0)
 ;
"RTN","SPNCTOUB",4,0)
 ; 
"RTN","SPNCTOUB",5,0)
IN ;called when there are no episodes on file and to 
"RTN","SPNCTOUB",6,0)
 ;start a new care episode
"RTN","SPNCTOUB",7,0)
 ;Q:SPNFEXIT=1
"RTN","SPNCTOUB",8,0)
 ;Q:$D(SPNFDFN)=""
"RTN","SPNCTOUB",9,0)
 ;S SPNFEXIT=0,SPNEXIT=0
"RTN","SPNCTOUB",10,0)
 ;S SPNDFN=SPNFDFN
"RTN","SPNCTOUB",11,0)
 ;S SPNCT=1  ;inpatient
"RTN","SPNCTOUB",12,0)
 ;;        ;^ was entered or they are finished with the group
"RTN","SPNCTOUB",13,0)
 ;I SPNSEL'="A" D ZAP Q
"RTN","SPNCTOUB",14,0)
 ;I SPNEXIT=1 D ZAP Q
"RTN","SPNCTOUB",15,0)
 ;Q
"RTN","SPNCTOUB",16,0)
ZAP ;
"RTN","SPNCTOUB",17,0)
 Q
"RTN","SPNCTOUB",18,0)
ADD ; *** Add a record to the OUTCOMES file (#154.1)
"RTN","SPNCTOUB",19,0)
 I $P($G(^TMP($J,0)),U,2)>1 I $P($G(^TMP($J,0)),U,3)="" S SPNSEL="^" S SPNEXIT=1 D  Q  ;episode is not closed.
"RTN","SPNCTOUB",20,0)
 .W !!?10,"You need to add an Outcome to the current episode and select"
"RTN","SPNCTOUB",21,0)
 .W !?10,"a Score Type of OUTPT FOLLOW-UP (END)."
"RTN","SPNCTOUB",22,0)
 .R !?15,"Press Return to continue ",SPNZ:DTIME K SPNZ
"RTN","SPNCTOUB",23,0)
 .Q
"RTN","SPNCTOUB",24,0)
 I $P($G(^TMP($J,0)),U,2)=0 D
"RTN","SPNCTOUB",25,0)
 .W !,*7,?10,"There are no OUTPATIENT episodes of care on file."
"RTN","SPNCTOUB",26,0)
 .W !?10,"(An ASIA should be entered first if an episode is created.)"
"RTN","SPNCTOUB",27,0)
 .W !?10,"Would you like to create an episode of care"
"RTN","SPNCTOUB",28,0)
 I $G(SPNSEL)["C" D
"RTN","SPNCTOUB",29,0)
 .W !?10,"Would you like to create a new episode of care"
"RTN","SPNCTOUB",30,0)
 S %=1 D YN^DICN
"RTN","SPNCTOUB",31,0)
 I %Y="^" I $D(^TMP($J,1)) D ZAP^SPNCTINA G RESTART^SPNCTOUA
"RTN","SPNCTOUB",32,0)
 I %Y="^" I $D(^TMP($J,1))=0 D ZAP^SPNCTINA G KILL^SPNCTINA
"RTN","SPNCTOUB",33,0)
 I %=2 I $D(^TMP($J,1))=0 G KILL^SPNCTINA
"RTN","SPNCTOUB",34,0)
 I %=2 I $D(^TMP($J,1)) D ZAP^SPNCTINA G RESTART^SPNCTOUA
"RTN","SPNCTOUB",35,0)
 I %Y["?" D  G RESTART^SPNCTOUA
"RTN","SPNCTOUB",36,0)
 .W !!?5,"Enter a Y to create a new OUTPATIENT episode."
"RTN","SPNCTOUB",37,0)
 .W !?5,"Enter a N or just Return to return to the last episode"
"RTN","SPNCTOUB",38,0)
 .R !!?10,"Press Return to continue",SPNASK:DTIME K SPNASK W !
"RTN","SPNCTOUB",39,0)
 I %'=1 D ZAP^SPNCTINA G RESTART^SPNCTOUA Q
"RTN","SPNCTOUB",40,0)
 I %'=1 D ZAP S SPNXIT=1 Q
"RTN","SPNCTOUB",41,0)
 ;set the score type to outpt start
"RTN","SPNCTOUB",42,0)
 S SPNSCOR=6,SPNXMIT=0,SPNEXIT=0
"RTN","SPNCTOUB",43,0)
 I $G(SPNFDFN)="" I +$G(SPNDFN) S SPNFDFN=SPNDFN
"RTN","SPNCTOUB",44,0)
 I SPNFDFN="" D ZAP^SPNOGRDA Q
"RTN","SPNCTOUB",45,0)
 D REPT^SPNFEDT0(SPNFDFN)
"RTN","SPNCTOUB",46,0)
 I $D(SPNFTYPE)=0 D ZAP Q
"RTN","SPNCTOUB",47,0)
 I SPNFTYPE="" D ZAP Q  ;no fim record type selected
"RTN","SPNCTOUB",48,0)
 I SPNEXIT=1 D ZAP Q
"RTN","SPNCTOUB",49,0)
 I '+SPNSCOR D ZAP Q
"RTN","SPNCTOUB",50,0)
 K DIR S DIR("A")="Enter a New Record Date: "
"RTN","SPNCTOUB",51,0)
 ;
"RTN","SPNCTOUB",52,0)
 D DATES  ;Date range set up of dir(0) set above as saftey
"RTN","SPNCTOUB",53,0)
 D ^DIR
"RTN","SPNCTOUB",54,0)
 I '+Y K DIR,Y S SPNFEXIT=1 Q
"RTN","SPNCTOUB",55,0)
 S SPNDATE=Y
"RTN","SPNCTOUB",56,0)
 K DD,DIC,DINUM,DO
"RTN","SPNCTOUB",57,0)
 S SPNFD0=-1
"RTN","SPNCTOUB",58,0)
 S DIC="^SPNL(154.1,",DIC(0)="L"
"RTN","SPNCTOUB",59,0)
 S DLAYGO=154.1,X=SPNFDFN
"RTN","SPNCTOUB",60,0)
 D FILE^DICN W ! S SPNFD0=+Y
"RTN","SPNCTOUB",61,0)
 K DA,DIE,DR
"RTN","SPNCTOUB",62,0)
 K ^TMP($J)  ;CLEAN UP THE LAST TABLE OF CARE
"RTN","SPNCTOUB",63,0)
 I $G(SPNSCOR)="" S SPNSCOR=""
"RTN","SPNCTOUB",64,0)
 S DIE="^SPNL(154.1,",DA=SPNFD0
"RTN","SPNCTOUB",65,0)
 S SPNCDT=SPNDATE
"RTN","SPNCTOUB",66,0)
 I SPNCDT="" W !,"No care start date is on file for this patient!" D ZAP Q
"RTN","SPNCTOUB",67,0)
 S DR=".02///^S X="_SPNFTYPE_";.04///"_SPNDATE_";.021///"_SPNSCOR_";.023///"_$$EN^SPNMAIN(DUZ)_";1001///"_SPNCDT_";1003////2"
"RTN","SPNCTOUB",68,0)
 D ^DIE
"RTN","SPNCTOUB",69,0)
 S SPNNEW="YES"
"RTN","SPNCTOUB",70,0)
 D EDIT^SPNFEDT0
"RTN","SPNCTOUB",71,0)
 D ZAP^SPNCTINA
"RTN","SPNCTOUB",72,0)
 S SPNFDFN=SPNDFN
"RTN","SPNCTOUB",73,0)
 G RESTART^SPNCTOUA
"RTN","SPNCTOUB",74,0)
 Q
"RTN","SPNCTOUB",75,0)
DATES ;set up upper and lower boundaries for the new record
"RTN","SPNCTOUB",76,0)
 ;     If there is a care stop date that will be the upper
"RTN","SPNCTOUB",77,0)
 ;     If there is a care start date that will be the lower
"RTN","SPNCTOUB",78,0)
 ;     Note that TMP is 2nd and 3rd piece is the care start
"RTN","SPNCTOUB",79,0)
 ;                      and endates
"RTN","SPNCTOUB",80,0)
 ;           So if they are adding a outcome to a closed episode
"RTN","SPNCTOUB",81,0)
 ;           piece 2 and 3 will be present.
"RTN","SPNCTOUB",82,0)
 S (SPNX,SPNY)="",DIR(0)=""
"RTN","SPNCTOUB",83,0)
 S SPNX=$P($G(^TMP($J,0)),U,2)
"RTN","SPNCTOUB",84,0)
 S SPNY=$P($G(^TMP($J,0)),U,3)
"RTN","SPNCTOUB",85,0)
 I SPNY'=""  S DIR(0)="DAO^"_SPNY_":"_DT_":EX" Q
"RTN","SPNCTOUB",86,0)
 ;spny = close date
"RTN","SPNCTOUB",87,0)
 I SPNX=0 I SPNY="" S DIR(0)="DAO^:NOW" Q
"RTN","SPNCTSHO")
0^12^B13517194
"RTN","SPNCTSHO",1,0)
SPNCTSHO ;WDE/SD SHOW ANN AND CONT ;6/27/02  05:15
"RTN","SPNCTSHO",2,0)
 ;;2.0;Spinal Cord Dysfunction;**19,20,21**;01/02/1997
"RTN","SPNCTSHO",3,0)
 ;
"RTN","SPNCTSHO",4,0)
 ; 
"RTN","SPNCTSHO",5,0)
EN(SPNDFN) ;
"RTN","SPNCTSHO",6,0)
 ;
"RTN","SPNCTSHO",7,0)
 ;S SPNA=$P($G(^TMP($J,0)),U,2)
"RTN","SPNCTSHO",8,0)
 ;I (SPNA=0)!(SPNA="") S SPNEXIT=1 Q  ;no care episodes on file
"RTN","SPNCTSHO",9,0)
 D HDR
"RTN","SPNCTSHO",10,0)
 D SHOW
"RTN","SPNCTSHO",11,0)
 Q
"RTN","SPNCTSHO",12,0)
SHOW ;       display records in ^tmp($j
"RTN","SPNCTSHO",13,0)
 S (SPNOTOL,SPNFD0,SPNOTNE,SPNW,SPNX,SPNY,SPNZ,SPNIEN,SPNSEL,SPNEXIT,SPNSUB,SPNFD0)=0
"RTN","SPNCTSHO",14,0)
 ;    spnw = number spnx = outcome type spny= date recorded
"RTN","SPNCTSHO",15,0)
 S SPNOUT=0
"RTN","SPNCTSHO",16,0)
 S SPNW=0 F  S SPNW=$O(^TMP($J,SPNW)) Q:SPNW=""   S SPNX=0 F OUT=1:1 S SPNX=$O(^TMP($J,SPNW,SPNX)) Q:SPNX=""  S SPNY=0 F  S SPNY=$O(^TMP($J,SPNW,SPNX,SPNY)) Q:(SPNY="")!('+SPNY)  D  I SPNEXIT=1 S OUT=99999 Q
"RTN","SPNCTSHO",17,0)
 .Q:SPNOUT=1
"RTN","SPNCTSHO",18,0)
 .S SPNFIEN=0 S SPNFIEN=$G(^TMP($J,SPNW,SPNX,SPNY))
"RTN","SPNCTSHO",19,0)
 .W !,SPNW,") ",$$FMTE^XLFDT(SPNX,"5DZP")
"RTN","SPNCTSHO",20,0)
 .I SPNCTYP=3 W ?15,$$GET1^DIQ(154.1,SPNFIEN_",",.02)
"RTN","SPNCTSHO",21,0)
 .I SPNCTYP=4 W ?15,$$GET1^DIQ(154.1,SPNFIEN_",",.021),?38,$$GET1^DIQ(154.1,SPNFIEN_",",.02)
"RTN","SPNCTSHO",22,0)
 .S SPNEDSS=$P($G(^SPNL(154.1,SPNFIEN,"MS")),U,9) I SPNEDSS'=""  W ?62,"EDSS: ",$P($G(^SPNL(154.2,SPNEDSS,0)),U,1)
"RTN","SPNCTSHO",23,0)
 .S SPNSUB=SPNSUB+1,SPNLINE=SPNLINE+1
"RTN","SPNCTSHO",24,0)
 .I SPNLINE>15 D SEL I SPNEXIT=0 I SPNFD0=0 D HDR
"RTN","SPNCTSHO",25,0)
 .I +SPNFD0 Q
"RTN","SPNCTSHO",26,0)
 .Q:SPNOUT=1
"RTN","SPNCTSHO",27,0)
 Q:SPNOUT=1
"RTN","SPNCTSHO",28,0)
 I '+SPNFD0 I SPNEXIT=0 D SEL
"RTN","SPNCTSHO",29,0)
 Q
"RTN","SPNCTSHO",30,0)
HDR ;
"RTN","SPNCTSHO",31,0)
 I $D(IOF) W @IOF
"RTN","SPNCTSHO",32,0)
 S OUT=0
"RTN","SPNCTSHO",33,0)
 S SPNCTYP=$P($G(^TMP($J,0)),U,4)
"RTN","SPNCTSHO",34,0)
 I $D(SPNHDR)=0 S SPNHDR=" Episodes of care"
"RTN","SPNCTSHO",35,0)
 W !?20,SPNHDR
"RTN","SPNCTSHO",36,0)
 S SPNSSN=$P($G(^DPT(SPNDFN,0)),U,9) S SPNSSN=$E(SPNSSN,1,3)_"-"_$E(SPNSSN,4,5)_"-"_$E(SPNSSN,6,9)
"RTN","SPNCTSHO",37,0)
 W !!,"Patient: ",$P(^DPT(SPNDFN,0),U,1),"    SSN: ",SPNSSN
"RTN","SPNCTSHO",38,0)
 W !,"--------------------------------------------------------------------------"
"RTN","SPNCTSHO",39,0)
 S SPNLINE=3
"RTN","SPNCTSHO",40,0)
 Q
"RTN","SPNCTSHO",41,0)
SEL ;prompt for a selection from the list
"RTN","SPNCTSHO",42,0)
 Q:SPNOUT=1
"RTN","SPNCTSHO",43,0)
 S (SPNSEL,SPNEXIT,Y)=0,SPNTOT=$P($G(^TMP($J,0)),U,1)
"RTN","SPNCTSHO",44,0)
 W !,"--------------------------------------------------------------------------"
"RTN","SPNCTSHO",45,0)
 I SPNSUB=0 W !?2,"There are no ",SPNHDR," Outcomes on file.",!?2,"(An ASIA should be entered first if you add outcomes.)"
"RTN","SPNCTSHO",46,0)
 I SPNSUB>0 W !?2,"Select 1-",SPNSUB," of ",SPNTOT," to view/edit an outcome, '^' to exit, or " I SPNSUB'=SPNTOT W "press"
"RTN","SPNCTSHO",47,0)
 I SPNSUB>0 I SPNSUB'=SPNTOT W !?2,"<Return> to see the next group"
"RTN","SPNCTSHO",48,0)
 W !?2,"<A> to Add a new outcome"
"RTN","SPNCTSHO",49,0)
PICK R !?5,"Selection: ",SPNSEL:DTIME
"RTN","SPNCTSHO",50,0)
 I SPNSEL["?" W !?2,"Enter a number within the range allowed, or one of the designated keys." G PICK
"RTN","SPNCTSHO",51,0)
 I SPNSEL=0 W !,$C(7),?10,"Selected number is outside the range." G PICK
"RTN","SPNCTSHO",52,0)
 I "Aa^"'[SPNSEL,(SPNSEL'?1.5N) W !,$C(7) G PICK
"RTN","SPNCTSHO",53,0)
 I SPNSEL="a" S SPNSEL="A"
"RTN","SPNCTSHO",54,0)
 I SPNSEL="A" S SPNEXIT=1 S SPNOUT=1 Q
"RTN","SPNCTSHO",55,0)
 I SPNSEL="^" S SPNEXIT=1 S SPNOUT=1 Q
"RTN","SPNCTSHO",56,0)
 I (SPNSEL>$P($G(^TMP($J,0)),U,1))!(SPNSEL>SPNSUB) W !,$C(7),?10,"Selected number is outside the range." G PICK
"RTN","SPNCTSHO",57,0)
 I SPNSEL="" I SPNSUB=SPNTOT S SPNEXIT=1 Q
"RTN","SPNCTSHO",58,0)
 I SPNEXIT=0  I +SPNSEL I $D(^TMP($J,SPNSEL))  D
"RTN","SPNCTSHO",59,0)
 .S (SPNB,SPNX)=""
"RTN","SPNCTSHO",60,0)
 .S SPNB=$O(^TMP($J,SPNSEL,SPNB))
"RTN","SPNCTSHO",61,0)
 .S SPNX=$O(^TMP($J,SPNSEL,SPNB,SPNX))
"RTN","SPNCTSHO",62,0)
 .S SPNFD0=$P($G(^TMP($J,SPNSEL,SPNB,SPNX)),U,1)
"RTN","SPNCTSHO",63,0)
 .I SPNFD0="" S SPNFD0="" S SPNEXIT=1 Q
"RTN","SPNCTSHO",64,0)
 .S SPNFTYPE=$P($G(^SPNL(154.1,SPNFD0,0)),U,2)
"RTN","SPNCTSHO",65,0)
 .I SPNFTYPE="" S SPNEXIT=1 Q
"RTN","SPNCTSHO",66,0)
 .S SPNOUT=1 S OUT=99999 Q
"RTN","SPNCTSHO",67,0)
 I SPNEXIT=1 S SPNOUT=1
"RTN","SPNCTSHO",68,0)
 Q
"RTN","SPNFMENU")
0^1^B9208049
"RTN","SPNFMENU",1,0)
SPNFMENU ;HISC/DAD/WAA-INPUT/OUTPUT MENU PROCESS ;8/19/96  11:06
"RTN","SPNFMENU",2,0)
 ;;2.0;Spinal Cord Dysfunction;**12,19,20,21**;01/02/1997
"RTN","SPNFMENU",3,0)
 ;
"RTN","SPNFMENU",4,0)
 ; This program is a menu program that allow the user to maintain
"RTN","SPNFMENU",5,0)
 ; the current patient and system varables.
"RTN","SPNFMENU",6,0)
 ; 
"RTN","SPNFMENU",7,0)
 ; This program will be called from the three major
"RTN","SPNFMENU",8,0)
 ; screen edit programs and allow the user to select another
"RTN","SPNFMENU",9,0)
 ; for those programs.
"RTN","SPNFMENU",10,0)
 ; 
"RTN","SPNFMENU",11,0)
 ; Input:
"RTN","SPNFMENU",12,0)
 ;     SPNFDFN = Patient DFN within file 2
"RTN","SPNFMENU",13,0)
 ;     SPNFREG = The menu Manager option that called him.
"RTN","SPNFMENU",14,0)
 ;
"RTN","SPNFMENU",15,0)
MENU(SPNFREG,SPNFDFN) ; Main menu loop
"RTN","SPNFMENU",16,0)
 ; This is to select the type of data to enter for a patient.
"RTN","SPNFMENU",17,0)
 ; If none of the give report are selected then SPNFEXIT is set to 1
"RTN","SPNFMENU",18,0)
 ; and the program exits.
"RTN","SPNFMENU",19,0)
 ; Returns SPNFREG as a value of 1 to 4 indicating the type
"RTN","SPNFMENU",20,0)
 ; of OPTION to be USED.
"RTN","SPNFMENU",21,0)
 ; Input:
"RTN","SPNFMENU",22,0)
 ;      SPNFREG = Menu Option
"RTN","SPNFMENU",23,0)
 ;      SPNFDFN = Patient DFN
"RTN","SPNFMENU",24,0)
 ;
"RTN","SPNFMENU",25,0)
 ; Output:
"RTN","SPNFMENU",26,0)
 ;      SPNFEXIT = 1 User exited
"RTN","SPNFMENU",27,0)
 ;                 0 User passed
"RTN","SPNFMENU",28,0)
 K DIRUT
"RTN","SPNFMENU",29,0)
 N SPNFREG1
"RTN","SPNFMENU",30,0)
 S SPNFEXIT=0
"RTN","SPNFMENU",31,0)
 D  G:SPNFEXIT EXIT
"RTN","SPNFMENU",32,0)
 . I SPNFDFN=0 D PAT^SPNFMENU Q:SPNFEXIT
"RTN","SPNFMENU",33,0)
 . I SPNFREG=0 D
"RTN","SPNFMENU",34,0)
 . .D  ; Menu Header
"RTN","SPNFMENU",35,0)
 . . .S DFN=SPNFDFN
"RTN","SPNFMENU",36,0)
 . . .D DEM^VADPT
"RTN","SPNFMENU",37,0)
 . . .W !!,"Patient: ",VADM(1),"  ",$P(VADM(2),U,2)
"RTN","SPNFMENU",38,0)
 . . .W ?60,"DOB: ",$P(VADM(3),U,2)
"RTN","SPNFMENU",39,0)
 . . .D KVAR^VADPT
"RTN","SPNFMENU",40,0)
 . . .Q
"RTN","SPNFMENU",41,0)
 . .K DIR S DIR(0)="SOM^1:Registration and Health Care Information;2:Outcome Information;3:Clinical Information;4:Select a NEW Patient"
"RTN","SPNFMENU",42,0)
 . .S DIR("A")="Select the type of record you wish to enter/edit"
"RTN","SPNFMENU",43,0)
 . .S DIR("?",1)="   Enter 1 to enter/edit Registration and Health Care Information"
"RTN","SPNFMENU",44,0)
 . .S DIR("?",2)="   Enter 2 to enter/edit Outcome Information"
"RTN","SPNFMENU",45,0)
 . .S DIR("?",3)="   Enter 3 to enter/edit Clinical Information"
"RTN","SPNFMENU",46,0)
 . .S DIR("?",4)="   Enter 4 to Select a NEW Patient"
"RTN","SPNFMENU",47,0)
 . .S DIR("?")="   Choose either 1,2,3, or 4."
"RTN","SPNFMENU",48,0)
 . .W ! D ^DIR K DIR S SPNFREG=+Y
"RTN","SPNFMENU",49,0)
 . .I $D(DIRUT) S:$D(DTOUT)!($D(DUOUT)) SPNFEXIT=1 Q
"RTN","SPNFMENU",50,0)
 . .Q
"RTN","SPNFMENU",51,0)
 . I SPNFREG=0 S SPNFEXIT=1 Q
"RTN","SPNFMENU",52,0)
 . D EDIT(SPNFREG,.SPNFDFN)
"RTN","SPNFMENU",53,0)
 . S SPNFREG=0
"RTN","SPNFMENU",54,0)
 . Q
"RTN","SPNFMENU",55,0)
 Q
"RTN","SPNFMENU",56,0)
EXIT K DA,DDSCHANG,DDSFILE,DDSSAVE,DIC,DIE,DIMSG,DR,DTOUT
"RTN","SPNFMENU",57,0)
 K SPNFFIM,SPNLD0,SPNFDFN,SPNLFLAG,X,Y
"RTN","SPNFMENU",58,0)
 Q
"RTN","SPNFMENU",59,0)
 ;
"RTN","SPNFMENU",60,0)
EDIT(SPNFTYPE,SPNFDFN) ; *** Choose add / edit a record
"RTN","SPNFMENU",61,0)
 ;  SPNFTYPE = 1 - Registration and Health Care Information
"RTN","SPNFMENU",62,0)
 ;             2 - Outcome Information
"RTN","SPNFMENU",63,0)
 ;             3 - Clinical Information
"RTN","SPNFMENU",64,0)
 ;             4 - Select a NEW Patient
"RTN","SPNFMENU",65,0)
 ;  SPNFDFN  = DFN in PATIENT file (#2)
"RTN","SPNFMENU",66,0)
 S SPNFEXIT=0
"RTN","SPNFMENU",67,0)
 I SPNFTYPE=2 D REPT^SPNFEDT0(SPNFDFN) Q
"RTN","SPNFMENU",68,0)
 I SPNFTYPE=1!(SPNFTYPE=3) D  Q
"RTN","SPNFMENU",69,0)
 .D PAT^SPNFEDT1(SPNFTYPE,SPNFDFN)
"RTN","SPNFMENU",70,0)
 .Q
"RTN","SPNFMENU",71,0)
 I SPNFTYPE=4 D PAT^SPNFMENU Q
"RTN","SPNFMENU",72,0)
 Q
"RTN","SPNFMENU",73,0)
 ;
"RTN","SPNFMENU",74,0)
PAT ;Select a patient from the patient file
"RTN","SPNFMENU",75,0)
 ;    Return list:
"RTN","SPNFMENU",76,0)
 ;          SPNFDFN = If DFN is null patient DFN from the patient file
"RTN","SPNFMENU",77,0)
 ;          SPNFMS  = 1 patient has MS Etiology
"RTN","SPNFMENU",78,0)
 ;                    0 Patient doesn't have MS
"RTN","SPNFMENU",79,0)
 ;
"RTN","SPNFMENU",80,0)
 I SPNFREG=3 D PAT1541 Q  ;USED TO ROUTE USER ON THE CLINICAL DATA
"RTN","SPNFMENU",81,0)
 S SPNFEXIT=0
"RTN","SPNFMENU",82,0)
 K DIC
"RTN","SPNFMENU",83,0)
 W ! S DLAYGO=154,DIC="^SPNL(154,",DIC(0)="AELMQ" D ^DIC
"RTN","SPNFMENU",84,0)
 I +Y'>0 S SPNFEXIT=1 Q
"RTN","SPNFMENU",85,0)
 S SPNFDFN=+Y
"RTN","SPNFMENU",86,0)
 Q
"RTN","SPNFMENU",87,0)
PAT1541 ;Used to look up patients for Outcomes info or Clinical info
"RTN","SPNFMENU",88,0)
 S SPNFEXIT=0
"RTN","SPNFMENU",89,0)
 K DIC
"RTN","SPNFMENU",90,0)
 S DIC("A")="Select SCD (SPINAL CORD) REGISTRY PATIENT: "
"RTN","SPNFMENU",91,0)
 S DIC="^SPNL(154,",DIC(0)="AEMQ" D ^DIC  ;no help text
"RTN","SPNFMENU",92,0)
 I +Y'>0 S SPNFEXIT=1 Q
"RTN","SPNFMENU",93,0)
 S SPNFDFN=+Y
"RTN","SPNPRI21")
0^6^B118828
"RTN","SPNPRI21",1,0)
SPNPRI21 ;SD/CM- Pre init action for patch 21; 8-20-2003
"RTN","SPNPRI21",2,0)
 ;;2.0;Spinal Cord Dysfunction;**21**;01/02/1997
"RTN","SPNPRI21",3,0)
EN ;
"RTN","SPNPRI21",4,0)
 S DA=""
"RTN","SPNPRI21",5,0)
 S DA=$O(^SPNL(154.92,"B","OUTCOMES",DA))
"RTN","SPNPRI21",6,0)
 I DA="" K DA Q
"RTN","SPNPRI21",7,0)
 S DIK="^SPNL(154.92,"
"RTN","SPNPRI21",8,0)
 D ^DIK
"RTN","SPNPRI21",9,0)
 K DA,DIK
"RTN","SPNPRI21",10,0)
 Q
"RTN","SPNPRT13")
0^2^B22128448
"RTN","SPNPRT13",1,0)
SPNPRT13 ;SD/CM- PRINT ADMISSIONS REPORT BY DATE RANGE ;8/29/2000
"RTN","SPNPRT13",2,0)
 ;;2.0;Spinal Cord Dysfunction;**13,21**;01/02/1997
"RTN","SPNPRT13",3,0)
EN1 ; Main Entry Point
"RTN","SPNPRT13",4,0)
 N SPNLEXIT,SPNIO,SPNPAGE,SPNDATE,SPNEDAT S SPNPAGE=1
"RTN","SPNPRT13",5,0)
 S SPNLEXIT=0,U="^"
"RTN","SPNPRT13",6,0)
 S SPNA="   Enter START Date: "
"RTN","SPNPRT13",7,0)
 S SPNQ=" Enter the earliest date of Admission for the print to START at."
"RTN","SPNPRT13",8,0)
 D QUEST^SPNPRT04("DA^:NOW:EP",SPNA,SPNQ) Q:SPNLEXIT
"RTN","SPNPRT13",9,0)
 S SPNDATE=Y
"RTN","SPNPRT13",10,0)
 S ZTSAVE("SPN*")=""
"RTN","SPNPRT13",11,0)
 S SPNA="   Enter END Date: "
"RTN","SPNPRT13",12,0)
 S SPNQ=" Enter the latest date of Admission for the print to END with."
"RTN","SPNPRT13",13,0)
 D QUEST^SPNPRT04("DA^"_SPNDATE_":NOW:EP",SPNA,SPNQ) Q:SPNLEXIT
"RTN","SPNPRT13",14,0)
 S SPNEDAT=Y
"RTN","SPNPRT13",15,0)
 D DEVICE^SPNPRTMT("PRINT^SPNPRT13","SCD Admissions",.ZTSAVE) Q:SPNLEXIT
"RTN","SPNPRT13",16,0)
 I SPNIO="Q" D EXIT Q  ; Print was Queued
"RTN","SPNPRT13",17,0)
 I IO'="" D PRINT D EXIT Q  ; Print was not Queued
"RTN","SPNPRT13",18,0)
 Q
"RTN","SPNPRT13",19,0)
EXIT ; Exit routine 
"RTN","SPNPRT13",20,0)
 K ^TMP($J,"SPN")
"RTN","SPNPRT13",21,0)
 K SPNA,SPNIEN,SPNLPRT,SPNQ,SPNQDAT,SPNDATE,VADM,VAIP,ZTSAVE
"RTN","SPNPRT13",22,0)
 Q
"RTN","SPNPRT13",23,0)
PRINT ; Print main Body
"RTN","SPNPRT13",24,0)
 U IO
"RTN","SPNPRT13",25,0)
 K ^TMP($J,"SPN")
"RTN","SPNPRT13",26,0)
 S SPNLEXIT=$G(SPNLEXIT,0) ; Ensure that the exit is set
"RTN","SPNPRT13",27,0)
 N SPNDFN,SPNX
"RTN","SPNPRT13",28,0)
 S (SPNDFN,SPNLPRT)=0
"RTN","SPNPRT13",29,0)
 S SPNQDAT=SPNDATE-.000001
"RTN","SPNPRT13",30,0)
 Q:SPNLEXIT
"RTN","SPNPRT13",31,0)
 S SPNQDAT=SPNDATE-000001 F  S SPNQDAT=$O(^DGPM("B",SPNQDAT)) Q:'+SPNQDAT  Q:(SPNQDAT>SPNEDAT)  D  Q:SPNLEXIT
"RTN","SPNPRT13",32,0)
 . S SPNIEN=0 F  S SPNIEN=$O(^DGPM("B",SPNQDAT,SPNIEN)) Q:'+SPNIEN  D:$P($G(^DGPM(SPNIEN,0)),U,2)=1  Q:SPNLEXIT
"RTN","SPNPRT13",33,0)
 .. S SPNDFN=$P(^DGPM(SPNIEN,0),U,3)
"RTN","SPNPRT13",34,0)
 .. N DFN,SPNLINE
"RTN","SPNPRT13",35,0)
 .. I '$D(^SPNL(154,SPNDFN,0)),'(+$$GET1^DIQ(2,SPNDFN,57.4,"I")) Q
"RTN","SPNPRT13",36,0)
 .. S DFN=SPNDFN,VAIP("E")=SPNIEN D IN5^VADPT
"RTN","SPNPRT13",37,0)
 .. ; SPNLINE=Admission date(E)^Ward location(E)^Room-Bed(E)^Adm date^Pointer to PTF
"RTN","SPNPRT13",38,0)
 .. S SPNLINE=$P(VAIP(3),U,1)_U_$P(VAIP(5),U,2)_U_$P(VAIP(6),U,2)_U_SPNQDAT_U_VAIP(12)
"RTN","SPNPRT13",39,0)
 .. S ^TMP($J,"SPN",$$GET1^DIQ(2,SPNDFN,.01,"E"),SPNDFN,SPNIEN)=SPNLINE
"RTN","SPNPRT13",40,0)
 .. D KVAR^VADPT
"RTN","SPNPRT13",41,0)
 .. Q
"RTN","SPNPRT13",42,0)
 . Q
"RTN","SPNPRT13",43,0)
 I $D(^TMP($J,"SPN")) D  Q:SPNLEXIT  ; Indicates the report had data
"RTN","SPNPRT13",44,0)
 . N SPNDFN,SPNNAME,SPNCOU
"RTN","SPNPRT13",45,0)
 . S SPNCOU=0
"RTN","SPNPRT13",46,0)
 . S SPNNAME="" F  S SPNNAME=$O(^TMP($J,"SPN",SPNNAME)) Q:SPNNAME=""  D  Q:SPNLEXIT
"RTN","SPNPRT13",47,0)
 .. S SPNDFN=0 F  S SPNDFN=$O(^TMP($J,"SPN",SPNNAME,SPNDFN)) Q:SPNDFN<1  D NEWPAT(SPNDFN) Q:SPNLEXIT  D  Q:SPNLEXIT  W !
"RTN","SPNPRT13",48,0)
 ... S SPNIEN=0 F  S SPNIEN=$O(^TMP($J,"SPN",SPNNAME,SPNDFN,SPNIEN)) Q:SPNIEN<1  D  Q:SPNLEXIT
"RTN","SPNPRT13",49,0)
 .... S SPNLINE=^TMP($J,"SPN",SPNNAME,SPNDFN,SPNIEN)
"RTN","SPNPRT13",50,0)
 ... D HEAD Q:SPNLEXIT
"RTN","SPNPRT13",51,0)
 ... D PATIENT(SPNDFN,SPNLINE) Q:SPNLEXIT
"RTN","SPNPRT13",52,0)
 ... Q
"RTN","SPNPRT13",53,0)
 .. Q
"RTN","SPNPRT13",54,0)
 .I SPNCOU D
"RTN","SPNPRT13",55,0)
 .. W !,?15,SPNCOU," Patients have been processed."
"RTN","SPNPRT13",56,0)
 .. Q
"RTN","SPNPRT13",57,0)
 . Q
"RTN","SPNPRT13",58,0)
 E  W !,"     ******* No Data for this report. *******"
"RTN","SPNPRT13",59,0)
 I $E(IOST,1)="C" N DIR S DIR(0)="E" D ^DIR  K Y
"RTN","SPNPRT13",60,0)
 D CLOSE^SPNPRTMT
"RTN","SPNPRT13",61,0)
 K ^TMP($J,"SPN")
"RTN","SPNPRT13",62,0)
 Q
"RTN","SPNPRT13",63,0)
NEWPAT(SPNDFN) ; New patient to print
"RTN","SPNPRT13",64,0)
 D HEAD Q:SPNLEXIT
"RTN","SPNPRT13",65,0)
 N DFN
"RTN","SPNPRT13",66,0)
 S DFN=SPNDFN D DEM^VADPT
"RTN","SPNPRT13",67,0)
 W !!,"  Patient: ",$E(VADM(1),1,18),?32,"SSN: ",$P(VADM(2),U),?49,"SCI: ",$E($$GET1^DIQ(2,SPNDFN,57.4,"E"),1,30)
"RTN","SPNPRT13",68,0)
 D KVAR^VADPT
"RTN","SPNPRT13",69,0)
 S SPNCOU=SPNCOU+1
"RTN","SPNPRT13",70,0)
 I '$D(^SPNL(154,SPNDFN,0)) Q
"RTN","SPNPRT13",71,0)
 I $O(^SPNL(154,SPNDFN,"E",0))<1 Q
"RTN","SPNPRT13",72,0)
 N SPNETI,SPNDFLG
"RTN","SPNPRT13",73,0)
 S (SPNETI,SPNDFLG)=0 W !,"  Etiology: "
"RTN","SPNPRT13",74,0)
 F  S SPNETI=$O(^SPNL(154,SPNDFN,"E",SPNETI)) Q:SPNETI<1  D  Q:SPNLEXIT
"RTN","SPNPRT13",75,0)
 .N SPNETO
"RTN","SPNPRT13",76,0)
 .S SPNETO=$P($G(^SPNL(154,SPNDFN,"E",SPNETI,0)),U) Q:SPNETO=""
"RTN","SPNPRT13",77,0)
 .I $X>13 D HEAD Q:SPNLEXIT  W !
"RTN","SPNPRT13",78,0)
 .W ?12,$E($$GET^DDSVAL(154.03,SPNETO,.01,"","E"),1,30)
"RTN","SPNPRT13",79,0)
 .I 'SPNDFLG W ?49,"Registration Date: ",$$FMTE^XLFDT($P($G(^SPNL(154,SPNDFN,0)),U,2),"5DZ") S SPNDFLG=1
"RTN","SPNPRT13",80,0)
 .Q
"RTN","SPNPRT13",81,0)
 Q
"RTN","SPNPRT13",82,0)
PATIENT(SPNDFN,SPNLINE) ; Print Patient data
"RTN","SPNPRT13",83,0)
 ; SPNLINE=Movement date(I)^Ward location(E)^Room-Bed(E)^Adm Date^Pointer to PTF
"RTN","SPNPRT13",84,0)
 ; SPNLINE=$P(VAIP(3),U,1)_U_VAIP(5),U,2)_U_$P(VAIP(6),U,2)_U_SPNQDAT_U_VAIP(12)
"RTN","SPNPRT13",85,0)
 Q:SPNLEXIT
"RTN","SPNPRT13",86,0)
 W !,$$FMTE^XLFDT($P(SPNLINE,U,1),"5Z"),?22,$E($P(SPNLINE,U,2),1,14),?37,$E($P(SPNLINE,U,3),1,15)
"RTN","SPNPRT13",87,0)
 Q:$P(SPNLINE,U,2)=""
"RTN","SPNPRT13",88,0)
 N SPNODE,SPNNODE
"RTN","SPNPRT13",89,0)
 S SPNNODE=$G(^DGPT($P(SPNLINE,U,5),70)) Q:SPNNODE=""
"RTN","SPNPRT13",90,0)
 N SPNY
"RTN","SPNPRT13",91,0)
 F SPNODE=10,16:1:24 D  Q:SPNLEXIT
"RTN","SPNPRT13",92,0)
 .S SPNY=$P(SPNNODE,U,SPNODE)
"RTN","SPNPRT13",93,0)
 .I SPNY'>0 Q
"RTN","SPNPRT13",94,0)
 .I $G(^ICD9(SPNY,0))="" Q
"RTN","SPNPRT13",95,0)
 .I $X>50 D HEAD Q:SPNLEXIT  W !
"RTN","SPNPRT13",96,0)
 .W ?50,$E($$GET1^DIQ(80,SPNY,3,"E"),1,29)
"RTN","SPNPRT13",97,0)
 .Q
"RTN","SPNPRT13",98,0)
 I '$D(^SPNL(154,SPNDFN,0)) W !?2,"*** NOT IN THE REGISTRY ! ***"
"RTN","SPNPRT13",99,0)
 Q
"RTN","SPNPRT13",100,0)
HEAD ; Header Print
"RTN","SPNPRT13",101,0)
 I SPNPAGE'=1 Q:$Y<(IOSL-4)
"RTN","SPNPRT13",102,0)
 I $E(IOST,1)="C" D  Q:SPNLEXIT
"RTN","SPNPRT13",103,0)
 .I SPNPAGE=1 W @IOF Q
"RTN","SPNPRT13",104,0)
 .I SPNPAGE'=1 D  Q:SPNLEXIT
"RTN","SPNPRT13",105,0)
 ..N DIR S DIR(0)="E" D ^DIR I 'Y S SPNLEXIT=1
"RTN","SPNPRT13",106,0)
 ..K Y
"RTN","SPNPRT13",107,0)
 ..Q
"RTN","SPNPRT13",108,0)
 .Q
"RTN","SPNPRT13",109,0)
 Q:SPNLEXIT
"RTN","SPNPRT13",110,0)
 I SPNPAGE'=1 W @IOF
"RTN","SPNPRT13",111,0)
 W !,$$FMTE^XLFDT($$NOW^XLFDT,1),?70,"Page: ",SPNPAGE
"RTN","SPNPRT13",112,0)
 W !!,?27,"SCD Admissions"
"RTN","SPNPRT13",113,0)
 W !,?27,"From ",$$FMTE^XLFDT(SPNDATE,"5DZ")," to ",$$FMTE^XLFDT(SPNEDAT,"5DZ")
"RTN","SPNPRT13",114,0)
 W !!,"Date Admitted",?22,"Ward",?37,"Room-Bed",?50,"Diagnosis Codes"
"RTN","SPNPRT13",115,0)
 W !,$$REPEAT^XLFSTR("-",79)
"RTN","SPNPRT13",116,0)
 S SPNPAGE=SPNPAGE+1
"RTN","SPNPRT13",117,0)
 I $D(ZTQUEUED) S:$$STPCK^SPNPRTMT SPNLEXIT=1
"RTN","SPNPRT13",118,0)
 Q
"VER")
8.0^22.0
**END**
**END**
