Released PX*1*112 SEQ #97
Extracted from mail message
**KIDS**:PX*1.0*112^

**INSTALL NAME**
PX*1.0*112
"BLD",4439,0)
PX*1.0*112^PCE PATIENT CARE ENCOUNTER^0^3030626^y
"BLD",4439,1,0)
^^4^4^3030623^^^^
"BLD",4439,1,1,0)
This patch addresses the following issues:
"BLD",4439,1,2,0)
- allows to enter only one primary diagnosis and not allows for duplicates
"BLD",4439,1,3,0)
- only one E&M procedure code may be accepted and with quantity=1 only
"BLD",4439,1,4,0)
- fix a misspelling in a called label to address MIW-0503-41153.
"BLD",4439,4,0)
^9.64PA^^0
"BLD",4439,"KRN",0)
^9.67PA^8989.52^19
"BLD",4439,"KRN",.4,0)
.4
"BLD",4439,"KRN",.401,0)
.401
"BLD",4439,"KRN",.402,0)
.402
"BLD",4439,"KRN",.403,0)
.403
"BLD",4439,"KRN",.5,0)
.5
"BLD",4439,"KRN",.84,0)
.84
"BLD",4439,"KRN",3.6,0)
3.6
"BLD",4439,"KRN",3.8,0)
3.8
"BLD",4439,"KRN",9.2,0)
9.2
"BLD",4439,"KRN",9.8,0)
9.8
"BLD",4439,"KRN",9.8,"NM",0)
^9.68A^13^10
"BLD",4439,"KRN",9.8,"NM",1,0)
PXAI^^0^B38699088
"BLD",4439,"KRN",9.8,"NM",4,0)
PXBGPOV^^0^B7101924
"BLD",4439,"KRN",9.8,"NM",5,0)
PXCEVFI1^^0^B16816847
"BLD",4439,"KRN",9.8,"NM",6,0)
PXCECPT^^0^B35800088
"BLD",4439,"KRN",9.8,"NM",7,0)
PXAICPT^^0^B18253216
"BLD",4439,"KRN",9.8,"NM",9,0)
PXBPQUA^^0^B3308675
"BLD",4439,"KRN",9.8,"NM",10,0)
PXBPPOV1^^0^B14236080
"BLD",4439,"KRN",9.8,"NM",11,0)
PXAIPOV^^0^B19310582
"BLD",4439,"KRN",9.8,"NM",12,0)
PXBPCPT^^0^B40260903
"BLD",4439,"KRN",9.8,"NM",13,0)
PXBPCPT1^^0^B20103669
"BLD",4439,"KRN",9.8,"NM","B","PXAI",1)

"BLD",4439,"KRN",9.8,"NM","B","PXAICPT",7)

"BLD",4439,"KRN",9.8,"NM","B","PXAIPOV",11)

"BLD",4439,"KRN",9.8,"NM","B","PXBGPOV",4)

"BLD",4439,"KRN",9.8,"NM","B","PXBPCPT",12)

"BLD",4439,"KRN",9.8,"NM","B","PXBPCPT1",13)

"BLD",4439,"KRN",9.8,"NM","B","PXBPPOV1",10)

"BLD",4439,"KRN",9.8,"NM","B","PXBPQUA",9)

"BLD",4439,"KRN",9.8,"NM","B","PXCECPT",6)

"BLD",4439,"KRN",9.8,"NM","B","PXCEVFI1",5)

"BLD",4439,"KRN",19,0)
19
"BLD",4439,"KRN",19.1,0)
19.1
"BLD",4439,"KRN",101,0)
101
"BLD",4439,"KRN",409.61,0)
409.61
"BLD",4439,"KRN",771,0)
771
"BLD",4439,"KRN",870,0)
870
"BLD",4439,"KRN",8989.51,0)
8989.51
"BLD",4439,"KRN",8989.52,0)
8989.52
"BLD",4439,"KRN",8994,0)
8994
"BLD",4439,"KRN","B",.4,.4)

"BLD",4439,"KRN","B",.401,.401)

"BLD",4439,"KRN","B",.402,.402)

"BLD",4439,"KRN","B",.403,.403)

"BLD",4439,"KRN","B",.5,.5)

"BLD",4439,"KRN","B",.84,.84)

"BLD",4439,"KRN","B",3.6,3.6)

"BLD",4439,"KRN","B",3.8,3.8)

"BLD",4439,"KRN","B",9.2,9.2)

"BLD",4439,"KRN","B",9.8,9.8)

"BLD",4439,"KRN","B",19,19)

"BLD",4439,"KRN","B",19.1,19.1)

"BLD",4439,"KRN","B",101,101)

"BLD",4439,"KRN","B",409.61,409.61)

"BLD",4439,"KRN","B",771,771)

"BLD",4439,"KRN","B",870,870)

"BLD",4439,"KRN","B",8989.51,8989.51)

"BLD",4439,"KRN","B",8989.52,8989.52)

"BLD",4439,"KRN","B",8994,8994)

"BLD",4439,"QUES",0)
^9.62^^
"BLD",4439,"REQB",0)
^9.611^3^3
"BLD",4439,"REQB",1,0)
PX*1.0*111^2
"BLD",4439,"REQB",2,0)
PX*1.0*108^2
"BLD",4439,"REQB",3,0)
PX*1.0*89^2
"BLD",4439,"REQB","B","PX*1.0*108",2)

"BLD",4439,"REQB","B","PX*1.0*111",1)

"BLD",4439,"REQB","B","PX*1.0*89",3)

"MBREQ")
0
"PKG",413,-1)
1^1
"PKG",413,0)
PCE PATIENT CARE ENCOUNTER^PX^Patient Care Encounter (VA Parent package)^
"PKG",413,20,0)
^9.402P^^
"PKG",413,22,0)
^9.49I^1^1
"PKG",413,22,1,0)
1.0^2960812^2960913^12537
"PKG",413,22,1,"PAH",1,0)
112^3030626^100884
"PKG",413,22,1,"PAH",1,1,0)
^^4^4^3030626
"PKG",413,22,1,"PAH",1,1,1,0)
This patch addresses the following issues:
"PKG",413,22,1,"PAH",1,1,2,0)
- allows to enter only one primary diagnosis and not allows for duplicates
"PKG",413,22,1,"PAH",1,1,3,0)
- only one E&M procedure code may be accepted and with quantity=1 only
"PKG",413,22,1,"PAH",1,1,4,0)
- fix a misspelling in a called label to address MIW-0503-41153.
"QUES","XPF1",0)
Y
"QUES","XPF1","??")
^D REP^XPDH
"QUES","XPF1","A")
Shall I write over your |FLAG| File
"QUES","XPF1","B")
YES
"QUES","XPF1","M")
D XPF1^XPDIQ
"QUES","XPF2",0)
Y
"QUES","XPF2","??")
^D DTA^XPDH
"QUES","XPF2","A")
Want my data |FLAG| yours
"QUES","XPF2","B")
YES
"QUES","XPF2","M")
D XPF2^XPDIQ
"QUES","XPI1",0)
YO
"QUES","XPI1","??")
^D INHIBIT^XPDH
"QUES","XPI1","A")
Want KIDS to INHIBIT LOGONs during the install
"QUES","XPI1","B")
YES
"QUES","XPI1","M")
D XPI1^XPDIQ
"QUES","XPM1",0)
PO^VA(200,:EM
"QUES","XPM1","??")
^D MG^XPDH
"QUES","XPM1","A")
Enter the Coordinator for Mail Group '|FLAG|'
"QUES","XPM1","B")

"QUES","XPM1","M")
D XPM1^XPDIQ
"QUES","XPO1",0)
Y
"QUES","XPO1","??")
^D MENU^XPDH
"QUES","XPO1","A")
Want KIDS to Rebuild Menu Trees Upon Completion of Install
"QUES","XPO1","B")
YES
"QUES","XPO1","M")
D XPO1^XPDIQ
"QUES","XPZ1",0)
Y
"QUES","XPZ1","??")
^D OPT^XPDH
"QUES","XPZ1","A")
Want to DISABLE Scheduled Options, Menu Options, and Protocols
"QUES","XPZ1","B")
YES
"QUES","XPZ1","M")
D XPZ1^XPDIQ
"QUES","XPZ2",0)
Y
"QUES","XPZ2","??")
^D RTN^XPDH
"QUES","XPZ2","A")
Want to MOVE routines to other CPUs
"QUES","XPZ2","B")
NO
"QUES","XPZ2","M")
D XPZ2^XPDIQ
"RTN")
10
"RTN","PXAI")
0^1^B38699088
"RTN","PXAI",1,0)
PXAI ;ISL/JVS,ISA/KWP,ESW - PCE DRIVING RTN FOR 'DATA2PCE' API ; 6/20/03 11:15am
"RTN","PXAI",2,0)
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**15,74,69,102,111,112**;Aug 12, 1996
"RTN","PXAI",3,0)
 Q
"RTN","PXAI",4,0)
 ;
"RTN","PXAI",5,0)
 ;+  1       2       3        4        5       6      7      8       9
"RTN","PXAI",6,0)
DATA2PCE(PXADATA,PXAPKG,PXASOURC,PXAVISIT,PXAUSER,PXANOT,ERRRET,PXAPREDT,PXAPROB) ;+API to pass data for add/edit/delete to PCE.
"RTN","PXAI",7,0)
 ;+  PXADATA  (required)
"RTN","PXAI",8,0)
 ;+  PXAPKG   (required)
"RTN","PXAI",9,0)
 ;+  PXASOURC (required)
"RTN","PXAI",10,0)
 ;+  PXAVISIT (optional) is pointer to a visit for which the data is to
"RTN","PXAI",11,0)
 ;+        be related.  If the visit is not know then there must be
"RTN","PXAI",12,0)
 ;+        the ENCOUNTER nodes needed to lookup/create the visit.
"RTN","PXAI",13,0)
 ;+  PXAUSER  (optional) this is a pointer to the user adding the data.
"RTN","PXAI",14,0)
 ;+  PXANOT   (optional) set to 1 if errors are to be displayed to the screen should only be set while writing and debugging the initial code.
"RTN","PXAI",15,0)
 ;+  ERRRET   (optional) passed by reference.  If present will return PXKERROR
"RTN","PXAI",16,0)
 ;+                      array elements to the caller.
"RTN","PXAI",17,0)
 ;+  PXAPREDT  (optional) Set to 1 if you want to edit the Primary Provder
"RTN","PXAI",18,0)
 ;+            only use if for the moment that editing is being done. (dangeous)
"RTN","PXAI",19,0)
 ;+  .PXAPROB   (optional) A dotted variable name. When errors and
"RTN","PXAI",20,0)
 ;+             warnings occur, They will be passed back in the form
"RTN","PXAI",21,0)
 ;+            of an array with the general description of the problem.
"RTN","PXAI",22,0)
 ;+ IF ERROR1 - (GENERAL ERRORS)
"RTN","PXAI",23,0)
 ;+      PXAPROB($J,SUBSCRIPT,"ERROR1",PASSED IN 'FILE',PASSED IN FIELD,
"RTN","PXAI",24,0)
 ;+              SUBSCRIPT FROM PXADATA)
"RTN","PXAI",25,0)
 ;+      PXAPROB(23432234,2,"ERROR1","PROVIDER","NAME",7)="BECAUSE..."
"RTN","PXAI",26,0)
 ;+ IF WARNING2 - (GENERAL WARNINGS)
"RTN","PXAI",27,0)
 ;+      PXAPROB($J,SUBSCRIPT,"WARNING2",PASSED IN 'FILE',PASSED IN FIELD,
"RTN","PXAI",28,0)
 ;+              SUBSCRIPT FROM PXADATA)
"RTN","PXAI",29,0)
 ;+      PXAPROB(23432234,3,"WARNING2","PROCEDURE","QTY",3)="BECAUSE..."
"RTN","PXAI",30,0)
 ;+ IF WARNING3 - (WARNINGS FOR SERVICE CONNECTION)
"RTN","PXAI",31,0)
 ;+      PXAPROB($J,1,"WARNING3","ENCOUNTER",1,"AO")=REASON
"RTN","PXAI",32,0)
 ;+      PXAPROB($J,1,"WARNING3","ENCOUNTER",1,"EC")=REASON
"RTN","PXAI",33,0)
 ;+      PXAPROB($J,1,"WARNING3","ENCOUNTER",1,"IR")=REASON
"RTN","PXAI",34,0)
 ;+      PXAPROB($J,1,"WARNING3","ENCOUNTER",1,"SC")=REASON
"RTN","PXAI",35,0)
 ;+      PXAPROB($J,1,"WARNING3","ENCOUNTER",1,"MST")=REASON
"RTN","PXAI",36,0)
 ;+      PXAPROB($J,1,"WARNING3","ENCOUNTER",1,"HNC")=REASON
"RTN","PXAI",37,0)
 ;+ IF ERROR4 - (PROBLEM LIST ERRORS)
"RTN","PXAI",38,0)
 ;+      PXAPROB($J,6,"ERROR4","PX/DL",(SUBSCRIPT FROM PXADATA))=REASON
"RTN","PXAI",39,0)
 ;+
"RTN","PXAI",40,0)
 ;+
"RTN","PXAI",41,0)
 ;+
"RTN","PXAI",42,0)
 ;+ Returns:
"RTN","PXAI",43,0)
 ;+   1  if no errors and process completely
"RTN","PXAI",44,0)
 ;+  -1  if errors occurred but processed completely as possible
"RTN","PXAI",45,0)
 ;+  -2  if could not get a visit
"RTN","PXAI",46,0)
 ;+  -3  if called incorrectly
"RTN","PXAI",47,0)
 ;
"RTN","PXAI",48,0)
NEW ;--NEW VARIABLES
"RTN","PXAI",49,0)
 N NOVSIT,PXAK,DFN,PXAERRF,PXADEC,PXELAP,PXASUB
"RTN","PXAI",50,0)
 N PATIENT,VALQUIET,PRIMFND
"RTN","PXAI",51,0)
 K PXAERROR,PXKERROR,PXAERR,PRVDR
"RTN","PXAI",52,0)
 S PXASUB=0,VALQUIET=1
"RTN","PXAI",53,0)
 ; needs to look up if not passed. 
"RTN","PXAI",54,0)
 I '$G(PXAVISIT),'$D(@PXADATA@("ENCOUNTER")) Q -3
"RTN","PXAI",55,0)
 I $G(PXAUSER)<1 S PXAUSER=DUZ
"RTN","PXAI",56,0)
 ;
"RTN","PXAI",57,0)
 K ^TMP("PXK",$J),^TMP("DIERR",$J),^TMP("PXAIADDPRV",$J)
"RTN","PXAI",58,0)
SOR ;--SOURCE
"RTN","PXAI",59,0)
 I PXAPKG=+PXAPKG S PXAPKG=PXAPKG
"RTN","PXAI",60,0)
 E  S PXAPKG=$$PKG2IEN^VSIT(PXAPKG)
"RTN","PXAI",61,0)
 I PXASOURC=+PXASOURC S PXASOURC=PXASOURC
"RTN","PXAI",62,0)
 E  S PXASOURC=$$SOURCE^PXAPIUTL(PXASOURC)
"RTN","PXAI",63,0)
 ;
"RTN","PXAI",64,0)
 D TMPSOURC^PXAPIUTL(PXASOURC) ;-SAVES & CREATES ^TMP("PXK",$J,"SOR")
"RTN","PXAI",65,0)
VST ;--VISIT
"RTN","PXAI",66,0)
 ;--KILL VISIT
"RTN","PXAI",67,0)
 I $G(PXAVISIT) D VPTR^PXAIVSTV I $G(PXAERRF) D ERR Q -2
"RTN","PXAI",68,0)
 D VST^PXAIVST
"RTN","PXAI",69,0)
 I $G(PXAVISIT)<0 Q -2
"RTN","PXAI",70,0)
 I $G(PXAERRF) D ERR K PXAERR Q -2
"RTN","PXAI",71,0)
PRV ;--PROVIDER
"RTN","PXAI",72,0)
 S PATIENT=$P($G(^AUPNVSIT(PXAVISIT,0)),"^",5)
"RTN","PXAI",73,0)
 S (PXAK,PRIMFND)=0
"RTN","PXAI",74,0)
 F  S PXAK=$O(@PXADATA@("PROVIDER",PXAK)) Q:(PRIMFND)!(PXAK="")  D
"RTN","PXAI",75,0)
 .I $D(@PXADATA@("PROVIDER",PXAK,"PRIMARY")) D
"RTN","PXAI",76,0)
 ..S PRIMFND=$G(@PXADATA@("PROVIDER",PXAK,"PRIMARY"))
"RTN","PXAI",77,0)
 I 'PRIMFND D  ;Check for each provider's status as Primary or Secondary
"RTN","PXAI",78,0)
 .S PXAK=0 F  S PXAK=$O(@PXADATA@("PROVIDER",PXAK)) Q:PXAK=""  D
"RTN","PXAI",79,0)
 ..I '$D(@PXADATA@("PROVIDER",PXAK,"PRIMARY")) D PROVDRST
"RTN","PXAI",80,0)
 S PXAK=0 F  S PXAK=$O(@PXADATA@("PROVIDER",PXAK)) Q:PXAK=""  D
"RTN","PXAI",81,0)
 . D PRV^PXAIPRV I $G(PXAERRF) D ERR
"RTN","PXAI",82,0)
 K PRI ;--FLAG FOR PRIMARY PROVIDER
"RTN","PXAI",83,0)
 K PXAERR
"RTN","PXAI",84,0)
CPT ;--PROCEDURE
"RTN","PXAI",85,0)
 S PXAK=0 F  S PXAK=$O(@PXADATA@("PROCEDURE",PXAK))  Q:PXAK=""  D
"RTN","PXAI",86,0)
 . D CPT^PXAICPT I $G(PXAERRF) D ERR
"RTN","PXAI",87,0)
 K PXAERR
"RTN","PXAI",88,0)
 ;
"RTN","PXAI",89,0)
POV ;--DIAGNOSIS
"RTN","PXAI",90,0)
 S (PXAK,PRIMFND)=0
"RTN","PXAI",91,0)
 F  S PXAK=$O(@PXADATA@("DX/PL",PXAK)) Q:(PXAK="")  D  Q:PRIMFND
"RTN","PXAI",92,0)
 .I +$G(@PXADATA@("DX/PL",PXAK,"PRIMARY"))=1 D
"RTN","PXAI",93,0)
 ..S PRIMFND=$G(@PXADATA@("DX/PL",PXAK,"DIAGNOSIS"))
"RTN","PXAI",94,0)
 I $D(@PXADATA@("DX/PL")) D POVPRM(PXAVISIT,PRIMFND,.PXADATA) D
"RTN","PXAI",95,0)
 .S PXAK=0 F  S PXAK=$O(@PXADATA@("DX/PL",PXAK))  Q:PXAK=""  D
"RTN","PXAI",96,0)
 ..D POV^PXAIPOV I $G(PXAERRF) D ERR
"RTN","PXAI",97,0)
 K PXAERR
"RTN","PXAI",98,0)
 ;
"RTN","PXAI",99,0)
EDU ;--PATIENT EDUCATION
"RTN","PXAI",100,0)
 S PXAK=0 F  S PXAK=$O(@PXADATA@("PATIENT ED",PXAK))  Q:PXAK=""  D
"RTN","PXAI",101,0)
 . D EDU^PXAIPED I $G(PXAERRF) D ERR
"RTN","PXAI",102,0)
 K PXAERR
"RTN","PXAI",103,0)
 ;
"RTN","PXAI",104,0)
EXAM ;--EXAMINATION
"RTN","PXAI",105,0)
 S PXAK=0 F  S PXAK=$O(@PXADATA@("EXAM",PXAK))  Q:PXAK=""  D
"RTN","PXAI",106,0)
 . D EXAM^PXAIXAM I $G(PXAERRF) D ERR
"RTN","PXAI",107,0)
 K PXAERR
"RTN","PXAI",108,0)
 ;
"RTN","PXAI",109,0)
HF ;--HEALTH FACTOR
"RTN","PXAI",110,0)
 S PXAK=0 F  S PXAK=$O(@PXADATA@("HEALTH FACTOR",PXAK))  Q:PXAK=""  D
"RTN","PXAI",111,0)
 . D HF^PXAIHF I $G(PXAERRF) D ERR
"RTN","PXAI",112,0)
 K PXAERR
"RTN","PXAI",113,0)
 ;
"RTN","PXAI",114,0)
IMM ;--IMMUNIZATION
"RTN","PXAI",115,0)
 S PXAK=0 F  S PXAK=$O(@PXADATA@("IMMUNIZATION",PXAK))  Q:PXAK=""  D
"RTN","PXAI",116,0)
 . D IMM^PXAIIMM I $G(PXAERRF) D ERR
"RTN","PXAI",117,0)
 K PXAERR
"RTN","PXAI",118,0)
 ;
"RTN","PXAI",119,0)
SKIN ;--SKIN TEST
"RTN","PXAI",120,0)
 S PXAK=0 F  S PXAK=$O(@PXADATA@("SKIN TEST",PXAK))  Q:PXAK=""  D
"RTN","PXAI",121,0)
 . D SKIN^PXAISK I $G(PXAERRF) D ERR
"RTN","PXAI",122,0)
 K PXAERR
"RTN","PXAI",123,0)
 ;
"RTN","PXAI",124,0)
 ;
"RTN","PXAI",125,0)
 D OTHER^PXAIPRV
"RTN","PXAI",126,0)
 ;
"RTN","PXAI",127,0)
 ;
"RTN","PXAI",128,0)
 I $D(^TMP("PXK",$J)) D
"RTN","PXAI",129,0)
 . D EN1^PXKMAIN
"RTN","PXAI",130,0)
 . M ERRRET=PXKERROR
"RTN","PXAI",131,0)
 . D PRIM^PXAIPRV K PRVDR
"RTN","PXAI",132,0)
 . D EVENT^PXKMAIN
"RTN","PXAI",133,0)
 K ^TMP("PXK",$J),PXAERR,PXKERROR
"RTN","PXAI",134,0)
 Q $S($G(PXAERRF):-1,1:1)
"RTN","PXAI",135,0)
 ;
"RTN","PXAI",136,0)
 ;
"RTN","PXAI",137,0)
EXIT ;--EXIT AND CLEAN UP
"RTN","PXAI",138,0)
 D EVENT^PXKMAIN
"RTN","PXAI",139,0)
 K ^TMP("PXK",$J),PRVDR
"RTN","PXAI",140,0)
 K PXAERR
"RTN","PXAI",141,0)
 Q
"RTN","PXAI",142,0)
 ;-----------------SUBROUTINES-----------------------
"RTN","PXAI",143,0)
ERR ;
"RTN","PXAI",144,0)
 ;
"RTN","PXAI",145,0)
 ;
"RTN","PXAI",146,0)
 I '$D(PXADI("DIALOG")) Q
"RTN","PXAI",147,0)
 N NODE,SCREEN
"RTN","PXAI",148,0)
 S PXAERR(1)=$G(PXADATA),PXAERR(2)=$G(PXAPKG),PXAERR(3)=$G(PXASOURC)
"RTN","PXAI",149,0)
 S PXAERR(4)=$G(PXAVISIT),PXAERR(5)=$G(PXAUSER)_"  "_$P($G(^VA(200,PXAUSER,0)),"^",1)
"RTN","PXAI",150,0)
 I $G(PXANOT)=1 D EXTERNAL
"RTN","PXAI",151,0)
 E  D INTERNAL
"RTN","PXAI",152,0)
 D ARRAY^PXAICPTV
"RTN","PXAI",153,0)
 K PXADI("DIALOG")
"RTN","PXAI",154,0)
 Q
"RTN","PXAI",155,0)
 ;
"RTN","PXAI",156,0)
EXTERNAL ;---SEND ERRORS TO SCREEN
"RTN","PXAI",157,0)
 W !,"-----------------------------------------------------------------"
"RTN","PXAI",158,0)
 D BLD^DIALOG($G(PXADI("DIALOG")),.PXAERR,"","SCREEN","F")
"RTN","PXAI",159,0)
 D MSG^DIALOG("ESW","",50,10,"SCREEN")
"RTN","PXAI",160,0)
 ;
"RTN","PXAI",161,0)
 Q
"RTN","PXAI",162,0)
INTERNAL ;---SET ERRORS TO GLOBAL ARRAY
"RTN","PXAI",163,0)
 S NODE=PXADATA
"RTN","PXAI",164,0)
 D BLD^DIALOG($G(PXADI("DIALOG")),.PXAERR,.PXAERR,NODE,"F")
"RTN","PXAI",165,0)
 S NODE=$NA(@PXADATA@("DIERR",$J)) D MSG^DIALOG("ESW","",50,10,NODE)
"RTN","PXAI",166,0)
 Q
"RTN","PXAI",167,0)
 ;
"RTN","PXAI",168,0)
PROVDRST ; Check provider status (Primary or Secondary)
"RTN","PXAI",169,0)
 N PRVIEN,DETS,DIC,DR,DA,DIQ,PRI,PRVPRIM
"RTN","PXAI",170,0)
 I $G(PXAK)="" QUIT
"RTN","PXAI",171,0)
 S PRVIEN=0
"RTN","PXAI",172,0)
 F  S PRVIEN=$O(^AUPNVPRV("AD",PXAVISIT,PRVIEN)) Q:PRVIEN=""  D
"RTN","PXAI",173,0)
 .S DETS=$G(^AUPNVPRV(PRVIEN,0))
"RTN","PXAI",174,0)
 .I $P(DETS,U)=$G(@PXADATA@("PROVIDER",PXAK,"NAME")) D
"RTN","PXAI",175,0)
 ..S DIC=9000010.06,DR=.04,DA=PRVIEN
"RTN","PXAI",176,0)
 ..S DIQ="PRVPRIM(",DIQ(0)="EI" D EN^DIQ1
"RTN","PXAI",177,0)
 ..S PRI=$E($G(PRVPRIM(9000010.06,DA,DR,"E")),1,1)
"RTN","PXAI",178,0)
 ..S @PXADATA@("PROVIDER",PXAK,"PRIMARY")=$S(PRI="P":1,1:0)
"RTN","PXAI",179,0)
 Q
"RTN","PXAI",180,0)
POVPRM(VISIT,PRIMFND,POVARR) ;
"RTN","PXAI",181,0)
 N PRVIEN,DETS,STOP,LPXAK,ORDX,NDX,ORDXP
"RTN","PXAI",182,0)
 S PRVIEN=0
"RTN","PXAI",183,0)
 ;create array of existing DX; ORDX - pointer to ^ICD9(
"RTN","PXAI",184,0)
 F  S PRVIEN=$O(^AUPNVPOV("AD",PXAVISIT,PRVIEN)) Q:PRVIEN=""  D
"RTN","PXAI",185,0)
 .S DETS=$G(^AUPNVPOV(PRVIEN,0)),ORDX=$P(DETS,U)
"RTN","PXAI",186,0)
 .S ORDX(ORDX)=PRVIEN I $P(DETS,U,12)="P" S ORDXP(ORDX)=""
"RTN","PXAI",187,0)
 ; create array of passed DX; NDX - pointer to ^ICD9(
"RTN","PXAI",188,0)
 S PXAK=0 F  S PXAK=$O(@POVARR@("DX/PL",PXAK)) Q:PXAK=""  D
"RTN","PXAI",189,0)
 .S NDX=$G(@POVARR@("DX/PL",PXAK,"DIAGNOSIS")) S NDX(NDX)=PXAK
"RTN","PXAI",190,0)
 ; force entry of originally primary diagnosis with "S" flag
"RTN","PXAI",191,0)
 I PRIMFND S ORDX="" D
"RTN","PXAI",192,0)
 .F  S ORDX=$O(ORDXP(ORDX)) Q:ORDX=""  I PRIMFND'=ORDX D
"RTN","PXAI",193,0)
 ..I $D(NDX(ORDX)) S @POVARR@("DX/PL",NDX(ORDX),"PRIMARY")=0
"RTN","PXAI",194,0)
 ..E  D
"RTN","PXAI",195,0)
 ...S LPXAK=$O(@POVARR@("DX/PL",""),-1)
"RTN","PXAI",196,0)
 ...S @POVARR@("DX/PL",LPXAK+1,"DIAGNOSIS")=ORDX
"RTN","PXAI",197,0)
 ...S @POVARR@("DX/PL",LPXAK+1,"PRIMARY")=0
"RTN","PXAI",198,0)
 Q
"RTN","PXAI",199,0)
 ;
"RTN","PXAICPT")
0^7^B18253216
"RTN","PXAICPT",1,0)
PXAICPT ;ISL/JVS,ISA/KWP,ESW - SET THE PROCEDURE(CPT) NODES ; 4/18/03 12:17pm
"RTN","PXAICPT",2,0)
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**19,73,108,112**;Aug 12, 1996
"RTN","PXAICPT",3,0)
 ;
"RTN","PXAICPT",4,0)
 ;
"RTN","PXAICPT",5,0)
 Q
"RTN","PXAICPT",6,0)
CPT ;--CREAT PROVIDERS
"RTN","PXAICPT",7,0)
 ;
"RTN","PXAICPT",8,0)
 ;
"RTN","PXAICPT",9,0)
SET ;--SET AND NEW VARIABLES
"RTN","PXAICPT",10,0)
 N AFTER0,AFTER1,AFTER12,AFTER801,AFTER802,AFTER811,AFTER812
"RTN","PXAICPT",11,0)
 N BEFOR0,BEFOR1,BEFOR12,BEFOR801,BEFOR802,BEFOR811,BEFOR812
"RTN","PXAICPT",12,0)
 N PXAA,PXAB,SUB,PIECE,PXAAX,IENB,STOP
"RTN","PXAICPT",13,0)
 ;New Modifier Variables
"RTN","PXAICPT",14,0)
 D SET^PXAIMOD
"RTN","PXAICPT",15,0)
 K PXAERR
"RTN","PXAICPT",16,0)
 S PXAERR(8)=PXAK
"RTN","PXAICPT",17,0)
 S PXAERR(7)="PROCEDURE"
"RTN","PXAICPT",18,0)
 ;
"RTN","PXAICPT",19,0)
 S SUB="" F  S SUB=$O(@PXADATA@("PROCEDURE",PXAK,SUB)) Q:SUB=""  D
"RTN","PXAICPT",20,0)
 .S PXAA(SUB)=$G(@PXADATA@("PROCEDURE",PXAK,SUB))
"RTN","PXAICPT",21,0)
 ;Setup PXAA array for Modifiers
"RTN","PXAICPT",22,0)
 S SUB=""
"RTN","PXAICPT",23,0)
 F  S SUB=$O(@PXADATA@("PROCEDURE",PXAK,"MODIFIERS",SUB)) Q:SUB=""  D
"RTN","PXAICPT",24,0)
 .S PXAA("MODIFIERS",SUB)=""
"RTN","PXAICPT",25,0)
 ;
"RTN","PXAICPT",26,0)
VAL ;--VALIDATE ENOUGH DATA
"RTN","PXAICPT",27,0)
 D VAL^PXAICPTV Q:$G(STOP)
"RTN","PXAICPT",28,0)
 ;
"RTN","PXAICPT",29,0)
 ;
"RTN","PXAICPT",30,0)
SETVARA ;--SET VISIT VARIABLES
"RTN","PXAICPT",31,0)
 S $P(AFTER0,"^",1)=$G(PXAA("PROCEDURE"))
"RTN","PXAICPT",32,0)
 I $G(PXAA("DELETE")) S $P(AFTER0,"^",1)="@"
"RTN","PXAICPT",33,0)
 S $P(AFTER0,"^",2)=$G(PATIENT)
"RTN","PXAICPT",34,0)
 S $P(AFTER0,"^",3)=$G(PXAVISIT)
"RTN","PXAICPT",35,0)
 S $P(AFTER0,"^",4)=$G(PXAA("NARRATIVE")) D
"RTN","PXAICPT",36,0)
 .I $G(PXAA("NARRATIVE"))']""!($L($G(PXAA("NARRATIVE")))>245) D
"RTN","PXAICPT",37,0)
 ..S $P(AFTER0,"^",4)=$$EXTTEXT^PXUTL1($G(PXAA("PROCEDURE")),1,81,2) ;--TEXT OF NARRATIVE
"RTN","PXAICPT",38,0)
 .I $G(PXAA("NARRATIVE"))]"" S $P(AFTER0,"^",4)=+$$PROVNARR^PXAPI($G(PXAA("NARRATIVE")),9000010.18)
"RTN","PXAICPT",39,0)
 I $P(AFTER0,"^",4)<0 D VAL04^PXAICPTV,ERR^PXAI Q:$D(STOP)
"RTN","PXAICPT",40,0)
 S $P(AFTER0,"^",5)=$G(PXAA("DIAGNOSIS"))
"RTN","PXAICPT",41,0)
 I $G(PXAA("QTY"))="" S PXAA("QTY")=1
"RTN","PXAICPT",42,0)
 S $P(AFTER0,"^",16)=$G(PXAA("QTY")) I $G(PXAA("QTY"))<1 S PXAA("DELETE")=1
"RTN","PXAICPT",43,0)
 ;Set Modifier nodes in AFTER1
"RTN","PXAICPT",44,0)
 D SETVARA^PXAIMOD
"RTN","PXAICPT",45,0)
 ;
"RTN","PXAICPT",46,0)
 S $P(AFTER12,"^",1)=$G(PXAA("EVENT D/T"))
"RTN","PXAICPT",47,0)
 S $P(AFTER12,"^",4)=$G(PXAA("ENC PROVIDER"))
"RTN","PXAICPT",48,0)
 ;PX*1*108 - do not try to file a provider from a "DELETED" cpt
"RTN","PXAICPT",49,0)
 I $G(PXAA("ENC PROVIDER"))]"",'$G(PXAA("DELETE")) D
"RTN","PXAICPT",50,0)
 .S ^TMP("PXAIADDPRV",$J,$G(PXAA("ENC PROVIDER")))=""
"RTN","PXAICPT",51,0)
 ;
"RTN","PXAICPT",52,0)
 S $P(AFTER802,"^",1)=$G(PXAA("CATEGORY"))
"RTN","PXAICPT",53,0)
 I $G(PXAA("CATEGORY"))]"" S $P(AFTER802,"^",1)=+$$PROVNARR^PXAPI($G(PXAA("CATEGORY")),9000010.18)
"RTN","PXAICPT",54,0)
 I $P(AFTER802,"^",1)<0 D VAL45^PXAICPTV,ERR^PXAI Q:$D(STOP)
"RTN","PXAICPT",55,0)
 S $P(AFTER811,"^",1)=$G(PXAA("COMMENT"))
"RTN","PXAICPT",56,0)
 ;
"RTN","PXAICPT",57,0)
 ;
"RTN","PXAICPT",58,0)
 ;
"RTN","PXAICPT",59,0)
 ;--PACKAGE AND SOURCE
"RTN","PXAICPT",60,0)
 ;
"RTN","PXAICPT",61,0)
 S $P(AFTER812,"^",2)=$G(PXAPKG)
"RTN","PXAICPT",62,0)
 S $P(AFTER812,"^",3)=$G(PXASOURC)
"RTN","PXAICPT",63,0)
 ;
"RTN","PXAICPT",64,0)
SETPXKA ;--SET PXK ARRAY AFTER
"RTN","PXAICPT",65,0)
 S ^TMP("PXK",$J,"CPT",PXAK,0,"AFTER")=AFTER0
"RTN","PXAICPT",66,0)
 ;Set ^TMP("PXK",$J,"CPT",PXAK,1,ien,"AFTER")=MODIEN
"RTN","PXAICPT",67,0)
 D SETPXKA^PXAIMOD
"RTN","PXAICPT",68,0)
 S ^TMP("PXK",$J,"CPT",PXAK,12,"AFTER")=AFTER12
"RTN","PXAICPT",69,0)
 S ^TMP("PXK",$J,"CPT",PXAK,802,"AFTER")=AFTER802
"RTN","PXAICPT",70,0)
 S ^TMP("PXK",$J,"CPT",PXAK,811,"AFTER")=AFTER811
"RTN","PXAICPT",71,0)
 S ^TMP("PXK",$J,"CPT",PXAK,812,"AFTER")=AFTER812
"RTN","PXAICPT",72,0)
 ;
"RTN","PXAICPT",73,0)
SETVARB ;--SET VARIABLES BEFORE
"RTN","PXAICPT",74,0)
 D
"RTN","PXAICPT",75,0)
 .N PXBKY,PXBSAM,PXBSKY,PXBCNT,PXI,PRV,ITEM
"RTN","PXAICPT",76,0)
 .D CPT^PXBGCPT(PXAVISIT)
"RTN","PXAICPT",77,0)
 .S PXAAX("PROCEDURE")=$P($G(^ICPT($G(PXAA("PROCEDURE")),0)),"^",1)
"RTN","PXAICPT",78,0)
 .I $G(PXAA("DELETE"))=1 S PXAAX("PROCEDURE")=$P($G(^ICPT($G(PXAA("PROCEDURE")),0)),"^",1)
"RTN","PXAICPT",79,0)
 .S ITEM=""
"RTN","PXAICPT",80,0)
 .I PXBCNT>0,$G(PXAAX("PROCEDURE"))]"" S ITEM=$O(PXBKY(PXAAX("PROCEDURE"),0))
"RTN","PXAICPT",81,0)
 .I ITEM]"" D
"RTN","PXAICPT",82,0)
 ..;--LOOK UP USING CPT AND PROVIDER
"RTN","PXAICPT",83,0)
 ..S PXI="" F  S PXI=$O(PXBKY(PXAAX("PROCEDURE"),PXI)) Q:PXI=""  D
"RTN","PXAICPT",84,0)
 ...I $D(^IBE(357.69,PXAAX("PROCEDURE"))) D  Q  ;DBIA #: 1906
"RTN","PXAICPT",85,0)
 ....S (^TMP("PXK",$J,"CPT",PXAK,"IEN"),IENB)=$O(PXBSKY(PXI,0))
"RTN","PXAICPT",86,0)
 ...I $G(PXAA("ENC PROVIDER")) D  Q
"RTN","PXAICPT",87,0)
 ....S PRV=$P(^VA(200,$G(PXAA("ENC PROVIDER")),0),"^",1)
"RTN","PXAICPT",88,0)
 ....I $P($G(PXBKY(PXAAX("PROCEDURE"),PXI)),"^",3)=PRV D
"RTN","PXAICPT",89,0)
 .....S (^TMP("PXK",$J,"CPT",PXAK,"IEN"),IENB)=$O(PXBSKY(PXI,0))
"RTN","PXAICPT",90,0)
 I $G(IENB) D
"RTN","PXAICPT",91,0)
 .F PIECE=0,12,802,811,812 S ^TMP("PXK",$J,"CPT",PXAK,PIECE,"BEFORE")=$G(^AUPNVCPT(IENB,PIECE))
"RTN","PXAICPT",92,0)
 .;Set ^TMP("PXK",$J,"CPT",PXAK,1,ien,"BEFORE")=MODIEN
"RTN","PXAICPT",93,0)
 .D SETVARB^PXAIMOD
"RTN","PXAICPT",94,0)
 E  D
"RTN","PXAICPT",95,0)
 .S (BEFOR0,BEFOR12,BEFOR802,BEFOR811,BEFOR812)=""
"RTN","PXAICPT",96,0)
 .;
"RTN","PXAICPT",97,0)
SETPXKB .;--SET PXK ARRAY BEFORE
"RTN","PXAICPT",98,0)
 .S ^TMP("PXK",$J,"CPT",PXAK,0,"BEFORE")=BEFOR0
"RTN","PXAICPT",99,0)
 .;Set ^TMP("PXK",$J,"CPT",PXAK,1,ien,"BEFORE")=MODIEN
"RTN","PXAICPT",100,0)
 .D SETPXKB^PXAIMOD
"RTN","PXAICPT",101,0)
 .S ^TMP("PXK",$J,"CPT",PXAK,12,"BEFORE")=BEFOR12
"RTN","PXAICPT",102,0)
 .S ^TMP("PXK",$J,"CPT",PXAK,802,"BEFORE")=BEFOR802
"RTN","PXAICPT",103,0)
 .S ^TMP("PXK",$J,"CPT",PXAK,811,"BEFORE")=BEFOR811
"RTN","PXAICPT",104,0)
 .S ^TMP("PXK",$J,"CPT",PXAK,812,"BEFORE")=BEFOR812
"RTN","PXAICPT",105,0)
 .S ^TMP("PXK",$J,"CPT",PXAK,"IEN")=""
"RTN","PXAICPT",106,0)
 ;
"RTN","PXAICPT",107,0)
MISC ;--MISCELLANEOUS NODE
"RTN","PXAICPT",108,0)
 ;
"RTN","PXAICPT",109,0)
 Q
"RTN","PXAIPOV")
0^11^B19310582
"RTN","PXAIPOV",1,0)
PXAIPOV ;ISL/JVS,ESW - SET THE DIAGNOSIS/PROBLEM LIST NODES ; 6/25/03 2:05pm
"RTN","PXAIPOV",2,0)
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**28,73,69,108,112**;Aug 12, 1996
"RTN","PXAIPOV",3,0)
 ;
"RTN","PXAIPOV",4,0)
 Q
"RTN","PXAIPOV",5,0)
POV ;--CREATE DIAGNOSIS
"RTN","PXAIPOV",6,0)
 ;
"RTN","PXAIPOV",7,0)
SET ;--SET AND NEW VARIABLES
"RTN","PXAIPOV",8,0)
 N AFTER0,AFTER12,AFTER800,AFTER801,AFTER811,AFTER802,AFTER812
"RTN","PXAIPOV",9,0)
 N BEFOR0,BEFOR12,BEFOR800,BEFOR801,BEFOR811,BEFOR802,BEFOR812
"RTN","PXAIPOV",10,0)
 N PXAA,PXAB,SUB,PIECE,PXAAX,IENB,STOP,VAR,AFTER8A
"RTN","PXAIPOV",11,0)
 N FPRI,J,LNARR,GMPSAVED,NOPLLIST,PXDIGNS,VAR,PRI
"RTN","PXAIPOV",12,0)
 N POVI,PRVDR,PXBCNT,PXBCNTPL,PXBKY,PXBPMT,PXBSAM,PXBSKY,PXKDONE
"RTN","PXAIPOV",13,0)
 ;
"RTN","PXAIPOV",14,0)
 K PXAERR
"RTN","PXAIPOV",15,0)
 S PXAERR(8)=PXAK
"RTN","PXAIPOV",16,0)
 S PXAERR(7)="DX/PL"
"RTN","PXAIPOV",17,0)
 ;
"RTN","PXAIPOV",18,0)
 S SUB="" F  S SUB=$O(@PXADATA@("DX/PL",PXAK,SUB)) Q:SUB=""  D
"RTN","PXAIPOV",19,0)
 .S PXAA(SUB)=@PXADATA@("DX/PL",PXAK,SUB)
"RTN","PXAIPOV",20,0)
 ;
"RTN","PXAIPOV",21,0)
 ;--VALIDATE ENOUGH DATA
"RTN","PXAIPOV",22,0)
 D VAL^PXAIPOVV Q:$G(STOP)
"RTN","PXAIPOV",23,0)
 ;
"RTN","PXAIPOV",24,0)
SETVARA ;--SET VISIT VARIABLES
"RTN","PXAIPOV",25,0)
 S $P(AFTER0,"^",1)=$G(PXAA("DIAGNOSIS"))
"RTN","PXAIPOV",26,0)
 I $G(PXAA("DELETE")) S $P(AFTER0,"^",1)="@"
"RTN","PXAIPOV",27,0)
 S $P(AFTER0,"^",2)=$G(PATIENT),PXAA("PATIENT")=$G(PATIENT)
"RTN","PXAIPOV",28,0)
 S $P(AFTER0,"^",3)=$G(PXAVISIT)
"RTN","PXAIPOV",29,0)
 S $P(AFTER0,"^",4)=$G(PXAA("NARRATIVE")) D
"RTN","PXAIPOV",30,0)
 .I $G(PXAA("NARRATIVE"))']""!($L($G(PXAA("NARRATIVE")))>245) D
"RTN","PXAIPOV",31,0)
 ..S PXAA("NARRATIVE")=$$EXTTEXT^PXUTL1($G(PXAA("DIAGNOSIS")),1,80,10,3) ;--TEXT OF NARRATIVE
"RTN","PXAIPOV",32,0)
 .S $P(AFTER0,"^",4)=+$$PROVNARR^PXAPI($G(PXAA("NARRATIVE")),9000010.07)
"RTN","PXAIPOV",33,0)
 S $P(AFTER0,"^",12)=$S($G(PXAA("PRIMARY"))=1:"P",1:"S")
"RTN","PXAIPOV",34,0)
 ;--ADDED FOR PATCH 28
"RTN","PXAIPOV",35,0)
 S $P(AFTER0,"^",15)=$G(PXAA("LEXICON TERM"))
"RTN","PXAIPOV",36,0)
 S $P(AFTER0,"^",16)=$G(PXAA("PL IEN"))
"RTN","PXAIPOV",37,0)
 ;--END OF NEW PATCH 28
"RTN","PXAIPOV",38,0)
 S $P(AFTER12,"^",1)=$G(PXAA("EVENT D/T"))
"RTN","PXAIPOV",39,0)
 S $P(AFTER12,"^",4)=$G(PXAA("ENC PROVIDER"))
"RTN","PXAIPOV",40,0)
 ;PX*1*108
"RTN","PXAIPOV",41,0)
 I $G(PXAA("ENC PROVIDER"))]"",'$G(PXAA("DELETE")) D
"RTN","PXAIPOV",42,0)
 .S ^TMP("PXAIADDPRV",$J,$G(PXAA("ENC PROVIDER")))=""
"RTN","PXAIPOV",43,0)
 ;
"RTN","PXAIPOV",44,0)
 I $G(PXAA("CATEGORY"))]"" S $P(AFTER802,"^",1)=+$$PROVNARR^PXAPI($G(PXAA("CATEGORY")),9000010.07)
"RTN","PXAIPOV",45,0)
 S $P(AFTER811,"^",1)=$G(PXAA("COMMENT"))
"RTN","PXAIPOV",46,0)
 ;
"RTN","PXAIPOV",47,0)
 ;
"RTN","PXAIPOV",48,0)
 ;
"RTN","PXAIPOV",49,0)
 ;
"RTN","PXAIPOV",50,0)
 S $P(AFTER800,"^",1)=$G(PXAA("PL SC"))
"RTN","PXAIPOV",51,0)
 S $P(AFTER800,"^",2)=$G(PXAA("PL AO"))
"RTN","PXAIPOV",52,0)
 S $P(AFTER800,"^",3)=$G(PXAA("PL IR"))
"RTN","PXAIPOV",53,0)
 S $P(AFTER800,"^",4)=$G(PXAA("PL EC"))
"RTN","PXAIPOV",54,0)
 S $P(AFTER800,U,5)=$G(PXAA("PL MST"))
"RTN","PXAIPOV",55,0)
 S $P(AFTER800,U,6)=$G(PXAA("PL HNC"))
"RTN","PXAIPOV",56,0)
 ;
"RTN","PXAIPOV",57,0)
 ;
"RTN","PXAIPOV",58,0)
 ;
"RTN","PXAIPOV",59,0)
 D SCC^PXUTLSCC(PATIENT,$P($G(^AUPNVSIT(PXAVISIT,0)),"^",1),$P($G(^AUPNVSIT(PXAVISIT,0)),"^",22),$G(PXAVISIT),AFTER800,.AFTER800)
"RTN","PXAIPOV",60,0)
 ;
"RTN","PXAIPOV",61,0)
 S $P(AFTER812,"^",3)=$G(PXASOURC)
"RTN","PXAIPOV",62,0)
 S $P(AFTER812,"^",2)=$G(PXAPKG)
"RTN","PXAIPOV",63,0)
 ;
"RTN","PXAIPOV",64,0)
 D PL^PXAIPL
"RTN","PXAIPOV",65,0)
 ;
"RTN","PXAIPOV",66,0)
 ;
"RTN","PXAIPOV",67,0)
SETPXKA ;--SET PXK ARRAY AFTER
"RTN","PXAIPOV",68,0)
 S ^TMP("PXK",$J,"POV",PXAK,0,"AFTER")=$G(AFTER0)
"RTN","PXAIPOV",69,0)
 S ^TMP("PXK",$J,"POV",PXAK,12,"AFTER")=$G(AFTER12)
"RTN","PXAIPOV",70,0)
 S ^TMP("PXK",$J,"POV",PXAK,800,"AFTER")=$G(AFTER800)
"RTN","PXAIPOV",71,0)
 S ^TMP("PXK",$J,"POV",PXAK,802,"AFTER")=$G(AFTER802)
"RTN","PXAIPOV",72,0)
 S ^TMP("PXK",$J,"POV",PXAK,811,"AFTER")=$G(AFTER811)
"RTN","PXAIPOV",73,0)
 S ^TMP("PXK",$J,"POV",PXAK,812,"AFTER")=$G(AFTER812)
"RTN","PXAIPOV",74,0)
 ;
"RTN","PXAIPOV",75,0)
SETVARB ;--SET VARIABLES BEFORE
"RTN","PXAIPOV",76,0)
 ;
"RTN","PXAIPOV",77,0)
 ;--GET IEN FOR 'PXK NODE'
"RTN","PXAIPOV",78,0)
 D POV^PXBGPOV(PXAVISIT)
"RTN","PXAIPOV",79,0)
 I $D(^TMP("PXBGPOVMATCH",$J,$G(PXAA("DIAGNOSIS")))) D
"RTN","PXAIPOV",80,0)
 .S (^TMP("PXK",$J,"POV",PXAK,"IEN"),IENB)=$O(^TMP("PXBGPOVMATCH",$J,$G(PXAA("DIAGNOSIS")),0))
"RTN","PXAIPOV",81,0)
 K ^TMP("PXBGPOVMATCH",$J)
"RTN","PXAIPOV",82,0)
 ;
"RTN","PXAIPOV",83,0)
BEFOR ;
"RTN","PXAIPOV",84,0)
 I $G(IENB) D
"RTN","PXAIPOV",85,0)
 .F PIECE=0,12,800,802,811 S ^TMP("PXK",$J,"POV",PXAK,PIECE,"BEFORE")=$G(^AUPNVPOV(IENB,PIECE))
"RTN","PXAIPOV",86,0)
 .K ^TMP("PXK",$J,"POV",PXAK,812)
"RTN","PXAIPOV",87,0)
 E  D
"RTN","PXAIPOV",88,0)
 .S (BEFOR0,BEFOR12,BEFOR800,BEFOR802,BEFOR811,BEFOR812)=""
"RTN","PXAIPOV",89,0)
 .;
"RTN","PXAIPOV",90,0)
SETPXKB .;--SET PXK ARRAY BEFORE
"RTN","PXAIPOV",91,0)
 .S ^TMP("PXK",$J,"POV",PXAK,0,"BEFORE")=$G(BEFOR0)
"RTN","PXAIPOV",92,0)
 .S ^TMP("PXK",$J,"POV",PXAK,12,"BEFORE")=$G(BEFOR12)
"RTN","PXAIPOV",93,0)
 .S ^TMP("PXK",$J,"POV",PXAK,800,"BEFORE")=$G(BEFOR800)
"RTN","PXAIPOV",94,0)
 .S ^TMP("PXK",$J,"POV",PXAK,802,"BEFORE")=$G(BEFOR802)
"RTN","PXAIPOV",95,0)
 .S ^TMP("PXK",$J,"POV",PXAK,811,"BEFORE")=$G(BEFOR811)
"RTN","PXAIPOV",96,0)
 .S ^TMP("PXK",$J,"POV",PXAK,812,"BEFORE")=$G(BEFOR812)
"RTN","PXAIPOV",97,0)
 .S ^TMP("PXK",$J,"POV",PXAK,"IEN")=""
"RTN","PXAIPOV",98,0)
 ;
"RTN","PXAIPOV",99,0)
MISC ;--MISCELLANEOUS NODE
"RTN","PXAIPOV",100,0)
 ;
"RTN","PXAIPOV",101,0)
 Q
"RTN","PXAIPOV",102,0)
PRIM ;--SET A PROVIDER AS PRIMARY
"RTN","PXAIPOV",103,0)
 N PXBCNT,PXBKY,PXBSAM,PXBSKY,PRVDR,FPRI ;108
"RTN","PXAIPOV",104,0)
 D PRV^PXBGPRV(PXAVISIT,.PXBSKY,.PXBKY,.PXBSAM,.PXBCNT,.PRVDR,.FPRI) ;108
"RTN","PXAIPOV",105,0)
 I $D(PRVDR) Q
"RTN","PXAIPOV",106,0)
 I '$D(PXBSKY) Q
"RTN","PXAIPOV",107,0)
 ;
"RTN","PXAIPOV",108,0)
 S $P(AFTER0,"^",1)=$P(^AUPNVPRV($O(PXBSKY(1,0)),0),"^",1)
"RTN","PXAIPOV",109,0)
 S $P(AFTER0,"^",2)=$P(^AUPNVSIT(PXAVISIT,0),"^",5)
"RTN","PXAIPOV",110,0)
 S $P(AFTER0,"^",3)=PXAVISIT
"RTN","PXAIPOV",111,0)
 S $P(AFTER0,"^",4)="P"
"RTN","PXAIPOV",112,0)
 S ^TMP("PXK",$J,"PRV",22222,0,"AFTER")=AFTER0
"RTN","PXAIPOV",113,0)
 S ^TMP("PXK",$J,"PRV",22222,0,"BEFORE")=$G(^AUPNVPRV($O(PXBSKY(1,0)),0))
"RTN","PXAIPOV",114,0)
 S ^TMP("PXK",$J,"PRV",22222,"IEN")=$O(PXBSKY(1,0))
"RTN","PXAIPOV",115,0)
 D EN1^PXKMAIN
"RTN","PXAIPOV",116,0)
 K PXRDR
"RTN","PXAIPOV",117,0)
 K ^TMP("PXBGPOVMATCH",$J)
"RTN","PXAIPOV",118,0)
 Q
"RTN","PXBGPOV")
0^4^B7101924
"RTN","PXBGPOV",1,0)
PXBGPOV ;ISL/JVS,ESW - GATHER POV (DIAGNOSIS) ; 12/2/02 6:22pm
"RTN","PXBGPOV",2,0)
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**11,112**;Aug 12, 1996
"RTN","PXBGPOV",3,0)
 ;
"RTN","PXBGPOV",4,0)
POV(VISIT) ;--Gather the entries in the V POV file
"RTN","PXBGPOV",5,0)
 ;
"RTN","PXBGPOV",6,0)
 N IEN,QUANTITY,PROVIDER,SNARR,POV,GROUP,PXBC,POVI
"RTN","PXBGPOV",7,0)
 N DIC,DR,DA,DIQ,PRIM,PROBLEM,PXBPLA,PXBPL,PKG,SOURC
"RTN","PXBGPOV",8,0)
 ;
"RTN","PXBGPOV",9,0)
 K ^TMP("PXBU",$J),POV,PXBKY,PXBSAM,PXBSKY,PXDIGNS,NOPLLIST
"RTN","PXBGPOV",10,0)
 K ^UTILITY("DIQ1",$J)
"RTN","PXBGPOV",11,0)
 S FPRI="",PROBLEM=""
"RTN","PXBGPOV",12,0)
 I $D(^AUPNVPOV("AD",VISIT)) D
"RTN","PXBGPOV",13,0)
 .S IEN=0 F  S IEN=$O(^AUPNVPOV("AD",VISIT,IEN)) Q:IEN'>0  D
"RTN","PXBGPOV",14,0)
 ..S ^TMP("PXBU",$J,"POV",IEN)=""
"RTN","PXBGPOV",15,0)
 ;
"RTN","PXBGPOV",16,0)
A ;--Set array with DIAGNOSIS codes
"RTN","PXBGPOV",17,0)
 ;
"RTN","PXBGPOV",18,0)
 D PL^PXBGPL(PATIENT)
"RTN","PXBGPOV",19,0)
 I $D(^TMP("PXBU",$J,"POV")) D
"RTN","PXBGPOV",20,0)
 .S IEN=0 F  S IEN=$O(^TMP("PXBU",$J,"POV",IEN)) Q:IEN'>0  D
"RTN","PXBGPOV",21,0)
 ..S DIC=9000010.07,DR=".01;1204;.04;.12;81202;81203",DA=IEN,DIQ(0)="IE" D EN^DIQ1
"RTN","PXBGPOV",22,0)
 ..S PROVIDER=$G(^UTILITY("DIQ1",$J,9000010.07,DA,"1204","E"))
"RTN","PXBGPOV",23,0)
 ..S LNARR=$G(^UTILITY("DIQ1",$J,9000010.07,DA,".04","E"))
"RTN","PXBGPOV",24,0)
 ..S POV=$G(^UTILITY("DIQ1",$J,9000010.07,DA,".01","E"))
"RTN","PXBGPOV",25,0)
 ..S PROBLEM="" S:$D(^TMP("PXBKYPL",$J,POV)) PROBLEM="YES"
"RTN","PXBGPOV",26,0)
 ..S POVI=$G(^UTILITY("DIQ1",$J,9000010.07,DA,".01","I"))
"RTN","PXBGPOV",27,0)
 ..S PRIM=$G(^UTILITY("DIQ1",$J,9000010.07,DA,".12","E"))
"RTN","PXBGPOV",28,0)
 ..S PKG=$G(^UTILITY("DIQ1",$J,9000010.07,DA,"81202","I"))
"RTN","PXBGPOV",29,0)
 ..I PKG']"" S PKG="NONE"
"RTN","PXBGPOV",30,0)
 ..S SOURC=$G(^UTILITY("DIQ1",$J,9000010.07,DA,"81203","I"))
"RTN","PXBGPOV",31,0)
 ..I SOURC']"" S SOURC="NONE"
"RTN","PXBGPOV",32,0)
 ..S SNARR=$$EXTTEXT^PXUTL1(POVI,1,80,3)
"RTN","PXBGPOV",33,0)
 ..I $L(LNARR)'>30 S LNARR=$$EXTTEXT^PXUTL1(POVI,1,80,10)
"RTN","PXBGPOV",34,0)
 ..S FPRI=FPRI_$E(PRIM,1,3) ;--Creating flag for Promary prompt
"RTN","PXBGPOV",35,0)
 ..S GROUP=POV_"^"_PROVIDER_"^"_SNARR_"^"_PRIM_"^"_PROBLEM
"RTN","PXBGPOV",36,0)
 ..;        1        2            3        4          5
"RTN","PXBGPOV",37,0)
 ..I PRIM["PRI" S PXDIGNS("PRIMARY")=POV
"RTN","PXBGPOV",38,0)
 ..S ^TMP("PXBPOV",$J,POV,IEN)=GROUP
"RTN","PXBGPOV",39,0)
 ..S ^TMP("PXBGPOVMATCH",$J,POVI,IEN)=""
"RTN","PXBGPOV",40,0)
 ..I $P(GROUP,"^",5)'["YES" S NOPLLIST=1
"RTN","PXBGPOV",41,0)
 ;
"RTN","PXBGPOV",42,0)
B ;--Add line numbers
"RTN","PXBGPOV",43,0)
 ;
"RTN","PXBGPOV",44,0)
 I $D(^TMP("PXBPOV",$J)) D
"RTN","PXBGPOV",45,0)
 .S PXBC=0,POV="" F  S POV=$O(^TMP("PXBPOV",$J,POV)) Q:POV=""  Q:PXBC>40  D
"RTN","PXBGPOV",46,0)
 ..S IEN=0 F  S IEN=$O(^TMP("PXBPOV",$J,POV,IEN)) Q:IEN=""  S PXBC=PXBC+1 D
"RTN","PXBGPOV",47,0)
 ...S PXBKY(POV,PXBC)=$G(^TMP("PXBPOV",$J,POV,IEN)),PXBSAM(PXBC)=$G(^TMP("PXBPOV",$J,POV,IEN))
"RTN","PXBGPOV",48,0)
 ...S PXBSKY(PXBC,IEN)=""
"RTN","PXBGPOV",49,0)
 ...S PXBSAM(PXBC,"LNARR")=LNARR
"RTN","PXBGPOV",50,0)
FINISG ;--finish up some variables
"RTN","PXBGPOV",51,0)
 ;--FPRI=0 NO PRIMARY
"RTN","PXBGPOV",52,0)
 S:FPRI'["PRI" FPRI=0 S:FPRI["PRI" FPRI=1
"RTN","PXBGPOV",53,0)
EXIT ;--KILL
"RTN","PXBGPOV",54,0)
 K ^TMP("PXBU",$J),^TMP("PXBKYPL",$J),^TMP("PXBSAMPL",$J),PXBSKYPL
"RTN","PXBGPOV",55,0)
 K ^TMP("PXBPOV",$J)
"RTN","PXBGPOV",56,0)
 K ^UTILITY("DIQ1",$J)
"RTN","PXBGPOV",57,0)
 S PXBCNT=+$G(PXBC)
"RTN","PXBGPOV",58,0)
 Q
"RTN","PXBGPOV",59,0)
 ;
"RTN","PXBPCPT")
0^12^B40260903
"RTN","PXBPCPT",1,0)
PXBPCPT ;ISL/JVS,ESW - PROMPT CPT ; 4/23/03 7:15pm
"RTN","PXBPCPT",2,0)
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**11,73,89,112**;Aug 12, 1996
"RTN","PXBPCPT",3,0)
 ;
"RTN","PXBPCPT",4,0)
 ;
"RTN","PXBPCPT",5,0)
 ;
"RTN","PXBPCPT",6,0)
CPT ;--CPT CODE
"RTN","PXBPCPT",7,0)
 ;SELINE=LINE NUMBER OF SELECTED ITEM
"RTN","PXBPCPT",8,0)
 N TIMED,PXBUT,EDATA,DIC,LINE,XFLAG,SELINE
"RTN","PXBPCPT",9,0)
 N I,X,Y,Q,DOUBLEQQ,NF,BAD,OK,CPT,PXEDIT
"RTN","PXBPCPT",10,0)
 I '$D(^DISV(DUZ,"PXBCPT-1")) S ^DISV(DUZ,"PXBCPT-1")=" "
"RTN","PXBPCPT",11,0)
 I '$D(IOSC) D TERM^PXBCC
"RTN","PXBPCPT",12,0)
 S DOUBLEQQ=0,PXEDIT=""
"RTN","PXBPCPT",13,0)
 S TIMED="I '$T!(DATA[""^"")!(DATA="""")"
"RTN","PXBPCPT",14,0)
 S DIC("S")="I $$CPTSCREN^PXBUTL(Y,IDATE)"
"RTN","PXBPCPT",15,0)
C ;--SECOND ENTRY POINT
"RTN","PXBPCPT",16,0)
 W IOSC
"RTN","PXBPCPT",17,0)
 ;---DYNAMIC  HEADER-----------------
"RTN","PXBPCPT",18,0)
 I '$D(CYCL) D
"RTN","PXBPCPT",19,0)
 .I PXBCNT=0,DOUBLEQQ=0 D LOC^PXBCC(2,10) W IOUON,"...There are "_$G(PXBCNT)_" PROCEDURES associated with this encounter.",IOUOFF,IOELEOL
"RTN","PXBPCPT",20,0)
 .I PXBCNT=1,DOUBLEQQ=0 D LOC^PXBCC(2,10) W IOUON,"...There is "_$G(PXBCNT)_" PROCEDURE associated with this encounter.",IOUOFF,IOELEOL
"RTN","PXBPCPT",21,0)
 .I PXBCNT>1,DOUBLEQQ=0 D LOC^PXBCC(2,10) W IOUON,"...There are "_$G(PXBCNT)_" PROCEDURES associated with this encounter.",IOUOFF,IOELEOL
"RTN","PXBPCPT",22,0)
 ;
"RTN","PXBPCPT",23,0)
 D LOC^PXBCC(15,0)
"RTN","PXBPCPT",24,0)
 ;I PXBCNT>30 
"RTN","PXBPCPT",25,0)
 ;W IOCUU,IOELEOL,
"RTN","PXBPCPT",26,0)
 W:PXTLNS>10 !,"Enter '+' for next page, '-' for last page." ;,IORC
"RTN","PXBPCPT",27,0)
 D WIN17^PXBCC(PXBCNT)
"RTN","PXBPCPT",28,0)
 I '$D(^TMP("PXK",$J,"CPT")) W !,"Enter PROCEDURE (CPT CODE): "
"RTN","PXBPCPT",29,0)
 I $D(^TMP("PXK",$J,"CPT")) W !,"Enter ",IOINHI,"NEXT",IOINLOW," PROCEDURE (CPT CODE): "
"RTN","PXBPCPT",30,0)
 W IOELEOL R DATA:DTIME S EDATA=DATA
"RTN","PXBPCPT",31,0)
C1 ;----Third entry point
"RTN","PXBPCPT",32,0)
 X TIMED I  S PXBUT=1 S:DATA="^^" PXBEXIT=0 S:DATA="^^^" PXBRRR="" G CPTX
"RTN","PXBPCPT",33,0)
 I DATA?1.N1"E".NAP S DATA=" "_DATA
"RTN","PXBPCPT",34,0)
 I $L(DATA)>200 S (DATA,EDATA)=$E(DATA,1,199)
"RTN","PXBPCPT",35,0)
 I DATA?24.N S (DATA,EDATA)=$E(DATA,1,24)
"RTN","PXBPCPT",36,0)
 D CASE^PXBUTL
"RTN","PXBPCPT",37,0)
 ;----SPACE BAR---
"RTN","PXBPCPT",38,0)
 I DATA=" ",$D(^DISV(DUZ,"PXBCPT-1")) S DATA=^DISV(DUZ,"PXBCPT-1") W DATA
"RTN","PXBPCPT",39,0)
 ;---------------
"RTN","PXBPCPT",40,0)
 I DATA["^P" G CPTX
"RTN","PXBPCPT",41,0)
 I DATA["^C" G CPTX
"RTN","PXBPCPT",42,0)
 ;
"RTN","PXBPCPT",43,0)
 I ((DATA="+")!(DATA="-")) D DISCPT4^PXBDCPT(DATA) G C
"RTN","PXBPCPT",44,0)
 ;
"RTN","PXBPCPT",45,0)
M ;--------If Multiple entries have been entered
"RTN","PXBPCPT",46,0)
 D ADDM^PXBPCPT1
"RTN","PXBPCPT",47,0)
 I $G(NF) G C1
"RTN","PXBPCPT",48,0)
 ;
"RTN","PXBPCPT",49,0)
DEL ;--------If Multiple deleting
"RTN","PXBPCPT",50,0)
 D DELM^PXBPCPT1
"RTN","PXBPCPT",51,0)
 I DATA["^C" G CPTX
"RTN","PXBPCPT",52,0)
 I $G(NF) G C1
"RTN","PXBPCPT",53,0)
 ;
"RTN","PXBPCPT",54,0)
 D MOD
"RTN","PXBPCPT",55,0)
 ;
"RTN","PXBPCPT",56,0)
LI ;--------If picked a line number display 
"RTN","PXBPCPT",57,0)
 ;
"RTN","PXBPCPT",58,0)
 I (DATA>0)&(DATA<(PXBCNT+1))&($L(DATA)'>$L(PXBCNT)) D
"RTN","PXBPCPT",59,0)
 .S XFLAG=1
"RTN","PXBPCPT",60,0)
 .D DISCPT4^PXBDCPT(PXBSAM(DATA,"LINE"))
"RTN","PXBPCPT",61,0)
 .D REVCPT^PXBCC(DATA,1)
"RTN","PXBPCPT",62,0)
 .S SELINE=DATA
"RTN","PXBPCPT",63,0)
 .F I=1:1:$L(DATA) W IOCUB,IOECH
"RTN","PXBPCPT",64,0)
 .S CPTQUA=$P($G(PXBSAM(DATA)),"^",2)
"RTN","PXBPCPT",65,0)
 .S DATA=$P($G(PXBSAM(DATA)),"^",1)
"RTN","PXBPCPT",66,0)
 .;I $G(Q)'>1 W DATA
"RTN","PXBPCPT",67,0)
 I $D(XFLAG),XFLAG=1 S Y=DATA G FIN
"RTN","PXBPCPT",68,0)
 ;
"RTN","PXBPCPT",69,0)
 ;
"RTN","PXBPCPT",70,0)
 ;--------If CPT is already in the file
"RTN","PXBPCPT",71,0)
 I $D(PXBKY(DATA)) D  I +PXEDIT<0 S DATA="^C" G C1
"RTN","PXBPCPT",72,0)
 .D DISCPT4^PXBDCPT(PXBSAM($O(PXBKY(DATA,0)),"LINE"))
"RTN","PXBPCPT",73,0)
 .K Q
"RTN","PXBPCPT",74,0)
 .D TIMES^PXBUTL(DATA)
"RTN","PXBPCPT",75,0)
 .S PXEDIT=$$MULTI(DATA) Q:+PXEDIT<0
"RTN","PXBPCPT",76,0)
 .I Q=1 D
"RTN","PXBPCPT",77,0)
 ..S LINE=$O(PXBKY(DATA,0))
"RTN","PXBPCPT",78,0)
 ..S XFLAG=1
"RTN","PXBPCPT",79,0)
 ..Q:PXEDIT="A"
"RTN","PXBPCPT",80,0)
 ..D REVCPT^PXBCC(LINE,1)
"RTN","PXBPCPT",81,0)
 ..S CPTQUA=$P($G(PXBSAM(LINE)),"^",2)
"RTN","PXBPCPT",82,0)
 ..S SELINE=$O(Q(0))
"RTN","PXBPCPT",83,0)
 .I Q>1,PXEDIT="E" D
"RTN","PXBPCPT",84,0)
 ..N PXPG
"RTN","PXBPCPT",85,0)
 ..S NLINE=0
"RTN","PXBPCPT",86,0)
 ..S PXPG=+$G(^TMP("PXBDCPT",$J,"START"))+10
"RTN","PXBPCPT",87,0)
 ..F  S NLINE=$O(Q(NLINE)) Q:NLINE=""  Q:PXBSAM(NLINE,"LINE")>PXPG  D
"RTN","PXBPCPT",88,0)
 ...D REVCPT^PXBCC(NLINE,1)
"RTN","PXBPCPT",89,0)
 I '$G(Q) K SELINE
"RTN","PXBPCPT",90,0)
 I PXEDIT="E",$D(Q),Q>1 D  G:DATA="^C" C1 G LI
"RTN","PXBPCPT",91,0)
 .D WHICH^PXBPWCH S:DATA["^" DATA="^C"
"RTN","PXBPCPT",92,0)
 I $D(XFLAG),XFLAG=1 S Y=DATA G FIN
"RTN","PXBPCPT",93,0)
 ;
"RTN","PXBPCPT",94,0)
 ;--------Need to do a DIC lookup on data
"RTN","PXBPCPT",95,0)
 I DATA'="??" D  G:DATA="^C" C I DATA="?" G C
"RTN","PXBPCPT",96,0)
 .D:DATA="?" EN1^PXBHLP0("PXB","CPT",1,"",1)
"RTN","PXBPCPT",97,0)
 I DATA="??" D  G:UDATA="^C" C1 G FIN
"RTN","PXBPCPT",98,0)
 .S DOUBLEQQ=1
"RTN","PXBPCPT",99,0)
 .D EN1^PXBHLP0("PXB","CPT","",1,2)
"RTN","PXBPCPT",100,0)
 .I $L(DATA,"^")>1 D
"RTN","PXBPCPT",101,0)
 ..S DATA=+$P(DATA,"^",2)_$S($P(DATA,U,3)]"":"-"_$P(DATA,U,3),1:"")
"RTN","PXBPCPT",102,0)
 ..D MOD
"RTN","PXBPCPT",103,0)
 ..S Y=DATA
"RTN","PXBPCPT",104,0)
 .S:$G(UDATA)="" UDATA="^C"
"RTN","PXBPCPT",105,0)
 .S:UDATA="^C" (DATA,EDATA,Y)=UDATA
"RTN","PXBPCPT",106,0)
 ;
"RTN","PXBPCPT",107,0)
 ;--If a "?" is NOT entered during lookup
"RTN","PXBPCPT",108,0)
 S FROM="CPT",(VAL,Y)=$P($P($$DOUBLE1^PXBGCPT2(FROM),"^",2),"--",1)
"RTN","PXBPCPT",109,0)
 S (X,DATA,EDATA)=VAL,DIC=81,DIC(0)="MZ" D ^DIC
"RTN","PXBPCPT",110,0)
 I Y<1 S DATA="^C" G C1
"RTN","PXBPCPT",111,0)
 ;
"RTN","PXBPCPT",112,0)
 ;--If Y is good and already in file...
"RTN","PXBPCPT",113,0)
 I $D(Y),$D(PXBKY(Y)) W IORC,IOCUU,IOEDEOP,! D
"RTN","PXBPCPT",114,0)
 .D DISCPT4^PXBDCPT($O(PXBKY($P(Y,"^",2),0)))
"RTN","PXBPCPT",115,0)
 .S LINE=$O(PXBKY($P(Y,"^",2),0)) D REVCPT^PXBCC(LINE,1)
"RTN","PXBPCPT",116,0)
 .S CPTQUA=$P($G(PXBSAM(LINE)),"^",2)
"RTN","PXBPCPT",117,0)
 ;
"RTN","PXBPCPT",118,0)
 ;
"RTN","PXBPCPT",119,0)
FIN ;--FINISH CPT
"RTN","PXBPCPT",120,0)
 I $G(SELINE) S $P(REQE,"^",1)=$P($G(PXBSAM(SELINE)),"^",3)
"RTN","PXBPCPT",121,0)
 I $P(REQE,"^",1)="" S $P(REQE,"^",1)="...No Provider Selected..."
"RTN","PXBPCPT",122,0)
 I $L(Y,"^")'>1 S X=Y,DIC=81,DIC(0)="ZM" D ^DIC
"RTN","PXBPCPT",123,0)
 I Y<0 D HELP^PXBUTL0("CPTM") G C
"RTN","PXBPCPT",124,0)
 S OK=$$CPTOK^PXBUTL(+Y,IDATE) D  G:+OK=0 C
"RTN","PXBPCPT",125,0)
 .I +OK=0 W IOCUF,IOCUF,IORVON,"INACTIVE!--",IORVOFF D HELP1^PXBUTL1("CPTI") ;--HELP
"RTN","PXBPCPT",126,0)
 S CPT=Y(0)
"RTN","PXBPCPT",127,0)
 S ^DISV(DUZ,"PXBCPT-1")=$P(CPT,"^",1)
"RTN","PXBPCPT",128,0)
 I $D(PXBNCPT) S PXBNCPTF=1
"RTN","PXBPCPT",129,0)
 I $D(PXBKY(Y(0,0))),$G(SELINE) D
"RTN","PXBPCPT",130,0)
 .S $P(REQI,"^",8)=$O(PXBSKY(SELINE,0))
"RTN","PXBPCPT",131,0)
 .S PREDOC=$P(PXBSAM(SELINE),"^",3)
"RTN","PXBPCPT",132,0)
 .I $D(PXBPRV($P(REQE,"^",1),$P(CPT,"^",1))) D
"RTN","PXBPCPT",133,0)
 ..Q:$P(REQI,"^",8)]""
"RTN","PXBPCPT",134,0)
 ..S $P(REQI,"^",8)=$O(PXBPRV($P(REQE,"^",1),$P(CPT,"^",1),0))
"RTN","PXBPCPT",135,0)
 .I $D(PXBPRV($P(REQE,"^",1))) D
"RTN","PXBPCPT",136,0)
 ..S CPTQUA=$P(PXBSAM($O(PXBPRV($P(REQE,"^",1),$P(CPT,"^",1),$O(PXBPRV($P(REQE,"^",1),$P(CPT,"^",1),0)),0))),"^",2)
"RTN","PXBPCPT",137,0)
 I $D(PXBKY(Y(0,0))),'$G(SELINE) D
"RTN","PXBPCPT",138,0)
 .;S $P(REQI,"^",8)=$O(PXBSKY($O(PXBKY(Y(0,0),0)),0))
"RTN","PXBPCPT",139,0)
 .S PREDOC=$P(PXBSAM($O(PXBKY(Y(0,0),0))),"^",3)
"RTN","PXBPCPT",140,0)
 .I $D(PXBPRV($P(REQE,"^",1),$P(CPT,"^",1))) D
"RTN","PXBPCPT",141,0)
 ..S $P(REQI,"^",8)=$O(PXBPRV($P(REQE,"^",1),$P(CPT,"^",1),0))
"RTN","PXBPCPT",142,0)
 .I $D(PXBPRV($P(REQE,"^",1),$P(CPT,"^",1))) D
"RTN","PXBPCPT",143,0)
 ..S CPTQUA=$P(PXBSAM($O(PXBPRV($P(REQE,"^",1),$P(CPT,"^",1),$O(PXBPRV($P(REQE,"^",1),$P(CPT,"^",1),0)),0))),"^",2)
"RTN","PXBPCPT",144,0)
 S $P(REQI,"^",3)=+Y
"RTN","PXBPCPT",145,0)
 S $P(REQE,"^",3)=$P(CPT,"^",1)_"-- "_$P(CPT,"^",2)
"RTN","PXBPCPT",146,0)
 S PXBNCPT($P(CPT,"^",1))=$P(REQI,"^",8)
"RTN","PXBPCPT",147,0)
 S:$P(REQI,"^",8)]"" PXBNCPT($P(CPT,"^",1),$P(REQI,"^",8))=""
"RTN","PXBPCPT",148,0)
 ;
"RTN","PXBPCPT",149,0)
CPTX ;--CPT Exit and cleanup
"RTN","PXBPCPT",150,0)
 I $P(REQE,"^",1)="" S $P(REQE,"^",1)="...No Provider Selected..."
"RTN","PXBPCPT",151,0)
 I $G(WHAT)="INTV",DATA="^" S PXBEXIT="^^"
"RTN","PXBPCPT",152,0)
 I $D(PXBRRR) S DATA="^"
"RTN","PXBPCPT",153,0)
 I $D(PREDOC) D
"RTN","PXBPCPT",154,0)
 .I PREDOC]""&($P(REQE,"^",1)'[PREDOC) W !,IOINHI,"--WARNING!",IOINLOW," Currently stored Provider of service:-",IOINHI,PREDOC,IOINLOW D
"RTN","PXBPCPT",155,0)
 ..I '$D(PXBPRV($P(REQE,"^",1),$P(CPT,"^",1))) S $P(REQI,"^",8)=""
"RTN","PXBPCPT",156,0)
 K PXBDPRV,PREDOC
"RTN","PXBPCPT",157,0)
 W IOEDEOP
"RTN","PXBPCPT",158,0)
 Q
"RTN","PXBPCPT",159,0)
MOD ;---Separate CPT modifiers from CPT codes in entry string, if entered
"RTN","PXBPCPT",160,0)
 I DATA?1.N1"-".NE D
"RTN","PXBPCPT",161,0)
 .S PXMODSTR=$P(DATA,"-",2)
"RTN","PXBPCPT",162,0)
 .S (DATA,EDATA)=$P(DATA,"-",1)
"RTN","PXBPCPT",163,0)
 Q
"RTN","PXBPCPT",164,0)
 ;
"RTN","PXBPCPT",165,0)
MULTI(CPTCD) ;--Prompt user to Edit existing CPT code or Add as new entry
"RTN","PXBPCPT",166,0)
 ;
"RTN","PXBPCPT",167,0)
 N DIR,DA,X,Y
"RTN","PXBPCPT",168,0)
 S DIR(0)="SB^E:EDIT;A:ADD"
"RTN","PXBPCPT",169,0)
 S DIR("A")="Do you wish to (E)dit or (A)dd"
"RTN","PXBPCPT",170,0)
 I $D(^IBE(357.69,+CPTCD)) S DIR(0)="SB^E:EDIT",DIR("A")="You may only (E)dit this code, no duplicate E&M allowed."
"RTN","PXBPCPT",171,0)
 S DIR("A",1)="CPT "_CPTCD_" already on file for this Encounter"
"RTN","PXBPCPT",172,0)
 D ^DIR
"RTN","PXBPCPT",173,0)
 I Y']""!(Y="^") Q -1
"RTN","PXBPCPT",174,0)
 Q Y
"RTN","PXBPCPT1")
0^13^B20103669
"RTN","PXBPCPT1",1,0)
PXBPCPT1 ;ISL/JVS,ESW - PROMPT CPT ; 5/19/03 4:11pm
"RTN","PXBPCPT1",2,0)
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**7,73,88,89,108,112**;Aug 12, 1996
"RTN","PXBPCPT1",3,0)
 ;
"RTN","PXBPCPT1",4,0)
 ;
"RTN","PXBPCPT1",5,0)
 ;
"RTN","PXBPCPT1",6,0)
 ;
"RTN","PXBPCPT1",7,0)
 ;
"RTN","PXBPCPT1",8,0)
ADDM ;--------If Multiple entries have been entered assume quantity 1
"RTN","PXBPCPT1",9,0)
 ;
"RTN","PXBPCPT1",10,0)
 ;
"RTN","PXBPCPT1",11,0)
 N OK,PXBLEN,BDATA,PXMDCNT
"RTN","PXBPCPT1",12,0)
 D WIN17^PXBCC(PXBCNT)
"RTN","PXBPCPT1",13,0)
 S NF=0,PXBLEN=0
"RTN","PXBPCPT1",14,0)
 D EDITMM
"RTN","PXBPCPT1",15,0)
 Q
"RTN","PXBPCPT1",16,0)
 I DATA[","&(DATA'["-")&($L($P(DATA,",",1))=5) S NF=1 D
"RTN","PXBPCPT1",17,0)
 .D HELP1^PXBUTL1("CPTMM"),HELP1^PXBUTL1("CON")
"RTN","PXBPCPT1",18,0)
 .R OK:DTIME
"RTN","PXBPCPT1",19,0)
 .S PXBLEN=$L(DATA,",") F PXI=1:1:PXBLEN S PXBPIECE=$P(DATA,",",PXI) D
"RTN","PXBPCPT1",20,0)
 ..I $L($G(PXBPIECE))'=5 S BAD($G(PXBPIECE))="" Q
"RTN","PXBPCPT1",21,0)
 ..I $L(PXBPIECE)=5 S X=PXBPIECE,DIC=81,DIC(0)="Z" D ^DIC
"RTN","PXBPCPT1",22,0)
 ..I Y=-1 S BAD(+$G(PXBPIECE))="" Q
"RTN","PXBPCPT1",23,0)
 ..S $P(REQI,"^",3)=+Y,$P(REQI,"^",4)=1
"RTN","PXBPCPT1",24,0)
 ..S PXBNCPT(PXBPIECE)=""
"RTN","PXBPCPT1",25,0)
 ..D EN0^PXBSTOR(PXBVST,PATIENT,REQI)
"RTN","PXBPCPT1",26,0)
 ..D EN1^PXKMAIN
"RTN","PXBPCPT1",27,0)
 ..D RSET^PXBDREQ("CPT")
"RTN","PXBPCPT1",28,0)
BAD ;----BAD CPT CODES
"RTN","PXBPCPT1",29,0)
 N Y I $G(NF)&($D(BAD)) D  Q
"RTN","PXBPCPT1",30,0)
 .S (BDATA,EDATA)=""
"RTN","PXBPCPT1",31,0)
 .F  S BDATA=$O(BAD(BDATA)) Q:BDATA=""  S EDATA=EDATA_BDATA_"  "
"RTN","PXBPCPT1",32,0)
 .W ! D HELP^PXBUTL0("CPTM") W !
"RTN","PXBPCPT1",33,0)
 .S DIR(0)="E" D ^DIR K DIR,DIRUT
"RTN","PXBPCPT1",34,0)
 .S:Y=1 DATA="^C" S:Y=0!(Y="") DATA="^"
"RTN","PXBPCPT1",35,0)
 I $G(NF)&('$D(BAD)) S DATA="^C" Q
"RTN","PXBPCPT1",36,0)
 Q
"RTN","PXBPCPT1",37,0)
 ;
"RTN","PXBPCPT1",38,0)
BADD(PAR,EDATA) ;----BAD CPT CODES - DISPLAY
"RTN","PXBPCPT1",39,0)
 I $G(NF)&($D(BAD)) D  Q
"RTN","PXBPCPT1",40,0)
 .W !,*7 D HELP^PXBUTL0(PAR) W !
"RTN","PXBPCPT1",41,0)
 Q
"RTN","PXBPCPT1",42,0)
EDITMM ;--ADD MULTIPLE ENTRIES
"RTN","PXBPCPT1",43,0)
 ;
"RTN","PXBPCPT1",44,0)
 N STOP,BAD,GONE,PXBLEN,PXBPIECE,BDATA,PX,PXI,YY,BAD
"RTN","PXBPCPT1",45,0)
 S STOP=0
"RTN","PXBPCPT1",46,0)
 I DATA[",",DATA'["-" D
"RTN","PXBPCPT1",47,0)
 .S PXBLEN=$L(DATA,",")
"RTN","PXBPCPT1",48,0)
 .S NF=1
"RTN","PXBPCPT1",49,0)
 .F PXI=1:1:PXBLEN S PXBPIECE=$P(DATA,",",PXI) Q:STOP=1  D
"RTN","PXBPCPT1",50,0)
 ..;----ADDED
"RTN","PXBPCPT1",51,0)
 ..I PXBPIECE="" Q
"RTN","PXBPCPT1",52,0)
 ..I $D(PXBKY(PXBPIECE)) S BAD(PXBPIECE)="" S NF=1 D BADD("CPTMDP",PXBPIECE) H 2 Q
"RTN","PXBPCPT1",53,0)
 ..I PXI>1 I ","_$P(DATA,",",1,PXI-1)_","[(","_PXBPIECE_",") W !!,*7,"PROCEDURE "_PXBPIECE_" was already processed." H 1 Q
"RTN","PXBPCPT1",54,0)
 ..S X=PXBPIECE,DIC=81,DIC(0)="ZB" D ^DIC
"RTN","PXBPCPT1",55,0)
 ..I Y<1 S BAD(PXBPIECE)="" S NF=1 D BADD("CPTM",PXBPIECE) Q
"RTN","PXBPCPT1",56,0)
 ..S $P(REQI,U,3)=+Y
"RTN","PXBPCPT1",57,0)
 ..S $P(REQI,U,8)=""
"RTN","PXBPCPT1",58,0)
 ..W !!,"For the PROCEDURE: "_X_"--"_$P(Y(0),U,2)
"RTN","PXBPCPT1",59,0)
 ..;--Prompt for CPT Modifiers
"RTN","PXBPCPT1",60,0)
 ..D FULL0^PXBCC
"RTN","PXBPCPT1",61,0)
 ..S PXMDCNT=$$CODM^ICPTCOD($P(REQI,"^",3),"^TMP(""PXMODARR"",$J",PXBSOURC,PXBVSTDT)
"RTN","PXBPCPT1",62,0)
 ..K ^TMP("PXMODARR",$J)
"RTN","PXBPCPT1",63,0)
 ..D MOD^PXBPMOD(PXBVST,PXBPAT,$P(REQI,"^",3),"",$P(REQI,"^",8),IDATE,PXMDCNT,.PXMREQ)
"RTN","PXBPCPT1",64,0)
 ..S:EDATA["^C" STOP=1
"RTN","PXBPCPT1",65,0)
 ..Q:STOP
"RTN","PXBPCPT1",66,0)
 ..S CPTQUA=1
"RTN","PXBPCPT1",67,0)
 ..D QUA^PXBPQUA
"RTN","PXBPCPT1",68,0)
 ..S:EDATA["^C" STOP=1 S:EDATA["^P" STOP=1 Q:STOP=1
"RTN","PXBPCPT1",69,0)
 ..;--Get Provider for CPT
"RTN","PXBPCPT1",70,0)
 ..N PXBSKY,PXBKY,PXBSAM,PXBCNT,PRVDR,FPRI
"RTN","PXBPCPT1",71,0)
 ..D PRV^PXBGPRV(PXBVST,.PXBSKY,.PXBKY,.PXBSAM,.PXBCNT,.PRVDR,.FPRI) W IOSC
"RTN","PXBPCPT1",72,0)
 ..S FROM="CPT" D  Q:STOP
"RTN","PXBPCPT1",73,0)
 ...N DATA D PRV^PXBPPRV I DATA["^P" D  W IOCUU S STOP=1 Q
"RTN","PXBPCPT1",74,0)
 ....S $P(REQI,"^",1)="",$P(REQI,"^",2)="",$P(REQI,"^",7)=""
"RTN","PXBPCPT1",75,0)
 ....K PXBDPRV
"RTN","PXBPCPT1",76,0)
 ..S PXBNCPT(PXBPIECE)=""
"RTN","PXBPCPT1",77,0)
 ..D EN0^PXBSTOR(PXBVST,PATIENT,REQI,.PXMREQ)
"RTN","PXBPCPT1",78,0)
 ..D EN1^PXKMAIN
"RTN","PXBPCPT1",79,0)
 ..D RSET^PXBDREQ("CPT")
"RTN","PXBPCPT1",80,0)
 ..D RSET^PXBDREQ("PRV")
"RTN","PXBPCPT1",81,0)
 ..K PXMREQ
"RTN","PXBPCPT1",82,0)
 ..S $P(REQI,"^",7)=""
"RTN","PXBPCPT1",83,0)
 .S DATA="^C"
"RTN","PXBPCPT1",84,0)
 Q
"RTN","PXBPCPT1",85,0)
 ;
"RTN","PXBPCPT1",86,0)
DELM ;--------If Multiple deleting
"RTN","PXBPCPT1",87,0)
 N DELM,PXBJ,BAD,PXBPIECE,PXBLEN
"RTN","PXBPCPT1",88,0)
 S NF=0,PXBLEN=0 S $P(DELM,"^",2)=1
"RTN","PXBPCPT1",89,0)
 I $E(DATA,1)="@" D
"RTN","PXBPCPT1",90,0)
 .I '$$SURE^PXCEAE2 S DATA="^C" Q
"RTN","PXBPCPT1",91,0)
 .S DATA=$P(DATA,"@",2),NF=1
"RTN","PXBPCPT1",92,0)
 .S PXBLEN=$L(DATA,",")
"RTN","PXBPCPT1",93,0)
 .F PXI=1:1:PXBLEN S PXBPIECE=$P(DATA,",",PXI) D
"RTN","PXBPCPT1",94,0)
 ..I PXBPIECE'["-"&(PXBPIECE'>0!(PXBPIECE'<(PXBCNT+1))) S BAD(+$G(PXBPIECE))="" Q
"RTN","PXBPCPT1",95,0)
 ..I PXBPIECE'["-" D
"RTN","PXBPCPT1",96,0)
 ...I $D(GONE(PXBPIECE)) Q
"RTN","PXBPCPT1",97,0)
 ...Q:PXBPIECE'?.N
"RTN","PXBPCPT1",98,0)
 ...S $P(REQI,"^",8)=$O(PXBSKY(PXBPIECE,0)) ;-IEN
"RTN","PXBPCPT1",99,0)
 ...S X=$P(PXBSAM(PXBPIECE),"^",1),DIC=81,DIC(0)="ZM" D ^DIC
"RTN","PXBPCPT1",100,0)
 ...S $P(REQI,"^",3)=+Y K Y
"RTN","PXBPCPT1",101,0)
 ...S $P(REQI,"^",4)=0 ;-QUANTITY
"RTN","PXBPCPT1",102,0)
 ...S GONE(PXBPIECE)=""
"RTN","PXBPCPT1",103,0)
 ...D EN0^PXBSTOR(PXBVST,PATIENT,REQI)
"RTN","PXBPCPT1",104,0)
 ...D EN1^PXKMAIN
"RTN","PXBPCPT1",105,0)
 ..I PXBPIECE["-" D
"RTN","PXBPCPT1",106,0)
 ...F PXBJ=$P(PXBPIECE,"-",1):1:$P(PXBPIECE,"-",2) D
"RTN","PXBPCPT1",107,0)
 ....I $D(GONE(PXBJ)) Q
"RTN","PXBPCPT1",108,0)
 ....I PXBJ'>0!(PXBJ'<(PXBCNT+1)) S BAD(PXBJ)="" Q
"RTN","PXBPCPT1",109,0)
 ....S $P(REQI,"^",8)=$O(PXBSKY(PXBJ,0)) ;-IEN
"RTN","PXBPCPT1",110,0)
 ....S X=$P(PXBSAM(PXBJ),"^",1),DIC=81,DIC(0)="ZM" D ^DIC
"RTN","PXBPCPT1",111,0)
 ....S $P(REQI,"^",3)=+Y K Y
"RTN","PXBPCPT1",112,0)
 ....S $P(REQI,"^",4)=0 ;-QUANTITY
"RTN","PXBPCPT1",113,0)
 ....S GONE(PXBJ)=""
"RTN","PXBPCPT1",114,0)
 ....D EN0^PXBSTOR(PXBVST,PATIENT,REQI)
"RTN","PXBPCPT1",115,0)
 ....D EN1^PXKMAIN
"RTN","PXBPCPT1",116,0)
 K GONE
"RTN","PXBPCPT1",117,0)
 I $G(NF)&($D(BAD)) D  Q
"RTN","PXBPCPT1",118,0)
 .S (BDATA,EDATA)=""
"RTN","PXBPCPT1",119,0)
 .F  S BDATA=$O(BAD(BDATA)) Q:BDATA=""  S EDATA=EDATA_BDATA_"  "
"RTN","PXBPCPT1",120,0)
 .W ! D HELP^PXBUTL0("CPTMD") W !
"RTN","PXBPCPT1",121,0)
 .S DIR(0)="E" D ^DIR K DIR
"RTN","PXBPCPT1",122,0)
 .S:Y=1 DATA="^C" S:Y=0!(Y="") DATA="^" K Y
"RTN","PXBPCPT1",123,0)
 I $G(NF)&('$D(BAD)) S DATA="^C" Q
"RTN","PXBPCPT1",124,0)
 Q
"RTN","PXBPPOV1")
0^10^B14236080
"RTN","PXBPPOV1",1,0)
PXBPPOV1 ;ISL/JVS,ESW - PROMPT POV ; 1/14/03 1:42pm
"RTN","PXBPPOV1",2,0)
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**11,112**;Aug 12, 1996
"RTN","PXBPPOV1",3,0)
 ;
"RTN","PXBPPOV1",4,0)
 ;
"RTN","PXBPPOV1",5,0)
 ;
"RTN","PXBPPOV1",6,0)
 ;
"RTN","PXBPPOV1",7,0)
 ;
"RTN","PXBPPOV1",8,0)
ADDM ;--------If Multiple POV entries have been entered.
"RTN","PXBPPOV1",9,0)
 ;
"RTN","PXBPPOV1",10,0)
 ;
"RTN","PXBPPOV1",11,0)
 ;
"RTN","PXBPPOV1",12,0)
 N OK,PXBLEN,BDATA
"RTN","PXBPPOV1",13,0)
 D WIN17^PXBCC(PXBCNT)
"RTN","PXBPPOV1",14,0)
 S NF=0,PXBLEN=0
"RTN","PXBPPOV1",15,0)
 I DATA[",",$E(DATA,1)'["@" S NF=1 D
"RTN","PXBPPOV1",16,0)
 .S PXBLEN=$L(DATA,",") F PXI=1:1:PXBLEN S PXBPIECE=$P(DATA,",",PXI) D
"RTN","PXBPPOV1",17,0)
 ..S X=PXBPIECE,DIC=80,DIC(0)="IMZ" D ^DIC
"RTN","PXBPPOV1",18,0)
 ..I Y=-1 S BAD(+$G(PXBPIECE))="" Q
"RTN","PXBPPOV1",19,0)
 ..S $P(REQI,"^",5)=+Y
"RTN","PXBPPOV1",20,0)
 ..S PXBNPOV(PXBPIECE)=""
"RTN","PXBPPOV1",21,0)
 ..D EN0^PXBSTOR(PXBVST,PATIENT,REQI)
"RTN","PXBPPOV1",22,0)
 ..D EN1^PXKMAIN
"RTN","PXBPPOV1",23,0)
 ..D RSET^PXBDREQ("POV")
"RTN","PXBPPOV1",24,0)
 I $G(NF)&($D(BAD)) D  Q
"RTN","PXBPPOV1",25,0)
 .S (BDATA,EDATA)="" F  S BDATA=$O(BAD(BDATA)) Q:BDATA=""  S EDATA=EDATA_BDATA_"  "
"RTN","PXBPPOV1",26,0)
 .W ! D HELP^PXBUTL0("CPTM") W !
"RTN","PXBPPOV1",27,0)
 .S DIR(0)="E" D ^DIR K DIR,DIRUT
"RTN","PXBPPOV1",28,0)
 .S:Y=1 DATA="^P" S:Y=0!(Y="") DATA="^" K Y
"RTN","PXBPPOV1",29,0)
 I $G(NF)&('$D(BAD)) S DATA="^P" Q
"RTN","PXBPPOV1",30,0)
 ;
"RTN","PXBPPOV1",31,0)
 Q
"RTN","PXBPPOV1",32,0)
 ;
"RTN","PXBPPOV1",33,0)
DELM ;--------If Multiple deleting
"RTN","PXBPPOV1",34,0)
 N DELM,PXBJ,BAD,PXBLEN,BDATA
"RTN","PXBPPOV1",35,0)
 S NF=0,PXBLEN=0 S $P(DELM,"^",3)=1
"RTN","PXBPPOV1",36,0)
 I $E(DATA,1)="@" S DATA=$P(DATA,"@",2),NF=1 D
"RTN","PXBPPOV1",37,0)
 .S PXBLEN=$L(DATA,",") F PXI=1:1:PXBLEN S PXBPIECE=$P(DATA,",",PXI) D
"RTN","PXBPPOV1",38,0)
 ..I PXBPIECE'["-"&(PXBPIECE'>0!(PXBPIECE'<(PXBCNT+1))) S BAD(+$G(PXBPIECE))="" Q
"RTN","PXBPPOV1",39,0)
 ..I PXBPIECE'["-" D
"RTN","PXBPPOV1",40,0)
 ...I $D(GONE(PXBPIECE)) Q
"RTN","PXBPPOV1",41,0)
 ...Q:PXBPIECE'?.N
"RTN","PXBPPOV1",42,0)
 ...S $P(REQI,"^",9)=$O(PXBSKY(PXBPIECE,0)) ;-IEN
"RTN","PXBPPOV1",43,0)
 ...S X=$P(PXBSAM(PXBPIECE),"^",1),DIC=80,DIC(0)="IZM" D ^DIC
"RTN","PXBPPOV1",44,0)
 ...S $P(REQI,"^",5)=+Y K Y
"RTN","PXBPPOV1",45,0)
 ...S GONE(PXBPIECE)=""
"RTN","PXBPPOV1",46,0)
 ...D EN0^PXBSTOR(PXBVST,PATIENT,REQI)
"RTN","PXBPPOV1",47,0)
 ...D EN1^PXKMAIN
"RTN","PXBPPOV1",48,0)
 ..I PXBPIECE["-" D
"RTN","PXBPPOV1",49,0)
 ...F PXBJ=$P(PXBPIECE,"-",1):1:$P(PXBPIECE,"-",2) D
"RTN","PXBPPOV1",50,0)
 ....I $D(GONE(PXBJ)) Q
"RTN","PXBPPOV1",51,0)
 ....I PXBJ'>0!(PXBJ'<(PXBCNT+1)) S BAD(PXBJ)="" Q
"RTN","PXBPPOV1",52,0)
 ....S $P(REQI,"^",9)=$O(PXBSKY(PXBJ,0)) ;-IEN
"RTN","PXBPPOV1",53,0)
 ....S X=$P(PXBSAM(PXBJ),"^",1),DIC=80,DIC(0)="IZM" D ^DIC
"RTN","PXBPPOV1",54,0)
 ....S $P(REQI,"^",5)=+Y K Y
"RTN","PXBPPOV1",55,0)
 ....S GONE(PXBJ)=""
"RTN","PXBPPOV1",56,0)
 ....D EN0^PXBSTOR(PXBVST,PATIENT,REQI)
"RTN","PXBPPOV1",57,0)
 ....D EN1^PXKMAIN
"RTN","PXBPPOV1",58,0)
 K GONE
"RTN","PXBPPOV1",59,0)
 I $G(NF)&($D(BAD)) D  Q
"RTN","PXBPPOV1",60,0)
 .S (BDATA,EDATA)="" F  S BDATA=$O(BAD(BDATA)) Q:BDATA=""  S EDATA=EDATA_BDATA_"  "
"RTN","PXBPPOV1",61,0)
 .W ! D HELP^PXBUTL0("CPTMD") W !
"RTN","PXBPPOV1",62,0)
 .S DIR(0)="E" D ^DIR K DIR
"RTN","PXBPPOV1",63,0)
 .S:Y=1 DATA="^P" S:Y=0!(Y="") DATA="^" K Y
"RTN","PXBPPOV1",64,0)
 I $G(NF)&('$D(BAD)) S DATA="^P" Q
"RTN","PXBPPOV1",65,0)
 Q
"RTN","PXBPPOV1",66,0)
PRI ;--Prompt for primary secondary DIAGNOSIS
"RTN","PXBPPOV1",67,0)
 N DIR,Y,X,SEQ
"RTN","PXBPPOV1",68,0)
 S SEQ=0 I $D(PXBKY(DATA)) S SEQ=+$O(PXBKY(DATA,"")) ;PX112
"RTN","PXBPPOV1",69,0)
 I $G(FPRI),$P($G(PXBKY(DATA,SEQ)),U,4)'="PRIMARY" Q  ;PX112
"RTN","PXBPPOV1",70,0)
 W IOCUD,IOELALL,IOCUU
"RTN","PXBPPOV1",71,0)
 S DIR("A",1)="ONE primary diagnosis must be established for each encounter!"
"RTN","PXBPPOV1",72,0)
 S DIR("A")="Is this the PRIMARY DIAGNOSIS for this ENCOUNTER? "
"RTN","PXBPPOV1",73,0)
 S DIR("B")="YES"
"RTN","PXBPPOV1",74,0)
 S DIR("?")="One PRIMARY DIAGNOSIS must be established for each patient encounter. 'Yes' will mean PRIMARY and 'No' will mean SECONDARY."
"RTN","PXBPPOV1",75,0)
 S DIR(0)="Y,A,O"
"RTN","PXBPPOV1",76,0)
 D ^DIR I $G(DIRUT) G PPXIT
"RTN","PXBPPOV1",77,0)
PPFIN ;--Finish off variables
"RTN","PXBPPOV1",78,0)
 I Y=1 S PRI="P^PRIMARY"
"RTN","PXBPPOV1",79,0)
 I Y=0 S PRI="S^SECONDARY"
"RTN","PXBPPOV1",80,0)
 S $P(REQI,"^",6)=$P(PRI,"^",1)
"RTN","PXBPPOV1",81,0)
 S $P(REQE,"^",6)=$P(PRI,"^",2)
"RTN","PXBPPOV1",82,0)
PPXIT ;--EXIT
"RTN","PXBPPOV1",83,0)
 Q
"RTN","PXBPPOV1",84,0)
PRBLM ;--Prompt for Problem list
"RTN","PXBPPOV1",85,0)
 N DIR,Y,X,VALL
"RTN","PXBPPOV1",86,0)
 W IOCUD,IOELALL,IOCUU
"RTN","PXBPPOV1",87,0)
 D WIN17^PXBCC(PXBCNT)
"RTN","PXBPPOV1",88,0)
 S DIR("?")="^S VALL=1,VALL=$$DOUBLE1^PXBGPL2(WHAT)"
"RTN","PXBPPOV1",89,0)
 S DIR("A")="Do you want this DIAGNOSIS added to the PROBLEM LIST? "
"RTN","PXBPPOV1",90,0)
 S DIR("B")="NO"
"RTN","PXBPPOV1",91,0)
 S DIR(0)="Y,A,O"
"RTN","PXBPPOV1",92,0)
 D ^DIR
"RTN","PXBPPOV1",93,0)
 I X="+"!(X="-") S DIR("?")="D DPOV4^PXBDPL(X)"
"RTN","PXBPPOV1",94,0)
 I $G(DIRUT) G PPXIT
"RTN","PXBPPOV1",95,0)
PRPFIN ;--Finish off variables
"RTN","PXBPPOV1",96,0)
 K PXBKYPL,PXBSKYPL,PXBSAMPL,PXBCNTPL
"RTN","PXBPPOV1",97,0)
 K ^TMP("PXBKYPL",$J),^TMP("PXBSAMPL",$J)
"RTN","PXBPPOV1",98,0)
 S PXBPRBLM=+Y
"RTN","PXBPPOV1",99,0)
PRPXIT ;--EXIT
"RTN","PXBPPOV1",100,0)
 Q
"RTN","PXBPPOV1",101,0)
 ;
"RTN","PXBPQUA")
0^9^B3308675
"RTN","PXBPQUA",1,0)
PXBPQUA ;ISL/JVS,ESW - PROMPT QUANTITY ; 6/18/03 6:34pm
"RTN","PXBPQUA",2,0)
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**11,112**;Aug 12, 1996
"RTN","PXBPQUA",3,0)
 ;
"RTN","PXBPQUA",4,0)
 ;
"RTN","PXBPQUA",5,0)
 ;
"RTN","PXBPQUA",6,0)
 ;
"RTN","PXBPQUA",7,0)
 ;
"RTN","PXBPQUA",8,0)
 ;
"RTN","PXBPQUA",9,0)
QUA ;--Quantity
"RTN","PXBPQUA",10,0)
 N TIMED,DATA,DIC,X
"RTN","PXBPQUA",11,0)
 K PXBUT,EDATA
"RTN","PXBPQUA",12,0)
 I '$D(IOEDEOP) D TERM^PXBCC
"RTN","PXBPQUA",13,0)
 S TIMED="I '$T!(DATA[""^"")"
"RTN","PXBPQUA",14,0)
Q ;--SECOND ENTRY POINT
"RTN","PXBPQUA",15,0)
 W !!,"How many times was this procedure performed: "_$S($G(CPTQUA):CPTQUA,1:1)_"//",IOELEOL R DATA:DTIME S EDATA=DATA
"RTN","PXBPQUA",16,0)
Q1 ;---
"RTN","PXBPQUA",17,0)
 X TIMED I  S PXBUT=1 D RSET^PXBDREQ("CPT") G QUAX
"RTN","PXBPQUA",18,0)
 I DATA?.N1"E".NAP S DATA=" "_DATA
"RTN","PXBPQUA",19,0)
 I DATA?24.N S DATA=$E(DATA,1,24)
"RTN","PXBPQUA",20,0)
 ;----SPACE BAR---
"RTN","PXBPQUA",21,0)
 I DATA'=" ",DATA'["^",DATA'="" S ^DISV(DUZ,"PXBQUA-5")=DATA
"RTN","PXBPQUA",22,0)
 I DATA=" ",$D(^DISV(DUZ,"PXBQUA-5")) S DATA=^DISV(DUZ,"PXBQUA-5") W DATA
"RTN","PXBPQUA",23,0)
 ;-----------------
"RTN","PXBPQUA",24,0)
 I DATA]"",DATA'?.2N D:DATA="?" HELP^PXBUTL0("QU1") D:DATA="??" HELP^PXBUTL0("QU2") G Q
"RTN","PXBPQUA",25,0)
 I DATA'="",DATA<1!(DATA>100) G Q
"RTN","PXBPQUA",26,0)
 I DATA="",$G(CPTQUA) S DATA=CPTQUA
"RTN","PXBPQUA",27,0)
 I DATA="",'$G(CPTQUA) S DATA=1
"RTN","PXBPQUA",28,0)
 I DATA="?" D HELP^PXBUTL0("QU1") G QUA
"RTN","PXBPQUA",29,0)
 I DATA="??" D HELP^PXBUTL0("QU2") G QUA
"RTN","PXBPQUA",30,0)
QFIN ;--FINISH UP VARIABLES
"RTN","PXBPQUA",31,0)
 S QUA=DATA
"RTN","PXBPQUA",32,0)
 N VALP S VALP=+$P($G(REQI),U,3)
"RTN","PXBPQUA",33,0)
 I +QUA>1,VALP>0,$D(^IBE(357.69,VALP)) W !,"Only one E&M allowed, quantity changed to 1." S QUA=1
"RTN","PXBPQUA",34,0)
 S $P(REQI,"^",4)=$P(QUA,"^",1)
"RTN","PXBPQUA",35,0)
 S $P(REQE,"^",4)=$P(QUA,"^",1)
"RTN","PXBPQUA",36,0)
QUAX ;--EXIT AND CLEANUP
"RTN","PXBPQUA",37,0)
 K X,CPTQUA
"RTN","PXBPQUA",38,0)
 Q
"RTN","PXCECPT")
0^6^B35800088
"RTN","PXCECPT",1,0)
PXCECPT ;ISL/dee,ISA/Zoltan,esw - Used to edit and display V CPT ; 1/13/03 4:21pm
"RTN","PXCECPT",2,0)
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**14,27,73,89,112**;Aug 12, 1996
"RTN","PXCECPT",3,0)
 ;; ;
"RTN","PXCECPT",4,0)
 Q
"RTN","PXCECPT",5,0)
 ;
"RTN","PXCECPT",6,0)
 ;+Structure of Line with the line label "FORMAT"
"RTN","PXCECPT",7,0)
 ;+;;Long name~File Number~Node Subscripts~Allow Duplicate entries (1=yes, 0=no)~File global name
"RTN","PXCECPT",8,0)
 ;+      1         2             3                   4                                   5
"RTN","PXCECPT",9,0)
 ;+
"RTN","PXCECPT",10,0)
 ;+Structure of Followning lines:
"RTN","PXCECPT",11,0)
 ;+;;Node~Piece~,Field Number~Edit Label~Display Label~Display Routine~Edit Routine~Help Text for DIR("?")~Set of PXCEKEYS that can Edit~D if Detail Display Only~
"RTN","PXCECPT",12,0)
 ;+   1  ~  2  ~      3      ~     4    ~        5    ~        6      ~     7      ~       8              ~          9                  ~         10
"RTN","PXCECPT",13,0)
 ;+The Display & Edit routines are for special cases.
"RTN","PXCECPT",14,0)
 ;+  (The .01 fields cannot have a special edit.)
"RTN","PXCECPT",15,0)
 ;
"RTN","PXCECPT",16,0)
FORMAT ;;CPT~9000010.18~0,1,12,802,811,812~1~^AUPNVCPT
"RTN","PXCECPT",17,0)
 ;;0~1~.01~CPT Code:  ~CPT Code:  ~$$DISPLY01^PXCECPT~ECPTCODE^PXCECPT~^D HELP^PXCEHELP~~B
"RTN","PXCECPT",18,0)
 ;;1~0~1~CPT Modifier:  ~CPT Modifier:  ~$$DISPMOD^PXCECPT~ECPTMOD^PXCECPT~Select a Modifier that is valid for the CPT code.~~B
"RTN","PXCECPT",19,0)
 ;;0~4~.04~Provider Narrative:  ~Provider Narrative:  ~$$DNARRAT^PXCECPT~ENARRAT^PXCEPOV1(1,1,1,81,2)~~~B
"RTN","PXCECPT",20,0)
 ;;0~16~.16~Quantity:  ~Quantity:  ~~EQUAN^PXCECPT~~~D
"RTN","PXCECPT",21,0)
 ;;0~7~.07~Principal Procedure:  ~Principal Procedure:  ~~~~~D
"RTN","PXCECPT",22,0)
 ;;12~4~1204~Encounter Provider:  ~Encounter Provider:  ~~EPROV12^PXCEPRV~~~D
"RTN","PXCECPT",23,0)
 ;;802~1~80201~Provider Narrative Category:  ~Provider Narrative Category:  ~$$DNARRAT^PXCECPT~ENARRAT^PXCEPOV1(0,2,0,81,3)~~C~D
"RTN","PXCECPT",24,0)
 ;;811~1~81101~Comments:  ~Comments:  ~~~~~D
"RTN","PXCECPT",25,0)
 ;;
"RTN","PXCECPT",26,0)
 ;Do not use this one
"RTN","PXCECPT",27,0)
 ;;0~5~.05~Diagnosis:  ~Diagnosis:  ~$$DISPLY01^PXCEPOV~~~~D
"RTN","PXCECPT",28,0)
 ;
"RTN","PXCECPT",29,0)
 ;The interface for AICS to get list on form for help.
"RTN","PXCECPT",30,0)
INTRFACE ;;DG SELECT CPT PROCEDURE CODES
"RTN","PXCECPT",31,0)
 ;+
"RTN","PXCECPT",32,0)
 ;+********************************
"RTN","PXCECPT",33,0)
 ;+Special cases for display.
"RTN","PXCECPT",34,0)
 ;
"RTN","PXCECPT",35,0)
DISPMOD(PXCECPT) ;
"RTN","PXCECPT",36,0)
 ;+Display the modifiers associated with this V CPT entry.
"RTN","PXCECPT",37,0)
 ;+PXCECPT = IEN in V CPT file.
"RTN","PXCECPT",38,0)
 N MODS,SIEN,MODIEN,SCRATCH,MODSTR,MODNAME,OUTSTR
"RTN","PXCECPT",39,0)
 I $G(PXCECPT)="" S PXCECPT=IEN
"RTN","PXCECPT",40,0)
 S OUTSTR=""
"RTN","PXCECPT",41,0)
 I PXCECPT="" Q OUTSTR
"RTN","PXCECPT",42,0)
 S SIEN=0
"RTN","PXCECPT",43,0)
 F MODS=1:1 S SIEN=$O(^AUPNVCPT(PXCECPT,1,SIEN)) Q:'SIEN  D
"RTN","PXCECPT",44,0)
 . S MODIEN=$P($G(^AUPNVCPT(PXCECPT,1,SIEN,0)),"^")
"RTN","PXCECPT",45,0)
 . S $P(OUTSTR,U,MODS)=$$MODTEXT(MODIEN)
"RTN","PXCECPT",46,0)
 Q OUTSTR
"RTN","PXCECPT",47,0)
DNARRAT(PNAR) ;+Display Provider Narrative for procedure in V CPT file.
"RTN","PXCECPT",48,0)
 I PNAR="" Q ""
"RTN","PXCECPT",49,0)
 N PXCEPNAR
"RTN","PXCECPT",50,0)
 S PXCEPNAR=$P(^AUTNPOV(PNAR,0),"^")
"RTN","PXCECPT",51,0)
 I $G(VIEW)="B",$D(ENTRY)>0 D
"RTN","PXCECPT",52,0)
 . N DIC,DR,DA,DIQ,PXCEDIQ1
"RTN","PXCECPT",53,0)
 . S DIC=81
"RTN","PXCECPT",54,0)
 . S DR="2"
"RTN","PXCECPT",55,0)
 . S DA=$P(ENTRY(0),"^",1)
"RTN","PXCECPT",56,0)
 . S DIQ="PXCEDIQ1("
"RTN","PXCECPT",57,0)
 . S DIQ(0)="E"
"RTN","PXCECPT",58,0)
 . D EN^DIQ1
"RTN","PXCECPT",59,0)
 . S:PXCEDIQ1(81,DA,2,"E")=PXCEPNAR PXCEPNAR=""
"RTN","PXCECPT",60,0)
 Q PXCEPNAR
"RTN","PXCECPT",61,0)
 ;+
"RTN","PXCECPT",62,0)
 ;+********************************
"RTN","PXCECPT",63,0)
 ;+Special cases for edit.
"RTN","PXCECPT",64,0)
 ;+
"RTN","PXCECPT",65,0)
ECPTCODE ;+Code to edit CPT Code in V CPT file.
"RTN","PXCECPT",66,0)
 K DIRUT
"RTN","PXCECPT",67,0)
 N DIC,DA,PXCPTDT,PXDFLT
"RTN","PXCECPT",68,0)
 S PXCPTDT=+^TMP("PXK",$J,"VST",1,0,"AFTER")
"RTN","PXCECPT",69,0)
 S (X,PXDFLT)=""
"RTN","PXCECPT",70,0)
 I $P(PXCEAFTR($P(PXCETEXT,"~",1)),"^",$P(PXCETEXT,"~",2))'="" D
"RTN","PXCECPT",71,0)
 . N DIERR,PXCEDILF,PXCEINT,PXCEEXT
"RTN","PXCECPT",72,0)
 . S PXCEINT=$P(PXCEAFTR($P(PXCETEXT,"~",1)),"^",$P(PXCETEXT,"~",2))
"RTN","PXCECPT",73,0)
 . S PXCEEXT=$$EXTERNAL^DILFD(PXCEFILE,$P(PXCETEXT,"~",3),"",PXCEINT,"PXCEDILF")
"RTN","PXCECPT",74,0)
 . S PXDFLT=$S('$D(DIERR):PXCEEXT,1:PXCEINT)
"RTN","PXCECPT",75,0)
 S Y=$$GETCODE^PXCPTAPI(PXDFLT,PXCPTDT)
"RTN","PXCECPT",76,0)
 I Y="@" S X="@" Q
"RTN","PXCECPT",77,0)
 I Y<0 S DIRUT=1 Q
"RTN","PXCECPT",78,0)
 S PXCEMOD=$P(Y,"-",2)
"RTN","PXCECPT",79,0)
 S Y=$P(Y,"-"),X=+Y
"RTN","PXCECPT",80,0)
 I PXCEDIRB="" Q
"RTN","PXCECPT",81,0)
 I $P(PXCEAFTR($P(PXCETEXT,"~",1)),"^",$P(PXCETEXT,"~",2))=X Q
"RTN","PXCECPT",82,0)
 Q:$$CHGCPT()
"RTN","PXCECPT",83,0)
 G ECPTCODE
"RTN","PXCECPT",84,0)
 ;
"RTN","PXCECPT",85,0)
ECPTMOD ;+Prompt for CPT Modifier in V CPT file.
"RTN","PXCECPT",86,0)
 ;
"RTN","PXCECPT",87,0)
 ;--If there are no modifiers for CPT code do not prompt
"RTN","PXCECPT",88,0)
 Q:PXMDCNT'>0
"RTN","PXCECPT",89,0)
 N DTOUT,DUOUT,DIROUT,DIR,PXSUB,PXSEQ,PXSTR,PXARR
"RTN","PXCECPT",90,0)
 N DA,DIC,PXLINE,SUBIEN,PXFILE,PXMOD,PXI
"RTN","PXCECPT",91,0)
 S PXSUB=1,PXSTR=""
"RTN","PXCECPT",92,0)
 S DA=^TMP("PXK",$J,PXCECATS,1,"IEN")
"RTN","PXCECPT",93,0)
 S DR=1
"RTN","PXCECPT",94,0)
 S DIE="^AUPNVCPT("
"RTN","PXCECPT",95,0)
 S DIC(0)="AELMQ"
"RTN","PXCECPT",96,0)
 L +@(DIE_"DA)"):10
"RTN","PXCECPT",97,0)
 I $G(PXCEMOD)]"" D
"RTN","PXCECPT",98,0)
 . I $L(PXCEMOD,",")=1 S DR="1//"_PXCEMOD Q
"RTN","PXCECPT",99,0)
 . S PXMOD=""
"RTN","PXCECPT",100,0)
 . F PXI=1:1 S PXMOD=$P(PXCEMOD,",",PXI) Q:PXMOD=""  D
"RTN","PXCECPT",101,0)
 .. K PXERR
"RTN","PXCECPT",102,0)
 .. D VAL^DIE(9000010.181,DA,.01,"",PXMOD,.PXERR)
"RTN","PXCECPT",103,0)
 .. Q:PXERR="^"
"RTN","PXCECPT",104,0)
 .. S DR="1///^S X=PXMOD"
"RTN","PXCECPT",105,0)
 .. D ^DIE
"RTN","PXCECPT",106,0)
 . S DR=1
"RTN","PXCECPT",107,0)
 D ^DIE
"RTN","PXCECPT",108,0)
 L -@(DIE_"DA)")
"RTN","PXCECPT",109,0)
 ; SET NEWLY FILED CPT MODIFIERS INTO LOCAL ARRAY
"RTN","PXCECPT",110,0)
 K PXCEAFTR(1)
"RTN","PXCECPT",111,0)
 D GETS^DIQ(9000010.18,^TMP("PXK",$J,PXCECATS,1,"IEN"),"1*","I","PXARR")
"RTN","PXCECPT",112,0)
 S PXFILE=9000010.181
"RTN","PXCECPT",113,0)
 S PXSUB=""
"RTN","PXCECPT",114,0)
 F  S PXSUB=$O(PXARR(PXFILE,PXSUB)) Q:PXSUB=""  D
"RTN","PXCECPT",115,0)
 . S PXCEAFTR(1,$P(PXSUB,","))=PXARR(PXFILE,PXSUB,.01,"I")
"RTN","PXCECPT",116,0)
 I $D(DTOUT)!$D(Y) S (PXCEEND,PXCEQUIT)=1 Q
"RTN","PXCECPT",117,0)
 Q
"RTN","PXCECPT",118,0)
 ;
"RTN","PXCECPT",119,0)
EQUAN ;+Code to edit Quantity in V CPT file.
"RTN","PXCECPT",120,0)
 I $P(PXCEAFTR($P(PXCETEXT,"~",1)),"^",$P(PXCETEXT,"~",2))'="" D
"RTN","PXCECPT",121,0)
 . N DIERR,PXCEDILF,PXCEINT,PXCEEXT
"RTN","PXCECPT",122,0)
 . S PXCEINT=$P(PXCEAFTR($P(PXCETEXT,"~",1)),"^",$P(PXCETEXT,"~",2))
"RTN","PXCECPT",123,0)
 . S PXCEEXT=$$EXTERNAL^DILFD(PXCEFILE,$P(PXCETEXT,"~",3),"",PXCEINT,"PXCEDILF")
"RTN","PXCECPT",124,0)
 . S DIR("B")=$S('$D(DIERR):PXCEEXT,1:PXCEINT)
"RTN","PXCECPT",125,0)
 E  S DIR("B")=1
"RTN","PXCECPT",126,0)
 S DIR(0)=PXCEFILE_","_$P(PXCETEXT,"~",3)_"A"
"RTN","PXCECPT",127,0)
 S DIR("A")=$P(PXCETEXT,"~",4)
"RTN","PXCECPT",128,0)
 S:$P(PXCETEXT,"~",8)]"" DIR("?")=$P(PXCETEXT,"~",8)
"RTN","PXCECPT",129,0)
 D ^DIR
"RTN","PXCECPT",130,0)
 K DIR,DA
"RTN","PXCECPT",131,0)
 I $D(DTOUT)!$D(DUOUT) S (PXCEEND,PXCEQUIT)=1 Q
"RTN","PXCECPT",132,0)
 I +Y<1 W !,$C(7),"Quanitity is required.",! G EQUAN
"RTN","PXCECPT",133,0)
 I +Y>1,$D(^IBE(357.69,$G(PXCEIN01))) W !,"Only one E&M allowed, quantity changed to 1.",! S Y=1 ;PX112
"RTN","PXCECPT",134,0)
 S:$P(Y,"^")="" Y=1
"RTN","PXCECPT",135,0)
 S $P(PXCEAFTR($P(PXCETEXT,"~",1)),"^",$P(PXCETEXT,"~",2))=$P(Y,"^")
"RTN","PXCECPT",136,0)
 Q
"RTN","PXCECPT",137,0)
 ;+
"RTN","PXCECPT",138,0)
 ;+********************************
"RTN","PXCECPT",139,0)
 ;+Special Reusable Functionality
"RTN","PXCECPT",140,0)
DISPLY01(PXCECPT) ;
"RTN","PXCECPT",141,0)
 ;Display text for the .01 field which is a pointer to ^ICPT.
"RTN","PXCECPT",142,0)
 ;Also called with the Evaluation and Management Code from the visit
"RTN","PXCECPT",143,0)
 ;  in the parameter.
"RTN","PXCECPT",144,0)
 ;(Must have is called by ASK^PXCEVFI2 and DEL^PXCEVFI2.)
"RTN","PXCECPT",145,0)
 N DIC,DR,DA,DIQ,PXCEFNUM,PXCEDIQ1
"RTN","PXCECPT",146,0)
 S (DIC,PXCEFNUM)=81
"RTN","PXCECPT",147,0)
 S DR=".01;2"
"RTN","PXCECPT",148,0)
 S DA=+$P(PXCECPT,"^",1)
"RTN","PXCECPT",149,0)
 S DIQ="PXCEDIQ1("
"RTN","PXCECPT",150,0)
 S DIQ(0)="E"
"RTN","PXCECPT",151,0)
 D EN^DIQ1
"RTN","PXCECPT",152,0)
 Q PXCEDIQ1(PXCEFNUM,DA,.01,"E")_"     "_PXCEDIQ1(PXCEFNUM,DA,2,"E")
"RTN","PXCECPT",153,0)
EDMOD(MODS,CPT) ;+Edit the Modifiers for a CPT code entry.
"RTN","PXCECPT",154,0)
 N MNUM S MNUM=0 ; Modifier number.
"RTN","PXCECPT",155,0)
 N MIEN,MTEXT
"RTN","PXCECPT",156,0)
 Q
"RTN","PXCECPT",157,0)
MODNAME(MODIEN) ;+Return #.02 NAME for this CPT MODIFIER (#81.3)
"RTN","PXCECPT",158,0)
 Q
"RTN","PXCECPT",159,0)
MODTEXT(MODIEN) ;+Return string of text describing modifier.
"RTN","PXCECPT",160,0)
 ;+MODIEN = IEN in CPT MODIFIER file (#81.3).
"RTN","PXCECPT",161,0)
 ;+Returns:  MODIFIER (#.01) followed by NAME(#.02).
"RTN","PXCECPT",162,0)
 N MOD,DESC,TEXT,RVAL
"RTN","PXCECPT",163,0)
 S RVAL=$$MOD^ICPTMOD(MODIEN,"I")
"RTN","PXCECPT",164,0)
 S MOD=$P(RVAL,"^",2)
"RTN","PXCECPT",165,0)
 S DESC=$P(RVAL,"^",3)
"RTN","PXCECPT",166,0)
 S TEXT=MOD_"  "_DESC
"RTN","PXCECPT",167,0)
 Q TEXT
"RTN","PXCECPT",168,0)
CHGCPT() ;Verify CPT code should be modified
"RTN","PXCECPT",169,0)
 ;If response is yes remove modifiers on file for CPT code
"RTN","PXCECPT",170,0)
 N DIR,DA,X,Y,PXIEN
"RTN","PXCECPT",171,0)
 W !!,$C(7),"WARNING!  THIS WILL ALSO DELETE ANY MODIFIERS ASSOCIATED WITH CPT CODE "_PXCEDIRB
"RTN","PXCECPT",172,0)
 S DIR(0)="Y"
"RTN","PXCECPT",173,0)
 S DIR("A")="SURE YOU WANT TO CHANGE THE CPT CODE?"
"RTN","PXCECPT",174,0)
 S DIR("B")="YES"
"RTN","PXCECPT",175,0)
 D ^DIR
"RTN","PXCECPT",176,0)
 ;Delete CPT Modifiers from V CPT file for current IEN
"RTN","PXCECPT",177,0)
 I 'Y Q +Y
"RTN","PXCECPT",178,0)
 S DA(1)=PXCEFIEN
"RTN","PXCECPT",179,0)
 S DIK="^AUPNVCPT("_DA(1)_","_1_","
"RTN","PXCECPT",180,0)
 S PXIEN=""
"RTN","PXCECPT",181,0)
 F  S PXIEN=$O(PXCEAFTR(1,PXIEN)) Q:PXIEN=""  D
"RTN","PXCECPT",182,0)
 . S DA=PXIEN
"RTN","PXCECPT",183,0)
 . D ^DIK
"RTN","PXCECPT",184,0)
 Q 1
"RTN","PXCECPT",185,0)
 ;
"RTN","PXCECPT",186,0)
NEWCODE ;
"RTN","PXCECPT",187,0)
 K DD,DO
"RTN","PXCECPT",188,0)
 N DIC,X,Y
"RTN","PXCECPT",189,0)
 S DIC="^AUPNVCPT("
"RTN","PXCECPT",190,0)
 S DIC(0)=""
"RTN","PXCECPT",191,0)
 S DIC("DR")=".02////^S X=$P(PXCEAFTR(0),""^"",2);"
"RTN","PXCECPT",192,0)
 S DIC("DR")=DIC("DR")_".03////^S X=$P(PXCEAFTR(0),""^"",3);"
"RTN","PXCECPT",193,0)
 S X=PXCEIN01
"RTN","PXCECPT",194,0)
 D FILE^DICN
"RTN","PXCECPT",195,0)
 S PXCEFIEN=+Y
"RTN","PXCECPT",196,0)
 Q
"RTN","PXCEVFI1")
0^5^B16816847
"RTN","PXCEVFI1",1,0)
PXCEVFI1 ;ISL/dee,esw - Routine to edit a visit or v-file entry ; 12/17/02 8:23am
"RTN","PXCEVFI1",2,0)
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**23,73,112**;Aug 12, 1996
"RTN","PXCEVFI1",3,0)
 Q
"RTN","PXCEVFI1",4,0)
 ;
"RTN","PXCEVFI1",5,0)
EDIT ; -- edit the V-File stored in "AFTER"
"RTN","PXCEVFI1",6,0)
 N DIR,DA,X,Y,C,PXCEINP,PXCEIN01,PXCEEND
"RTN","PXCEVFI1",7,0)
 N PXCELINE,PXCETEXT,PXCEDIRB,PXCEMOD
"RTN","PXCEVFI1",8,0)
 N PXCEKEY,PXCEIKEY,PXCENKEY,PXMDCNT
"RTN","PXCEVFI1",9,0)
 W !
"RTN","PXCEVFI1",10,0)
 G:PXCECAT="VST"!(PXCECAT="APPM")!(PXCECAT="CSTP") REST
"RTN","PXCEVFI1",11,0)
 ;
"RTN","PXCEVFI1",12,0)
EDIT01 ;
"RTN","PXCEVFI1",13,0)
 S PXCETEXT=$P($T(FORMAT+1^@PXCECODE),";;",2)
"RTN","PXCEVFI1",14,0)
 K DIR,DA,X,Y,C,PXCEDIRB
"RTN","PXCEVFI1",15,0)
 I $P(PXCEAFTR(0),"^",1) D
"RTN","PXCEVFI1",16,0)
 . N DIEER,PXCEDILF,PXCEEXT
"RTN","PXCEVFI1",17,0)
 . S PXCEEXT=$$EXTERNAL^DILFD(PXCEFILE,.01,"",$P(PXCEAFTR(0),"^",1),"PXCEDILF")
"RTN","PXCEVFI1",18,0)
 . S PXCEDIRB=$S('$D(DIERR):PXCEEXT,1:$P(PXCEAFTR(0),"^",1))
"RTN","PXCEVFI1",19,0)
 E  S PXCEDIRB=""
"RTN","PXCEVFI1",20,0)
 I $P(PXCETEXT,"~",7)]"" D
"RTN","PXCEVFI1",21,0)
 . D @$P(PXCETEXT,"~",7)
"RTN","PXCEVFI1",22,0)
 E  D
"RTN","PXCEVFI1",23,0)
 . I PXCEDIRB'="" S DIR("B")=PXCEDIRB
"RTN","PXCEVFI1",24,0)
 . S DIR(0)=PXCEFILE_",.01OA"
"RTN","PXCEVFI1",25,0)
 . S DIR("A")=$P(PXCETEXT,"~",4)
"RTN","PXCEVFI1",26,0)
 . S:$P(PXCETEXT,"~",8)]"" DIR("?")=$P(PXCETEXT,"~",8)
"RTN","PXCEVFI1",27,0)
 . D ^DIR
"RTN","PXCEVFI1",28,0)
 I X="@" D  G ENDEDIT
"RTN","PXCEVFI1",29,0)
 . N DIRUT
"RTN","PXCEVFI1",30,0)
 . I $P(PXCEAFTR(0),"^",1)="" D
"RTN","PXCEVFI1",31,0)
 .. W !,"There is no entry to delete."
"RTN","PXCEVFI1",32,0)
 .. D WAIT^PXCEHELP
"RTN","PXCEVFI1",33,0)
 . E  D DEL^PXCEVFI2(PXCECAT)
"RTN","PXCEVFI1",34,0)
 I $D(DIRUT),$P(PXCEAFTR(0),"^",1)="" S PXCELOOP=1
"RTN","PXCEVFI1",35,0)
 I $D(DIRUT) S PXCEQUIT=1 Q
"RTN","PXCEVFI1",36,0)
 S PXCEINP=Y
"RTN","PXCEVFI1",37,0)
 S PXCEIN01=X
"RTN","PXCEVFI1",38,0)
 I X'=PXCEDIRB,$$DUP(PXCEINP) G EDIT01
"RTN","PXCEVFI1",39,0)
 ;--File new CPT code and retrieve IEN
"RTN","PXCEVFI1",40,0)
 I PXCECAT="CPT" D
"RTN","PXCEVFI1",41,0)
 . S PXMDCNT=$$CODM^ICPTCOD(+Y,"^TMP(""PXMODARR"",$J",PXCESOR,+^TMP("PXK",$J,"VST",1,0,"AFTER"))
"RTN","PXCEVFI1",42,0)
 . K ^TMP("PXMODARR",$J)
"RTN","PXCEVFI1",43,0)
 . I $P(PXCEAFTR(0),"^",1)'=""!(PXMDCNT'>0) Q
"RTN","PXCEVFI1",44,0)
 . N PXCEFIEN
"RTN","PXCEVFI1",45,0)
 . D NEWCODE^PXCECPT
"RTN","PXCEVFI1",46,0)
 . S ^TMP("PXK",$J,PXCECATS,1,"IEN")=PXCEFIEN
"RTN","PXCEVFI1",47,0)
 S $P(PXCEAFTR(0),"^",1)=$P(PXCEINP,"^")
"RTN","PXCEVFI1",48,0)
 K DIR,DA
"RTN","PXCEVFI1",49,0)
 ;
"RTN","PXCEVFI1",50,0)
 ;
"RTN","PXCEVFI1",51,0)
REST S PXCEEND=0
"RTN","PXCEVFI1",52,0)
 F PXCELINE=2:1 S PXCETEXT=$P($T(FORMAT+PXCELINE^@PXCECODE),";;",2) Q:PXCETEXT']""  D  Q:PXCEEND
"RTN","PXCEVFI1",53,0)
 . I $P(PXCETEXT,"~",9)]"",$P(PXCETEXT,"~",3)'=80201 S PXCEKEY="" D  Q:PXCEKEY'=1
"RTN","PXCEVFI1",54,0)
 .. S PXCENKEY=$L($P(PXCETEXT,"~",9))
"RTN","PXCEVFI1",55,0)
 .. F PXCEIKEY=1:1:PXCENKEY I PXCEKEYS[$E($P(PXCETEXT,"~",9),PXCEIKEY) S PXCEKEY=1 Q
"RTN","PXCEVFI1",56,0)
 . K DIR,DA,X,Y,C
"RTN","PXCEVFI1",57,0)
 . I $P(PXCETEXT,"~",7)]"" D
"RTN","PXCEVFI1",58,0)
 .. D @$P(PXCETEXT,"~",7)
"RTN","PXCEVFI1",59,0)
 . E  D
"RTN","PXCEVFI1",60,0)
 .. I $P(PXCEAFTR($P(PXCETEXT,"~",1)),"^",$P(PXCETEXT,"~",2))'="" D
"RTN","PXCEVFI1",61,0)
 ... N DIERR,PXCEDILF,PXCEINT,PXCEEXT
"RTN","PXCEVFI1",62,0)
 ... S PXCEINT=$P(PXCEAFTR($P(PXCETEXT,"~",1)),"^",$P(PXCETEXT,"~",2))
"RTN","PXCEVFI1",63,0)
 ... S PXCEEXT=$$EXTERNAL^DILFD(PXCEFILE,$P(PXCETEXT,"~",3),"",PXCEINT,"PXCEDILF")
"RTN","PXCEVFI1",64,0)
 ... S DIR("B")=$S('$D(DIERR):PXCEEXT,1:PXCEINT)
"RTN","PXCEVFI1",65,0)
 .. S DIR(0)=PXCEFILE_","_$P(PXCETEXT,"~",3)_"A"
"RTN","PXCEVFI1",66,0)
 .. S DIR("A")=$P(PXCETEXT,"~",4)
"RTN","PXCEVFI1",67,0)
 .. S:$P(PXCETEXT,"~",8)]"" DIR("?")=$P(PXCETEXT,"~",8)
"RTN","PXCEVFI1",68,0)
 .. D ^DIR
"RTN","PXCEVFI1",69,0)
 .. K DIR,DA
"RTN","PXCEVFI1",70,0)
 .. I X="@" S Y="@"
"RTN","PXCEVFI1",71,0)
 .. E  I $D(DTOUT)!$D(DUOUT) S PXCEEND=1 S:PXCECAT="SIT"!(PXCECAT="APPM")!(PXCECAT="HIST") PXCEQUIT=1 Q
"RTN","PXCEVFI1",72,0)
 .. S $P(PXCEAFTR($P(PXCETEXT,"~",1)),"^",$P(PXCETEXT,"~",2))=$P(Y,"^")
"RTN","PXCEVFI1",73,0)
 . I ($P(PXCETEXT,"~",3)=1202!($P(PXCETEXT,"~",3)=1204)) D:+Y>0 PROVIDER^PXCEVFI4(+Y)
"RTN","PXCEVFI1",74,0)
 ;
"RTN","PXCEVFI1",75,0)
ENDEDIT ;
"RTN","PXCEVFI1",76,0)
 Q
"RTN","PXCEVFI1",77,0)
 ;
"RTN","PXCEVFI1",78,0)
DUP(PXCEINP) ; -- Check for dup entries.
"RTN","PXCEVFI1",79,0)
 Q:PXCECAT="SIT"!(PXCECAT="APPM")!(PXCECAT="HIST") 0
"RTN","PXCEVFI1",80,0)
 ;
"RTN","PXCEVFI1",81,0)
 N PXCEDUP,PXCEINDX,X,Y
"RTN","PXCEVFI1",82,0)
 S PXCEDUP=0
"RTN","PXCEVFI1",83,0)
 S PXCEINDX=""
"RTN","PXCEVFI1",84,0)
 F  S PXCEINDX=$O(@(PXCEAUPN_"(""AD"",PXCEVIEN,PXCEINDX)")) Q:'PXCEINDX!PXCEDUP  S:+@(PXCEAUPN_"(PXCEINDX,0)")=+PXCEINP&(PXCEINDX'=PXCEFIEN) PXCEDUP=1
"RTN","PXCEVFI1",85,0)
 I PXCEDUP D
"RTN","PXCEVFI1",86,0)
 . I PXCEDUP
"RTN","PXCEVFI1",87,0)
 . W !,$P(PXCEINP,"^",2)," is already a "_PXCECATT_" for this Encounter."
"RTN","PXCEVFI1",88,0)
 . I PXCECAT="POV" W !!,"Duplicate Diagnosis Not Allowed." Q  ;PX/112
"RTN","PXCEVFI1",89,0)
 . I PXCECAT="CPT",$D(^IBE(357.69,+$P(PXCEINP,U,2))) W !,"No Duplicate E&M Codes Are Allowed." Q  ;DBIA #: 1906
"RTN","PXCEVFI1",90,0)
 . I $P($T(FORMAT^@PXCECODE),"~",4) D
"RTN","PXCEVFI1",91,0)
 .. N DIR,DA
"RTN","PXCEVFI1",92,0)
 .. S DIR(0)="Y"
"RTN","PXCEVFI1",93,0)
 .. S DIR("A")="Do you want to add another "_$P(PXCEINP,"^",2)_""
"RTN","PXCEVFI1",94,0)
 .. S DIR("B")="NO"
"RTN","PXCEVFI1",95,0)
 .. D ^DIR
"RTN","PXCEVFI1",96,0)
 .. S PXCEDUP='+Y
"RTN","PXCEVFI1",97,0)
 Q PXCEDUP
"RTN","PXCEVFI1",98,0)
 ;
"VER")
8.0^22
**END**
**END**
