Released PX*1*141 SEQ #111
Extracted from mail message
**KIDS**:PX*1.0*141^

**INSTALL NAME**
PX*1.0*141
"BLD",5438,0)
PX*1.0*141^PCE PATIENT CARE ENCOUNTER^0^3040622^y
"BLD",5438,1,0)
^^1^1^3040526^
"BLD",5438,1,1,0)
Provider coming up as invalid provider
"BLD",5438,4,0)
^9.64PA^^
"BLD",5438,"KRN",0)
^9.67PA^8989.52^19
"BLD",5438,"KRN",.4,0)
.4
"BLD",5438,"KRN",.401,0)
.401
"BLD",5438,"KRN",.402,0)
.402
"BLD",5438,"KRN",.403,0)
.403
"BLD",5438,"KRN",.5,0)
.5
"BLD",5438,"KRN",.84,0)
.84
"BLD",5438,"KRN",3.6,0)
3.6
"BLD",5438,"KRN",3.8,0)
3.8
"BLD",5438,"KRN",9.2,0)
9.2
"BLD",5438,"KRN",9.8,0)
9.8
"BLD",5438,"KRN",9.8,"NM",0)
^9.68A^2^2
"BLD",5438,"KRN",9.8,"NM",1,0)
PXBPPRV^^0^B34594557
"BLD",5438,"KRN",9.8,"NM",2,0)
PXBCC^^0^B43544227
"BLD",5438,"KRN",9.8,"NM","B","PXBCC",2)

"BLD",5438,"KRN",9.8,"NM","B","PXBPPRV",1)

"BLD",5438,"KRN",19,0)
19
"BLD",5438,"KRN",19.1,0)
19.1
"BLD",5438,"KRN",101,0)
101
"BLD",5438,"KRN",409.61,0)
409.61
"BLD",5438,"KRN",771,0)
771
"BLD",5438,"KRN",870,0)
870
"BLD",5438,"KRN",8989.51,0)
8989.51
"BLD",5438,"KRN",8989.52,0)
8989.52
"BLD",5438,"KRN",8994,0)
8994
"BLD",5438,"KRN","B",.4,.4)

"BLD",5438,"KRN","B",.401,.401)

"BLD",5438,"KRN","B",.402,.402)

"BLD",5438,"KRN","B",.403,.403)

"BLD",5438,"KRN","B",.5,.5)

"BLD",5438,"KRN","B",.84,.84)

"BLD",5438,"KRN","B",3.6,3.6)

"BLD",5438,"KRN","B",3.8,3.8)

"BLD",5438,"KRN","B",9.2,9.2)

"BLD",5438,"KRN","B",9.8,9.8)

"BLD",5438,"KRN","B",19,19)

"BLD",5438,"KRN","B",19.1,19.1)

"BLD",5438,"KRN","B",101,101)

"BLD",5438,"KRN","B",409.61,409.61)

"BLD",5438,"KRN","B",771,771)

"BLD",5438,"KRN","B",870,870)

"BLD",5438,"KRN","B",8989.51,8989.51)

"BLD",5438,"KRN","B",8989.52,8989.52)

"BLD",5438,"KRN","B",8994,8994)

"BLD",5438,"QUES",0)
^9.62^^
"BLD",5438,"REQB",0)
^9.611^2^2
"BLD",5438,"REQB",1,0)
PX*1.0*108^2
"BLD",5438,"REQB",2,0)
PX*1.0*73^2
"BLD",5438,"REQB","B","PX*1.0*108",1)

"BLD",5438,"REQB","B","PX*1.0*73",2)

"MBREQ")
0
"PKG",413,-1)
1^1
"PKG",413,0)
PCE PATIENT CARE ENCOUNTER^PX^Patient Care Encounter (VA Parent package)^
"PKG",413,20,0)
^9.402P^^
"PKG",413,22,0)
^9.49I^1^1
"PKG",413,22,1,0)
1.0^2960812^2960913^12537
"PKG",413,22,1,"PAH",1,0)
141^3040622
"PKG",413,22,1,"PAH",1,1,0)
^^1^1^3040622
"PKG",413,22,1,"PAH",1,1,1,0)
Provider coming up as invalid provider
"QUES","XPF1",0)
Y
"QUES","XPF1","??")
^D REP^XPDH
"QUES","XPF1","A")
Shall I write over your |FLAG| File
"QUES","XPF1","B")
YES
"QUES","XPF1","M")
D XPF1^XPDIQ
"QUES","XPF2",0)
Y
"QUES","XPF2","??")
^D DTA^XPDH
"QUES","XPF2","A")
Want my data |FLAG| yours
"QUES","XPF2","B")
YES
"QUES","XPF2","M")
D XPF2^XPDIQ
"QUES","XPI1",0)
YO
"QUES","XPI1","??")
^D INHIBIT^XPDH
"QUES","XPI1","A")
Want KIDS to INHIBIT LOGONs during the install
"QUES","XPI1","B")
YES
"QUES","XPI1","M")
D XPI1^XPDIQ
"QUES","XPM1",0)
PO^VA(200,:EM
"QUES","XPM1","??")
^D MG^XPDH
"QUES","XPM1","A")
Enter the Coordinator for Mail Group '|FLAG|'
"QUES","XPM1","B")

"QUES","XPM1","M")
D XPM1^XPDIQ
"QUES","XPO1",0)
Y
"QUES","XPO1","??")
^D MENU^XPDH
"QUES","XPO1","A")
Want KIDS to Rebuild Menu Trees Upon Completion of Install
"QUES","XPO1","B")
YES
"QUES","XPO1","M")
D XPO1^XPDIQ
"QUES","XPZ1",0)
Y
"QUES","XPZ1","??")
^D OPT^XPDH
"QUES","XPZ1","A")
Want to DISABLE Scheduled Options, Menu Options, and Protocols
"QUES","XPZ1","B")
YES
"QUES","XPZ1","M")
D XPZ1^XPDIQ
"QUES","XPZ2",0)
Y
"QUES","XPZ2","??")
^D RTN^XPDH
"QUES","XPZ2","A")
Want to MOVE routines to other CPUs
"QUES","XPZ2","B")
NO
"QUES","XPZ2","M")
D XPZ2^XPDIQ
"RTN")
2
"RTN","PXBCC")
0^2^B43544227
"RTN","PXBCC",1,0)
PXBCC ;ISL/JVS - CURSOR CONTROLS-UTILITY ROUTINES ;10/16/96  10:09
"RTN","PXBCC",2,0)
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**7,73,141**;Aug 12, 1996
"RTN","PXBCC",3,0)
 ;
"RTN","PXBCC",4,0)
 ; Variable List
"RTN","PXBCC",5,0)
 ; PXBSAVE= A Second dopy fo the top Margin in a window
"RTN","PXBCC",6,0)
 ; PXBCNT=  A Count of how many Items listed in top window
"RTN","PXBCC",7,0)
 ;
"RTN","PXBCC",8,0)
ZERO ;--ZERO $X & $Y
"RTN","PXBCC",9,0)
 N DX,DY
"RTN","PXBCC",10,0)
 S DX=0,DY=0 X ^%ZOSF("XY")
"RTN","PXBCC",11,0)
 Q
"RTN","PXBCC",12,0)
DXDY ;RESET $X $Y
"RTN","PXBCC",13,0)
 X ^%ZOSF("XY")
"RTN","PXBCC",14,0)
 Q
"RTN","PXBCC",15,0)
INHI() ; Switch to highlighted video (IOINHI must be defined by caller)
"RTN","PXBCC",16,0)
 S DX=$X#81,DY=$Y#25 W IOINHI X ^%ZOSF("XY")
"RTN","PXBCC",17,0)
 Q ""
"RTN","PXBCC",18,0)
INLO() ; Switch to lowlighted video (IOINLOW must be defined by caller)
"RTN","PXBCC",19,0)
 S DX=$X#81,DY=$Y#25 W IOINLOW X ^%ZOSF("XY")
"RTN","PXBCC",20,0)
 Q ""
"RTN","PXBCC",21,0)
FIX ;--FIX
"RTN","PXBCC",22,0)
 D TERM,FULL0 W IOUOFF,IOG0
"RTN","PXBCC",23,0)
 Q
"RTN","PXBCC",24,0)
FIX1 ;--FIX
"RTN","PXBCC",25,0)
 D TERM,FULL0 W IOUOFF,IOG0
"RTN","PXBCC",26,0)
 Q
"RTN","PXBCC",27,0)
WINDOW(PXBCNT,DOWN) ;--set up window area
"RTN","PXBCC",28,0)
 N I,IOTM,IOBM
"RTN","PXBCC",29,0)
 I PXBCNT>10 S IOTM=17
"RTN","PXBCC",30,0)
 I PXBCNT<11 S IOTM=PXBCNT+7
"RTN","PXBCC",31,0)
 S PXBSAVE=IOTM I '$D(IOSC) D TERM
"RTN","PXBCC",32,0)
 S IOBM=(IOSL-1)
"RTN","PXBCC",33,0)
 W IOSC W @IOSTBM W IORC ;--Create smaller window
"RTN","PXBCC",34,0)
 I '$D(DOWN) F I=1:1:2 W IOCUD ;-- move currsor down twice
"RTN","PXBCC",35,0)
 S PXBWIN=""
"RTN","PXBCC",36,0)
 Q
"RTN","PXBCC",37,0)
WIN17(PXBCNT) ;--set up window area on the 17th line
"RTN","PXBCC",38,0)
 N I,IOTM,IOBM
"RTN","PXBCC",39,0)
 W IOCUOFF
"RTN","PXBCC",40,0)
 S IOTM=17
"RTN","PXBCC",41,0)
 S PXBSAVE=IOTM I '$D(IOSC) D TERM
"RTN","PXBCC",42,0)
 S IOBM=(IOSL-0)
"RTN","PXBCC",43,0)
 W IOSC W @IOSTBM W IORC ;--Create smaller window
"RTN","PXBCC",44,0)
 S PXBWIN=""
"RTN","PXBCC",45,0)
 W IOCUON
"RTN","PXBCC",46,0)
 Q
"RTN","PXBCC",47,0)
 ;
"RTN","PXBCC",48,0)
WINDOW1(PXBCNT) ;--set up window area
"RTN","PXBCC",49,0)
 N I,IOTM,IOBM
"RTN","PXBCC",50,0)
 S IOBM=IOSL-1
"RTN","PXBCC",51,0)
 W IOSC W @IOSTBM W IORC ;--Create smaller window
"RTN","PXBCC",52,0)
 F I=1:1:2 W IOCUD ;-- move currsor down once
"RTN","PXBCC",53,0)
 Q
"RTN","PXBCC",54,0)
 ;
"RTN","PXBCC",55,0)
TERM ;--set up the terminal variables
"RTN","PXBCC",56,0)
 N X
"RTN","PXBCC",57,0)
 S X="IOSGRO;IOSTBM;IOCUU;IOSC;IORC;IOCUD;IOHOME;IOELALL;IORVON;IORVOFF;IOCUF;IONEL;IOBON;IOBOFF;IOUON;IOUOFF;IOELEOL;IOEDALL;IOEDEOP;IOCUB;IOECH;IOELBOL;IOIND"
"RTN","PXBCC",58,0)
 D ENDR^%ZISS,GSET^%ZISS
"RTN","PXBCC",59,0)
 S X="IOINLOW;IOINHI;IOINORM;IOCUOFF;IOCUON;IORI;IOIND;IORESET;IOCUOFF;IOCUON;IOSGR0"
"RTN","PXBCC",60,0)
 D ENDR^%ZISS
"RTN","PXBCC",61,0)
 I IOSTBM="" S IOSTBM=1
"RTN","PXBCC",62,0)
 Q
"RTN","PXBCC",63,0)
FULL ;--set terminal to full scrolling window
"RTN","PXBCC",64,0)
 N IOTM,IOBM,X
"RTN","PXBCC",65,0)
 K PXBWIN
"RTN","PXBCC",66,0)
 I '$D(IOSTBM) D TERM
"RTN","PXBCC",67,0)
 I IOSTBM]"" S IOTM=1,IOBM=(IOSL-(1)) W IOSC W @IOSTBM W IORC
"RTN","PXBCC",68,0)
 S X=IOM X ^%ZOSF("RM")
"RTN","PXBCC",69,0)
 Q
"RTN","PXBCC",70,0)
FULL0 ;--set terminal to full scrolling window
"RTN","PXBCC",71,0)
 N IOTM,IOBM,X
"RTN","PXBCC",72,0)
 I '$D(IOSTBM) D TERM
"RTN","PXBCC",73,0)
 I IOSTBM]"" S IOTM=1,IOBM=IOSL W IOSC W @IOSTBM W IORC
"RTN","PXBCC",74,0)
 S X=IOM X ^%ZOSF("RM")
"RTN","PXBCC",75,0)
 Q
"RTN","PXBCC",76,0)
CLEAR1 ;--clean out all cursor control varibles
"RTN","PXBCC",77,0)
 D KILL^%ZISS,GKILL^%ZISS
"RTN","PXBCC",78,0)
 Q
"RTN","PXBCC",79,0)
UNDON ;--underline on
"RTN","PXBCC",80,0)
 I '$D(IOUON) D TERM^PXBCC
"RTN","PXBCC",81,0)
 W IOUON
"RTN","PXBCC",82,0)
 Q
"RTN","PXBCC",83,0)
UNDOFF ;--underline off
"RTN","PXBCC",84,0)
 I '$D(IOUON) D TERM^PXBCC
"RTN","PXBCC",85,0)
 W IOUOFF
"RTN","PXBCC",86,0)
 Q
"RTN","PXBCC",87,0)
REVCPT(LINE,PXRVON) ;--Reverse Video a particular CPT CODE,PROVIDER OR POV
"RTN","PXBCC",88,0)
 ;
"RTN","PXBCC",89,0)
 ;     INPUT:  LINE = Selection from PXBSAM array
"RTN","PXBCC",90,0)
 ;             PXRVON = Flag to turn reverse video on/off
"RTN","PXBCC",91,0)
 ;                 where: 1 = reverse video on
"RTN","PXBCC",92,0)
 ;                        0 = reverse video off   
"RTN","PXBCC",93,0)
 ;
"RTN","PXBCC",94,0)
 Q:$G(NOREV)=1
"RTN","PXBCC",95,0)
 N ENTRY,XLINE,I,IOTM,IOBM,COL,DX,DY
"RTN","PXBCC",96,0)
 S ENTRY=$G(PXBSAM(LINE))
"RTN","PXBCC",97,0)
 ;Actual line on which CPT code displayed
"RTN","PXBCC",98,0)
 S XLINE=LINE#10+4
"RTN","PXBCC",99,0)
 I XLINE<5 S XLINE=XLINE+10
"RTN","PXBCC",100,0)
 I '$D(IOSC) D TERM
"RTN","PXBCC",101,0)
 S COL=4
"RTN","PXBCC",102,0)
 W IOSC S IOTM=1,IOBM=IOSL W @IOSTBM W IOHOME D ZERO
"RTN","PXBCC",103,0)
 F I=1:1:XLINE W IOCUD
"RTN","PXBCC",104,0)
 F I=1:1:COL W IOCUF
"RTN","PXBCC",105,0)
 S DY=XLINE,DX=COL D DXDY
"RTN","PXBCC",106,0)
 I $G(PXRVON) W IORVON,$P(ENTRY,"^",1),IORVOFF
"RTN","PXBCC",107,0)
 I '$G(PXRVON) W IORVOFF,$P(ENTRY,"^",1)
"RTN","PXBCC",108,0)
 S IOTM=PXBSAVE,IOBM=IOSL W @IOSTBM W IORC
"RTN","PXBCC",109,0)
 Q
"RTN","PXBCC",110,0)
REVPRV(LINE) ;--Reverse Video a particular CPT CODE,PROVIDER OR POV
"RTN","PXBCC",111,0)
 Q:$G(NOREV)=1  Q:$G(FROM)["CPT"  Q:$G(FROM)["PL"
"RTN","PXBCC",112,0)
 N ENTRY,XLINE,I,IOTM,IOBM,COL,DX,DY
"RTN","PXBCC",113,0)
 S ENTRY=$G(PXBSAM(LINE)),XLINE=(LINE#10)+4
"RTN","PXBCC",114,0)
 I XLINE<5 S XLINE=XLINE+10
"RTN","PXBCC",115,0)
 I '$D(IOSC) D TERM
"RTN","PXBCC",116,0)
 S COL=4
"RTN","PXBCC",117,0)
 W IOSC S IOTM=1,IOBM=IOSL W @IOSTBM W IOHOME D ZERO
"RTN","PXBCC",118,0)
 F I=1:1:XLINE W IOCUD
"RTN","PXBCC",119,0)
 F I=1:1:COL W IOCUF
"RTN","PXBCC",120,0)
 S DY=XLINE,DX=COL D DXDY
"RTN","PXBCC",121,0)
 W IORVON,$P(ENTRY,"^",1),IORVOFF
"RTN","PXBCC",122,0)
 S IOTM=PXBSAVE,IOBM=IOSL W @IOSTBM W IORC
"RTN","PXBCC",123,0)
 Q
"RTN","PXBCC",124,0)
REVPOV(LINE) ;--Reverse Video a particular CPT CODE,PROVIDER OR POV
"RTN","PXBCC",125,0)
 Q:$G(NOREV)=1
"RTN","PXBCC",126,0)
 N ENTRY,XLINE,I,IOTM,IOBM,COL,DX,DY
"RTN","PXBCC",127,0)
 S ENTRY=$G(PXBSAM(LINE)),XLINE=(LINE#10)+4
"RTN","PXBCC",128,0)
 I XLINE<5 S XLINE=XLINE+10
"RTN","PXBCC",129,0)
 I '$D(IOSC) D TERM
"RTN","PXBCC",130,0)
 S COL=4
"RTN","PXBCC",131,0)
 W IOSC S IOTM=1,IOBM=IOSL W @IOSTBM W IOHOME D ZERO
"RTN","PXBCC",132,0)
 F I=1:1:XLINE W IOCUD
"RTN","PXBCC",133,0)
 F I=1:1:COL W IOCUF
"RTN","PXBCC",134,0)
 S DY=XLINE,DX=COL D DXDY
"RTN","PXBCC",135,0)
 W IORVON,$J($P($P(ENTRY,"^",1),".",1),4),".",$P($P(ENTRY,"^",1),".",2),IORVOFF
"RTN","PXBCC",136,0)
 S IOTM=PXBSAVE,IOBM=IOSL W @IOSTBM W IORC
"RTN","PXBCC",137,0)
 Q
"RTN","PXBCC",138,0)
REVSTP(LINE) ;--Reverse Video a particular CPT CODE,PROVIDER OR POV
"RTN","PXBCC",139,0)
 Q:$G(NOREV)=1
"RTN","PXBCC",140,0)
 N ENTRY,XLINE,I,IOTM,IOBM,COL,DX,DY
"RTN","PXBCC",141,0)
 S ENTRY=$G(PXBSAM(LINE)),XLINE=(LINE#10)+4
"RTN","PXBCC",142,0)
 I XLINE<5 S XLINE=XLINE+10
"RTN","PXBCC",143,0)
 I '$D(IOSC) D TERM
"RTN","PXBCC",144,0)
 S COL=4
"RTN","PXBCC",145,0)
 W IOSC S IOTM=1,IOBM=IOSL W @IOSTBM W IOHOME D ZERO
"RTN","PXBCC",146,0)
 F I=1:1:XLINE W IOCUD
"RTN","PXBCC",147,0)
 F I=1:1:COL W IOCUF
"RTN","PXBCC",148,0)
 S DY=XLINE,DX=COL D DXDY
"RTN","PXBCC",149,0)
 W IORVON,$P(ENTRY,"^",1),IORVOFF
"RTN","PXBCC",150,0)
 S IOTM=PXBSAVE,IOBM=IOSL W @IOSTBM W IORC
"RTN","PXBCC",151,0)
 Q
"RTN","PXBCC",152,0)
 ;
"RTN","PXBCC",153,0)
UREV(LINE) ;--Reverse Video a particular CPT CODE,PROVIDER OR POV
"RTN","PXBCC",154,0)
 Q
"RTN","PXBCC",155,0)
 ;--**OUT OF ORDER
"RTN","PXBCC",156,0)
 N ENTRY,XLINE,I,IOTM,IOBM,DX,DY
"RTN","PXBCC",157,0)
 S ENTRY=$G(PXBSAM(LINE)),XLINE=LINE+4
"RTN","PXBCC",158,0)
 I '$D(IOSC) D TERM
"RTN","PXBCC",159,0)
 W IOSC S IOTM=1,IOBM=IOSL W @IOSTBM W IOHOME D ZERO
"RTN","PXBCC",160,0)
 F I=1:1:XLINE W IOCUD
"RTN","PXBCC",161,0)
 F I=1:1:4 W IOCUF
"RTN","PXBCC",162,0)
 S DY=XLINE,DX=COL D DXDY
"RTN","PXBCC",163,0)
 W $P(ENTRY,"^",1)
"RTN","PXBCC",164,0)
 S IOTM=PXBSAVE,IOBM=IOSL W @IOSTBM W IORC
"RTN","PXBCC",165,0)
 Q
"RTN","PXBCC",166,0)
 ;
"RTN","PXBCC",167,0)
RREV(LINE,COLUMN,ENTRY) ;--Reverse REQUESTED information
"RTN","PXBCC",168,0)
 Q:$G(NOREV)=1
"RTN","PXBCC",169,0)
 N XLINE,I,IOTM,IOBM,DX,DY
"RTN","PXBCC",170,0)
 S XLINE=LINE+1
"RTN","PXBCC",171,0)
 I '$D(IOSC) D TERM
"RTN","PXBCC",172,0)
 W IOSC S IOTM=1,IOBM=IOSL W @IOSTBM W IOHOME D ZERO
"RTN","PXBCC",173,0)
 F I=1:1:XLINE W IOCUD
"RTN","PXBCC",174,0)
 F I=1:1:COLUMN W IOCUF
"RTN","PXBCC",175,0)
 S DY=XLINE,DX=COLUMN D DXDY
"RTN","PXBCC",176,0)
 W IOELEOL,IOINHI,ENTRY,IOINLOW
"RTN","PXBCC",177,0)
 S IOTM=PXBSAVE,IOBM=IOSL W @IOSTBM W IORC
"RTN","PXBCC",178,0)
 Q
"RTN","PXBCC",179,0)
RREVST(LINE,COLUMN,ENTRY) ;--Reverse REQUESTED information
"RTN","PXBCC",180,0)
 Q:$G(NOREV)=1
"RTN","PXBCC",181,0)
 N XLINE,I,IOTM,IOBM,DX,DY
"RTN","PXBCC",182,0)
 S XLINE=LINE+1
"RTN","PXBCC",183,0)
 I '$D(IOSC) D TERM
"RTN","PXBCC",184,0)
 W IOSC S IOTM=1,IOBM=IOSL W @IOSTBM W IOHOME D ZERO
"RTN","PXBCC",185,0)
 F I=1:1:XLINE W IOCUD
"RTN","PXBCC",186,0)
 F I=1:1:COLUMN W IOCUF
"RTN","PXBCC",187,0)
 S DY=XLINE,DX=COLUMN D DXDY
"RTN","PXBCC",188,0)
 W IORVON,ENTRY,IORVOFF
"RTN","PXBCC",189,0)
 S IOTM=PXBSAVE,IOBM=IOSL W @IOSTBM W IORC
"RTN","PXBCC",190,0)
 Q
"RTN","PXBCC",191,0)
RREVH(LINE,COLUMN,ENTRY) ;--Reverse REQUESTED information
"RTN","PXBCC",192,0)
 Q:$G(NOREV)=1
"RTN","PXBCC",193,0)
 N XLINE,I,IOTM,IOBM,DX,DY
"RTN","PXBCC",194,0)
 S XLINE=LINE+1
"RTN","PXBCC",195,0)
 I '$D(IOSC) D TERM
"RTN","PXBCC",196,0)
 W IOSC S IOTM=1,IOBM=IOSL W @IOSTBM W IOHOME D ZERO
"RTN","PXBCC",197,0)
 F I=1:1:XLINE W IOCUD
"RTN","PXBCC",198,0)
 F I=1:1:COLUMN W IOCUF
"RTN","PXBCC",199,0)
 S DY=XLINE,DX=COLUMN D DXDY
"RTN","PXBCC",200,0)
 W IOELEOL,IOINHI,IOUON,ENTRY,IOINLOW,IOUON F I=1:1:5 W " "
"RTN","PXBCC",201,0)
 W IOUOFF
"RTN","PXBCC",202,0)
 S IOTM=PXBSAVE,IOBM=IOSL W @IOSTBM W IORC
"RTN","PXBCC",203,0)
 Q
"RTN","PXBCC",204,0)
LOC(LINE,COLUMN) ;--Locate Cursor to specified position
"RTN","PXBCC",205,0)
 N PXBOS
"RTN","PXBCC",206,0)
 S PXBOS=^%ZOSF("OS")
"RTN","PXBCC",207,0)
 I PXBOS'["MSM" N DY,DX S DY=LINE,DX=COLUMN X IOXY,^%ZOSF("XY") Q
"RTN","PXBCC",208,0)
 N XLINE,I,IOTM,IOBM,DX,DY
"RTN","PXBCC",209,0)
 W IOCUOFF
"RTN","PXBCC",210,0)
 I '$D(IOSTBM) D TERM
"RTN","PXBCC",211,0)
 S IOTM=1,IOBM=IOSL W @IOSTBM W IOHOME D ZERO
"RTN","PXBCC",212,0)
 I $D(LINE) F I=1:1:LINE W IOIND
"RTN","PXBCC",213,0)
 F I=1:1:COLUMN W IOCUF
"RTN","PXBCC",214,0)
 I $D(LINE) S DY=LINE
"RTN","PXBCC",215,0)
 E  S DY=$Y
"RTN","PXBCC",216,0)
 S DX=COLUMN D DXDY
"RTN","PXBCC",217,0)
 W IOCUON
"RTN","PXBCC",218,0)
 Q
"RTN","PXBCC",219,0)
 ;
"RTN","PXBCC",220,0)
ERASE ;---ERASE THE LIST GOING UPWARDS
"RTN","PXBCC",221,0)
 N PXI
"RTN","PXBCC",222,0)
 I '$D(IOCUU) D TERM^PXBCC
"RTN","PXBCC",223,0)
 D LOC^PXBCC(15,1)
"RTN","PXBCC",224,0)
 S PXI=0 F I=1:1:11 W IORI,IOELALL
"RTN","PXBCC",225,0)
 Q 
"RTN","PXBPPRV")
0^1^B34594557
"RTN","PXBPPRV",1,0)
PXBPPRV ;ISL/JVS,ESW - PROMPT PROVIDER ; 10/31/02 12:12pm
"RTN","PXBPPRV",2,0)
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**1,7,11,19,108,141**;Aug 12, 1996
"RTN","PXBPPRV",3,0)
 ;
"RTN","PXBPPRV",4,0)
 ; VARIABLE LIST
"RTN","PXBPPRV",5,0)
 ; SELINE= Line number of selected item
"RTN","PXBPPRV",6,0)
 ;
"RTN","PXBPPRV",7,0)
PRV ;--PROVIDER
"RTN","PXBPPRV",8,0)
 I $D(PXBNPRVL) W IOSC D LOC^PXBCC(2,0) W IOUON,"Previous Entry:   ",$G(PXBNPRVL(1)) F I=1:1:10 W " "
"RTN","PXBPPRV",9,0)
 I $D(PXBNPRVL) W IORC
"RTN","PXBPPRV",10,0)
 W IOUOFF
"RTN","PXBPPRV",11,0)
 N TIMED,EDATA,DIC,LINE,XFLAG,SELINE,UDATA,ECHO
"RTN","PXBPPRV",12,0)
 I '$D(^DISV(DUZ,"PXBPRV-4")) S ^DISV(DUZ,"PXBPRV-4")=" "
"RTN","PXBPPRV",13,0)
 I '$D(IOSC) D TERM^PXBCC
"RTN","PXBPPRV",14,0)
 S DOUBLEQQ=0
"RTN","PXBPPRV",15,0)
 S TIMED="I '$T!(DATA=""^"")"
"RTN","PXBPPRV",16,0)
P ;--Second Entry point
"RTN","PXBPPRV",17,0)
 W IOSC
"RTN","PXBPPRV",18,0)
 ;--DYNAMIC  HEADER--
"RTN","PXBPPRV",19,0)
 I '$D(CYCL) D
"RTN","PXBPPRV",20,0)
 .I PXBCNT=0,DOUBLEQQ=0,$G(WHAT)'["PRV" D LOC^PXBCC(1,10) W "...There are "_$G(PXBCNT)_" PROVIDER(S) associated with this encounter."
"RTN","PXBPPRV",21,0)
 .I PXBCNT=1,DOUBLEQQ=0,$G(WHAT)'["PRV" D LOC^PXBCC(1,10) W "...There is "_$G(PXBCNT)_" PROVIDER associated with this encounter."
"RTN","PXBPPRV",22,0)
 .I PXBCNT>1,DOUBLEQQ=0,$G(WHAT)'["PRV" D LOC^PXBCC(1,10) W "...There are "_$G(PXBCNT)_" PROVIDERS associated with this encounter."
"RTN","PXBPPRV",23,0)
 ;
"RTN","PXBPPRV",24,0)
 I $G(FROM)'="PL" D LOC^PXBCC(15,0)
"RTN","PXBPPRV",25,0)
 I $G(FROM)'["PRV" N PXBNPRVL
"RTN","PXBPPRV",26,0)
 I $D(FROM),FROM="PL" W IORC
"RTN","PXBPPRV",27,0)
 I $G(FROM)'="PL",PXBCNT>10&('$G(DOUBLEQQ)) W IOELEOL,!,"Enter '+' for next page, '-' for previous page."
"RTN","PXBPPRV",28,0)
 ;--Dynamic prompting for the provider--
"RTN","PXBPPRV",29,0)
 I '$D(^TMP("PXK",$J,"PRV")),'$D(FROM) W !,"Enter PROVIDER: " W IOELEOL
"RTN","PXBPPRV",30,0)
 I '$D(FROM),$D(^TMP("PXK",$J,"PRV")) W !,"Enter ",IOINHI,"NEXT",IOINLOW," PROVIDER: " W IOELEOL
"RTN","PXBPPRV",31,0)
 I $D(FROM),FROM="CPT",'$D(^TMP("PXK",$J,"PRV")) W IORC,!,"Enter PROVIDER associated with PROCEDURE: " W IOELEOL
"RTN","PXBPPRV",32,0)
 I $D(FROM),FROM="PRV" W !,"Enter PROVIDER: " W IOELEOL
"RTN","PXBPPRV",33,0)
 I $D(FROM),FROM="CPT",$D(^TMP("PXK",$J,"PRV")) W IORC,!,"Enter PROVIDER associated with PROCEDURES: " W IOELEOL
"RTN","PXBPPRV",34,0)
 I $D(FROM),FROM="PL"  W !,"Enter PROVIDER associated with PROBLEM: " W IOELEOL
"RTN","PXBPPRV",35,0)
 I $D(FROM),FROM="PL" S PXBDPRV="^"_$P($G(PRVDR("PRIMARY")),U)  ;;108
"RTN","PXBPPRV",36,0)
 ;I $D(PRVDR) S PXBDPRV="^"_$P(PRVDR("PRIMARY"),U) S:$G(PXBCNT)>1&($P($G(REQE),U)=0) D0=$P($G(PRVDR("PRIMARY")),U,3)
"RTN","PXBPPRV",37,0)
 I $D(PRVDR) S PXBDPRV="^"_$P(PRVDR("PRIMARY"),U),D0=$P($G(PRVDR("PRIMARY")),U,3)
"RTN","PXBPPRV",38,0)
 I $D(FROM),FROM="CPT",$P(REQI,U,1),$P(REQE,U,1)'["..." S $P(PXBDPRV,U,2)=$P(REQE,U,1)
"RTN","PXBPPRV",39,0)
 I $P($G(REQI),U,8)'="",$G(FROM)'="CPT" S D0=$P($G(^AUPNVCPT($P(REQI,U,8),12)),U,4),PXBDPRV="^"_$P(REQE,U)
"RTN","PXBPPRV",40,0)
 W $P($G(PXBDPRV),"^",2) W:$D(PXBDPRV) " // ",IOELEOL
"RTN","PXBPPRV",41,0)
 ;
"RTN","PXBPPRV",42,0)
 R DATA:DTIME S (EDATA,ECHO)=DATA
"RTN","PXBPPRV",43,0)
P1 ;--Third entry point
"RTN","PXBPPRV",44,0)
 X TIMED I  S PXBUT=1 S:DATA="^" LEAVE=1 G PRVX
"RTN","PXBPPRV",45,0)
 I DATA?1.N1"E".NAP S DATA=" "_DATA
"RTN","PXBPPRV",46,0)
 I $L(DATA)>200 S (DATA,EDATA)=$E(DATA,1,199)
"RTN","PXBPPRV",47,0)
 I DATA?24.N S (DATA,EDATA)=$E(DATA,1,24)
"RTN","PXBPPRV",48,0)
 D CASE^PXBUTL
"RTN","PXBPPRV",49,0)
 ;---SPACE BAR
"RTN","PXBPPRV",50,0)
 I DATA=" ",$D(^DISV(DUZ,"PXBPRV-4")) S (DATA,EDATA)=^DISV(DUZ,"PXBPRV-4") W DATA
"RTN","PXBPPRV",51,0)
 ;-----------
"RTN","PXBPPRV",52,0)
 I DATA="^^" S PXBEXIT=0 G PRVX
"RTN","PXBPPRV",53,0)
 ;---I Prompt can jump to others put symbols in here
"RTN","PXBPPRV",54,0)
 I DATA["^P" G PRVX
"RTN","PXBPPRV",55,0)
 I DATA["^I" G PRVX
"RTN","PXBPPRV",56,0)
 ;
"RTN","PXBPPRV",57,0)
 I DATA="",$D(PXBDPRV) S DATA=$P($G(PXBDPRV),"^",2) I DATA="" S PXBUT=1 G PRVX
"RTN","PXBPPRV",58,0)
 I DATA="",'$D(PXBDPRV) S PXBUT=1 G PRVX
"RTN","PXBPPRV",59,0)
 ;
"RTN","PXBPPRV",60,0)
 I PXBCNT>10&((DATA="+")!(DATA="-")) D DPRV4^PXBDPRV(DATA) W IORC D WIN17^PXBCC(PXBCNT) G P
"RTN","PXBPPRV",61,0)
 ;
"RTN","PXBPPRV",62,0)
 K PRVN1 S VIEN=0 F I=1:1 S VIEN=$O(PXBSAM(VIEN)) Q:VIEN=""  S PRVN1=PXBSAM(VIEN),PRVN1($P(PRVN1,U,4))=PRVN1_"^"_VIEN
"RTN","PXBPPRV",63,0)
M ;--IF Multiple entries have been entered
"RTN","PXBPPRV",64,0)
 ;--CAN'T DO!!!!
"RTN","PXBPPRV",65,0)
 ;--IF Multiple deleting of entries
"RTN","PXBPPRV",66,0)
 D DELM^PXBPPRV1
"RTN","PXBPPRV",67,0)
 I $G(NF) G P1
"RTN","PXBPPRV",68,0)
 ;
"RTN","PXBPPRV",69,0)
LI ;--If picked a line number
"RTN","PXBPPRV",70,0)
 I (DATA>0)&(DATA<(PXBCNT+1))&($L(DATA)'>$L(PXBCNT)) S XFLAG=1 D REVPRV^PXBCC(DATA) S SELINE=DATA D
"RTN","PXBPPRV",71,0)
 .I $G(FROM)["PL" Q
"RTN","PXBPPRV",72,0)
 .I $G(FROM)["CPT"  K SELINE S DATA="NOT VALID" Q
"RTN","PXBPPRV",73,0)
 .F I=1:1:$L(DATA) W IOCUB,IOECH
"RTN","PXBPPRV",74,0)
 .S PRISEC=$P($G(PXBSAM(DATA)),U,2) S:PRISEC["PRI" FPRI=0
"RTN","PXBPPRV",75,0)
 .S DATA=$P($G(PXBSAM(DATA)),U,1)
"RTN","PXBPPRV",76,0)
 I $D(XFLAG),XFLAG=1 S Y=DATA G PFIN
"RTN","PXBPPRV",77,0)
 ;
"RTN","PXBPPRV",78,0)
 ;--If PRV is already in the file
"RTN","PXBPPRV",79,0)
 I DATA="" S PXBUT=1 G PRVX
"RTN","PXBPPRV",80,0)
 I $G(FROM)'="CPT",'$G(DOUBLEQQ),$D(PXBKY(DATA)) D
"RTN","PXBPPRV",81,0)
 .I PXBCNT>10 D DPRV4^PXBDPRV($O(PXBKY(DATA,0)))
"RTN","PXBPPRV",82,0)
 .K Q D TIMES^PXBUTL(DATA)
"RTN","PXBPPRV",83,0)
 .I Q=1 S LINE=$O(PXBKY(DATA,0)) S XFLAG=1 D:$G(FROM)'="PL" REVPRV^PXBCC(LINE) S PRISEC=$P($G(PXBSAM(LINE)),"^",2) I $P(PXBSAM(LINE),"^",2)["PRI" S FPRI=0
"RTN","PXBPPRV",84,0)
 .I Q>1 S NLINE=0 F  S NLINE=$O(Q(NLINE)) Q:NLINE=""  D REVPRV^PXBCC(NLINE)
"RTN","PXBPPRV",85,0)
 I $D(Q),Q>1 D WHICH^PXBPWCH G LI
"RTN","PXBPPRV",86,0)
 I $D(XFLAG),XFLAG=1 S Y=DATA S:"CPT:PRV"[FROM&($G(D0)>0) Y="`"_D0 G PFIN
"RTN","PXBPPRV",87,0)
 ;--Need to do a DIC lookup on data
"RTN","PXBPPRV",88,0)
 ;
"RTN","PXBPPRV",89,0)
 K FIRST
"RTN","PXBPPRV",90,0)
 I DATA'="??" D:DATA="?" EN1^PXBHLP0("PXB","PRV",1,"",1) G:DATA="^P" P I DATA="?" G P
"RTN","PXBPPRV",91,0)
 I DATA="??" S DOUBLEQQ=1 D EN1^PXBHLP0("PXB","PRV","",1,2) S:DATA="P" UDATA="^P" S:$L(DATA,"^")>1 (Y,DATA,EDATA)=$P(DATA,U,2) S:$G(UDATA)="" UDATA="^P" S:UDATA="^P" (DATA,EDATA,Y)=UDATA G:UDATA="^P" P1 G PFIN
"RTN","PXBPPRV",92,0)
 ;
"RTN","PXBPPRV",93,0)
 ;--If a "?" is NOT entered during lookup
"RTN","PXBPPRV",94,0)
 S FROM="PRV",(VAL,Y)=$$DOUBLE1^PXBGPRV2(FROM) I Y<1 S DATA="^P",DOUBLEQQ=1 G P1
"RTN","PXBPPRV",95,0)
 ;S (X,DATA,EDATA)=$P(VAL,U,2),DIC="^VA(200,",DIC(0)="MZ" D ^DIC
"RTN","PXBPPRV",96,0)
 S X="`"_+Y,(DATA,EDATA)=$P(VAL,U,2),DIC="^VA(200,",DIC(0)="MZ" D ^DIC
"RTN","PXBPPRV",97,0)
 I Y=-1 S PXBUT=1 G PRVX
"RTN","PXBPPRV",98,0)
 ;
"RTN","PXBPPRV",99,0)
 ;--If Y is good and already in file...
"RTN","PXBPPRV",100,0)
 ;I '$G(DOUBLEQQ),$D(Y),$D(PXBKY($P(Y,"^",2))) D
"RTN","PXBPPRV",101,0)
 I '$G(DOUBLEQQ),($P($G(Y),U)>0),$D(PRVN1($P(Y,U))) D
"RTN","PXBPPRV",102,0)
 .S LINE=$P(PRVN1($P(Y,U)),U,5)
"RTN","PXBPPRV",103,0)
 .S PRISEC=$P($G(PXBSAM(LINE)),"^",2) S:PRISEC["PRI" FPRI=0
"RTN","PXBPPRV",104,0)
 S PRV=Y(0)
"RTN","PXBPPRV",105,0)
 ;
"RTN","PXBPPRV",106,0)
PFIN ;--Finish the Provider
"RTN","PXBPPRV",107,0)
 I $L(Y,"^")'>1,$G(SELINE) S X="`"_$P(^AUPNVPRV($O(PXBSKY(SELINE,0)),0),"^",1),DIC="^VA(200,",DIC(0)="MZ" D ^DIC
"RTN","PXBPPRV",108,0)
 I $L(Y,"^")'>1,'$G(SELINE) S X=Y,DIC="^VA(200,",DIC(0)="MZ" D ^DIC
"RTN","PXBPPRV",109,0)
 I +Y<0 D HELP^PXBUTL0("PRVM") W IOCUU G P
"RTN","PXBPPRV",110,0)
 S PRV=Y(0)
"RTN","PXBPPRV",111,0)
 S PXBNPRV($P(PRV,U,1))=""
"RTN","PXBPPRV",112,0)
 S PXBNPRVL(1)=$P(PRV,U,1) S ^DISV(DUZ,"PXBPRV-4")=$P(PRV,U,1)
"RTN","PXBPPRV",113,0)
 I $D(PRVN1($P(Y,U))),$G(SELINE) S $P(REQI,U,7)=$O(PXBSKY(SELINE,0)),$P(REQI,U,2)=$P($G(PXBSAM(SELINE)),U,2)
"RTN","PXBPPRV",114,0)
 I $D(PRVN1($P(Y,U))),'$G(SELINE) S PRVN1=PRVN1($P(Y,U)) D
"RTN","PXBPPRV",115,0)
 .S $P(REQI,U,7)=$O(PXBSKY($P(PRVN1,U,5),0))
"RTN","PXBPPRV",116,0)
 .S PAT=$P(Y(0),U,1),ITEM=$P(PRVN1,U,5),$P(REQI,U,2)=$E($P(PRVN1,U,2),1),$P(REQE,U,2)=$P(PRVN1,U,2)
"RTN","PXBPPRV",117,0)
 S $P(REQI,U,1)=+Y
"RTN","PXBPPRV",118,0)
 I $P(REQI,U,2)']"" S $P(REQI,U,2)="S",$P(REQE,U,2)="SECONDARY"
"RTN","PXBPPRV",119,0)
 S $P(REQE,U,1)=$P(PRV,U,1)
"RTN","PXBPPRV",120,0)
 I '$D(REQI) S REQI=""
"RTN","PXBPPRV",121,0)
 ;---IF INACTIVE ISSUE A WARNING
"RTN","PXBPPRV",122,0)
 I DATA]"" D ACTIVE^PXBPPRV1 K DIR
"RTN","PXBPPRV",123,0)
PRVX ;--EXIT AND CLEAN UP
"RTN","PXBPPRV",124,0)
 K PRVN1,VIEN,D0
"RTN","PXBPPRV",125,0)
 I $G(WHAT)="INTV",DATA="^" S PXBEXIT="^^"
"RTN","PXBPPRV",126,0)
 I '$D(REQI) S REQI=""
"RTN","PXBPPRV",127,0)
 I '$D(REQE) S REQE=""
"RTN","PXBPPRV",128,0)
 I $P(REQE,U,1)="" S $P(REQE,U,1)="...No Provider Selected..."
"RTN","PXBPPRV",129,0)
 I FROM="PRV",$L(EDATA)<40 D
"RTN","PXBPPRV",130,0)
 .F I=1:1:$L(ECHO) W IOCUB,IOELEOL
"RTN","PXBPPRV",131,0)
 .F I=1:1:$L(ECHO) W IOCUF
"RTN","PXBPPRV",132,0)
 .I $P(REQE,U,1)'["...No" W $P(REQE,U,1)
"RTN","PXBPPRV",133,0)
 Q
"VER")
8.0^22
**END**
**END**
