Released MC*2.3*16 SEQ #16
Extracted from mail message
**KIDS**:MC*2.3*16^

**INSTALL NAME**
MC*2.3*16
"BLD",208,0)
MC*2.3*16^MEDICINE^0^2980313^y
"BLD",208,1,0)
^^1^1^2980313^^^^
"BLD",208,1,1,0)
Refer to the patch for the patch description.
"BLD",208,4,0)
^9.64PA^^
"BLD",208,"KRN",0)
^9.67PA^19^18
"BLD",208,"KRN",.4,0)
.4
"BLD",208,"KRN",.401,0)
.401
"BLD",208,"KRN",.402,0)
.402
"BLD",208,"KRN",.403,0)
.403
"BLD",208,"KRN",.5,0)
.5
"BLD",208,"KRN",.84,0)
.84
"BLD",208,"KRN",3.6,0)
3.6
"BLD",208,"KRN",3.8,0)
3.8
"BLD",208,"KRN",9.2,0)
9.2
"BLD",208,"KRN",9.8,0)
9.8
"BLD",208,"KRN",9.8,"NM",0)
^9.68A^9^9
"BLD",208,"KRN",9.8,"NM",1,0)
MCARPAL^^0^B12124288
"BLD",208,"KRN",9.8,"NM",2,0)
MCBPFTP1^^0^B22165624
"BLD",208,"KRN",9.8,"NM",3,0)
MCPFTP1^^0^B22355958
"BLD",208,"KRN",9.8,"NM",4,0)
MCARGES^^0^B25713899
"BLD",208,"KRN",9.8,"NM",5,0)
MCARPACE^^0^B11457429
"BLD",208,"KRN",9.8,"NM",6,0)
MCARHP^^0^B17968839
"BLD",208,"KRN",9.8,"NM",7,0)
MCARAP^^0^B22520575
"BLD",208,"KRN",9.8,"NM",8,0)
MCARP1^^0^B10963685
"BLD",208,"KRN",9.8,"NM",9,0)
MCARAM2^^0^B13953498
"BLD",208,"KRN",9.8,"NM","B","MCARAM2",9)

"BLD",208,"KRN",9.8,"NM","B","MCARAP",7)

"BLD",208,"KRN",9.8,"NM","B","MCARGES",4)

"BLD",208,"KRN",9.8,"NM","B","MCARHP",6)

"BLD",208,"KRN",9.8,"NM","B","MCARP1",8)

"BLD",208,"KRN",9.8,"NM","B","MCARPACE",5)

"BLD",208,"KRN",9.8,"NM","B","MCARPAL",1)

"BLD",208,"KRN",9.8,"NM","B","MCBPFTP1",2)

"BLD",208,"KRN",9.8,"NM","B","MCPFTP1",3)

"BLD",208,"KRN",19,0)
19
"BLD",208,"KRN",19.1,0)
19.1
"BLD",208,"KRN",101,0)
101
"BLD",208,"KRN",409.61,0)
409.61
"BLD",208,"KRN",771,0)
771
"BLD",208,"KRN",869.2,0)
869.2
"BLD",208,"KRN",870,0)
870
"BLD",208,"KRN",8994,0)
8994
"BLD",208,"KRN","B",.4,.4)

"BLD",208,"KRN","B",.401,.401)

"BLD",208,"KRN","B",.402,.402)

"BLD",208,"KRN","B",.403,.403)

"BLD",208,"KRN","B",.5,.5)

"BLD",208,"KRN","B",.84,.84)

"BLD",208,"KRN","B",3.6,3.6)

"BLD",208,"KRN","B",3.8,3.8)

"BLD",208,"KRN","B",9.2,9.2)

"BLD",208,"KRN","B",9.8,9.8)

"BLD",208,"KRN","B",19,19)

"BLD",208,"KRN","B",19.1,19.1)

"BLD",208,"KRN","B",101,101)

"BLD",208,"KRN","B",409.61,409.61)

"BLD",208,"KRN","B",771,771)

"BLD",208,"KRN","B",869.2,869.2)

"BLD",208,"KRN","B",870,870)

"BLD",208,"KRN","B",8994,8994)

"BLD",208,"QUES",0)
^9.62^^
"BLD",208,"REQB",0)
^9.611^^
"OER",113,0)
113^^1^^
"OER",113,4)
K MCGLO,MCNAM
"PKG",113,-1)
1^1
"PKG",113,0)
MEDICINE^MC^MEDICINE PACKAGE INCLUDES ALL AREAS OF MEDICINE
"PKG",113,22,0)
^9.49I^1^1
"PKG",113,22,1,0)
2.3^2960913^2961015^363
"PKG",113,22,1,"PAH",1,0)
16^2980313^10000
"PKG",113,22,1,"PAH",1,1,0)
^^1^1^2980316
"PKG",113,22,1,"PAH",1,1,1,0)
Refer to the patch for the patch description.
"QUES","XPF1",0)
Y
"QUES","XPF1","??")
^D REP^XPDH
"QUES","XPF1","A")
Shall I write over your |FLAG| File
"QUES","XPF1","B")
YES
"QUES","XPF1","M")
D XPF1^XPDIQ
"QUES","XPF2",0)
Y
"QUES","XPF2","??")
^D DTA^XPDH
"QUES","XPF2","A")
Want my data |FLAG| yours
"QUES","XPF2","B")
YES
"QUES","XPF2","M")
D XPF2^XPDIQ
"QUES","XPM1",0)
PO^VA(200,:EM
"QUES","XPM1","??")
^D MG^XPDH
"QUES","XPM1","A")
Enter the Coordinator for Mail Group '|FLAG|'
"QUES","XPM1","B")

"QUES","XPM1","M")
D XPM1^XPDIQ
"QUES","XPZ1",0)
Y
"QUES","XPZ1","??")
^D OPT^XPDH
"QUES","XPZ1","A")
Want to DISABLE Scheduled Options, Menu Options, and Protocols
"QUES","XPZ1","B")
YES
"QUES","XPZ1","M")
D XPZ1^XPDIQ
"QUES","XPZ2",0)
Y
"QUES","XPZ2","??")
^D RTN^XPDH
"QUES","XPZ2","A")
Want to MOVE routines to other CPUs
"QUES","XPZ2","B")
NO
"QUES","XPZ2","M")
D XPZ2^XPDIQ
"RTN")
9
"RTN","MCARAM2")
0^9^B13953498
"RTN","MCARAM2",1,0)
MCARAM2 ;WASH ISC/JKL-MUSE TRANSFER LAB DATA TO LOCAL ;2/13/98  09:12
"RTN","MCARAM2",2,0)
 ;;2.3;Medicine;**16**;09/13/1996
"RTN","MCARAM2",3,0)
 ;
"RTN","MCARAM2",4,0)
 ;
"RTN","MCARAM2",5,0)
 ;Modules to return lab data in a local array
"RTN","MCARAM2",6,0)
 ; USAGE: S X=$$L#^MCARAM2(.A,B) , where # = integer from 7 to 12
"RTN","MCARAM2",7,0)
 ; WHERE: .A=local array into which data is placed
"RTN","MCARAM2",8,0)
 ;         B=1 line of lab data
"RTN","MCARAM2",9,0)
 ;  if unsuccessful, returns an error message
"RTN","MCARAM2",10,0)
 ;  if successful, returns a function value of 0 and a value array:
"RTN","MCARAM2",11,0)
 ;  MCA(field #) = value of field
"RTN","MCARAM2",12,0)
 ;  MCA("CONT") = diagnosis line # in alphabetic form
"RTN","MCARAM2",13,0)
 ;  MCA("DX,#") = line of diagnosis data
"RTN","MCARAM2",14,0)
 ;  MCA("DT") = date/time in FM format
"RTN","MCARAM2",15,0)
 ;
"RTN","MCARAM2",16,0)
L7(MCA,MCD) ;Returns "DT" = date/time in FM format
"RTN","MCARAM2",17,0)
 ;        "DX,G" = 7th line of diagnosis
"RTN","MCARAM2",18,0)
 N MCERR,Y
"RTN","MCARAM2",19,0)
 S MCERR=$$AR^MCARAM4(.MCA,"DAY",MCD,11,22) Q:+MCERR=2 $$LOG^MCARAM7("51-Date is a null data field")  I +MCERR>50 Q MCERR
"RTN","MCARAM2",20,0)
 S MCERR=$$AR^MCARAM4(.MCA,"TM",MCD,23,31) Q:+MCERR=2 $$LOG^MCARAM7("51-Time is a null data field")  I +MCERR>50 Q MCERR
"RTN","MCARAM2",21,0)
 S X=MCA("DAY")_"@"_MCA("TM")
"RTN","MCARAM2",22,0)
 I X?2N1"-"3A1"-"2N1"@"2N1":"2N Q $$LOG^MCARAM7("52-Date/Time not DD-MMM-YYYY@HH:MM")
"RTN","MCARAM2",23,0)
 I X'?2N1"-"3A1"-"4N1"@"2N1":"2N Q $$LOG^MCARAM7("52-Date/Time not DD-MMM-YYYY@HH:MM")
"RTN","MCARAM2",24,0)
 S %DT="RX" D ^%DT I Y'>0 Q $$LOG^MCARAM7("53-Date/Time rejected by %DT")
"RTN","MCARAM2",25,0)
 S:Y>0 MCA("DT")=Y
"RTN","MCARAM2",26,0)
 S MCERR=$$AR^MCARAM4(.MCA,"DX,"_MCA("CONT"),MCD,32,134) I +MCERR>50 Q MCERR
"RTN","MCARAM2",27,0)
 Q 0
"RTN","MCARAM2",28,0)
 ;
"RTN","MCARAM2",29,0)
L8(MCA,MCD) ;Returns Field 3 = vent. rate, "DX,H" = 8th line of diagnosis
"RTN","MCARAM2",30,0)
 N MCERR
"RTN","MCARAM2",31,0)
 S MCERR=$$AR^MCARAM4(.MCA,3,MCD,11,18,1)
"RTN","MCARAM2",32,0)
 I +MCERR=2 K MCA(3) S MCERR=$$LOG^MCARAM7("2-Vent. rate is a null data field")
"RTN","MCARAM2",33,0)
 I +MCERR=1 K MCA(3) S MCERR=$$LOG^MCARAM7("1-Vent. rate not numeric")
"RTN","MCARAM2",34,0)
 I +MCERR>50 Q MCERR
"RTN","MCARAM2",35,0)
 S MCERR=$$AR^MCARAM4(.MCA,"DX,"_MCA("CONT"),MCD,32,134) I +MCERR>50 Q MCERR
"RTN","MCARAM2",36,0)
 Q 0
"RTN","MCARAM2",37,0)
 ;
"RTN","MCARAM2",38,0)
L9(MCA,MCD) ;Returns Field 4 = PR interval, "DX,I" = 9th line of diagnosis
"RTN","MCARAM2",39,0)
 N MCERR
"RTN","MCARAM2",40,0)
 S MCERR=$$AR^MCARAM4(.MCA,4,MCD,12,18,1)
"RTN","MCARAM2",41,0)
 I +MCERR=2 K MCA(4) S MCERR=$$LOG^MCARAM7("2-PR interval is a null data field")
"RTN","MCARAM2",42,0)
 I +MCERR=1 K MCA(4) S MCERR=$$LOG^MCARAM7("1-PR interval not numeric")
"RTN","MCARAM2",43,0)
 I +MCERR>50 Q MCERR
"RTN","MCARAM2",44,0)
 S MCERR=$$AR^MCARAM4(.MCA,"DX,"_MCA("CONT"),MCD,32,134) I +MCERR>50 Q MCERR
"RTN","MCARAM2",45,0)
 Q 0
"RTN","MCARAM2",46,0)
 ;
"RTN","MCARAM2",47,0)
L10(MCA,MCD) ;Returns Field 5 = QRS duration, "DX,J" =10th line of diagnosis
"RTN","MCARAM2",48,0)
 N MCERR
"RTN","MCARAM2",49,0)
 S MCERR=$$AR^MCARAM4(.MCA,5,MCD,13,18,1)
"RTN","MCARAM2",50,0)
 I +MCERR=2 K MCA(5) S MCERR=$$LOG^MCARAM7("2-QRS duration is a null data field")
"RTN","MCARAM2",51,0)
 I +MCERR=1 K MCA(5) S MCERR=$$LOG^MCARAM7("1-QRS duration not numeric")
"RTN","MCARAM2",52,0)
 I +MCERR>50 Q MCERR
"RTN","MCARAM2",53,0)
 S MCERR=$$AR^MCARAM4(.MCA,"DX,"_MCA("CONT"),MCD,32,134) I +MCERR>50 Q MCERR
"RTN","MCARAM2",54,0)
 Q 0
"RTN","MCARAM2",55,0)
 ;
"RTN","MCARAM2",56,0)
L11(MCA,MCD) ;Returns Field 6 = QT, 7 = QTc, "DX,K"=11th line of diagnosis
"RTN","MCARAM2",57,0)
 N MCERR
"RTN","MCARAM2",58,0)
 S MCERR=$$AR^MCARAM4(.MCA,6,MCD,7,14,1)
"RTN","MCARAM2",59,0)
 I +MCERR=2 K MCA(6) S MCERR=$$LOG^MCARAM7("2-QT is a null data field")
"RTN","MCARAM2",60,0)
 I +MCERR=1 K MCA(6) S MCERR=$$LOG^MCARAM7("1-QT not numeric")
"RTN","MCARAM2",61,0)
 I +MCERR>50 Q MCERR
"RTN","MCARAM2",62,0)
 S MCERR=$$AR^MCARAM4(.MCA,7,MCD,16,18,1)
"RTN","MCARAM2",63,0)
 I +MCERR=2 K MCA(7) S MCERR=$$LOG^MCARAM7("2-QTc is a null data field")
"RTN","MCARAM2",64,0)
 I +MCERR=1 K MCA(7) S MCERR=$$LOG^MCARAM7("1-QTc not numeric")
"RTN","MCARAM2",65,0)
 I +MCERR>50 Q MCERR
"RTN","MCARAM2",66,0)
 S MCERR=$$AR^MCARAM4(.MCA,"DX,"_MCA("CONT"),MCD,32,134) I +MCERR>50 Q MCERR
"RTN","MCARAM2",67,0)
 Q 0
"RTN","MCARAM2",68,0)
 ;
"RTN","MCARAM2",69,0)
KNMK ; Kill name check variables
"RTN","MCARAM2",70,0)
 K MCNAM,MCFNAM,MCLNAM,MC12NAM,MC12FNAM,MC12LNAM,MCA12 Q
"RTN","MCARAM2",71,0)
 ;
"RTN","MCARAM2",72,0)
ERR ;Error return
"RTN","MCARAM2",73,0)
 Q MCERR
"RTN","MCARAM2",74,0)
DATE(MCDATE) ; Get the two digit century for the date
"RTN","MCARAM2",75,0)
 N MCMTH,A1,A2,A3,SD
"RTN","MCARAM2",76,0)
 S SD=$P(MCDATE,"@",1),A2=0
"RTN","MCARAM2",77,0)
 S A1=$P(SD,"-",2) G:A1'?3A EXIT
"RTN","MCARAM2",78,0)
 S A1=$TR(A1,"abcdefghijklmnopqrstuvwxyz","ABCDEFGHIJKLMNOPQRSTUVWXYZ")
"RTN","MCARAM2",79,0)
 S A2=$S(A1="JAN":1,A1="FEB":2,A1="MAR":3,A1="APR":4,A1="MAY":5,A1="JUN":6,A1="JUL":7,A1="AUG":8,A1="SEP":9,A1="OCT":10,A1="NOV":11,A1="DEC":12,1:0) G:'A2 EXIT
"RTN","MCARAM2",80,0)
EXIT Q $E(MCDATE,1,7)_1700+$S(A2&(A2>$E(DT,4,5)):1700+$E(DT,1)_$E(MCDATE,8,15))
"RTN","MCARAP")
0^7^B22520575
"RTN","MCARAP",1,0)
MCARAP ;WASH ISC/SAE-MEDICINE AUTO INSTRUMENT INTERFACE SUMMARY PRINT ;5/7/96  09:40
"RTN","MCARAP",2,0)
 ;;2.3;Medicine;**16**;09/13/1996
"RTN","MCARAP",3,0)
 ;
"RTN","MCARAP",4,0)
 D NOW^%DTC S Y=% D DD^%DT S MCDAY=$E(Y,1,12),MCTIME=$E(Y,13,18)
"RTN","MCARAP",5,0)
 K GOOD,BAD,J,DIC,ENTRY,DATE1,DATE2,PDATE,IJ,ZIP,REDO,NAME,ALL
"RTN","MCARAP",6,0)
 W @IOF,?17,"MEDICINE AUTO INSTRUMENT SUMMARY OF RECORDS TRANSFER"
"RTN","MCARAP",7,0)
 W !!!!,?5,"S",?10,"SUCCESSFUL RECORD TRANSFERS"
"RTN","MCARAP",8,0)
 W !!,?5,"U",?10,"UNSUCCESSFUL RECORD TRANSFERRAL ATTEMPTS"
"RTN","MCARAP",9,0)
 W !!,?5,"A",?10,"ALL RECORD TRANSFERRAL ATTEMPTS"
"RTN","MCARAP",10,0)
ASK R !!!,"Enter selection(S,U,A), '?' for help, or return to escape: ",RPT:DTIME
"RTN","MCARAP",11,0)
 G EXIT1^MCARAP1:'$T,EXIT1^MCARAP1:RPT="" K GOOD,BAD,ALL
"RTN","MCARAP",12,0)
 I RPT="S" S GOOD=1 K BAD G NAME
"RTN","MCARAP",13,0)
 I RPT="U" S BAD=1 K GOOD G NAME
"RTN","MCARAP",14,0)
 I RPT="A" S ALL=1 K GOOD,BAD G NAME
"RTN","MCARAP",15,0)
 I RPT="?" D QMARK^MCARAP2
"RTN","MCARAP",16,0)
 I RPT="?" D PROMPT G EXIT1^MCARAP1:'$T,EXIT1^MCARAP1:ZIP=U D QMARK2^MCARAP2,PROMPT G EXIT1^MCARAP1:'$T,EXIT1^MCARAP1:ZIP=U,MCARAP
"RTN","MCARAP",17,0)
 I RPT=U!(RPT="") G EXIT1^MCARAP1
"RTN","MCARAP",18,0)
 G MCARAP
"RTN","MCARAP",19,0)
PROMPT R !!,"Press return to continue, or '^' to escape: ",ZIP:DTIME Q
"RTN","MCARAP",20,0)
UPDATE ; Kill all nodes for entries more than 1 month old
"RTN","MCARAP",21,0)
 D NOW^%DTC S X1=%
"RTN","MCARAP",22,0)
 W @IOF,!,?14,"MEDICINE AUTO INSTRUMENT SUMMARY OF RECORDS TRANSFER"
"RTN","MCARAP",23,0)
 W !!!,?14,"Enter the number of days of reports you wish to retain"
"RTN","MCARAP",24,0)
 W !,?14,"(30 day minimum), or return to escape: ",*7 R PERIOD:DTIME G:'$T!(PERIOD=U)!(PERIOD="") EXIT1^MCARAP1 G:PERIOD<30 UPDATE
"RTN","MCARAP",25,0)
 S X2=-PERIOD D C^%DTC S EXDAY=X ; B
"RTN","MCARAP",26,0)
 S PDATE=0 F IJ=1:1 S PDATE=$O(^MCAR(700.5,"C",PDATE)) Q:PDATE=""  Q:PDATE>EXDAY  D STYPE^MCARAP1 I $D(TYPE) K TYPE S ENT="",ENTRY(IJ)=$O(^MCAR(700.5,"C",PDATE,ENT))
"RTN","MCARAP",27,0)
 F IJ=1:1 Q:'$D(ENTRY(IJ))  S DIK="^MCAR(700.5,",DA=ENTRY(IJ) D ^DIK
"RTN","MCARAP",28,0)
 K MCARA,EXDAY,IJ,DIK,ENT,ENTRY,PDATE,PERIOD Q
"RTN","MCARAP",29,0)
NAME R !!,"Enter Patient Name (if single Patient search), or '^' to escape: ",NAME:DTIME
"RTN","MCARAP",30,0)
 I '$T K NAME G EXIT^MCARAP1
"RTN","MCARAP",31,0)
 I NAME=U K NAME G EXIT1^MCARAP1
"RTN","MCARAP",32,0)
 I NAME="?" W !,"Enter name (examples: SM/SMITH/SMITH,BILL/SMITH,BILL M)",!,"...or press return to search all Patients)" G NAME
"RTN","MCARAP",33,0)
 I NAME?1." ".E W !,"Leading spaces not acceptable",*7 G NAME
"RTN","MCARAP",34,0)
 I '$D(NAME)!(NAME="") K NAME G DATE1
"RTN","MCARAP",35,0)
 S:NAME[", " NAME=$P(NAME,",")_","_$P(NAME,", ",2) S:NAME["  " NAME=$P(NAME,"  ")_" "_$P(NAME,"  ",2)
"RTN","MCARAP",36,0)
 S NAMEE=$E(NAME,1,($L(NAME)-1))_$C($A($E(NAME,$L(NAME)))-1)_"ZZZ"
"RTN","MCARAP",37,0)
 K ^TMP($J,"MCARA")
"RTN","MCARAP",38,0)
 F J=1:1 S NAMEE=$O(^MCAR(700.5,"PT",NAMEE)) Q:NAMEE=""  Q:NAME'=$E(NAMEE,1,$L(NAME))  S RN=$O(^(NAMEE,0)),^TMP($J,"MCARA",J)=NAMEE_U_$P(^MCAR(700.5,RN,0),U,3)
"RTN","MCARAP",39,0)
 G:'$D(^TMP($J,"MCARA")) NAME2
"RTN","MCARAP",40,0)
 W ! F J=1:1 Q:'$D(^TMP($J,"MCARA",J))  W !,?5,J,?10,$P(^(J),U),?40,$P(^(J),U,2)
"RTN","MCARAP",41,0)
NAME1 R !!,"Enter Number: ",ZIP:DTIME G EXIT1^MCARAP1:'$T,EXIT1^MCARAP1:ZIP=U
"RTN","MCARAP",42,0)
 I ZIP="" W !!,"No Individual Patient selected",*7 K NAME G NAME
"RTN","MCARAP",43,0)
 I ZIP="?" W !,"Enter Number to select Patient, press return to continue, or enter ^ to exit" G NAME1
"RTN","MCARAP",44,0)
 I '$D(^TMP($J,"MCARA",ZIP)) W !,"No Individual Patient selected",*7 G NAME1
"RTN","MCARAP",45,0)
 S NAME=$P(^TMP($J,"MCARA",ZIP),U)
"RTN","MCARAP",46,0)
 G DATE1
"RTN","MCARAP",47,0)
NAME2 W !,"No Entries found in Summary File",*7 G NAME
"RTN","MCARAP",48,0)
DATE1 ; Enter starting date of range of dates for report
"RTN","MCARAP",49,0)
 W !! K DTOUT S %DT="AEXPT",%DT("A")="Enter Starting Date: ",%DT("B")="TODAY",%DT(0)="-NOW"
"RTN","MCARAP",50,0)
 D ^%DT I X="" K %DT(0) Q
"RTN","MCARAP",51,0)
 G:$D(DTOUT) MCARAP G:X=U EXIT1^MCARAP1
"RTN","MCARAP",52,0)
 I Y=-1 W *7 R !!,"Invalid date, press return to continue, or ^ to exit: ",ZIP:DTIME G EXIT1^MCARAP1:'$T,EXIT1^MCARAP1:ZIP=U W ! G DATE1
"RTN","MCARAP",53,0)
 S DATE1=Y
"RTN","MCARAP",54,0)
DATE2 K DTOUT S %DT="AEXPT",%DT("A")="Enter Ending Date: ",%DT("B")="TODAY",%DT(0)="-NOW"
"RTN","MCARAP",55,0)
 D ^%DT I X="" K %DT(0) Q
"RTN","MCARAP",56,0)
 G:$D(DTOUT) MCARAP G:X=U EXIT1^MCARAP1
"RTN","MCARAP",57,0)
 I Y=-1 W *7 R !!,"Invalid date, press return to continue, or ^ to exit: ",ZIP:DTIME G EXIT1^MCARAP1:'$T,EXIT1^MCARAP1:ZIP=U W ! G DATE2
"RTN","MCARAP",58,0)
 S DATE2=Y I DATE2<DATE1 W *7 R !!,"Starting date must precede or equal ending date",!,"Press return to continue, or ^ to exit: ",ZIP:DTIME G EXIT1^MCARAP1:'$T,EXIT1^MCARAP1:ZIP=U W ! G DATE1
"RTN","MCARAP",59,0)
DEVICE ; Select Device
"RTN","MCARAP",60,0)
 K IO("Q") S %ZIS="Q" D ^%ZIS G EXIT1^MCARAP1:POP
"RTN","MCARAP",61,0)
QUE ; Perform queueing if selected
"RTN","MCARAP",62,0)
 I $D(IO("Q")) S ZTRTN="^MCARAP1",ZTSAVE("DATE*")="",ZTDESC="Medicine Auto Instrument Interface Summary Report" S:$D(GOOD) ZTSAVE("GOOD")="" S:$D(BAD) ZTSAVE("BAD")="" S:$D(NAME) ZTSAVE("NAME")="" S REDO=1
"RTN","MCARAP",63,0)
 I $D(IO("Q")) S:$D(MCARA) ZTSAVE("MCARA")=MCARA S:$D(ALL) ZTSAVE("ALL")="" D ^%ZTLOAD K ZTSK,IO("Q") G EXIT1^MCARAP1
"RTN","MCARAP",64,0)
 U IO
"RTN","MCARAP",65,0)
 G ^MCARAP1
"RTN","MCARGES")
0^4^B25713899
"RTN","MCARGES",1,0)
MCARGES ;WISC/TJK-SCREEN ENTER/EDIT-ENDOSCOPY,HEMATOLOGY,PACEMAKER ;4/7/97  14:14
"RTN","MCARGES",2,0)
 ;;2.3;Medicine;**8,15,16**;09/13/1996
"RTN","MCARGES",3,0)
START ;
"RTN","MCARGES",4,0)
 K EXIT,MCDEMO,MCESFL S MCESFL=1
"RTN","MCARGES",5,0)
 D ENTER I '$D(MCFILE)!('$D(MCARGDA)) D EXIT Q
"RTN","MCARGES",6,0)
 I '$D(^MCAR(MCFILE,MCARGDA,0)),$D(MCBACK) D BACKSS^MCESEDT K MCBACK S EXIT=1
"RTN","MCARGES",7,0)
 K:'$D(^MCAR(MCFILE,MCARGDA,0)) MCESFL D EXIT
"RTN","MCARGES",8,0)
 Q
"RTN","MCARGES",9,0)
ENTER ; edit a GI procedure record and display/edit history if selected
"RTN","MCARGES",10,0)
 D DPT^MCARGE I $D(EXIT) Q
"RTN","MCARGES",11,0)
 I MCARCODE="G"!(MCARCODE="P") S MCDEMO=1 D DEMO^MCARGE
"RTN","MCARGES",12,0)
 ;if user wants to edit patient history in patient file
"RTN","MCARGES",13,0)
 I $D(MCDEMO) D
"RTN","MCARGES",14,0)
 .S DJSC="MCGDEM",DIC="MCAR(690,",DJDN=DFN,DIC(0)="EQ" D EN^MCARD
"RTN","MCARGES",15,0)
 .S:$D(DUOUT) EXIT=1
"RTN","MCARGES",16,0)
 .I '$D(EXIT),$D(^DIC(120.8)) N VADM D EN2^GMRAPEM0
"RTN","MCARGES",17,0)
 .K MCDEMO
"RTN","MCARGES",18,0)
 .;restore the procedure record number after patient lookup in 690
"RTN","MCARGES",19,0)
 .S MCARGDA=+$G(MCARDA)
"RTN","MCARGES",20,0)
 Q:$D(EXIT)  D EDIT Q
"RTN","MCARGES",21,0)
EDIT D:MCARCODE="G" SETVAR^MCARGE K DIC
"RTN","MCARGES",22,0)
 S DJSC=MCEPROC
"RTN","MCARGES",23,0)
 S DJDN=MCARGDA,DIC="^MCAR("_MCFILE_","
"RTN","MCARGES",24,0)
 S DIC(0)="EQ"
"RTN","MCARGES",25,0)
 D IN^MCEO
"RTN","MCARGES",26,0)
 I $D(DTOUT)!$D(DUOUT) S EXIT=1 Q
"RTN","MCARGES",27,0)
 D EN^MCARD
"RTN","MCARGES",28,0)
 I $D(DUOUT) S EXIT=1 Q
"RTN","MCARGES",29,0)
 I '$D(^MCAR(MCFILE,MCARGDA,0)) S EXIT=1 Q
"RTN","MCARGES",30,0)
 S MCDFLAG="" I MCARGNAM'="NON-ENDO" D ^MCARGD
"RTN","MCARGES",31,0)
 D OUT^MCEO
"RTN","MCARGES",32,0)
 Q
"RTN","MCARGES",33,0)
CONSULT ;
"RTN","MCARGES",34,0)
 K DIC S MCDFLAG="" D CONSULT^MCARGE
"RTN","MCARGES",35,0)
 G EXIT:$D(DTOUT),EXIT:$D(DUOUT) I $D(Y),Y<0 G EXIT
"RTN","MCARGES",36,0)
 S DJSC=$S($G(MCBS)=1:"MCCONSULTBR",1:"MCCONSULT")
"RTN","MCARGES",37,0)
 S DIC="^MCAR(699.5,",DJDN=MCARGDA,DIC(0)="EQ",MCFILE=699.5 D IN^MCEO G EXIT:$D(DTOUT)!$D(DUOUT) D EN^MCARD,OUT^MCEO
"RTN","MCARGES",38,0)
EXIT ;
"RTN","MCARGES",39,0)
 I '$D(DTOUT),'$D(DUOUT),$D(MCESFL),$D(MCFILE),$D(MCARGDA),MCESON D:MCESFL=0 ESRC^MCESSCR(MCFILE,MCARGDA)
"RTN","MCARGES",40,0)
 K AV,MULTI,EXIT,X,MCPRO,MCEPROC,MCPATNM D EXIT^MCARGE
"RTN","MCARGES",41,0)
 Q
"RTN","MCARGES",42,0)
GENEX(MCARGDA,GENEX) ;Check and resolve non-associated procedures
"RTN","MCARGES",43,0)
 I ('$P(^MCAR(699.5,MCARGDA,0),U,2)!'$P(^(0),U,6)) S DIK="^MCAR(699.5,",DA=MCARGDA,GENEX=1 D ^DIK Q
"RTN","MCARGES",44,0)
 Q
"RTN","MCARGES",45,0)
GENERIC ;Generic Medicine Enter/Edit
"RTN","MCARGES",46,0)
 W !,"GENERIC EDIT"
"RTN","MCARGES",47,0)
 N GENEX S GENEX=0
"RTN","MCARGES",48,0)
 D MCEPROC^MCARE,^MCAREH
"RTN","MCARGES",49,0)
 S DIC="^MCAR(699.5,",DIC(0)="AEQLM",(DLAYGO,DIDEL,MCFILE)=699.5,DIC("S")="I '$P(^MCAR(699.5,+Y,0),U,3)"
"RTN","MCARGES",50,0)
 S DR=".01;.02;.05" D ^DIC G EXIT:Y<0  S MCARGDA=+Y,MCESFL=0
"RTN","MCARGES",51,0)
 D GENEX(MCARGDA,.GENEX) G:GENEX EXIT
"RTN","MCARGES",52,0)
 ;    allow user to edit .01 field
"RTN","MCARGES",53,0)
 I MCESON,("125"'[$$ESTONUM^MCESSCR(MCFILE,MCARGDA)) D ESRC^MCESSCR(MCFILE,.MCARGDA) G:$D(MCBACK) SETUP K DIC Q
"RTN","MCARGES",54,0)
SUPS S DIE="^MCAR(699.5,",DA=MCARGDA,DR=".01;.02;.05" D ^DIE
"RTN","MCARGES",55,0)
 I $D(DA) D GENEX(MCARGDA,.GENEX) G:GENEX EXIT
"RTN","MCARGES",56,0)
 I $D(DTOUT)!$D(DUOUT)!'$D(DA) G EXIT
"RTN","MCARGES",57,0)
 S MCARGNUM=$P(^MCAR(699.5,MCARGDA,0),U,6),DFN=$P(^(0),U,2)
"RTN","MCARGES",58,0)
 S DJSC=MCEPROC
"RTN","MCARGES",59,0)
 S MCARGNAM=$P(^MCAR(699.5,MCARGDA,0),U),DJDN=MCARGDA,DIC="^MCAR(699.5,",DIC(0)="EQ"
"RTN","MCARGES",60,0)
 S MCHOLD=MCARGDA
"RTN","MCARGES",61,0)
 ;D IN^MCEO G EXIT:$D(DTOUT)!$D(DUOUT) D EN^MCARD S MCARGDA=MCHOLD D GENEX(MCARGDA,.GENEX) K MCHOLD G:GENEX EXIT
"RTN","MCARGES",62,0)
 D IN^MCEO G EXIT:$D(DUOUT) D EN^MCARD S MCARGDA=MCHOLD D GENEX(MCARGDA,.GENEX) K MCHOLD  ;MC*2.3*8
"RTN","MCARGES",63,0)
 D OUT^MCEO,QTASK^MCPARAM G EXIT
"RTN","MCARGES",64,0)
 ;
"RTN","MCARGES",65,0)
HEM S DIC="^MCAR(694,",DIC(0)="AEQLM",(DLAYGO,DIDEL,MCFILE)=694 D ^DIC G EXIT:Y<0
"RTN","MCARGES",66,0)
 S MCARGDA=+Y I $D(DTOUT),('$P(^MCAR(694,+Y,0),U,2))!('$P(^(0),U,3)) S DIK="^MCAR(694,",DA=MCARGDA D ^DIK W "??" G EXIT
"RTN","MCARGES",67,0)
 S MCARGNUM=$P(^MCAR(694,MCARGDA,0),U,3),DFN=$P(^(0),U,2),DJSC=MCEPROC
"RTN","MCARGES",68,0)
 S MCARGNAM=$P(^MCAR(697.2,MCARGNUM,0),U),DJDN=MCARGDA,DIC="^MCAR(694,",DIC(0)="EQ"
"RTN","MCARGES",69,0)
 G EXIT:$D(DTOUT)!$D(DUOUT) D EN^MCARD,QTASK^MCPARAM G EXIT
"RTN","MCARGES",70,0)
MULTI K MULTI S MULTI="",MCARGDA=-1 D GEN G EXIT:$D(DTOUT),EXIT:$D(DUOUT),EXIT:'$G(MCARGDA)
"RTN","MCARGES",71,0)
 S AV=$G(^MCAR(698,MCARGDA,0)),DFN=$P(AV,U,2),AV=$P(AV,U,7) G EXIT:AV=""!("AV"'[AV)
"RTN","MCARGES",72,0)
 K DIC S DIC("S")="I $P(^(0),U,2)=DFN" D ALEAD:AV["A" G EXIT:$D(DUOUT)!($D(DTOUT))
"RTN","MCARGES",73,0)
 K DIC S DIC("S")="I $P(^(0),U,2)=DFN" D VLEAD:AV["V" G EXIT
"RTN","MCARGES",74,0)
GEN S MCFILE=698
"RTN","MCARGES",75,0)
 S MCPRO="GEN.IMPL." D MCEPROC^MCARE S MCARGNUM=MCARGNAM,MCARGNAM="GENERATOR IMPLANT" G LOOK
"RTN","MCARGES",76,0)
VLEAD S MCFILE=698.1
"RTN","MCARGES",77,0)
 D:$D(MULTI) LAST^MCARPACE
"RTN","MCARGES",78,0)
 S MCPRO="V-LEAD IMP" D MCEPROC^MCARE S MCARGNUM=MCARGNAM,MCARGNAM="VENTRICAL LEAD IMPLANT" G LOOK
"RTN","MCARGES",79,0)
ALEAD S MCFILE=698.2
"RTN","MCARGES",80,0)
 D:$D(MULTI) LAST^MCARPACE
"RTN","MCARGES",81,0)
 S MCPRO="A-LEAD IMP" D MCEPROC^MCARE S MCARGNUM=MCARGNAM,MCARGNAM="ATRIAL LEAD IMPLANT" G LOOK
"RTN","MCARGES",82,0)
DEMO ;
"RTN","MCARGES",83,0)
 W @IOF,!!!,"DEMOGRAPHIC INFORMATION      *** SCREEN EDIT ***",!!!
"RTN","MCARGES",84,0)
 D
"RTN","MCARGES",85,0)
 .N DLAYGO
"RTN","MCARGES",86,0)
 .S DLAYGO=690,DIC="^MCAR(690,",DIC(0)="AEQLM",DIC("B")=$G(MCPATNM)
"RTN","MCARGES",87,0)
 .D ^DIC
"RTN","MCARGES",88,0)
 .Q
"RTN","MCARGES",89,0)
 G EXIT:Y<0
"RTN","MCARGES",90,0)
 S (DJDN,MCARGDA)=+Y,DJSC="MCPACEDEMO",DIC(0)="EQ" D EN^MCARD
"RTN","MCARGES",91,0)
 ;get new default patient name
"RTN","MCARGES",92,0)
 S MCX=$$VALUE^MCENDIQ1(690,MCARGDA,.01)
"RTN","MCARGES",93,0)
 I MCX'="" S MCPATNM=MCX
"RTN","MCARGES",94,0)
 G EXIT
"RTN","MCARGES",95,0)
LOOK ;
"RTN","MCARGES",96,0)
 W @IOF,!!!,MCARGNAM," PROCEDURES      *** SCREEN EDIT ***",!!!
"RTN","MCARGES",97,0)
 S DIC="^MCAR("_MCFILE_",",DIC(0)="AEQLM"
"RTN","MCARGES",98,0)
 S DIC("A")="Enter patient name, or date and time: "
"RTN","MCARGES",99,0)
 ;S DIC("B")=$G(MCPATNM)
"RTN","MCARGES",100,0)
 S (DLAYGO,DIDEL)=MCFILE D ^DIC G EX:Y<0
"RTN","MCARGES",101,0)
 ;
"RTN","MCARGES",102,0)
 ;    NOTE:  next line must define DFN for Order Entry to work
"RTN","MCARGES",103,0)
 S MCARGDA=+Y,DFN=$P($G(^MCAR(MCFILE,MCARGDA,0)),U,2) I $D(DTOUT),'DFN S DIK=DIC,DA=MCARGDA D ^DIK G EX
"RTN","MCARGES",104,0)
 S MCARGNUM=$O(^MCAR(697.2,"BA",MCARGNAM,0))
"RTN","MCARGES",105,0)
 S DJSC=MCEPROC
"RTN","MCARGES",106,0)
 S MCARGNAM=$P(^MCAR(697.2,MCARGNUM,0),U),DJDN=MCARGDA,DIC(0)="EQ" D IN^MCEO G EXIT:$D(DTOUT)!$D(DUOUT) D EN^MCARD,OUT^MCEO
"RTN","MCARGES",107,0)
 ;get new default patient name
"RTN","MCARGES",108,0)
 S MCX=$$VALUE^MCENDIQ1(MCFILE,MCARGDA,1)
"RTN","MCARGES",109,0)
 I MCX'="" S MCPATNM=MCX
"RTN","MCARGES",110,0)
EX Q:$D(MULTI)  G EXIT
"RTN","MCARGES",111,0)
SETUP ; If the record is superseded, the user will be allow to edit the superseded record.
"RTN","MCARGES",112,0)
 S Y=MCY,DA=Y,Y(0)=MCY(0),Y(0,0)=MCY(0,0),MCARGDA=+MCY K MCY,DTOUT,DIROUT,DUOUT,DIC
"RTN","MCARGES",113,0)
 G SUPS
"RTN","MCARHP")
0^6^B17968839
"RTN","MCARHP",1,0)
MCARHP ;WISC/SAE,TJK-PRINT HEMATOLOGY REPORTS ;12/15/97  14:49
"RTN","MCARHP",2,0)
 ;;2.3;Medicine;**15,16**;09/13/1996
"RTN","MCARHP",3,0)
LOOK ;
"RTN","MCARHP",4,0)
 D MCPPROC^MCARP
"RTN","MCARHP",5,0)
 S DIC="^MCAR(694,",(MCFILE,MCFILE1)=+$P(DIC,"(",2),DIC(0)="AEZMQ"
"RTN","MCARHP",6,0)
 S:MCESON DIC("S")=$$PREVIEW^MCESSCR(MCFILE)
"RTN","MCARHP",7,0)
 D ^DIC G EXIT:Y<0 S (MCARGDA,D0)=+Y
"RTN","MCARHP",8,0)
 W !!
"RTN","MCARHP",9,0)
EN1 ;ENTRY POINT FROM SUMMARY OF PATIENT PROCEDURES ROUTINE
"RTN","MCARHP",10,0)
 I $D(ORHFS) U IO G HEM ;dcm/slc added for CPRS
"RTN","MCARHP",11,0)
DEVQUE ; Device control and queuing control
"RTN","MCARHP",12,0)
 S MCARZ="HEMATOLOGY REPORT"
"RTN","MCARHP",13,0)
 D:$G(MCESON) STATUS^MCESPRT(MCFILE,MCARGDA)
"RTN","MCARHP",14,0)
 K IO("Q") S %ZIS="MQ" D ^%ZIS G EXIT:POP
"RTN","MCARHP",15,0)
 I $D(IO("Q")) S ZTRTN="HEM^MCARHP",(ZTSAVE("MC*"),ZTSAVE("DIC"))="",ZTDESC="Hematology Report" D ^%ZTLOAD K ZTSK G EXIT
"RTN","MCARHP",16,0)
 U IO
"RTN","MCARHP",17,0)
HEM ; Print Report and entry point for queued report
"RTN","MCARHP",18,0)
INIT ; Initialize variables
"RTN","MCARHP",19,0)
 K DXS,DIOT(2),^UTILITY($J),MCOUT
"RTN","MCARHP",20,0)
 S PG=0,D0=MCARGDA,DFN=$P(^MCAR(694,D0,0),U,2),MCARGDT=$P(^(0),U),MCARZ="HEMATOLOGY REPORT" S:MCESON MCARZ=MCARZ_" - "_MCSTAT
"RTN","MCARHP",21,0)
 S X=MCARGDT D DTIME^MCARP S MCARGDT2=X D NOW^%DTC S X=% D DTIME^MCARP S MCARDTM=X
"RTN","MCARHP",22,0)
 ; ------------------------
"RTN","MCARHP",23,0)
 ; SSN = Enternal Format of the patients SSN with the first letter
"RTN","MCARHP",24,0)
 ; of the last name tacked on the end
"RTN","MCARHP",25,0)
 ; ------------------------
"RTN","MCARHP",26,0)
 D DEM^VADPT S MCARGNM=VADM(1),SSN=VA("PID"),X=$P(VADM(3),"^",2),MCARDOB=$S(X'="":X,1:"") D KVAR^VADPT
"RTN","MCARHP",27,0)
 D INP^VADPT S MCARWARD=$S(VAIN(4)'="":$P(VAIN(4),U,2),1:"NOT INPATIENT"),MCARRB=VAIN(5) D KVAR^VADPT
"RTN","MCARHP",28,0)
 S ^UTILITY($J,1)="S MCY="""" I $Y>(IOSL-3) R:$E(IOST,1,2)=""C-"" !!,""Press return to continue, '^' to escape: "",MCY:DTIME S:'$T MCY=U S:MCY=U DN=0,MCOUT=1 D:DN HEAD^MCARP K MCY"
"RTN","MCARHP",29,0)
HEMP ; Bone Marrow basic print (MCAROHB), and Differential (MCAROHD)
"RTN","MCARHP",30,0)
 S MCFILET=MCFILE
"RTN","MCARHP",31,0)
 D HEAD^MCARP,^MCAROHB K DXS G EXIT:$D(MCOUT)
"RTN","MCARHP",32,0)
 I $D(^MCAR(694,D0,4)) D ^MCAROHD K DXS G EXIT:$D(MCOUT)
"RTN","MCARHP",33,0)
 D ^MCAROHF G EXIT:$D(MCOUT)
"RTN","MCARHP",34,0)
 S MCFILE=MCFILET
"RTN","MCARHP",35,0)
 D FOOTER^MCESPRT(MCFILE,MCARGDA)
"RTN","MCARHP",36,0)
 R:$E(IOST,1,2)="C-" !!,"Press return to continue ",X:DTIME
"RTN","MCARHP",37,0)
 G EXIT
"RTN","MCARHP",38,0)
BMB ; Print fields specific to BMB
"RTN","MCARHP",39,0)
 G BMB2:'$D(^MCAR(694,D0,6)),BMB2:$P(^MCAR(694,D0,6),U,3)=""
"RTN","MCARHP",40,0)
 S NP=$P(^MCAR(694,D0,6),U,3),FX=$P(^(6),U,2)
"RTN","MCARHP",41,0)
 S FX=$S(FX="M":"Methanol",FX="E":"Ethanol",1:"Formalin")
"RTN","MCARHP",42,0)
 I $Y>(IOSL-3),$E(IOST,1,2)="C-" R !!,"Press return to continue, '^' to escape: ",X:DTIME S:'$T X=U G:X=U BMBQ D HEAD^MCARP
"RTN","MCARHP",43,0)
 W ?4,"GROSS DESCRIPTION:  The specimen consisted of "_NP_" piece(s), measuring",!,?23
"RTN","MCARHP",44,0)
 F AZ=1:1:NP S LP=$P(^MCAR(694,D0,6),U,AZ+3) W:LP'="" $S(AZ'=1:" mm, ",1:" "),LP
"RTN","MCARHP",45,0)
 W " mm, submitted in "_FX_"."
"RTN","MCARHP",46,0)
 W !!
"RTN","MCARHP",47,0)
 I $Y>(IOSL-3),($E(IOST,1,2)="C-") R !!,"Press return to continue, '^' to escape: ",X:DTIME S:'$T X=U G:X=U BMBQ D HEAD^MCARP
"RTN","MCARHP",48,0)
BMB2 G BMB21:'$D(^MCAR(694,D0,9)) S X=^(9)
"RTN","MCARHP",49,0)
 I $P(X,U,1)="Y" W ?6,"This specimen is submitted for decalcification in EDTA."
"RTN","MCARHP",50,0)
 I $P(X,U,2)="Y" W !,?6,"Part of the specimen is fixed and submitted for processing in plastic."
"RTN","MCARHP",51,0)
BMB21 K X G BMBQ:$P(^MCAR(694,D0,0),U,6)="" W !!,?4,"BIOPSY COMMENTS:" K ^UTILITY($J,"W")
"RTN","MCARHP",52,0)
 S DIWL=23,DIWR=IOM,DIWF="WC56",X=$P(^MCAR(694,D0,0),U,6) Q:$P(^(0),U,6)=""
"RTN","MCARHP",53,0)
 D ^DIWP,^DIWW W !
"RTN","MCARHP",54,0)
 K X I $Y>(IOSL-3),($E(IOST,1,2)="C-") R !!,"Press return to continue, '^' to escape: ",X:DTIME S:'$T X=U G:X=U BMBQ D HEAD^MCARP
"RTN","MCARHP",55,0)
BMBQ I $D(X),X=U S MCOUT=1
"RTN","MCARHP",56,0)
 Q
"RTN","MCARHP",57,0)
UNRELP ;ENTRY POINT FOR SUPERVISOR TO PRINT UNRELEASED REPORT
"RTN","MCARHP",58,0)
 S MCAREL="" G LOOK
"RTN","MCARHP",59,0)
REL S DIC="^MCAR(694,",DIC(0)="AEMZQ" D ^DIC G EXIT:Y<0
"RTN","MCARHP",60,0)
 S $P(^MCAR(694,+Y,0),U,9)="Y"
"RTN","MCARHP",61,0)
 W !,*7,"Report Released for Printing." R !,"* END * Press return to continue: ",X:DTIME
"RTN","MCARHP",62,0)
EXIT W @IOF S:$D(ZTQUEUED) ZTREQ="@" K ZTSK
"RTN","MCARHP",63,0)
 K %Y,LPDT,X,Y,DIC,IOP,MCARPPS,IJ,PT,D1,NE,NP,FX,AZ,PG,Z,L,FLDS,MCAREL,MCOUT,VA
"RTN","MCARHP",64,0)
 K ^UTILITY($J),IO("Q"),MCARGDA,MCARGDT,SSN K MCARGNM,MCARGRTN,X,DFN,SSN
"RTN","MCARHP",65,0)
 K MCARGNUM,MCARGNAM,MCARZ,DN,D0,MCARCODE,DIOEND,DIOBEG,DI,DICS,DICSS,MCARWARD,MCARDTM,MCARDOB,MCARRB,MCARGDT,MCOUNT,MCFOOTER
"RTN","MCARHP",66,0)
 K DJ,BY,A,DIEDT,DIQ,DIPZ,DIL,DXS,DALL,DSC,DCL,DPP,DPQ,DQI,DU,DY
"RTN","MCARHP",67,0)
 K S,LP,DC,DL,DV,DE,DA,DK,Y,R,C,D,I,J,Q,M,P,N,D1,DIW,DIWL,DIWR,DIWF,DIWT
"RTN","MCARHP",68,0)
 W:IOST?1"P-".E @IOF D ^%ZISC Q
"RTN","MCARP1")
0^8^B10963685
"RTN","MCARP1",1,0)
MCARP1 ;WISC/TJK-PRINT ROUTINES TWO ;5/3/96  08:18
"RTN","MCARP1",2,0)
 ;;2.3;Medicine;**14,15,16**;09/13/1996
"RTN","MCARP1",3,0)
EXIT ;
"RTN","MCARP1",4,0)
 I IOST'?1"P-".E,'$D(MCOUT),$G(Y)'<0 R !!,"* END * Press return to continue: ",X:DTIME
"RTN","MCARP1",5,0)
 K ^UTILITY($J),IO("Q"),MCARGDA,MCARGDT,SSN,MCOUT,VA,DICMX,V
"RTN","MCARP1",6,0)
 K MCARGNM,MCARGRTN,X,DFN,SSN,MCARGNUM,MCARGNAM,MCARZ,DN,D0,FLDS,MCARCODE
"RTN","MCARP1",7,0)
 K DIOEND,DIOBEG,DI,DIC,DJ,BY,A,DICSS,MCARGDT2,MCARPPS
"RTN","MCARP1",8,0)
 K DIEDT,DIQ,DIWF,DIPZ,DIL,DXS,DALL,DSC,DCL,DPP,DPQ,DIC,DU,DQI,DY,S,DC
"RTN","MCARP1",9,0)
 K DL,DV,DE,DA,DK,Y,R,RH,C,D,I,J,Q,M,P,N,D1,DIW,DIWL,DIWR,DIWT,PG,Z,L,%T,D2
"RTN","MCARP1",10,0)
 K MCAR,MCARDOB,MCARDTM,MCARHDR,MCARRB,MCARWARD,MCRHR,VADM,VAIN
"RTN","MCARP1",11,0)
 K MCARP,MCFILE,MCESON,MCESKEY,MCROUT,MCTYPE,MCARPS,MCSUP
"RTN","MCARP1",12,0)
 K MCEBRIEF,MCEFULL,MCPBRIEF,MCPFULL,MCPRTRTN,MCBS,MCSTAT
"RTN","MCARP1",13,0)
 K MCARCODE,MCARDE,MCARGNAM,MCARGNUM,MCARGRTN,MCARP,MCARZ,MCBS
"RTN","MCARP1",14,0)
 K MCESS,MCESSEC,MCOUNT,MCPATFLD,MCPRO,MCSUP
"RTN","MCARP1",15,0)
 K ZTQUEUED,ZTREQ,FULL,MCPROP
"RTN","MCARP1",16,0)
 D ^%ZISC
"RTN","MCARP1",17,0)
 Q
"RTN","MCARP1",18,0)
INIT(MCARZ,MCARGDT,MCFILE) ;
"RTN","MCARP1",19,0)
 S PG=0
"RTN","MCARP1",20,0)
 I '$D(MCARGDT2) S X=MCARGDT D DTIME^MCARP S MCARGDT2=X
"RTN","MCARP1",21,0)
 D NOW^%DTC S X=% D DTIME^MCARP S MCARDTM=X
"RTN","MCARP1",22,0)
 ; ------------------------
"RTN","MCARP1",23,0)
 ; SSN = Enternal Format of the patients SSN with the first letter
"RTN","MCARP1",24,0)
 ; of the last name tacked on the end
"RTN","MCARP1",25,0)
 ; ------------------------
"RTN","MCARP1",26,0)
 D DEM^VADPT S MCARGNM=VADM(1),SSN=VA("PID"),X=$P(VADM(3),"^",2),MCARDOB=$S(X'="":X,1:"")
"RTN","MCARP1",27,0)
 I MCFILE=699,($G(MCARGNUM)'="") S MCARGNAM=$P(^MCAR(697.2,MCARGNUM,0),U)
"RTN","MCARP1",28,0)
 D KVAR^VADPT
"RTN","MCARP1",29,0)
 D INP^VADPT S MCARWARD=$S(VAIN(4)'="":$P(VAIN(4),U,2),1:"NOT INPATIENT"),MCARRB=VAIN(5) D KVAR^VADPT
"RTN","MCARP1",30,0)
 S MCARHDR=" CONFIDENTIAL "_MCARZ,MCAR="",$P(MCAR,"*",(77-$L(MCARHDR))\2)="*",MCARHDR=MCAR_" "_MCARHDR_" "_MCAR
"RTN","MCARP1",31,0)
 Q
"RTN","MCARP1",32,0)
MCPPROC ; Get require variables
"RTN","MCARP1",33,0)
 N OTEMP,TEMP,OPTION
"RTN","MCARP1",34,0)
 ;MCabPROC  <=== name of an option, screen or line edit.
"RTN","MCARP1",35,0)
 ; a = (B =>  Brief),  (F => Full)
"RTN","MCARP1",36,0)
 ; b = (S =>  Screen Edit), (L =>  Line Edit), (P =>  Printing)
"RTN","MCARP1",37,0)
 ; PROC = the name of the procedure
"RTN","MCARP1",38,0)
 S OTEMP=$S(XQY0["SUMMARY":"FP"_$G(MCPRO),1:$P(XQY0,U))
"RTN","MCARP1",39,0)
 S:$L($G(MCPRO))<2 MCPRO=$$MCPROP^MCARP(OTEMP)
"RTN","MCARP1",40,0)
 S MCARP="",(MCARP,MCARGNUM,MCARGNAM)=+$O(^MCAR(697.2,"B",MCPRO,MCARP)),OPTION=$E(OTEMP,3,4)
"RTN","MCARP1",41,0)
 S TEMP=$G(^MCAR(697.2,MCARP,0)),MCESS=0,MCSUP=+$P(TEMP,U,16)
"RTN","MCARP1",42,0)
 S (MCROUT,MCARDE)=$P(TEMP,U,8),MCFILE=+$P($P(TEMP,U,2),"MCAR(",2),MCESON=+$P(TEMP,U,14),MCESSEC=0,MCESKEY=$P(TEMP,U,15)
"RTN","MCARP1",43,0)
 S MCARGNAM=$P(TEMP,U),MCPATFLD=$P(TEMP,U,12),MCOUNT=0
"RTN","MCARP1",44,0)
 I MCESON,MCESKEY'="" S:$D(^XUSEC(MCESKEY,DUZ)) MCESSEC=1
"RTN","MCARP1",45,0)
 I MCFILE=699 S MCARCODE=$S($P(XQY0,U)["GI":"G",$P(XQY0,U)["NONENDO":"Z",1:"P"),DIC("S")="I $D(^MCAR(697.2,""D"",MCARCODE,+$P(^MCAR(699,+Y,0),U,12)))"
"RTN","MCARP1",46,0)
 S MCPRTRTN=$P(TEMP,U,5)_"^"_$P(TEMP,U,6)
"RTN","MCARP1",47,0)
 S MCBS=$S(OPTION["B":1,1:0) Q
"RTN","MCARP1",48,0)
 Q
"RTN","MCARP1",49,0)
DELETE ;DELETES GI PROCEDURES Taken from MCARGE routine for size
"RTN","MCARP1",50,0)
 S DIC="^MCAR(699,",DIC(0)="AEQM",DIC("A")="Select Patient Name or Date of Procedure to Delete:  ",DIC("S")="I $D(^MCAR(697.2,""D"",MCARCODE,$P(^MCAR(699,+Y,0),U,12)))"
"RTN","MCARP1",51,0)
 I MCESON S DIC("S")=DIC("S")_",$$SCRDEL^MCESSCR(699)"
"RTN","MCARP1",52,0)
 D ^DIC G EXIT:Y<0 S MCARGDA=+Y
"RTN","MCARP1",53,0)
 S DIR("A")="ARE YOU SURE YOU WANT TO DELETE",DIR("B")="N",DIR(0)="Y"
"RTN","MCARP1",54,0)
 D ^DIR
"RTN","MCARP1",55,0)
 I Y S DA=MCARGDA,DIK="^MCAR(699," D ^DIK W !!,"Procedure Deleted ",MCARGDA=0
"RTN","MCARP1",56,0)
 Q
"RTN","MCARPACE")
0^5^B11457429
"RTN","MCARPACE",1,0)
MCARPACE ;WISC/RMP,TJK-COMBINED GENERATOR,LEAD ENTER/EDIT ;5/2/96  13:02
"RTN","MCARPACE",2,0)
 ;;2.3;Medicine;**16**;09/13/1996
"RTN","MCARPACE",3,0)
 W @IOF,!!!,"COMBINED IMPLANT/LEADS PROCEDURES",!!!
"RTN","MCARPACE",4,0)
 S DIC="^MCAR(698,",DIC(0)="AELQM",(DLAYGO,DIDEL)=698
"RTN","MCARPACE",5,0)
 S DIC("A")="Enter Patient name or Date of Generator Implant: "
"RTN","MCARPACE",6,0)
 S DIC("DR")=".01;1//"_$G(MCPATNM)
"RTN","MCARPACE",7,0)
 D ^DIC G:Y<1 EXIT
"RTN","MCARPACE",8,0)
 S DFN=$P(^MCAR(698,+Y,0),U,2),DFNUM=$P(^MCAR(690,DFN,0),U,1),MCPATNM=$P(^DPT(DFNUM,0),"^",1)
"RTN","MCARPACE",9,0)
 W !,"Generator Information...."
"RTN","MCARPACE",10,0)
 S DIE=DIC,(DA,MCARGDA,MCARGDA1)=+Y,DR="2;4;6;S:$P(^(0),U,6)'=12 Y=7;6.1;7;12;14;19:601",MCFILE=698 S MCARGNUM=$$NUM(MCFILE) D IN^MCEO
"RTN","MCARPACE",11,0)
 G EXIT:$D(DTOUT)!$D(DUOUT) D ^DIE,OUT^MCEO,QTASK^MCPARAM G EXIT:$D(DUOUT),EXIT:$D(DTOUT) K DIC,DIE,DR,DA S MCSEL=$P(^MCAR(698,MCARGDA,0),U,7)
"RTN","MCARPACE",12,0)
 G @($S(MCSEL["A":"ALEAD",MCSEL["V":"VLEAD",1:"EXIT"))
"RTN","MCARPACE",13,0)
ALEAD W !,"Atrial Lead Data...." S (DLAYGO,MCFILE,DIDEL)=698.2 D LAST
"RTN","MCARPACE",14,0)
 S DIC="^MCAR(698.2,",DIC(0)="AELQM",DIC("DR")="1////^S X=DFN",DIC("S")="I $P(^(0),U,2)=DFN",DIC("B")=$P(^MCAR(698,MCARGDA,0),U)
"RTN","MCARPACE",15,0)
 D ^DIC K DIC("B"),DIC("S") G EXIT:$D(DUOUT)!($D(DTOUT)) G:Y<0 @$S(MCSEL["V":"VLEAD",1:"EXIT")
"RTN","MCARPACE",16,0)
 S DIE=DIC,(MCARGDA,DA)=+Y,DR="2;4:601",MCFILE=698.2 K ORIFN,GMRCO S MCARGNUM=$$NUM(MCFILE) D IN^MCEO G EXIT:$D(DTOUT)!$D(DUOUT) D ^DIE,OUT^MCEO,QTASK^MCPARAM K DIC,DIE,DR,DA
"RTN","MCARPACE",17,0)
 G @($S(MCSEL["V":"VLEAD",1:"EXIT"))
"RTN","MCARPACE",18,0)
VLEAD W !,"Ventricular Lead Data..." S (DLAYGO,MCFILE,DIDEL)=698.1 D LAST
"RTN","MCARPACE",19,0)
 S DIC="^MCAR(698.1,",DIC(0)="AEQLM",DIC("DR")="1////^S X=DFN",DIC("S")="I $P(^(0),U,2)=DFN",DIC("B")=$P(^MCAR(698,MCARGDA,0),U)
"RTN","MCARPACE",20,0)
 D ^DIC K DIC("B"),DIC("S") G EXIT:$D(DUOUT)!($D(DTOUT)),EXIT:Y<0
"RTN","MCARPACE",21,0)
 S DIE=DIC,(MCARGDA,DA)=+Y,DR="2;4:601",MCFILE=698.1 K ORIFN,GMRCO S MCARGNUM=$$NUM(MCFILE) D IN^MCEO G EXIT:$D(DTOUT)!$D(DUOUT) D ^DIE,OUT^MCEO,QTASK^MCPARAM K DIC,DIE,DR,DA
"RTN","MCARPACE",22,0)
 G EXIT
"RTN","MCARPACE",23,0)
GEN2 W !,"GENERATOR DATA..."
"RTN","MCARPACE",24,0)
 I $D(MCOEON) S ORIFN=MCORSV(1),GMRCO=MCORSV(2) K MCORSV
"RTN","MCARPACE",25,0)
 S MCFILE=698,DIE="^MCAR(698,",(DA,MCARGDA)=MCARGDA1,DR="19:601" D ^DIE K DIC,DIE,DR,DA,MCARGDA1 D ORDER1,QTASK^MCPARAM
"RTN","MCARPACE",26,0)
EXIT K MCSEL,DFN,MCARGDA,DLAYGO,DIDEL,DFNUM Q
"RTN","MCARPACE",27,0)
NUM(MCFILE) ;
"RTN","MCARPACE",28,0)
 Q $O(^MCAR(697.2,"C","MCAR("_MCFILE,0))
"RTN","MCARPACE",29,0)
LAST S (Y,I)=0 F  S I=$O(^MCAR(MCFILE,"C",DFN,I)) Q:I=""  S X=+$G(^MCAR(MCFILE,I,0)) I X,X>Y S Y=X
"RTN","MCARPACE",30,0)
 I 'Y W !!,"No ",$S(MCFILE=698.1:"Ventricular",1:"Atrial")," Lead data entered for this patient",!! K I,Y,X Q
"RTN","MCARPACE",31,0)
 X ^DD("DD") W !!,"Last ",$S(MCFILE=698.1:"Ventricular",1:"Atrial")," Lead implanted on ",Y,!! K X,Y,I Q
"RTN","MCARPACE",32,0)
 ;
"RTN","MCARPACE",33,0)
DEM ;    EDIT DEMOGRAPHIC INFORMATION ONLY
"RTN","MCARPACE",34,0)
 W @IOF,!!!,"DEMOGRAPHIC INFORMATION",!!!
"RTN","MCARPACE",35,0)
 ;S (DIC,DIE)="^MCAR(690,",DIC(0)="AEMQZ",DIC("B")=$G(MCPATNM)
"RTN","MCARPACE",36,0)
 S (DIC,DIE)="^MCAR(690,",DIC(0)="AELMQZ",DIC("B")=$G(MCPATNM),DLAYGO=690
"RTN","MCARPACE",37,0)
 D ^DIC
"RTN","MCARPACE",38,0)
 K DIC
"RTN","MCARPACE",39,0)
 IF Y'<0 D
"RTN","MCARPACE",40,0)
 .  S MCPATNM=Y(0,0) ;    new default name
"RTN","MCARPACE",41,0)
 .  S DA=+Y,DR="[MCARPACEDIT]"
"RTN","MCARPACE",42,0)
 .  D ^DIE
"RTN","MCARPACE",43,0)
 .  Q
"RTN","MCARPACE",44,0)
 ;END IF
"RTN","MCARPACE",45,0)
 ;
"RTN","MCARPACE",46,0)
 QUIT
"RTN","MCARPACE",47,0)
 ;
"RTN","MCARPACE",48,0)
ORDER1 ;
"RTN","MCARPACE",49,0)
 Q:'$D(MCOEON)  Q:'$D(^MCAR(MCFILE,MCARGDA))  I $D(DTOUT) S ORSTS=9 D RESULT^GMRCR Q
"RTN","MCARPAL")
0^1^B12124288
"RTN","MCARPAL",1,0)
MCARPAL ;WISC/TJK-PACEMAKER ACTIVE PATIENT LIST ;5/7/96  13:35
"RTN","MCARPAL",2,0)
 ;;2.3;Medicine;**16**;09/13/1996
"RTN","MCARPAL",3,0)
 W @IOF,!!,"ACTIVE PATIENT LIST"
"RTN","MCARPAL",4,0)
 W !! F I=1:1:80 W "*"
"RTN","MCARPAL",5,0)
 W !,"*",?37,"NOTICE",?79,"*"
"RTN","MCARPAL",6,0)
 W !,"*",?79,"*",!,"*",?10,"This report has been set up to print with a line length of 132",?79,"*",!,"*",?10,"characters. Select a device that uses a 132 character line length.",?79,"*"
"RTN","MCARPAL",7,0)
 W !,"*",?79,"*",! F I=1:1:80 W "*"
"RTN","MCARPAL",8,0)
 W !!,"<RETURN> to continue " R X:DTIME G EXIT:'$T,EXIT:X=U
"RTN","MCARPAL",9,0)
 K IO("Q") S %ZIS="QM" D ^%ZIS G EXIT:POP
"RTN","MCARPAL",10,0)
 I $D(IO("Q")) K IO("Q") S ZTRTN="CALC^MCARPAL",ZTDESC="PACEMAKER ACTIVE PATIENT LIST" D ^%ZTLOAD K ZTSK G EXIT
"RTN","MCARPAL",11,0)
 U IO
"RTN","MCARPAL",12,0)
CALC K ^TMP($J) S DFN=""
"RTN","MCARPAL",13,0)
CALC1 S DFN=$O(^MCAR(698,"C",DFN)) G PRINT:DFN=""
"RTN","MCARPAL",14,0)
 S MCAREG="" S:$D(^MCAR(690,DFN,"P2")) MCAREG=$P(^("P2"),U) G CALC1:'MCAREG
"RTN","MCARPAL",15,0)
 G CALC1:(MCAREG=2)!(MCAREG=3)!(MCAREG=5)!(MCAREG=6)!(MCAREG=8)
"RTN","MCARPAL",16,0)
 D DEM^VADPT S MCARNM=VADM(1),DOB=$P(VADM(3),U,2),SSN=VADM(2)
"RTN","MCARPAL",17,0)
 F DIC=698,698.1,698.2 S:DIC'=698.2 CT=0 S MCARCD=$S(DIC=698:"G",1:"L") D LEAD
"RTN","MCARPAL",18,0)
 S ^TMP($J,MCARNM,0)=MCAREG_U_DOB_U_SSN G CALC1
"RTN","MCARPAL",19,0)
PRINT S PG=0,LN="-------------------------------------" D HEAD S MCARNM=""
"RTN","MCARPAL",20,0)
PRINT1 S MCARNM=$O(^TMP($J,MCARNM)) G EXIT:MCARNM="" S X=^(MCARNM,0)
"RTN","MCARPAL",21,0)
 S A="" I $Y>(IOSL-3) R:IOST'?1"P-".E !,"<RETURN> to Continue",A:DTIME G EXIT:A=U D HEAD
"RTN","MCARPAL",22,0)
 W !!,MCARNM S Y=$P(X,U,3) W !,$E(Y,1,3),"-",$E(Y,4,5),"-",$E(Y,6,9)
"RTN","MCARPAL",23,0)
 W ?17 S Y=$P(X,U,2) W Y
"RTN","MCARPAL",24,0)
 S Y=$P(X,U) W ?29,$S(Y=1:"EAST PSC FOLLOW-UP",Y=4:"REGISTRY ONLY",Y=7:"WEST PSC FOLLOW-UP",1:"")
"RTN","MCARPAL",25,0)
 S A="" F I=1:1 Q:'$D(^TMP($J,MCARNM,"G",I))&('$D(^TMP($J,MCARNM,"L",I)))  D PR I $Y>(IOSL-3) R:IOST'?1"P-".E !,"<RETURN> to Continue",A:DTIME Q:A=U  D HEAD
"RTN","MCARPAL",26,0)
 G EXIT:A=U,PRINT1
"RTN","MCARPAL",27,0)
EXIT ;
"RTN","MCARPAL",28,0)
 I IOST'?1"P-".E R !!,"PRESS RETURN TO CONTINUE",X:DTIME
"RTN","MCARPAL",29,0)
 K A,CT,DFN,DIC,DOB,I,LN,MCARCD,MCAREG,MCARNM,PG,POP,SSN,X,Y,Z,VA,VADM
"RTN","MCARPAL",30,0)
 W:IOST?1"P-".E @IOF D ^%ZISC Q
"RTN","MCARPAL",31,0)
LEAD F I=0:0 S I=$O(^MCAR(DIC,"C",DFN,I)) Q:I=""  S CT=CT+1,Y=^MCAR(DIC,I,0),^TMP($J,MCARNM,MCARCD,CT)=$P(Y,U,1)_U_$P(Y,U,3)_U_$P(Y,U,4)_U_$P(Y,U,5)_$S(MCARCD="G":"",1:U_DIC)
"RTN","MCARPAL",32,0)
 Q
"RTN","MCARPAL",33,0)
PR W:I>1 !
"RTN","MCARPAL",34,0)
 I $D(^TMP($J,MCARNM,"G",I)) S X=^(I),Y=$P(X,U,1) W ?51,$E(Y,4,5),"/",$E(Y,6,7),"/",$E(Y,2,3) D MANUF W ?60,Y,?64,Z,?77,$P(X,U,4)
"RTN","MCARPAL",35,0)
 I $D(^TMP($J,MCARNM,"L",I)) S X=^(I),Y=$P(X,U,1) W ?90,$S($P(X,U,5)=698.1:"V: ",1:"A: "),$E(Y,4,5),"/",$E(Y,6,7),"/",$E(Y,2,3) D MANUF W ?102,Y,?106,Z,?119,$P(X,U,4)
"RTN","MCARPAL",36,0)
 Q
"RTN","MCARPAL",37,0)
MANUF S Y=$P(X,U,3) I Y,$D(^MCAR(698.6,Y,0)) S Y=$P(^(0),U,2)
"RTN","MCARPAL",38,0)
 S Z=$P(X,U,2) I Z,$D(^MCAR(698.4,Z,0)) S Z=$P(^(0),U)
"RTN","MCARPAL",39,0)
 Q
"RTN","MCARPAL",40,0)
HEAD S PG=PG+1 W @IOF,!!,?47,"VETERANS ADMINISTRATION MEDICAL CENTER",?120,"Pg.",PG
"RTN","MCARPAL",41,0)
 ;W !,?132-$L(^DD("SITE"))/2,^DD("SITE")
"RTN","MCARPAL",42,0)
 W !,?132-$L($$GET1^DIQ(4.3,1,217))/2,$$GET1^DIQ(4.3,1,217)
"RTN","MCARPAL",43,0)
 W !,?52,"PACEMAKER ACTIVE PATIENT LIST"
"RTN","MCARPAL",44,0)
 W !!,"PATIENT",?51,"GENERATOR IMPLANT DATA",?93,"V AND A LEAD IMPLANT DATA"
"RTN","MCARPAL",45,0)
 W !,"SSN",?17,"DOB",?29,"STATUS",?51,"DATE",?60,"MFR MODEL",?77,"SER. NO.",?93,"DATE",?102,"MFR MODEL",?119,"SER. NO."
"RTN","MCARPAL",46,0)
 W !,?51,LN,?93,LN
"RTN","MCARPAL",47,0)
 Q
"RTN","MCBPFTP1")
0^2^B22165624
"RTN","MCBPFTP1",1,0)
MCBPFTP1 ;WISC/TJK,ALG-PFT BRIEF REPORT-DEMO INFO ;5/15/96  16:04
"RTN","MCBPFTP1",2,0)
 ;;2.3;Medicine;**5,14,16**;09/13/1996
"RTN","MCBPFTP1",3,0)
 ; ------------------------
"RTN","MCBPFTP1",4,0)
 ; SSN = Enternal Format of the patients SSN with the first letter
"RTN","MCBPFTP1",5,0)
 ; of the last name tacked on the end
"RTN","MCBPFTP1",6,0)
 ; ------------------------
"RTN","MCBPFTP1",7,0)
 D DEM^VADPT S MCARGNM=VADM(1),SSN=VA("PID")
"RTN","MCBPFTP1",8,0)
 S X1=$E($P(MCPFT0,U),1,7),X2=$P(VADM(3),U)
"RTN","MCBPFTP1",9,0)
 ; ---------------------
"RTN","MCBPFTP1",10,0)
 ; AGE = the patients age at the date of the procedure
"RTN","MCBPFTP1",11,0)
 ; ---------------------
"RTN","MCBPFTP1",12,0)
 S AGE=$E(X1,1,3)-$E(X2,1,3)-($E(X1,4,7)<$E(X2,4,7))
"RTN","MCBPFTP1",13,0)
 S RACE=$P(VADM(8),U,2),CLIN="" S:$P(MCPFT0,U,10) CLIN=$P(MCPFT0,U,10) I CLIN,$D(^SC(CLIN,0)) S CLIN=$P(^(0),U)
"RTN","MCBPFTP1",14,0)
 S DATE=$P(MCPFT0,U),DATE=+$E(DATE,4,5)_"/"_+$E(DATE,6,7)_"/"_$E(DATE,2,3)_$S($P(DATE,".",2):"@"_+$E(DATE,9,10)_":"_$S($L($E(DATE,11,12))=2:$E(DATE,11,12),$L($E(DATE,11,12))=1:$E(DATE,11)_"0",1:"00"),1:"")
"RTN","MCBPFTP1",15,0)
 S HT1=$P(MCPFT0,U,4),WT1=$P(MCPFT0,U,5) S $P(MCDOT,".",81)=""
"RTN","MCBPFTP1",16,0)
 S HT=HT1*2.54,WT=WT1/2.2
"RTN","MCBPFTP1",17,0)
 S:'HT HT=$P(MCPFT0,U,3),HT1=HT/2.54 S:'WT WT=$P(MCPFT0,U,6),WT1=WT*2.2
"RTN","MCBPFTP1",18,0)
 S (MC17,MCEFF,MCSEX)="" S:$D(^MCAR(700,MCARGDA,17)) MC17=^(17),MCEFF=$P(MC17,U,6),MCEFF=$S(MCEFF="G":"GOOD",MCEFF="E":"EXCELLENT",MCEFF="P":"POOR",1:"")
"RTN","MCBPFTP1",19,0)
 ;S MCSEX=$P(VADM(5),U),X=$P(VADM(3),"^",2) S MCARDOB=$S(X'="":X,1:""),X=$P(MCPFT0,U) D DTIME^MCARP S MCARGDT=X,MCARZ="PULMONARY FUNCTION TEST"
"RTN","MCBPFTP1",20,0)
 S MCSEX=$P(VADM(5),U),X=$P(VADM(3),"^",2) S MCARDOB=$S(X'="":X,1:""),X=$P(MCPFT0,U),MCARGDT=X,MCARZ="PULMONARY FUNCTION TEST"
"RTN","MCBPFTP1",21,0)
 D INP^VADPT S MCARWARD=$S(VAIN(4)'="":$P(VAIN(4),U,2),1:"NOT INPATIENT"),MCARRB=VAIN(5) D NOW^%DTC S X=% D DTIME^MCARP S MCARDTM=X
"RTN","MCBPFTP1",22,0)
 S MCARZ="PULMONARY FUNCTION TEST"
"RTN","MCBPFTP1",23,0)
 D INIT^MCARP1(MCARZ,MCARGDT,MCFILE),HEAD^MCARP
"RTN","MCBPFTP1",24,0)
 W !,"SEX: ",MCSEX,"  AGE:",AGE,?30,HT1," in/",WT1," lb",?60,"AMBIENT: ",$P(MCPFT0,U,12),"C/",$P(MCPFT0,U,7),"T" K HT1,WT1
"RTN","MCBPFTP1",25,0)
 W !,RACE S TECH=$$GETVALUE^MCU(700,MCARGDA,34)
"RTN","MCBPFTP1",26,0)
 W ?60,"TECH: ",$E(TECH,1,14)
"RTN","MCBPFTP1",27,0)
 W !,$S($P(MCPFT0,U,8)="Y":"SMOKER",$P(MCPFT0,U,8)="N":"NON-SMOKER",1:"")
"RTN","MCBPFTP1",28,0)
 W ?30 W:$P(MCPFT0,U,9)="Y" "CURRENT BRONCHODILATOR USE"
"RTN","MCBPFTP1",29,0)
 W ?60,"EFFORT: ",MCEFF
"RTN","MCBPFTP1",30,0)
 S MCFF="S DN=1,MCY="""" I $Y>(IOSL-3) R:$E(IOST,1,2)=""C-"" !!,""Press Return to Continue, '^' to escape: "",MCY:DTIME S:'$T MCY=U S:MCY=U MCOUT=1,DN=0 Q:$D(MCOUT)  D:DN HEAD^MCARP D:$D(HEAD1) HEAD1^MCBPFTP2,HEAD2^MCBPFTP2 K MCY"
"RTN","MCBPFTP1",31,0)
 K ^UTILITY("DIQ1",$J) W !!,"CONSULT DX: " S DR(700.01)=.01,DIQ(0)="E",DIC="^MCAR(700,"
"RTN","MCBPFTP1",32,0)
 F K=0:0 S K=$O(^MCAR(700,MCARGDA,1,K)) Q:K'?1N.N  S DA=MCARGDA,DA(700.01)=K,DR=11,DIQ(0)="E" D EN^DIQ1 W ?15,^UTILITY("DIQ1",$J,700.01,K,.01,"E"),! X MCFF Q:$D(MCOUT)
"RTN","MCBPFTP1",33,0)
 S BSA=$$BSA^MCPFTP1(HT,WT) K ^UTILITY("DIQ1",$J),DIQ Q:$D(MCOUT)  W !,MCDOT X MCFF Q:$D(MCOUT)  D PRED
"RTN","MCBPFTP1",34,0)
 S RDATE=9999999.9999-$P(MCPFT0,U)
"RTN","MCBPFTP1",35,0)
 W:$D(MCRCN) !,MCRCN D ^MCBPFTP2
"RTN","MCBPFTP1",36,0)
 I '$D(MCOUT),$G(MCESON) D FOOTER^MCESPRT(MCFILE,MCARGDA)  ;PATCH 28
"RTN","MCBPFTP1",37,0)
EXIT D:$D(ZTSK) KILL^%ZTLOAD K ZTSK
"RTN","MCBPFTP1",38,0)
EXIT1 D KVAR^VADPT K MCOUT,ACT,AGE,CK,CLIN,D0,D1,DA,DATE,CI95
"RTN","MCBPFTP1",39,0)
 K MCARGDT2
"RTN","MCBPFTP1",40,0)
 K BSA,HB,PH,PACO2,PAO2,O2HB,COHB,FIO2,MHB,PAAO2,QSQT,CAO2,CVO2
"RTN","MCBPFTP1",41,0)
 K DFN,DIC,DIW,DIWL,DIWR,DIWT,DLCOSB,DN,MCDOT,DR,FEV1,FRC,FVC,MC17
"RTN","MCBPFTP1",42,0)
 K HT,I,J,K,MCARGDA,MCARGNM,MCFF,MCK,MCN,MCPI,MCREC,MCREC1,MCVCN
"RTN","MCBPFTP1",43,0)
 K MCREC2,MCTLCN,MCVN,MCX,MEAS,FEF2575,ND,ND1,P1,P2,PC,PD1,PD11,MCEFF
"RTN","MCBPFTP1",44,0)
 K PD2,PD21,PF,MCPFT0,PG,PRED,MCPV,RACE,RDATE,RDATE1,RDATE2,RV,MCSEX
"RTN","MCBPFTP1",45,0)
 K SSN,TAB,TECH,TLC,TYPE,UNIT,UNITS,VC,WT,X,Z,VA,MCRCN
"RTN","MCBPFTP1",46,0)
 K MCMVVN,MVV,PMVV,MCSP,MCP1S0,MCP1S1,MCP1S2,MCP2S0,MCP2S1,MCP2S2
"RTN","MCBPFTP1",47,0)
 K CDLCOSB,MCIAO1,MCIAO2,MCIDA,MCIDL,MCIDP,MCIFA,MCIFE
"RTN","MCBPFTP1",48,0)
 K MCIFL,MCIFV,MCIPTL,MCIRV,MCITL,MCMAIN,MCP1,MCP2,MCRC,MCRCR,MCTYPEP,MCY,MCRC1,MCRC2,MCRC3,MCRC4   ;,MCARGDA
"RTN","MCBPFTP1",49,0)
 K MCARRB,MCARDOB,MCARWARD,MCARDTM,MCARHDR,MCARZ,MCARGDT,MCDL,MCLNG D KVAR^VADPT D ^%ZISC Q
"RTN","MCBPFTP1",50,0)
PRED S (FVC,CFVC,FEV1,F,TLC,MVV)=""
"RTN","MCBPFTP1",51,0)
 Q:'HT!'WT!'AGE!'$D(^MCAR(700,MCARGDA,"PV"))  Q:'(^("PV"))
"RTN","MCBPFTP1",52,0)
 S MCPV=^MCAR(700,MCARGDA,"PV") Q:'$D(^MCAR(700.1,MCPV))
"RTN","MCBPFTP1",53,0)
 F I="FEV1","FVC","TLC","MVV" D
"RTN","MCBPFTP1",54,0)
    .S:$D(^MCAR(700.1,MCPV,I)) @("P"_I)="S "_I_"="_$P(^MCAR(700.2,^MCAR(700.1,MCPV,I),0),U),@("C"_I)=$P(^MCAR(700.2,^MCAR(700.1,MCPV,I),0),U,5) X:$D(^MCAR(700.1,MCPV,I)) @("P"_I)
"RTN","MCBPFTP1",55,0)
 K PDLCOSB,PFEV1,PFRC,PFVC,PFEF2575,PPF,PRV,PTLC,PVC
"RTN","MCBPFTP1",56,0)
 S MCRCR="",MCRC=$G(^MCAR(700.1,MCPV,"RC")) Q:MCRC=""
"RTN","MCBPFTP1",57,0)
 S MCRCR=$G(^MCAR(700,MCARGDA,17)) Q:MCRCR=""  Q:$P(MCRCR,U,5)'="Y"
"RTN","MCBPFTP1",58,0)
 S MCRCR=$S(RACE["BLACK":"B",RACE["ASIAN":"O",1:"") Q:MCRCR=""
"RTN","MCBPFTP1",59,0)
 F I=1:1:4 I $P(MCRC,U,I) S J=$P(MCRC,U,I) D:J
"RTN","MCBPFTP1",60,0)
    .Q:'$D(^MCAR(700.2,J,0))  S J=$P(^(0),U,1)
"RTN","MCBPFTP1",61,0)
    .S @("MCRC"_I)="S ACT="_J
"RTN","MCBPFTP1",62,0)
 K J G ORIENTAL:MCRCR="O" K MCRC2
"RTN","MCBPFTP1",63,0)
 I '$D(MCRC1),'$D(MCRC3),'$D(MCRC4) Q
"RTN","MCBPFTP1",64,0)
 S:$D(MCRC1) MCRCN="TLC,FVC,FEV1" S:$D(MCRC3) MCRCN=MCRCN_",FRC,RV" S:$D(MCRC4) MCRCN=MCRCN_",FEF25-75" S:$E(MCRCN,1)="," MCRCN=$E(MCRCN,2,30)
"RTN","MCBPFTP1",65,0)
 G NOTE
"RTN","MCBPFTP1",66,0)
ORIENTAL I '$D(MCRC2) K MCRC1,MCRC3,MCRC4 Q
"RTN","MCBPFTP1",67,0)
 S MCRC1=MCRC2 K MCRC3,MCRC4 S MCRCN="TLC,FVC,FEV1"
"RTN","MCBPFTP1",68,0)
NOTE S MCRCN="NOTE:   Race Correction done on predicted values for: "_MCRCN
"RTN","MCBPFTP1",69,0)
 Q
"RTN","MCPFTP1")
0^3^B22355958
"RTN","MCPFTP1",1,0)
MCPFTP1 ;WISC/TJK-PFT REPORT-DEMO INFO ;6/18/96  08:27
"RTN","MCPFTP1",2,0)
 ;;2.3;Medicine;**14,16**;09/13/1996
"RTN","MCPFTP1",3,0)
 ; ------------------------
"RTN","MCPFTP1",4,0)
 ; SSN = Enternal Format of the patients SSN with the first letter
"RTN","MCPFTP1",5,0)
 ; of the last name tacked on the end
"RTN","MCPFTP1",6,0)
 ; ------------------------
"RTN","MCPFTP1",7,0)
 D DEM^VADPT S MCARGNM=VADM(1),SSN=VA("PID")
"RTN","MCPFTP1",8,0)
 S X1=$E($P(MCPFT0,U),1,7),X2=$P(VADM(3),U)
"RTN","MCPFTP1",9,0)
 ; ---------------------
"RTN","MCPFTP1",10,0)
 ; AGE = the patients age at the date of the procedure
"RTN","MCPFTP1",11,0)
 ; ---------------------
"RTN","MCPFTP1",12,0)
 S AGE=$E(X1,1,3)-$E(X2,1,3)-($E(X1,4,7)<$E(X2,4,7))
"RTN","MCPFTP1",13,0)
 S RACE=$P(VADM(8),U,2),CLIN="" S:$P(MCPFT0,U,10) CLIN=$P(MCPFT0,U,10) I CLIN,$D(^SC(CLIN,0)) S CLIN=$P(^(0),U)
"RTN","MCPFTP1",14,0)
 S DATE=$P(MCPFT0,U),DATE=+$E(DATE,4,5)_"/"_+$E(DATE,6,7)_"/"_$E(DATE,2,3)_$S($P(DATE,".",2):"@"_+$E(DATE,9,10)_":"_$S($L($E(DATE,11,12))=2:$E(DATE,11,12),$L($E(DATE,11,12))=1:$E(DATE,11)_"0",1:"00"),1:"")
"RTN","MCPFTP1",15,0)
 S HT1=$P(MCPFT0,U,4),WT1=$P(MCPFT0,U,5) S $P(MCDOT,".",81)=""
"RTN","MCPFTP1",16,0)
 S HT=HT1*2.54,WT=WT1/2.2
"RTN","MCPFTP1",17,0)
 S:'HT HT=$P(MCPFT0,U,3),HT1=HT/2.54 S:'WT WT=$P(MCPFT0,U,6),WT1=WT*2.2
"RTN","MCPFTP1",18,0)
 S (MC17,MCEFF,MCSEX)="" S:$D(^MCAR(700,MCARGDA,17)) MC17=^(17),MCEFF=$P(MC17,U,6),MCEFF=$S(MCEFF="G":"GOOD",MCEFF="E":"EXCELLENT",MCEFF="P":"POOR",1:"")
"RTN","MCPFTP1",19,0)
 S MCSEX=$P(VADM(5),U),X=$P(VADM(3),"^",2) S MCARDOB=$S(X'="":X,1:""),X=$P(MCPFT0,U) D DTIME^MCARP S (MCARGDT,MCARGDT2)=X,MCARZ="PULMONARY FUNCTION TEST " S:MCESON MCARZ=MCARZ_" - "_MCSTAT
"RTN","MCPFTP1",20,0)
 D INP^VADPT S MCARWARD=$S(VAIN(4)'="":$P(VAIN(4),U,2),1:"NOT INPATIENT"),MCARRB=VAIN(5) D NOW^%DTC S X=% D DTIME^MCARP S MCARDTM=X
"RTN","MCPFTP1",21,0)
 D INIT^MCARP1(MCARZ,MCARGDT,MCFILE)
"RTN","MCPFTP1",22,0)
 D HEAD^MCARP
"RTN","MCPFTP1",23,0)
 W !,"SEX: ",MCSEX,"  AGE:",AGE,?30,+$J(HT1,0,1)," in/",+$J(WT1,0,1)," lb",?60,"AMBIENT: ",$P(MCPFT0,U,12),"C/",$P(MCPFT0,U,7),"T" K HT1,WT1
"RTN","MCPFTP1",24,0)
 W !,RACE S TECH=$P(MCPFT0,U,13) I TECH,$D(^VA(200,TECH,0)) S TECH=$P(^(0),U)
"RTN","MCPFTP1",25,0)
 W ?60,"TECH: ",$E(TECH,1,14)
"RTN","MCPFTP1",26,0)
 W !,$S($P(MCPFT0,U,8)="Y":"SMOKER",$P(MCPFT0,U,8)="N":"NON-SMOKER",1:"")
"RTN","MCPFTP1",27,0)
 W ?30 W:$P(MCPFT0,U,9)="Y" "CURRENT BRONCHODILATOR USE"
"RTN","MCPFTP1",28,0)
 W ?60,"EFFORT: ",MCEFF
"RTN","MCPFTP1",29,0)
 S MCFF="S DN=1,MCY="""" I $Y>(IOSL-3) R:$E(IOST,1,2)=""C-"" !!,""Press Return to Continue, '^' to escape: "",MCY:DTIME S:'$T MCY=U S:MCY=U MCOUT=1,DN=0 Q:$D(MCOUT)  D:DN HEAD^MCARP D:$D(HEAD1) HEAD1^MCPFTP2,HEAD2^MCPFTP2 K MCY"
"RTN","MCPFTP1",30,0)
 K ^UTILITY("DIQ1",$J) W !!,"CONSULT DX: " S DR(700.01)=.01,DIQ(0)="E",DIC="^MCAR(700,"
"RTN","MCPFTP1",31,0)
 F K=0:0 S K=$O(^MCAR(700,MCARGDA,1,K)) Q:K'?1N.N  S DA=MCARGDA,DA(700.01)=K,DR=11,DIQ(0)="E" D EN^DIQ1 W ?15,^UTILITY("DIQ1",$J,700.01,K,.01,"E"),! X MCFF Q:$D(MCOUT)
"RTN","MCPFTP1",32,0)
 K ^UTILITY("DIQ1",$J),DIQ Q:$D(MCOUT)  W !,MCDOT X MCFF Q:$D(MCOUT)  D PRED
"RTN","MCPFTP1",33,0)
 S RDATE=9999999.9999-$P(MCPFT0,U)
"RTN","MCPFTP1",34,0)
 W:$D(MCRCN) !,MCRCN
"RTN","MCPFTP1",35,0)
 D ^MCPFTP2
"RTN","MCPFTP1",36,0)
 D:$G(MCESON) FOOTER^MCESPRT(MCFILE,MCARGDA)
"RTN","MCPFTP1",37,0)
EXIT S:$D(ZTQUEUED) ZTREQ="@" K ZTSK
"RTN","MCPFTP1",38,0)
EXIT1 ;
"RTN","MCPFTP1",39,0)
 D EXIT^MCPFTP1A
"RTN","MCPFTP1",40,0)
 Q 
"RTN","MCPFTP1",41,0)
PRED S (DLCOSB,FEV1,FRC,FVC,FEF2575,PF,RV,TLC,VC,MVV,CTLC,CVC,CFRC,CRV,CFVC,CFEV1,CPF,CFEF2575,CMVV,CDLCOSB,ACT,COHB)=""
"RTN","MCPFTP1",42,0)
 S MCPV=$$MCPV(MCARGDA)
"RTN","MCPFTP1",43,0)
 I ('HT)!('WT)!('AGE)!(MCPV=0) Q
"RTN","MCPFTP1",44,0)
 D PREDS,MCRACE Q
"RTN","MCPFTP1",45,0)
MCRACE S MCRCR="",MCRC=$G(^MCAR(700.1,MCPV,"RC")) Q:MCRC=""
"RTN","MCPFTP1",46,0)
 S MCRCR=$G(^MCAR(700,MCARGDA,17)) Q:MCRCR=""  Q:$P(MCRCR,U,5)'="Y"
"RTN","MCPFTP1",47,0)
 S MCRCR=$S(RACE["BLACK":"B",RACE["ASIAN":"O",1:"") Q:MCRCR=""
"RTN","MCPFTP1",48,0)
 F I=1:1:4 I $P(MCRC,U,I) S J=$P(MCRC,U,I) D:J
"RTN","MCPFTP1",49,0)
 .Q:'$D(^MCAR(700.2,J,0))  S J=$P(^(0),U,1)
"RTN","MCPFTP1",50,0)
 .S @("MCRC"_I)="S PRED="_J
"RTN","MCPFTP1",51,0)
 K J G ORIENTAL:MCRCR="O" K MCRC2
"RTN","MCPFTP1",52,0)
 I '$D(MCRC1),'$D(MCRC3),'$D(MCRC4) Q
"RTN","MCPFTP1",53,0)
 S:$D(MCRC1) MCRCN="TLC,VC,FVC,FEV1" S:$D(MCRC3) MCRCN=MCRCN_",FRC,RV" S:$D(MCRC4) MCRCN=MCRCN_",FEF25-75" S:$E(MCRCN,1)="," MCRCN=$E(MCRCN,2,30)
"RTN","MCPFTP1",54,0)
 G NOTE
"RTN","MCPFTP1",55,0)
ORIENTAL I '$D(MCRC2) K MCRC1,MCRC3,MCRC4 Q
"RTN","MCPFTP1",56,0)
 S MCRC1=MCRC2 K MCRC3,MCRC4 S MCRCN="TLC,VC,FVC,FEV1"
"RTN","MCPFTP1",57,0)
NOTE S MCRCN="NOTE:   Race Correction done on predicted values for: "_MCRCN
"RTN","MCPFTP1",58,0)
 Q
"RTN","MCPFTP1",59,0)
CONFID(MCPV,VALUE) ;
"RTN","MCPFTP1",60,0)
 Q $P(^MCAR(700.2,^MCAR(700.1,MCPV,VALUE),0),U,5)
"RTN","MCPFTP1",61,0)
PREDV(MCPV,VALUE)       ;
"RTN","MCPFTP1",62,0)
 N EXPRESS,FORMULA,IEN,RESULT
"RTN","MCPFTP1",63,0)
 S IEN=+$P($G(^MCAR(700.1,MCPV,VALUE)),U)
"RTN","MCPFTP1",64,0)
 S FORMULA=$P($G(^MCAR(700.2,IEN,0)),U)
"RTN","MCPFTP1",65,0)
 S RESULT=""
"RTN","MCPFTP1",66,0)
 I FORMULA]"" S EXPRESS="S RESULT="_FORMULA X EXPRESS
"RTN","MCPFTP1",67,0)
 Q $S(RESULT]"":RESULT,1:"")
"RTN","MCPFTP1",68,0)
MCPV(MCDA) ; Get the Predicted Value entry
"RTN","MCPFTP1",69,0)
 Q $S($D(^MCAR(700,MCDA,"PV")):^("PV"),1:0)
"RTN","MCPFTP1",70,0)
PREDS S BSA=+$$BSA(HT,WT),I="DLCOSB",DLCOSB=$$PREDV(MCPV,"DLCOSB"),CDLCOSB=$$CONFID(MCPV,"DLCOSB")
"RTN","MCPFTP1",71,0)
 S FEV1=$$PREDV(MCPV,"FEV1"),CFEV1=$$CONFID(MCPV,"FEV1")
"RTN","MCPFTP1",72,0)
 S FRC=$$PREDV(MCPV,"FRC"),CFRC=$$CONFID(MCPV,"FRC")
"RTN","MCPFTP1",73,0)
 S FVC=$$PREDV(MCPV,"FVC"),CFVC=$$CONFID(MCPV,"FVC")
"RTN","MCPFTP1",74,0)
 S FEF2575=$$PREDV(MCPV,"FEF2575"),CFEF2575=$$CONFID(MCPV,"FEF2575")
"RTN","MCPFTP1",75,0)
 S PF=$$PREDV(MCPV,"PF"),CPF=$$CONFID(MCPV,"PF")
"RTN","MCPFTP1",76,0)
 S RV=$$PREDV(MCPV,"RV"),CRV=$$CONFID(MCPV,"RV")
"RTN","MCPFTP1",77,0)
 S TLC=$$PREDV(MCPV,"TLC"),CTLC=$$CONFID(MCPV,"TLC")
"RTN","MCPFTP1",78,0)
 S VC=$$PREDV(MCPV,"VC"),CVC=$$CONFID(MCPV,"VC")
"RTN","MCPFTP1",79,0)
 S MVV=$$PREDV(MCPV,"MVV"),CMVV=$$CONFID(MCPV,"MVV")
"RTN","MCPFTP1",80,0)
 Q
"RTN","MCPFTP1",81,0)
BSA(HT,WT) ; Compute BSA
"RTN","MCPFTP1",82,0)
 D COMPUTE^MCARBSA
"RTN","MCPFTP1",83,0)
 Q X
"VER")
8.0^21.0
**END**
**END**
