Released PRPF*3*7 SEQ #7
Extracted from mail message
**KIDS**:PRPF*3.0*7^

**INSTALL NAME**
PRPF*3.0*7
"BLD",693,0)
PRPF*3.0*7^INTEGRATED PATIENT FUNDS^0^2970710^n
"BLD",693,1,0)
^^10^10^2970725^
"BLD",693,1,1,0)
 
"BLD",693,1,2,0)
This patch contains the changes necessary to support the following
"BLD",693,1,3,0)
items:
"BLD",693,1,4,0)
 
"BLD",693,1,5,0)
1. Remove routines previously used for conversion from 3/6/16.
"BLD",693,1,6,0)
2. Run a File 16 conversion of the Provider Authorizing Restriction field,
"BLD",693,1,7,0)
of file 470 which was inadvertantly missed in Patch PRPF*3.0*6.
"BLD",693,1,8,0)
3. Modify the header used in the PRPF Archive tape.
"BLD",693,1,9,0)
4. Corrects problems identified in NOIS - DAY-0697-40888, DAN-0697-42229
"BLD",693,1,10,0)
and BAN-0697-11023
"BLD",693,4,0)
^9.64PA^^0
"BLD",693,"INI")

"BLD",693,"INIT")

"BLD",693,"KRN",0)
^9.67PA^19^18
"BLD",693,"KRN",.4,0)
.4
"BLD",693,"KRN",.4,"NM",0)
^9.68A^^0
"BLD",693,"KRN",.401,0)
.401
"BLD",693,"KRN",.401,"NM",0)
^9.68A^^0
"BLD",693,"KRN",.402,0)
.402
"BLD",693,"KRN",.402,"NM",0)
^9.68A^^0
"BLD",693,"KRN",.403,0)
.403
"BLD",693,"KRN",.5,0)
.5
"BLD",693,"KRN",.84,0)
.84
"BLD",693,"KRN",3.6,0)
3.6
"BLD",693,"KRN",3.8,0)
3.8
"BLD",693,"KRN",3.8,"NM",0)
^9.68A^^0
"BLD",693,"KRN",9.2,0)
9.2
"BLD",693,"KRN",9.8,0)
9.8
"BLD",693,"KRN",9.8,"NM",0)
^9.68A^49^18
"BLD",693,"KRN",9.8,"NM",6)
^^^
"BLD",693,"KRN",9.8,"NM",6,0)
PRPFCVT^^1^
"BLD",693,"KRN",9.8,"NM",7)
^^^
"BLD",693,"KRN",9.8,"NM",7,0)
PRPFCVT0^^1^
"BLD",693,"KRN",9.8,"NM",8)
^^^
"BLD",693,"KRN",9.8,"NM",8,0)
PRPFCVT1^^1^
"BLD",693,"KRN",9.8,"NM",14,0)
PRPFDST^^0^B9331817
"BLD",693,"KRN",9.8,"NM",28,0)
PRPFPUR1^^0^B18593117
"BLD",693,"KRN",9.8,"NM",34)
^^^
"BLD",693,"KRN",9.8,"NM",34,0)
PRPFSCV^^1^
"BLD",693,"KRN",9.8,"NM",35)
^^^
"BLD",693,"KRN",9.8,"NM",35,0)
PRPFSCV1^^1^
"BLD",693,"KRN",9.8,"NM",36)
^^^
"BLD",693,"KRN",9.8,"NM",36,0)
PRPFSCV2^^1^
"BLD",693,"KRN",9.8,"NM",37)
^^^
"BLD",693,"KRN",9.8,"NM",37,0)
PRPFSCV3^^1^
"BLD",693,"KRN",9.8,"NM",38,0)
PRPFSIG^^0^B2698729
"BLD",693,"KRN",9.8,"NM",40)
^^^
"BLD",693,"KRN",9.8,"NM",40,0)
PRPFSIG2^^1^
"BLD",693,"KRN",9.8,"NM",42)
^^^
"BLD",693,"KRN",9.8,"NM",42,0)
PRPFSUM^^1^
"BLD",693,"KRN",9.8,"NM",43)
^^^
"BLD",693,"KRN",9.8,"NM",43,0)
PRPFIENV^^1^
"BLD",693,"KRN",9.8,"NM",44)
^^^
"BLD",693,"KRN",9.8,"NM",44,0)
PRPFIPRE^^1^
"BLD",693,"KRN",9.8,"NM",46,0)
PRPFPNT^^0^B4522739
"BLD",693,"KRN",9.8,"NM",47,0)
PRPFARC^^0^B14358906
"BLD",693,"KRN",9.8,"NM",48,0)
PRPFIPST^^0^B9554736
"BLD",693,"KRN",9.8,"NM",49,0)
PRPFNQ^^0^B20910385
"BLD",693,"KRN",9.8,"NM","B","PRPFARC",47)

"BLD",693,"KRN",9.8,"NM","B","PRPFCVT",6)
 
"BLD",693,"KRN",9.8,"NM","B","PRPFCVT0",7)
 
"BLD",693,"KRN",9.8,"NM","B","PRPFCVT1",8)
 
"BLD",693,"KRN",9.8,"NM","B","PRPFDST",14)
 
"BLD",693,"KRN",9.8,"NM","B","PRPFIENV",43)

"BLD",693,"KRN",9.8,"NM","B","PRPFIPRE",44)

"BLD",693,"KRN",9.8,"NM","B","PRPFIPST",48)

"BLD",693,"KRN",9.8,"NM","B","PRPFNQ",49)

"BLD",693,"KRN",9.8,"NM","B","PRPFPNT",46)

"BLD",693,"KRN",9.8,"NM","B","PRPFPUR1",28)
 
"BLD",693,"KRN",9.8,"NM","B","PRPFSCV",34)
 
"BLD",693,"KRN",9.8,"NM","B","PRPFSCV1",35)
 
"BLD",693,"KRN",9.8,"NM","B","PRPFSCV2",36)
 
"BLD",693,"KRN",9.8,"NM","B","PRPFSCV3",37)
 
"BLD",693,"KRN",9.8,"NM","B","PRPFSIG",38)
 
"BLD",693,"KRN",9.8,"NM","B","PRPFSIG2",40)
 
"BLD",693,"KRN",9.8,"NM","B","PRPFSUM",42)
 
"BLD",693,"KRN",19,0)
19
"BLD",693,"KRN",19,"NM",0)
^9.68A^^0
"BLD",693,"KRN",19.1,0)
19.1
"BLD",693,"KRN",19.1,"NM",0)
^9.68A^^0
"BLD",693,"KRN",101,0)
101
"BLD",693,"KRN",409.61,0)
409.61
"BLD",693,"KRN",771,0)
771
"BLD",693,"KRN",869.2,0)
869.2
"BLD",693,"KRN",870,0)
870
"BLD",693,"KRN",8994,0)
8994
"BLD",693,"KRN","B",.4,.4)
 
"BLD",693,"KRN","B",.401,.401)
 
"BLD",693,"KRN","B",.402,.402)
 
"BLD",693,"KRN","B",.403,.403)
 
"BLD",693,"KRN","B",.5,.5)
 
"BLD",693,"KRN","B",.84,.84)
 
"BLD",693,"KRN","B",3.6,3.6)
 
"BLD",693,"KRN","B",3.8,3.8)
 
"BLD",693,"KRN","B",9.2,9.2)
 
"BLD",693,"KRN","B",9.8,9.8)
 
"BLD",693,"KRN","B",19,19)
 
"BLD",693,"KRN","B",19.1,19.1)
 
"BLD",693,"KRN","B",101,101)
 
"BLD",693,"KRN","B",409.61,409.61)
 
"BLD",693,"KRN","B",771,771)
 
"BLD",693,"KRN","B",869.2,869.2)
 
"BLD",693,"KRN","B",870,870)
 
"BLD",693,"KRN","B",8994,8994)
 
"BLD",693,"PRE")

"BLD",693,"QUES",0)
^9.62^^
"BLD",693,"REQB",0)
^9.611^1^1
"BLD",693,"REQB",1,0)
PRPF*3.0*6^1
"BLD",693,"REQB","B","PRPF*3.0*6",1)

"OER",90,0)
90^^0^M.A.S.^
"ORD",0,9.8)
9.8;;1;RTNF^XPDTA;RTNE^XPDTA
"ORD",0,9.8,0)
ROUTINE
"PKG",90,-1)
1^1
"PKG",90,0)
INTEGRATED PATIENT FUNDS^PRPF^PATIENT FUNDS.  INTEGRATED WITH PATIENT FILE
"PKG",90,22,0)
^9.49I^1^1
"PKG",90,22,1,0)
3.0^2970224
"PKG",90,22,1,"PAH",1,0)
7^2970710^1
"PKG",90,22,1,"PAH",1,1,0)
^^10^10^2980107
"PKG",90,22,1,"PAH",1,1,1,0)
 
"PKG",90,22,1,"PAH",1,1,2,0)
This patch contains the changes necessary to support the following
"PKG",90,22,1,"PAH",1,1,3,0)
items:
"PKG",90,22,1,"PAH",1,1,4,0)
 
"PKG",90,22,1,"PAH",1,1,5,0)
1. Remove routines previously used for conversion from 3/6/16.
"PKG",90,22,1,"PAH",1,1,6,0)
2. Run a File 16 conversion of the Provider Authorizing Restriction field,
"PKG",90,22,1,"PAH",1,1,7,0)
of file 470 which was inadvertantly missed in Patch PRPF*3.0*6.
"PKG",90,22,1,"PAH",1,1,8,0)
3. Modify the header used in the PRPF Archive tape.
"PKG",90,22,1,"PAH",1,1,9,0)
4. Corrects problems identified in NOIS - DAY-0697-40888, DAN-0697-42229
"PKG",90,22,1,"PAH",1,1,10,0)
and BAN-0697-11023
"QUES","XPF1",0)
Y
"QUES","XPF1","??")
^D REP^XPDH
"QUES","XPF1","A")
Shall I write over your |FLAG| File
"QUES","XPF1","B")
YES
"QUES","XPF1","M")
D XPF1^XPDIQ
"QUES","XPF2",0)
Y
"QUES","XPF2","??")
^D DTA^XPDH
"QUES","XPF2","A")
Want my data |FLAG| yours
"QUES","XPF2","B")
YES
"QUES","XPF2","M")
D XPF2^XPDIQ
"QUES","XPM1",0)
PO^VA(200,:EM
"QUES","XPM1","??")
^D MG^XPDH
"QUES","XPM1","A")
Enter the Coordinator for Mail Group '|FLAG|'
"QUES","XPM1","B")

"QUES","XPM1","M")
D XPM1^XPDIQ
"QUES","XPZ1",0)
Y
"QUES","XPZ1","??")
^D OPT^XPDH
"QUES","XPZ1","A")
Want to DISABLE Scheduled Options, Menu Options, and Protocols
"QUES","XPZ1","B")
YES
"QUES","XPZ1","M")
D XPZ1^XPDIQ
"QUES","XPZ2",0)
Y
"QUES","XPZ2","??")
^D RTN^XPDH
"QUES","XPZ2","A")
Want to MOVE routines to other CPUs
"QUES","XPZ2","B")
NO
"QUES","XPZ2","M")
D XPZ2^XPDIQ
"RTN")
18
"RTN","PRPFARC")
0^47^B14358906
"RTN","PRPFARC",1,0)
PRPFARC ;CTB/ALTOONA   PATIENT FUNDS ARCHIVE  ;1/7/98  12:25 PM
"RTN","PRPFARC",2,0)
V ;;3.0;PATIENT FUNDS;**6,7**;JUNE 1, 1989
"RTN","PRPFARC",3,0)
 N X,MTIO,NAME,PGCOUNT,XPDNM,ZTQUEUED
"RTN","PRPFARC",4,0)
 S X="This option will cause all transactions of all cards to be written to tape in alphabetical order" D MSG^PRPFU1
"RTN","PRPFARC",5,0)
 K ^TMP($J,"PRPFARC")
"RTN","PRPFARC",6,0)
 S PGCOUNT=0
"RTN","PRPFARC",7,0)
 S %A="Are You Ready to Begin",%B="",%=1 D ^PRPFYN Q:%'=1
"RTN","PRPFARC",8,0)
 S MESSAGE="BUILDING ALPHABETIC CROSS REFERENCE IN ^TMP.  ITEMS=PATIENTS"
"RTN","PRPFARC",9,0)
 S TREC=$P(^PRPF(470,0),"^",4)
"RTN","PRPFARC",10,0)
 QUIT:TREC=0
"RTN","PRPFARC",11,0)
 D BEGIN^PRPFU
"RTN","PRPFARC",12,0)
 S DA=0 F  D  S XCOUNT=XCOUNT+COUNT D:'$D(ZTQUEUED) PERCENT^PRPFU Q:'DA
"RTN","PRPFARC",13,0)
 . F COUNT=1:1:LREC S DA=$O(^PRPF(470,DA)) Q:'DA  S:$D(^DPT(DA,0)) ^TMP($J,"PRPFARC",$P(^DPT(DA,0),"^"),DA)=""
"RTN","PRPFARC",14,0)
 . QUIT
"RTN","PRPFARC",15,0)
 K X S $P(X," ",40)=""
"RTN","PRPFARC",16,0)
 W !!!!,"100% complete."_$P(X," ",1,40),!
"RTN","PRPFARC",17,0)
 D:$G(XPDNM)="" KILL^%ZISS
"RTN","PRPFARC",18,0)
HDR W !!,"You now need to enter the header information:"
"RTN","PRPFARC",19,0)
 S DIR(0)="FA^3:30",DIR("A")="Select Header Line 1: ",DIR("B")=$S($D(LINE(1)):LINE(1),1:"VA MEDICAL CENTER"),DIR("?")="Enter the first line of the header to be printed on the archive record tape or an '^' to quit"
"RTN","PRPFARC",20,0)
 D ^DIR K DIR I $$DIR^PRPFU2 D TERM QUIT
"RTN","PRPFARC",21,0)
 S LINE(1)=Y
"RTN","PRPFARC",22,0)
 S DIR(0)="FA^3:30",DIR("A")="Select Header Line 2: ",DIR("?")="Enter the second line of the header to be printed on the archive record tape or an '^' to quit" S:$D(LINE(2)) DIR("B")=LINE(2)
"RTN","PRPFARC",23,0)
 D ^DIR K DIR I $$DIR^PRPFU2 D TERM QUIT
"RTN","PRPFARC",24,0)
 S LINE(2)=Y
"RTN","PRPFARC",25,0)
 S DIR(0)="FOA^3:30",DIR("A")="Select Header Line 3: ",DIR("?")="Enter the third line of the header to be printed on the archive record tape or an '^' to quit" S:$D(LINE(3)) DIR("B")=LINE(3)
"RTN","PRPFARC",26,0)
 D ^DIR K DIR I Y]"",$$DIR^PRPFU2 D TERM QUIT
"RTN","PRPFARC",27,0)
 S LINE(3)=Y
"RTN","PRPFARC",28,0)
 W !! F I=1:1:3 W LINE(I),!
"RTN","PRPFARC",29,0)
 D NOW^PRPFQ S LINE(4)=%X
"RTN","PRPFARC",30,0)
 S DIR("A")="IS THIS OK",DIR(0)="Y" D ^DIR I $$DIR^PRPFU2 D TERM QUIT
"RTN","PRPFARC",31,0)
 I 'Y W !!,"OK, you may now edit this information.",! G HDR
"RTN","PRPFARC",32,0)
 S %ZIS("A")="Select Tape/HFS Device: "
"RTN","PRPFARC",33,0)
 D ^%ZIS I POP D TERM QUIT
"RTN","PRPFARC",34,0)
 S MTIO=IO D HOME^%ZIS
"RTN","PRPFARC",35,0)
 S PRPF("ARCHIVE")=""
"RTN","PRPFARC",36,0)
 U MTIO W "1^PATIENT FUNDS ARCHIVE^"_$$DATE^PRPFU1(DT),!,"2^"_LINE(1),!,"2^"_LINE(2)
"RTN","PRPFARC",37,0)
 U MTIO I $G(LINE(3))]"" W !,"2^"_LINE(3)
"RTN","PRPFARC",38,0)
 U MTIO W !,"3^~~PRPF~~^"_$P(^PRPF(470,0),"^",4)_"^^"
"RTN","PRPFARC",39,0)
 U MTIO W !,"4^NAME^CLAIM^SSN"
"RTN","PRPFARC",40,0)
 U MTIO W !,"5^LANDSCAPE^COURIER NEW^24",!
"RTN","PRPFARC",41,0)
 S MESSAGE="ARCHIVING PATIENT FUNDS CARDS.  ITEMS=PATIENT NAME"
"RTN","PRPFARC",42,0)
 S NAME="" F I=0:1 S NAME=$O(^TMP($J,"PRPFARC",NAME)) Q:NAME=""
"RTN","PRPFARC",43,0)
 S TREC=I
"RTN","PRPFARC",44,0)
 QUIT:TREC=0
"RTN","PRPFARC",45,0)
 U IO D BEGIN^PRPFU
"RTN","PRPFARC",46,0)
 S NAME="" F  U MTIO D  S XCOUNT=XCOUNT+COUNT U IO D:'$D(ZTQUEUED) PERCENT^PRPFU Q:NAME=""
"RTN","PRPFARC",47,0)
 . F COUNT=1:1:LREC S NAME=$O(^TMP($J,"PRPFARC",NAME)) Q:NAME=""  D
"RTN","PRPFARC",48,0)
 . . S DA=0 F  S DA=$O(^TMP($J,"PRPFARC",NAME,DA)) Q:'DA  D
"RTN","PRPFARC",49,0)
 . . . S DFN=DA
"RTN","PRPFARC",50,0)
 . . . U MTIO D EN2^PRPFCD
"RTN","PRPFARC",51,0)
 . . . QUIT
"RTN","PRPFARC",52,0)
 . . QUIT
"RTN","PRPFARC",53,0)
 . QUIT
"RTN","PRPFARC",54,0)
 U MTIO W !!,"ARCHIVE COMPLETED*^^*"
"RTN","PRPFARC",55,0)
 D:$G(XPDNM)="" KILL^%ZISS
"RTN","PRPFARC",56,0)
 D ADD("ARCHIVE",DT)
"RTN","PRPFARC",57,0)
 D CLOSE^PRPFU,END^PRPFU
"RTN","PRPFARC",58,0)
 U IO W !!,"ARCHIVE COMPLETED",*7
"RTN","PRPFARC",59,0)
 QUIT
"RTN","PRPFARC",60,0)
TERM ;
"RTN","PRPFARC",61,0)
 U IO W "  OPTION TERMINATED",*7 Q
"RTN","PRPFARC",62,0)
ADD(TYPE,THRU) ;ADD ENTRY TO ARCHIVE HISTORY FILE
"RTN","PRPFARC",63,0)
 NEW DIC,X,%,%H,%I,DA,DR,DLAYGO
"RTN","PRPFARC",64,0)
 D NOW^%DTC S X=%
"RTN","PRPFARC",65,0)
 K DD,D0 S DIC="^PRPF(470.9,",DIC(0)="ML",DLAYGO=470.9
"RTN","PRPFARC",66,0)
 S DIC("DR")="1///"_TYPE I $D(THRU) S DIC("DR")=DIC("DR")_";2///"_THRU
"RTN","PRPFARC",67,0)
 D FILE^DICN
"RTN","PRPFARC",68,0)
 QUIT
"RTN","PRPFCVT")
1^6
"RTN","PRPFCVT0")
1^7
"RTN","PRPFCVT1")
1^8
"RTN","PRPFDST")
0^14^B9331817
"RTN","PRPFDST",1,0)
PRPFDST ;ALTOONA/CTB  DISPLAY TRANACTIONS ;7/24/97  8:36 AM
"RTN","PRPFDST",2,0)
V ;;3.0;PATIENT FUNDS;**6,7**;JUNE 1, 1989
"RTN","PRPFDST",3,0)
 D ^PRPFSITE I % D HILO^PRPFBAL S PAGE=1,DIC=470,DIC(0)="AEMNZ" D ^DIC I Y>0 S DFN=+Y D D W !! G V
"RTN","PRPFDST",4,0)
OUT K %,%W,%Y,C,DA,DFN,DIC,DIYS,J,K,LINE,MADA,N,P,PAGE,FR,TO,PFHI,PFLO,PFNORM,POP,PRPF,PRPFQ,PRPFL,PTRDA,S,TMP,X,X1,Y,ZDA Q
"RTN","PRPFDST",5,0)
D ;;DISPLAY/PRINT PATIENT FUNDS TRANSACTIONS
"RTN","PRPFDST",6,0)
 D DRNG^PRPFQ G:'% OUT
"RTN","PRPFDST",7,0)
 S ZTRTN="EN1^PRPFDST",(ZTSAVE("FR"),ZTSAVE("TO"),ZTSAVE("PRPF*"),ZTSAVE("DFN"))="",ZTDESC=$P($T(D),";",3) D ^PRPFQ
"RTN","PRPFDST",8,0)
 Q
"RTN","PRPFDST",9,0)
EN1 ;DIRECT ENTRY POINT, UN QUEUED
"RTN","PRPFDST",10,0)
 I $D(ZTQUEUED) S ZTREQ="@"
"RTN","PRPFDST",11,0)
 S IOP=PRIOP,U="^"
"RTN","PRPFDST",12,0)
H I '$D(PFHI)!('$D(PFLO))!('$D(PFNORM)) S (PFHI,PFLO,PFNORM)="*0"
"RTN","PRPFDST",13,0)
 K LINE S $P(LINE,"-",(IOM+1))=""
"RTN","PRPFDST",14,0)
 S DFN(0)=^DPT(DFN,0),DFN(.31)=$S($D(^(.31)):^(.31),1:""),PAGE=1
"RTN","PRPFDST",15,0)
 S FR=FR-.1,TO=TO+.1
"RTN","PRPFDST",16,0)
 S N=FR F K=1:1 S N=$O(^PRPF(470,DFN,3,"AC",N)) D A Q:'%
"RTN","PRPFDST",17,0)
 D OUT Q
"RTN","PRPFDST",18,0)
A I N="",K=1 G W1
"RTN","PRPFDST",19,0)
 I N'<TO,K=1 G W1
"RTN","PRPFDST",20,0)
 I N'<TO S %=0 Q
"RTN","PRPFDST",21,0)
 I 'N S %=0 Q
"RTN","PRPFDST",22,0)
 S DA=0,%=1 F J=1:1 S DA=$O(^PRPF(470,DFN,3,"AC",N,DA)) Q:'DA  S ZDA=DA D B S DA=ZDA I '% K ZDA Q
"RTN","PRPFDST",23,0)
 Q
"RTN","PRPFDST",24,0)
B S %=1,X="" I $Y>(IOSL-5)!(K=1&(J=1)) R:PAGE>1&('$D(ZTSK)) !,"Press return to continue or '^' to exit:",X:$S($D(DTIME):DTIME,1:60) S:X["^" %=0 Q:'%  D HDR S X1=1
"RTN","PRPFDST",25,0)
 S PTRDA=DA,PTRDA(0)=^PRPF(470,DFN,3,DA,0),MADA=+PTRDA(0),MADA(0)=^PRPF(470.1,MADA,0) W:X1>1 ! S X1=2 W !,$P(MADA(0),"^") S X=$P(MADA(0),U,5) D DATE
"RTN","PRPFDST",26,0)
 W ?7,X,?17,$P(MADA(0),U,7),?29,$P(MADA(0),U,8) S X=$P(PTRDA(0),U,3),X=$S($P(MADA(0),"^",8)["D":X,1:-X) W $J(X,9,2),?41,$J($P(PTRDA(0),U,6),8,2)
"RTN","PRPFDST",27,0)
 S X=$P(MADA(0),U,21) D:X]"" DATE W ?54,X,?66,$P(MADA(0),U,10),?71 S X=$P(MADA(0),U,9),DD=470.1,F=8 D ^PRPFU1
"RTN","PRPFDST",28,0)
 W:% Y S DA=MADA_"^"_$P(MADA(0),"^",4,6),DA=$$SUM^PRPFSIG(DA),X=$P(MADA(0),U,15),P=$P(MADA(0),U,14)
"RTN","PRPFDST",29,0)
 W:IOM<81 ! S X=$X W "     /ES/"_$$DECODE^PRPFSIG1(MADA),?X+35,$P(MADA(0),"^",16)
"RTN","PRPFDST",30,0)
 S %=1 Q
"RTN","PRPFDST",31,0)
W1 W *7,!!,"      No transactions recorded for this Period." H 2 S %=0 Q
"RTN","PRPFDST",32,0)
HDR W @IOF W "Name: ",@PFHI,$P(DFN(0),"^"),?$X+3 S SSN=$P(DFN(0),"^",9) W @PFLO,"SSN: ",@PFHI,$E(SSN,1,3),"-",$E(SSN,4,5),"-",$E(SSN,6,9)
"RTN","PRPFDST",33,0)
 W @PFLO,"  Claim #: ",@PFHI,$P(DFN(.31),"^",3),?72,@PFLO,"PAGE: ",@PFHI,PAGE K SSN S PAGE=PAGE+1 W @PFNORM
"RTN","PRPFDST",34,0)
 W !!,"TR #   DATE",?17,"REFERENCE  D/W  AMOUNT   BALANCE     DEFERRED   P/G  CA/CK/OTH" W:IOM<81 ! W "     SIGNATURE",?$X+20,"REMARKS"
"RTN","PRPFDST",35,0)
 W !,LINE
"RTN","PRPFDST",36,0)
 Q
"RTN","PRPFDST",37,0)
DATE ;CONVERT DATE TO SLASH FORMAT
"RTN","PRPFDST",38,0)
 I +X<2000000 S X="" Q
"RTN","PRPFDST",39,0)
 S X=$E(X,4,5)_"/"_$E(X,6,7)_"/"_$E(X,2,3) Q
"RTN","PRPFIENV")
1^43
"RTN","PRPFIPRE")
1^44
"RTN","PRPFIPST")
0^48^B9554736
"RTN","PRPFIPST",1,0)
PRPFIPST  ; ;1/7/98  12:34 PM
"RTN","PRPFIPST",2,0)
 ;CTB/WASH-ISC@ALTOONA  PATIENT FUNDS XREF CONVERSION  ;1/6/98  4:33 PM
"RTN","PRPFIPST",3,0)
V ;;3.0;PATIENT FUNDS;**6,7**;JUNE 1, 1989
"RTN","PRPFIPST",4,0)
 ;LOOP THROUGH 470 GET POINTER
"RTN","PRPFIPST",5,0)
 ;DISPLAY FILE 16 AND FILE 200 VALUE
"RTN","PRPFIPST",6,0)
 ;SELECT NUMBER IN FILE 16 LINE WHICH ARE WRONG
"RTN","PRPFIPST",7,0)
 ;PROCESS CHANGES
"RTN","PRPFIPST",8,0)
 N %DT,CONVDATE,UNINSTAL,%A,%B,%,DA,Y
"RTN","PRPFIPST",9,0)
 S %DT("A")="Select Date of Installation of Patch PRPF*3*6: ",%DT="AE",DT("?")="Enter the date the Data Dictionaries for Patch PRPF*3*6 were installed. " D ^%DT
"RTN","PRPFIPST",10,0)
 QUIT:Y<0
"RTN","PRPFIPST",11,0)
 S CONVDATE=+Y
"RTN","PRPFIPST",12,0)
 S UNINSTAL=0
"RTN","PRPFIPST",13,0)
 S %=1,%A="Do you wish to prepare an UNINSTALL File",%B="An UNINSTALL file will permit you to reverse this action." D ^PRPFYN Q:%<1
"RTN","PRPFIPST",14,0)
 I %=1 S UNINSTAL=1
"RTN","PRPFIPST",15,0)
 W !! S %A="OK TO BEGIN",%=2,%B="" D ^PRPFYN
"RTN","PRPFIPST",16,0)
 I %'=1 W !!,"NO ACTION TAKEN" Q
"RTN","PRPFIPST",17,0)
 K ^TMP("PRPF UNINSTALL")
"RTN","PRPFIPST",18,0)
 S DA=0 F  S DA=$O(^PRPF(470,DA)) Q:'DA  D
"RTN","PRPFIPST",19,0)
 . N OLDDA,NEWDA,RDATE
"RTN","PRPFIPST",20,0)
 . S X=$G(^PRPF(470,DA,0))
"RTN","PRPFIPST",21,0)
 . S RDATE=+$P(X,"^",12) I RDATE>CONVDATE QUIT
"RTN","PRPFIPST",22,0)
 . S OLDDA=$P(X,"^",13)  Q:OLDDA=""
"RTN","PRPFIPST",23,0)
 . S NEWDA=$G(^DIC(16,OLDDA,"A3")) Q:NEWDA=""
"RTN","PRPFIPST",24,0)
 . S $P(^PRPF(470,DA,0),"^",13)=NEWDA I UNINSTAL=1 S ^TMP("PRPF UNINSTALL",DA)=OLDDA W "."
"RTN","PRPFIPST",25,0)
 . QUIT
"RTN","PRPFIPST",26,0)
 W !,"DONE.  " I UNINSTAL,$D(^TMP("PRPF UNINSTALL")) W "UNINSTALL OPTION AVAILABLE." W !!
"RTN","PRPFIPST",27,0)
 Q
"RTN","PRPFIPST",28,0)
UNINSTAL ;
"RTN","PRPFIPST",29,0)
 N %A,%B,%,DA
"RTN","PRPFIPST",30,0)
 I '$D(^TMP("PRPF UNINSTALL")) W !,*7,"No Uninstall file available" QUIT
"RTN","PRPFIPST",31,0)
 S %=1,%A="This option will reverse the Provider Conversion for Patient Funds Patch PRPF*3*7",%A(1)="OK TO CONTINUE",%B="" D ^PRPFYN
"RTN","PRPFIPST",32,0)
 I %'=1 W !,"NO ACTION TAKEN" QUIT
"RTN","PRPFIPST",33,0)
 S DA=0 F  S DA=$O(^TMP("PRPF UNINSTALL",DA)) Q:'DA  S $P(^PRPF(470,DA,0),"^",13)=^TMP("PRPF UNINSTALL",DA) K ^TMP("PRPF UNINSTALL",DA)
"RTN","PRPFIPST",34,0)
 W !,"UNINSTALL COMPLETED"
"RTN","PRPFIPST",35,0)
 QUIT
"RTN","PRPFIPST",36,0)
REMOVE ;
"RTN","PRPFIPST",37,0)
 N %A,%B,%
"RTN","PRPFIPST",38,0)
 I '$D(^TMP("PRPF UNINSTALL")) W !,*7,"No Uninstall file available to remove." QUIT
"RTN","PRPFIPST",39,0)
 S %=1,%A="This option will remove the ^TMP("_""""_"PRPF UNINSTALL"_""""_")) global.",%A(1)="Removal will prevent recovery of original, pre-conversion data.",%A(2)="MAKE SURE YOU HAVE VERIFIED THE CONVERSION."
"RTN","PRPFIPST",40,0)
 S %A(3)="",%A(4)="OK TO CONTINUE",%B="" D ^PRPFYN
"RTN","PRPFIPST",41,0)
 I %'=1 W !,"NO ACTION TAKEN" QUIT
"RTN","PRPFIPST",42,0)
 K ^TMP("PRPF UNINSTALL")
"RTN","PRPFIPST",43,0)
 W !!,"UNINSTALL FILE REMOVED"
"RTN","PRPFIPST",44,0)
 QUIT
"RTN","PRPFNQ")
0^49^B20910385
"RTN","PRPFNQ",1,0)
PRPFNQ ;ALTOONA/CTB-PATIENT FUNDS MULTIPLE CARD DRIVER ;12/19/97  12:03 PM
"RTN","PRPFNQ",2,0)
V ;;3.0;PATIENT FUNDS;**3,5,6,7**;JUNE 1, 1989
"RTN","PRPFNQ",3,0)
 N BDATE W *7,!,"REMEMBER, this option requires a printer with a line length of at least",!,"132 characters and a page length of at least 62 lines.",!
"RTN","PRPFNQ",4,0)
 W !!,"Enter the names(s) of cards required, one at a time.  "
"RTN","PRPFNQ",5,0)
 S LIST=1
"RTN","PRPFNQ",6,0)
 S DIC("A")="Select PATIENT NAME: "
"RTN","PRPFNQ",7,0)
A S DIC=470,DIC(0)="AEQM" D ^DIC K DIC("A") I +Y>0  D ADD S DIC("A")="Select Next PATIENT NAME: " G A
"RTN","PRPFNQ",8,0)
 K DIC
"RTN","PRPFNQ",9,0)
 I $D(LIST)'=11 W !,*7,"No cards selected, Option is Terminated! " R X:3 K IOP D OUT Q
"RTN","PRPFNQ",10,0)
 D DATE IF $D(DTOUT)!($D(DUOUT))!($D(DIROUT)) K BDATE,DTOUT,DUOUT,DIROUT D OUT Q
"RTN","PRPFNQ",11,0)
 S ZTDESC="PRINT SELECTED PATIENT FUND CARDS",ZTSAVE("DIC")="^PRPF(470," S:$D(BDATE) ZTSAVE("BDATE*")="",ZTRTN="DQ^PRPFNQ",ZTSAVE("LIST*")="" D ^PRPFQ
"RTN","PRPFNQ",12,0)
 K LIST,%Y,Y
"RTN","PRPFNQ",13,0)
 QUIT
"RTN","PRPFNQ",14,0)
ADD NEW X
"RTN","PRPFNQ",15,0)
 I $L($G(LIST(LIST))_+Y)>240 S LIST=LIST+1
"RTN","PRPFNQ",16,0)
 S LIST(LIST)=$G(LIST(LIST))_+Y_"^"
"RTN","PRPFNQ",17,0)
 QUIT
"RTN","PRPFNQ",18,0)
DQ K ^TMP("PRPFAD",$J)
"RTN","PRPFNQ",19,0)
 F I=1:1:LIST F J=1:1 S N=$P(LIST(I),"^",J) Q:'N  S ^TMP("PRPFAD",$J,N)=""
"RTN","PRPFNQ",20,0)
 S DIC="^PRPF(470,"
"RTN","PRPFNQ",21,0)
 S IOP=PRIOP
"RTN","PRPFNQ",22,0)
 S BY=".01",(FR,TO)="",BY(0)="^TMP(""PRPFAD"",$J,",FLDS="[PRPF CARD]",L=0,L(0)=1,DIOEND="K ^TMP(""PRPFAD"",$J)"
"RTN","PRPFNQ",23,0)
 D EN1^DIP D OUT
"RTN","PRPFNQ",24,0)
 Q
"RTN","PRPFNQ",25,0)
DATE ;IF PARTIAL LIST IS REQUESTED, ASK EARLIEST DATE  ELSE S DATE=01/01/1900
"RTN","PRPFNQ",26,0)
 S DIR(0)="SA^A:ALL;P:PARTIAL",DIR("A")="Partial List or All Tranactions: ",DIR("B")="ALL"
"RTN","PRPFNQ",27,0)
 S DIR("?")="You may enter (A)LL or (P)ARTIAL",DIR("?",1)="Selecting PARTIAL will allow you to print only those transactions",DIR("?",2)="starting with the date you select."
"RTN","PRPFNQ",28,0)
 D ^DIR K DIR IF $D(DTOUT)!($D(DUOUT))!($D(DIROUT)) Q
"RTN","PRPFNQ",29,0)
 S BDATE=2000101,X=BDATE D CNVD^PRPFQ S BDATE1=X I Y="A" QUIT
"RTN","PRPFNQ",30,0)
 S DIR(0)="DOA^:DT:EX",DIR("A")="Select Earliest Date to Print on Cards: ",DIR("?")="^D HELP^PRPFNQ" D ^DIR K DIR
"RTN","PRPFNQ",31,0)
 IF $D(DTOUT)!($D(DUOUT))!($D(DIROUT)) Q
"RTN","PRPFNQ",32,0)
 IF Y>0 S BDATE=+Y-1,X=+Y D CNVD^PRPFQ S BDATE1=X
"RTN","PRPFNQ",33,0)
 QUIT
"RTN","PRPFNQ",34,0)
DOIT S DIC="^PRPF(470,",L=0,(FLDS,BY)="[PRPF RANGE OF CARDS]" D EN1^DIP
"RTN","PRPFNQ",35,0)
 Q
"RTN","PRPFNQ",36,0)
ALL ;PRINT ALL CARDS
"RTN","PRPFNQ",37,0)
 S %A="This option will print a card for each ACTIVE patient, or for ALL patients,",%A(1)="   regardless of status, within the range selected."
"RTN","PRPFNQ",38,0)
 S %A(2)="Are you sure that you want to run this option now"
"RTN","PRPFNQ",39,0)
 S %B="A 'Yes' will begin the job, after you select a device.  Remember,"
"RTN","PRPFNQ",40,0)
 S %B(1)="this job will take a while to run.  Enter an '^' to terminate the option." D ^PRPFYN Q:%'=1
"RTN","PRPFNQ",41,0)
 D DATE IF $D(DTOUT)!($D(DUOUT))!($D(DIROUT)) K BDATE,BDATE1,DTOUT,DUOUT,DIROUT D OUT Q
"RTN","PRPFNQ",42,0)
 S %A="Do you wish to print only the ACTIVE cards",%B="",%=1 D ^PRPFYN Q:%<0  W !!,"I will now print a card for ",$S(%=1:"ALL ACTIVE ",1:"ALL")," cards."
"RTN","PRPFNQ",43,0)
 K DIS(0) I %=1 S DIS(0)="I $P(^PRPF(470,D0,0),U,2)=""A"""
"RTN","PRPFNQ",44,0)
 S M="PATIENT" D RNG^PRPFQ I '$D(FR)!('$D(TO)) D OUT Q
"RTN","PRPFNQ",45,0)
 S BY="[PRPF RANGE OF CARDS]",%=1,%A="OK TO CONTINUE",%B="" D ^PRPFYN Q:%'=1
"RTN","PRPFNQ",46,0)
 S DIC="^PRPF(470,",L=0,FLDS="[PRPF CARD]" D EN1^DIP
"RTN","PRPFNQ",47,0)
OUT K %,%DT,%H,%I,%W,%X,BDATE,BDATE1,DCC,DFN,DGA1,DG1,DGT,DGX,DIJ,DIOEND,DIOP,DIPT,DIR,DISH,DIYS,DP,F,FLDS,IOX,IOY,L,O,POP,MTR,PAGE,PRPFKEY,PTR,W,X,ZTSK
"RTN","PRPFNQ",48,0)
 QUIT
"RTN","PRPFNQ",49,0)
RESEARCH ;;SEARCH OF PATIENT FUNDS FOR DATES OF RESTRICTION OVER 6 MONTHS OLD
"RTN","PRPFNQ",50,0)
 ;HITS ARE STORED IN THE AK CROSSREFERENCE
"RTN","PRPFNQ",51,0)
 S ZTRTN="DQRES^PRPFNQ",ZTDESC=$P($T(RESEARCH),";",3) D ^PRPFQ,OUT Q
"RTN","PRPFNQ",52,0)
DQRES ;DQ POINT FOR RESTRICTION SEARCH
"RTN","PRPFNQ",53,0)
 I $D(ZTQUEUED) S IOP=PRIOP,ZTREQ="@"
"RTN","PRPFNQ",54,0)
 K ^TMP("PRPFAK",$J)
"RTN","PRPFNQ",55,0)
 S X="T-181",%DT="" D ^%DT
"RTN","PRPFNQ",56,0)
 S X="Please hold on, I'm searching the file now.*" D MSG^PRPFQ
"RTN","PRPFNQ",57,0)
 S DA=0 F  S DA=$O(^PRPF(470,DA)) Q:'DA  S X=$P($G(^PRPF(470,DA,0)),"^",12) I X]"",X<Y S ^TMP("PRPFAK",$J,DA)=""
"RTN","PRPFNQ",58,0)
 I $D(^TMP("PRPFAK",$J))<9 S X="No matches found today.*" D MSG^PRPFQ G OUTR
"RTN","PRPFNQ",59,0)
 S:$D(PRIOP) IOP=PRIOP S DIC="^PRPF(470,",L=0,L(0)=1,BY=".01",(FR,TO)="",BY(0)="^TMP(""PRPFAK"",$J,",FLDS="[PRPF OVERDUE PRINT",DIOEND="K ^TMP(""PRPFAK"",$J)"
"RTN","PRPFNQ",60,0)
 D EN1^DIP
"RTN","PRPFNQ",61,0)
OUTR ;
"RTN","PRPFNQ",62,0)
 K IOP,PRIOP,PFM,T5,^TMP("PRPFAK",$J) D DIKILL^PRPFQ G ZTKILL^PRPFQ
"RTN","PRPFNQ",63,0)
 Q
"RTN","PRPFNQ",64,0)
HELP W !,"If you enter a date, ALL entries on the card, before that date",!,"  will be consolidated.",! D HELP^%DTC Q
"RTN","PRPFPNT")
0^46^B4522739
"RTN","PRPFPNT",1,0)
PRPFPNT ;ALTOONA/CTB   OUTPUT DRIVER FOR "PRPF" (PATIENT FUNDS) ;7/15/97  10:00 AM
"RTN","PRPFPNT",2,0)
V ;;3.0;PATIENT FUNDS;**6,7**;JUNE 1, 1989
"RTN","PRPFPNT",3,0)
CLERK ;CLERK STATISTICS
"RTN","PRPFPNT",4,0)
 D DRNG^PRPFQ G:'% OUT D WAIT^PRPFYN S PRPFFR=FR,PRPFTO=TO,DIC="^PRPF(470.1,",L=0,BY="+PATIENT FUNDS CLERK,'DATE TRANSACTION ENTERED",FR=","_FR,TO=","_TO,FLDS="!REFERENCE,",DHD="[PRPF CLERK STAT HDR]"
"RTN","PRPFPNT",5,0)
DIP S L=0 D WAIT^PRPFYN,EN1^DIP D:'$D(XQY) ENCON^PRPFQ
"RTN","PRPFPNT",6,0)
OUT K %H,%I,DATE,DG1,DGA1,DGT,DGX,DINS,DFN,DIYS,DTOUT,DIOP,DNP,M,PRPFD,PRPFFR,PRPFTO,Q3 D DIKILL^PRPFQ G ZTKILL^PRPFQ
"RTN","PRPFPNT",7,0)
FISTRANS ;FISCAL TRANSACTION SUMMARY
"RTN","PRPFPNT",8,0)
 S DIC="^PRPF(470.1,",(BY,FLDS)="[PRPF FISCAL TRANS SUMMARY]" G DIP
"RTN","PRPFPNT",9,0)
FISACTIV ;FISCAL ACTIVITY REPORT
"RTN","PRPFPNT",10,0)
 S DIC="^PRPF(470.1,",(BY,FLDS)="[PRPF FISCAL ACTIVITY REPORT]" G DIP
"RTN","PRPFPNT",11,0)
AUDIT ;DAILY ACTIVITY (AUDIT) LISTING
"RTN","PRPFPNT",12,0)
 W ! D DRNG^PRPFQ G:'% OUT
"RTN","PRPFPNT",13,0)
 S FR=FR_",,,,",TO=TO_",,,,",DIC="^PRPF(470.1,",(BY,FLDS)="[PRPF DAILY ACTIVITY]" G DIP
"RTN","PRPFPNT",14,0)
TRANS ;LISTING OF TRANSACTIONS
"RTN","PRPFPNT",15,0)
 W ! D DRNG^PRPFQ G:'% OUT
"RTN","PRPFPNT",16,0)
 S DIC="^PRPF(470.1,",(BY,FLDS)="[PRPF DAILY TRANSACTION SUMMARY]" G DIP
"RTN","PRPFPNT",17,0)
INACTIVE ;INACTIVE ACCOUNT LIST
"RTN","PRPFPNT",18,0)
 S DIC="^PRPF(470,",(BY,FLDS)="[PRPF INACTIVE ACCOUNTS]" G DIP
"RTN","PRPFPNT",19,0)
INDIGENT ;INDIGENT PATIENT LIST
"RTN","PRPFPNT",20,0)
 S DIC="^PRPF(470,",(BY,FLDS)="[PRPF INDIGENT LIST]" G DIP
"RTN","PRPFPNT",21,0)
BALANCE ;BALANCE IN ALL ACCOUNTS
"RTN","PRPFPNT",22,0)
 S DIC="^PRPF(470,",BY="@NUMBER",FLDS="[PRPF BALANCE IN ACCOUNTS]",FR="",TO="" G DIP
"RTN","PRPFPNT",23,0)
PATLIST ;PATIENT LIST
"RTN","PRPFPNT",24,0)
 S DIC="^PRPF(470,",BY="[PRPF BY PATIENT]",FLDS="[PRPF PATIENT LIST]" G DIP
"RTN","PRPFPNT",25,0)
SUMMARY ;;PATIENT SUMMARY REPORT
"RTN","PRPFPNT",26,0)
 S DIC="^PRPF(470,",(BY,FLDS)="[PRPF PATIENT SUMMARY]" G DIP
"RTN","PRPFPUR1")
0^28^B18593117
"RTN","PRPFPUR1",1,0)
PRPFPUR1 ;CTB/ALTOONA  PURGE ONE PATIENT FUNDS RECORD ;7/15/97  9:55 AM
"RTN","PRPFPUR1",2,0)
V ;;3.0;PATIENT FUNDS;**6,7**;JUNE 1, 1989
"RTN","PRPFPUR1",3,0)
ONE(X) ;
"RTN","PRPFPUR1",4,0)
 ;PURGE PATIENT FUNDS MASTER TRANSACTION FILE AND PATIENT TRANSACTION
"RTN","PRPFPUR1",5,0)
 ;  MULTIPLE FOR ONE PATIENT THRU AND INCLUDING EDATE.
"RTN","PRPFPUR1",6,0)
 ;DFN=INTERNAL REFERENCE FOR PATIENT
"RTN","PRPFPUR1",7,0)
 ;EDATE=INTERNAL FM DATE, ALL TRANSACTIONS THRU AND INCLUDING THIS
"RTN","PRPFPUR1",8,0)
 ;  DATE WILL BE SUMMARIZED AND DELETED.
"RTN","PRPFPUR1",9,0)
 ;K ^TMP(UCIJOB,"PRPFPURGE",DFN)
"RTN","PRPFPUR1",10,0)
 N DATE,ERROR,PBAL,GBAL,TRDA,TRNODE,MADA,MANODE,BAL,REC,MREC,MRECID,UCIJOB,DFN,EDATE
"RTN","PRPFPUR1",11,0)
 S DFN=$P(X,",",1),EDATE=$P(X,",",2)
"RTN","PRPFPUR1",12,0)
 X ^%ZOSF("UCI") S UCIJOB=Y_","_$J
"RTN","PRPFPUR1",13,0)
 S (DATE,ERROR,PBAL,GBAL,BAL)=0
"RTN","PRPFPUR1",14,0)
 F  S DATE=$O(^PRPF(470,DFN,3,"AC",DATE)) Q:DATE=""!(DATE>EDATE)!(ERROR)  D
"RTN","PRPFPUR1",15,0)
 . S (TRDA,ERROR)=0
"RTN","PRPFPUR1",16,0)
 . F  S TRDA=$O(^PRPF(470,DFN,3,"AC",DATE,TRDA)) Q:TRDA=""  D  Q:ERROR
"RTN","PRPFPUR1",17,0)
 . . S ERROR=$$VERIFY(DFN,TRDA,DATE) Q:ERROR
"RTN","PRPFPUR1",18,0)
 . . S ^TMP(UCIJOB,"PRPFPURGE",DFN,TRDA)=""
"RTN","PRPFPUR1",19,0)
 . . QUIT
"RTN","PRPFPUR1",20,0)
 . QUIT
"RTN","PRPFPUR1",21,0)
 I ERROR S X="ERROR FOUND IN PROCESSING PURGE FOR "_$P(^DPT(DFN,0),"^",1)_".   <No Purge has occurred for this patient>" D MSG^PRPFU1 Q
"RTN","PRPFPUR1",22,0)
 S TRDA=0,REC=0
"RTN","PRPFPUR1",23,0)
 F  S TRDA=$O(^TMP(UCIJOB,"PRPFPURGE",DFN,TRDA)) Q:'TRDA  D
"RTN","PRPFPUR1",24,0)
 . N TRNODE,TPAMT,TGAMT,TAMT,MADA,MID
"RTN","PRPFPUR1",25,0)
 . S TRNODE=^PRPF(470,DFN,3,TRDA,0)
"RTN","PRPFPUR1",26,0)
 . S TPAMT=$P(TRNODE,"^",4),TGAMT=$P(TRNODE,"^",5),TAMT=$P(TRNODE,"^",3),MADA=$P(TRNODE,"^",1),MID=$P(^PRPF(470.1,MADA,0),"^")
"RTN","PRPFPUR1",27,0)
 . S PBAL=PBAL+TPAMT,GBAL=GBAL+TGAMT,BAL=BAL+TAMT
"RTN","PRPFPUR1",28,0)
 . S REC=TRDA,MREC=MADA,MRECID=MID
"RTN","PRPFPUR1",29,0)
 . D  ;DELETE MASTER TRANSACTION
"RTN","PRPFPUR1",30,0)
 . . N NODE
"RTN","PRPFPUR1",31,0)
 . . S NODE=$G(^PRPF(470.1,MADA,0)) Q:NODE=""
"RTN","PRPFPUR1",32,0)
 . . I $P(NODE,"^",1)]"" K ^PRPF(470.1,"B",$P(NODE,"^",1),MADA)
"RTN","PRPFPUR1",33,0)
 . . I $P(NODE,"^",5)]"" K ^PRPF(470.1,"AD",$P(NODE,"^",4),MADA)
"RTN","PRPFPUR1",34,0)
 . . I $P(NODE,"^",6)]"" K ^PRPF(470.1,"AC",$P(NODE,"^",6),MADA)
"RTN","PRPFPUR1",35,0)
 . . L +^PRPF(470.1,0):10 I $T S $P(^(0),"^",4)=$P(^PRPF(470.1,0),"^",4)-1 L -^PRPF(470.1,0)
"RTN","PRPFPUR1",36,0)
 . . K ^PRPF(470.1,MADA)
"RTN","PRPFPUR1",37,0)
 . . QUIT  ;DELETE MASTER TRANSACTION
"RTN","PRPFPUR1",38,0)
 . D  ;DELETE PATIENT TRANSACTION
"RTN","PRPFPUR1",39,0)
 . . N NODE
"RTN","PRPFPUR1",40,0)
 . . S NODE=$G(^PRPF(470,DFN,3,TRDA,0)) Q:NODE=""
"RTN","PRPFPUR1",41,0)
 . . I $P(NODE,"^",1)]"" K ^PRPF(470,DFN,3,"B",$P(NODE,"^",1),TRDA)
"RTN","PRPFPUR1",42,0)
 . . I $P(NODE,"^",2)]"" K ^PRPF(470,DFN,3,"AC",$P(NODE,"^",2),TRDA)
"RTN","PRPFPUR1",43,0)
 . . L +^PRPF(470,DFN,3,0):10 I $T S $P(^(0),"^",4)=$P(^PRPF(470,DFN,3,0),"^",4)-1 L -^PRPF(470,DFN,3,0)
"RTN","PRPFPUR1",44,0)
 . . K ^PRPF(470,DFN,3,TRDA)
"RTN","PRPFPUR1",45,0)
 . . QUIT  ;DELETE PATIENT TRANSACTION
"RTN","PRPFPUR1",46,0)
 . QUIT
"RTN","PRPFPUR1",47,0)
 ;ENTER BALANCE CARRIED FORWARD TRANSACTION
"RTN","PRPFPUR1",48,0)
 Q:REC=0
"RTN","PRPFPUR1",49,0)
 L +^PRPF
"RTN","PRPFPUR1",50,0)
 S $P(^PRPF(470.1,0),"^",4)=$P(^PRPF(470.1,0),"^",4)+1
"RTN","PRPFPUR1",51,0)
 S $P(^PRPF(470,DFN,3,0),"^",4)=$P(^PRPF(470,DFN,3,0),"^",4)+1
"RTN","PRPFPUR1",52,0)
 S ^PRPF(470,DFN,3,REC,0)=MREC_"^"_EDATE_"^"_BAL_"^"_PBAL_"^"_GBAL_"^",^PRPF(470,DFN,3,"B",MREC,REC)="",^PRPF(470,DFN,3,"AC",EDATE,REC)=""
"RTN","PRPFPUR1",53,0)
 S X=$O(^PRPF(470.2,"B","BALCARFWD",0))
"RTN","PRPFPUR1",54,0)
 S MREC(0)=MRECID_"^"_DFN_"^"_REC_"^"_BAL_"^"_EDATE_"^"_EDATE_"^BALCARFWD^D^3^B^"_X_"^"_PBAL_"^"_GBAL_"^"_DUZ_"^^Balance Carried Forward - Purge"
"RTN","PRPFPUR1",55,0)
 S MREC(1)=$P(^VA(200,DUZ,0),"^")
"RTN","PRPFPUR1",56,0)
 S STRING=$$SUM^PRPFSIG(MREC_"^"_$P(MREC(0),"^",4,6))
"RTN","PRPFPUR1",57,0)
 S $P(MREC(0),"^",15)=$$ENCODE^PRPFSIG(MREC(1),DUZ,STRING)
"RTN","PRPFPUR1",58,0)
 S ^PRPF(470.1,MREC,0)=MREC(0),^(1)=MREC(1)
"RTN","PRPFPUR1",59,0)
 S ^PRPF(470.1,"B",MRECID,MREC)="",^PRPF(470.1,"AD",EDATE,MREC)="",^PRPF(470.1,"AC",EDATE,MREC)=""
"RTN","PRPFPUR1",60,0)
 L -^PRPF
"RTN","PRPFPUR1",61,0)
 K ^TMP(UCIJOB,"PRPFPURGE")
"RTN","PRPFPUR1",62,0)
 QUIT
"RTN","PRPFPUR1",63,0)
 ;
"RTN","PRPFPUR1",64,0)
VERIFY(DFN,TRDA,DATE) ;VERIFY INTEGRITY OF INDIVIDUAL PATIENT TRANSACTION
"RTN","PRPFPUR1",65,0)
 ;   AND ASSOCIATED MASTER TRANSACTION.
"RTN","PRPFPUR1",66,0)
 N TRNODE,ERROR,TDATE,MDATE,MAMT,MPAMT,MGAMT,TGAMT,TAMT,TPAMT,TBAL,MADA,MNODE
"RTN","PRPFPUR1",67,0)
 S TRNODE=$G(^PRPF(470,DFN,3,TRDA,0)) I TRNODE="" S ERROR=1 D ERROR Q
"RTN","PRPFPUR1",68,0)
 S TDATE=$P(TRNODE,"^",2),TAMT=$P(TRNODE,"^",3),TPAMT=$P(TRNODE,"^",4),TGAMT=$P(TRNODE,"^",5),TBAL=$P(TRNODE,"^",6),MADA=+TRNODE
"RTN","PRPFPUR1",69,0)
 S MNODE=$G(^PRPF(470.1,+MADA,0)) I MNODE="" S ERROR=3 D ERROR Q 1
"RTN","PRPFPUR1",70,0)
 S MDATE=$P(MNODE,"^",5),MAMT=$P(MNODE,"^",4),MPAMT=$P(MNODE,"^",12),MGAMT=$P(MNODE,"^",13)
"RTN","PRPFPUR1",71,0)
 I TDATE=""!(TDATE'=$P(DATE,".")) S ERROR=1 D ERROR Q 1
"RTN","PRPFPUR1",72,0)
 I (+TAMT'=+MAMT)!(+TPAMT'=+MPAMT)!(+TGAMT'=+MGAMT) S ERROR=4 D ERROR Q 1
"RTN","PRPFPUR1",73,0)
 I MDATE'=TDATE S ERROR=2 D ERROR Q 1
"RTN","PRPFPUR1",74,0)
 Q 0
"RTN","PRPFPUR1",75,0)
ERROR S X=$P($T(ERROR+ERROR),";",3,99)_" "_TRDA D MSG^PRPFU1 W ! Q
"RTN","PRPFPUR1",76,0)
 ;;INVALID 'AC' CROSS REFERENCE IN FILE 470, FIELD 30
"RTN","PRPFPUR1",77,0)
 ;;DATE IN TRANSACTION MULTIPLE OF 470 DOES NOT MATCH CROSS REFERENCE
"RTN","PRPFPUR1",78,0)
 ;;PATIENT TRANSACTION MULTIPLE POINTS TO INVALID MASTER RECORD
"RTN","PRPFPUR1",79,0)
 ;;BALANCES ARE OUT OF DATE BETWEEN MASTER TRANSACTION FILE AND PATIENT TRANSACTION MULTIPLE
"RTN","PRPFSCV")
1^34
"RTN","PRPFSCV1")
1^35
"RTN","PRPFSCV2")
1^36
"RTN","PRPFSCV3")
1^37
"RTN","PRPFSIG")
0^38^B2698729
"RTN","PRPFSIG",1,0)
PRPFSIG ;WISC@ALTOONA/CTB/TEN-ROUTINE TO ENTER OR CHANGE ELECTRONIC SIGNATURE CODE ;7/15/97  9:56 AM
"RTN","PRPFSIG",2,0)
V ;;3.0;PATIENT FUNDS;**6,7**;JUNE 1, 1989
"RTN","PRPFSIG",3,0)
ENCODE(X,X1,X2) D EN^XUSHSHP Q X
"RTN","PRPFSIG",4,0)
DECODE(X,X1,X2) D DE^XUSHSHP Q X
"RTN","PRPFSIG",5,0)
HASH(X) D HASH^XUSHSHP Q X
"RTN","PRPFSIG",6,0)
SUM(X) ;CREATE CHECKSUM VALUE FOR STRING
"RTN","PRPFSIG",7,0)
 N I,Y
"RTN","PRPFSIG",8,0)
 S Y=0 F I=1:1:$L(X) S Y=$A(X,I)*I+Y
"RTN","PRPFSIG",9,0)
 Q Y
"RTN","PRPFSIG",10,0)
ESIG(USERNUM,MESSAGE) ;interogate user for electronic signature code
"RTN","PRPFSIG",11,0)
 ;1= valid code entered
"RTN","PRPFSIG",12,0)
 ;0= invalid code entered
"RTN","PRPFSIG",13,0)
 ;-1= user up arrowed out
"RTN","PRPFSIG",14,0)
 ;-2= signature read time out
"RTN","PRPFSIG",15,0)
 ;-3= no signature on file
"RTN","PRPFSIG",16,0)
 NEW X,SIGCODE,ZZI,OUT
"RTN","PRPFSIG",17,0)
 S SIGCODE=$P($G(^VA(200,USERNUM,20)),"^",4)
"RTN","PRPFSIG",18,0)
 I SIGCODE="" W !,"You have no signature code on file.  Please contact your IRM staff for assistance.",*7,! S MESSAGE=-3 QUIT
"RTN","PRPFSIG",19,0)
 F ZZI=1:1:3 D  Q:OUT]""
"RTN","PRPFSIG",20,0)
 . K OUT
"RTN","PRPFSIG",21,0)
 . W !,"Enter ELECTRONIC SIGNATURE CODE: "
"RTN","PRPFSIG",22,0)
 . X ^%ZOSF("EOFF") R X:60 X ^%ZOSF("EON")
"RTN","PRPFSIG",23,0)
 . I '$T S OUT=-2 QUIT
"RTN","PRPFSIG",24,0)
 . I $E(X)="^" S OUT=-1 QUIT
"RTN","PRPFSIG",25,0)
 . S X=$TR(X,"abcdefghijklmnopqrstuvwxyz","ABCDEFGHIJKLMNOPQRSTUVWXYZ")
"RTN","PRPFSIG",26,0)
 . I $$HASH(X)=SIGCODE W ?60,"Thank you." S OUT=1 QUIT
"RTN","PRPFSIG",27,0)
 . W !,"Sorry, but that's not your correct electronic signature code."
"RTN","PRPFSIG",28,0)
 . S OUT=""
"RTN","PRPFSIG",29,0)
 . QUIT
"RTN","PRPFSIG",30,0)
 S MESSAGE=+$G(OUT) QUIT
"RTN","PRPFSIG",31,0)
 ;
"RTN","PRPFSIG",32,0)
NOW() ;Extrinsic function to return current time
"RTN","PRPFSIG",33,0)
 N %,%I,%H,X
"RTN","PRPFSIG",34,0)
 D NOW^%DTC
"RTN","PRPFSIG",35,0)
 QUIT %
"RTN","PRPFSIG2")
1^40
"RTN","PRPFSUM")
1^42
"VER")
8.0^21.0
**END**
**END**
