Released OR*3*162 SEQ #157
Extracted from mail message
**KIDS**:OR*3.0*162^

**INSTALL NAME**
OR*3.0*162
"BLD",4032,0)
OR*3.0*162^ORDER ENTRY/RESULTS REPORTING^0^3021205^y
"BLD",4032,4,0)
^9.64PA^^
"BLD",4032,"INID")
^
"BLD",4032,"INIT")

"BLD",4032,"KRN",0)
^9.67PA^8989.52^19
"BLD",4032,"KRN",.4,0)
.4
"BLD",4032,"KRN",.401,0)
.401
"BLD",4032,"KRN",.402,0)
.402
"BLD",4032,"KRN",.403,0)
.403
"BLD",4032,"KRN",.5,0)
.5
"BLD",4032,"KRN",.84,0)
.84
"BLD",4032,"KRN",3.6,0)
3.6
"BLD",4032,"KRN",3.8,0)
3.8
"BLD",4032,"KRN",9.2,0)
9.2
"BLD",4032,"KRN",9.8,0)
9.8
"BLD",4032,"KRN",9.8,"NM",0)
^9.68A^3^3
"BLD",4032,"KRN",9.8,"NM",1,0)
ORKCHK4^^0^B26163402
"BLD",4032,"KRN",9.8,"NM",2,0)
ORKCHK6^^0^B26704586
"BLD",4032,"KRN",9.8,"NM",3,0)
ORQQAL^^0^B21002381
"BLD",4032,"KRN",9.8,"NM","B","ORKCHK4",1)

"BLD",4032,"KRN",9.8,"NM","B","ORKCHK6",2)

"BLD",4032,"KRN",9.8,"NM","B","ORQQAL",3)

"BLD",4032,"KRN",19,0)
19
"BLD",4032,"KRN",19,"NM",0)
^9.68A^^
"BLD",4032,"KRN",19.1,0)
19.1
"BLD",4032,"KRN",101,0)
101
"BLD",4032,"KRN",409.61,0)
409.61
"BLD",4032,"KRN",771,0)
771
"BLD",4032,"KRN",870,0)
870
"BLD",4032,"KRN",8989.51,0)
8989.51
"BLD",4032,"KRN",8989.52,0)
8989.52
"BLD",4032,"KRN",8994,0)
8994
"BLD",4032,"KRN","B",.4,.4)

"BLD",4032,"KRN","B",.401,.401)

"BLD",4032,"KRN","B",.402,.402)

"BLD",4032,"KRN","B",.403,.403)

"BLD",4032,"KRN","B",.5,.5)

"BLD",4032,"KRN","B",.84,.84)

"BLD",4032,"KRN","B",3.6,3.6)

"BLD",4032,"KRN","B",3.8,3.8)

"BLD",4032,"KRN","B",9.2,9.2)

"BLD",4032,"KRN","B",9.8,9.8)

"BLD",4032,"KRN","B",19,19)

"BLD",4032,"KRN","B",19.1,19.1)

"BLD",4032,"KRN","B",101,101)

"BLD",4032,"KRN","B",409.61,409.61)

"BLD",4032,"KRN","B",771,771)

"BLD",4032,"KRN","B",870,870)

"BLD",4032,"KRN","B",8989.51,8989.51)

"BLD",4032,"KRN","B",8989.52,8989.52)

"BLD",4032,"KRN","B",8994,8994)

"BLD",4032,"QUES",0)
^9.62^^
"BLD",4032,"REQB",0)
^9.611^1^1
"BLD",4032,"REQB",1,0)
OR*3.0*123^2
"BLD",4032,"REQB","B","OR*3.0*123",1)

"MBREQ")
0
"PKG",110,-1)
1^1
"PKG",110,0)
ORDER ENTRY/RESULTS REPORTING^OR^Order Entry/Results Reporting
"PKG",110,20,0)
^9.402P^^
"PKG",110,22,0)
^9.49I^1^1
"PKG",110,22,1,0)
3.0^2971217
"PKG",110,22,1,"PAH",1,0)
162^3021205
"QUES","XPF1",0)
Y
"QUES","XPF1","??")
^D REP^XPDH
"QUES","XPF1","A")
Shall I write over your |FLAG| File
"QUES","XPF1","B")
YES
"QUES","XPF1","M")
D XPF1^XPDIQ
"QUES","XPF2",0)
Y
"QUES","XPF2","??")
^D DTA^XPDH
"QUES","XPF2","A")
Want my data |FLAG| yours
"QUES","XPF2","B")
YES
"QUES","XPF2","M")
D XPF2^XPDIQ
"QUES","XPI1",0)
YO
"QUES","XPI1","??")
^D INHIBIT^XPDH
"QUES","XPI1","A")
Want KIDS to INHIBIT LOGONs during the install
"QUES","XPI1","B")
YES
"QUES","XPI1","M")
D XPI1^XPDIQ
"QUES","XPM1",0)
PO^VA(200,:EM
"QUES","XPM1","??")
^D MG^XPDH
"QUES","XPM1","A")
Enter the Coordinator for Mail Group '|FLAG|'
"QUES","XPM1","B")

"QUES","XPM1","M")
D XPM1^XPDIQ
"QUES","XPO1",0)
Y
"QUES","XPO1","??")
^D MENU^XPDH
"QUES","XPO1","A")
Want KIDS to Rebuild Menu Trees Upon Completion of Install
"QUES","XPO1","B")
YES
"QUES","XPO1","M")
D XPO1^XPDIQ
"QUES","XPZ1",0)
Y
"QUES","XPZ1","??")
^D OPT^XPDH
"QUES","XPZ1","A")
Want to DISABLE Scheduled Options, Menu Options, and Protocols
"QUES","XPZ1","B")
YES
"QUES","XPZ1","M")
D XPZ1^XPDIQ
"QUES","XPZ2",0)
Y
"QUES","XPZ2","??")
^D RTN^XPDH
"QUES","XPZ2","A")
Want to MOVE routines to other CPUs
"QUES","XPZ2","B")
NO
"QUES","XPZ2","M")
D XPZ2^XPDIQ
"RTN")
3
"RTN","ORKCHK4")
0^1^B26163402
"RTN","ORKCHK4",1,0)
ORKCHK4 ; slc/CLA - Support routine called by ORKCHK to do SELECT mode order checks ;3/6/97  9:35
"RTN","ORKCHK4",2,0)
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**6,32,74,87,94,123,162**;Dec 17, 1997
"RTN","ORKCHK4",3,0)
 Q
"RTN","ORKCHK4",4,0)
 ;
"RTN","ORKCHK4",5,0)
EN(ORKS,ORKDFN,ORKA,ORENT,ORKTMODE) ;perform order checking for orderable item selection
"RTN","ORKCHK4",6,0)
 Q:$$GET^XPAR("DIV^SYS^PKG","ORK SYSTEM ENABLE/DISABLE",1,"I")="D"
"RTN","ORKCHK4",7,0)
 ;
"RTN","ORKCHK4",8,0)
 N OI,ORKDG,HL7,ODT,ORNUM,HL7NPTR,HL7NTXT,HL7NCOD,HL7LPTR,HL7LTXT,HL7LCOD
"RTN","ORKCHK4",9,0)
 N ORKMSG,ORKT,ORKTXT
"RTN","ORKCHK4",10,0)
 ;
"RTN","ORKCHK4",11,0)
 S OI=$P(ORKA,"|"),ORKDG=$P(ORKA,"|",2)
"RTN","ORKCHK4",12,0)
 S HL7=$P(ORKA,"|",3),ODT=$P(ORKA,"|",4),ORNUM=$P(ORKA,"|",5)
"RTN","ORKCHK4",13,0)
 S HL7NPTR=$P(HL7,U),HL7NTXT=$P(HL7,U,2),HL7NCOD=$P(HL7,U,3)
"RTN","ORKCHK4",14,0)
 S HL7LPTR=$P(HL7,U,4),HL7LTXT=$P(HL7,U,5),HL7LCOD=$P(HL7,U,6)
"RTN","ORKCHK4",15,0)
 ;
"RTN","ORKCHK4",16,0)
 I $E(ORKDG,1,2)="PS" D PHARM
"RTN","ORKCHK4",17,0)
 I $E(ORKDG,1,2)'="PS" D MLM^ORKCHK2(.ORKS,ORKDFN,ORKA,ORENT,"SELECT")
"RTN","ORKCHK4",18,0)
 Q
"RTN","ORKCHK4",19,0)
 ;
"RTN","ORKCHK4",20,0)
PHARM ;process pharmacy order checks:
"RTN","ORKCHK4",21,0)
 N ORPSPKG,ORPSA,ORKDD
"RTN","ORKCHK4",22,0)
 N ORCRITN,ORCRITF,ORCRITD,ORSIGN,ORSIGF,ORSIGD,ORDUPN,ORDUPF,ORDUPD,ORDUPCN,ORDUPCF,ORDUPCD
"RTN","ORKCHK4",23,0)
 ;
"RTN","ORKCHK4",24,0)
 D PARAMS("CRITICAL DRUG INTERACTION",.ORCRITN,.ORCRITF,.ORCRITD)
"RTN","ORKCHK4",25,0)
 D PARAMS("SIGNIFICANT DRUG INTERACTION",.ORSIGN,.ORSIGF,.ORSIGD)
"RTN","ORKCHK4",26,0)
 D PARAMS("DUPLICATE DRUG ORDER",.ORDUPN,.ORDUPF,.ORDUPD)
"RTN","ORKCHK4",27,0)
 D PARAMS("DUPLICATE DRUG CLASS ORDER",.ORDUPCN,.ORDUPCF,.ORDUPCD)
"RTN","ORKCHK4",28,0)
 ;
"RTN","ORKCHK4",29,0)
 ;dispense drug selected:
"RTN","ORKCHK4",30,0)
 I $L($G(HL7LPTR)),($G(HL7LCOD)="99PSD") D
"RTN","ORKCHK4",31,0)
 .D RXOCS
"RTN","ORKCHK4",32,0)
 .D MLM^ORKCHK2(.ORKS,ORKDFN,ORKA,ORENT,"SELECT")
"RTN","ORKCHK4",33,0)
 ;
"RTN","ORKCHK4",34,0)
 ;dispense drug NOT selected, split OI into dispense drugs:
"RTN","ORKCHK4",35,0)
 I '$L($G(HL7LPTR)) D
"RTN","ORKCHK4",36,0)
 .S ORPSPKG=$E(ORKDG,3)
"RTN","ORKCHK4",37,0)
 .I "IO"[ORPSPKG D OI2DD(.ORPSA,OI,ORPSPKG)
"RTN","ORKCHK4",38,0)
 .S ORKDD=0 F  S ORKDD=$O(ORPSA(ORKDD)) Q:'ORKDD  D
"RTN","ORKCHK4",39,0)
 ..S HL7LTXT=ORPSA(ORKDD)
"RTN","ORKCHK4",40,0)
 ..S HL7NPTR=$P(ORKDD,";",2)
"RTN","ORKCHK4",41,0)
 ..S HL7LPTR=+ORKDD
"RTN","ORKCHK4",42,0)
 ..S HL7LCOD="99PSD",HL7NCOD="99NDF"
"RTN","ORKCHK4",43,0)
 ..S $P(HL7,U)=HL7NPTR,$P(HL7,U,3)=HL7NCOD
"RTN","ORKCHK4",44,0)
 ..S $P(HL7,U,4)=HL7LPTR,$P(HL7,U,5)=HL7LTXT,$P(HL7,U,6)=HL7LCOD
"RTN","ORKCHK4",45,0)
 ..S $P(ORKA,"|",3)=HL7  ;set these for MLM OCX call
"RTN","ORKCHK4",46,0)
 ..D RXOCS
"RTN","ORKCHK4",47,0)
 ..D MLM^ORKCHK2(.ORKS,ORKDFN,ORKA,ORENT,"SELECT")
"RTN","ORKCHK4",48,0)
 Q
"RTN","ORKCHK4",49,0)
 ;
"RTN","ORKCHK4",50,0)
RXOCS ;drug-drug interaction, duplicate drug order, duplicate drug class
"RTN","ORKCHK4",51,0)
 Q:ORCRITF_ORSIGF_ORDUPF_ORDUPCF'["E"  ;quit if none are "E"nabled
"RTN","ORKCHK4",52,0)
 N ORKRX,ORPSNUM
"RTN","ORKCHK4",53,0)
 D CHECK^ORKPS(.ORKRX,ORKDFN,HL7LPTR,OI,ORKDG)
"RTN","ORKCHK4",54,0)
 N CHK,XX S CHK=0,XX=""
"RTN","ORKCHK4",55,0)
 F  S CHK=$O(ORKRX(CHK)) Q:'CHK  D
"RTN","ORKCHK4",56,0)
 .S XX=ORKRX(CHK)
"RTN","ORKCHK4",57,0)
 .;
"RTN","ORKCHK4",58,0)
 .;critical drug interaction:
"RTN","ORKCHK4",59,0)
 .I $P(XX,U)="DI",$P(XX,U,5)="CRITICAL" D  ;,(ORKTMODE'="ALL") D
"RTN","ORKCHK4",60,0)
 ..Q:ORCRITF="D"
"RTN","ORKCHK4",61,0)
 ..S ORPSNUM=$P(XX,U,8)  ;get the associated order number
"RTN","ORKCHK4",62,0)
 ..I $L(ORPSNUM),$G(^OR(100,+ORPSNUM,0)) S ORKT=$$FULLTEXT^ORQOR1(+ORPSNUM),ORKTXT=$P(ORKT,U)_" ["_$P(ORKT,U,2)_"]"
"RTN","ORKCHK4",63,0)
 ..E  S ORKTXT=$P(XX,U,3)
"RTN","ORKCHK4",64,0)
 ..S ORKMSG=$P(XX,U,5)_" drug-drug interaction: "_$P(XX,U,6)_" & "_$P(XX,U,7)
"RTN","ORKCHK4",65,0)
 ..S ORKS("ORK",ORCRITD_","_$G(ORNUM)_","_ORPSNUM_","_$E(ORKMSG,1,225))=ORNUM_U_ORCRITN_U_ORCRITD_U_ORKMSG_" ("_ORKTXT_")"_U_$G(ORPSNUM)
"RTN","ORKCHK4",66,0)
 .;
"RTN","ORKCHK4",67,0)
 .;significant drug interaction:
"RTN","ORKCHK4",68,0)
 .I $P(XX,U)="DI",$P(XX,U,5)="SIGNIFICANT" D  ;,(ORKTMODE'="ALL") D
"RTN","ORKCHK4",69,0)
 ..Q:ORSIGF="D"
"RTN","ORKCHK4",70,0)
 ..S ORPSNUM=$P(XX,U,8)  ;get the associated order number
"RTN","ORKCHK4",71,0)
 ..I $L(ORPSNUM),$G(^OR(100,+ORPSNUM,0)) S ORKT=$$FULLTEXT^ORQOR1(+ORPSNUM),ORKTXT=$P(ORKT,U)_" ["_$P(ORKT,U,2)_"]"
"RTN","ORKCHK4",72,0)
 ..E  S ORKTXT=$P(XX,U,3)
"RTN","ORKCHK4",73,0)
 ..S ORKMSG=$P(XX,U,5)_" drug-drug interaction: "_$P(XX,U,6)_" & "_$P(XX,U,7)
"RTN","ORKCHK4",74,0)
 ..S ORKS("ORK",ORSIGD_","_$G(ORNUM)_","_ORPSNUM_","_$E(ORKMSG,1,225))=ORNUM_U_ORSIGN_U_ORSIGD_U_ORKMSG_" ("_ORKTXT_")"_U_$G(ORPSNUM)
"RTN","ORKCHK4",75,0)
 .;
"RTN","ORKCHK4",76,0)
 .;duplicate drug:
"RTN","ORKCHK4",77,0)
 .I $P(XX,U)="DD" D  ;,(ORKTMODE'="ALL") D
"RTN","ORKCHK4",78,0)
 ..Q:ORDUPF="D"
"RTN","ORKCHK4",79,0)
 ..S ORPSNUM=$P(XX,U,4)  ;get the associated order number
"RTN","ORKCHK4",80,0)
 ..I $L(ORPSNUM),$G(^OR(100,+ORPSNUM,0)) S ORKT=$$FULLTEXT^ORQOR1(+ORPSNUM),ORKTXT=$P(ORKT,U)_" ["_$P(ORKT,U,2)_"]"
"RTN","ORKCHK4",81,0)
 ..E  S ORKTXT=$P(XX,U,3)
"RTN","ORKCHK4",82,0)
 ..S ORKMSG="Duplicate order: "_ORKTXT
"RTN","ORKCHK4",83,0)
 ..S ORKS("ORK",ORDUPD_","_$G(ORNUM)_","_ORPSNUM_",Duplicate order: "_$P(XX,U,3))=ORNUM_U_ORDUPN_U_ORDUPD_U_ORKMSG_U_$G(ORPSNUM)
"RTN","ORKCHK4",84,0)
 .;
"RTN","ORKCHK4",85,0)
 .;duplicate class:
"RTN","ORKCHK4",86,0)
 .I $P(XX,U)="DC" D  ;,(ORKTMODE'="ALL") D
"RTN","ORKCHK4",87,0)
 ..Q:ORDUPCF="D"
"RTN","ORKCHK4",88,0)
 ..S ORPSNUM=$P(XX,U,6)  ;get the associated order number
"RTN","ORKCHK4",89,0)
 ..I $L(ORPSNUM),$G(^OR(100,+ORPSNUM,0)) S ORKT=$$FULLTEXT^ORQOR1(+ORPSNUM),ORKTXT=$P(ORKT,U)_" ["_$P(ORKT,U,2)_"]"
"RTN","ORKCHK4",90,0)
 ..E  S ORKTXT=$P(XX,U,5)
"RTN","ORKCHK4",91,0)
 ..S ORKMSG="Duplicate drug class order: "_$P(XX,U,3)
"RTN","ORKCHK4",92,0)
 ..S ORKS("ORK",ORDUPCD_","_$G(ORNUM)_","_ORPSNUM_","_$E(ORKMSG,1,225))=ORNUM_U_ORDUPCN_U_ORDUPCD_U_ORKMSG_" ("_ORKTXT_")"_U_$G(ORPSNUM)
"RTN","ORKCHK4",93,0)
 Q
"RTN","ORKCHK4",94,0)
 ;
"RTN","ORKCHK4",95,0)
OI2DD(ORPSA,OROI,ORPSPKG)       ;rtn dispense drugs for a PS OI
"RTN","ORKCHK4",96,0)
 N PSOI
"RTN","ORKCHK4",97,0)
 Q:'$D(^ORD(101.43,OROI,0))
"RTN","ORKCHK4",98,0)
 S PSOI=$P($P(^ORD(101.43,OROI,0),U,2),";")
"RTN","ORKCHK4",99,0)
 Q:+$G(PSOI)<1
"RTN","ORKCHK4",100,0)
 D DRG^PSSUTIL1(.ORPSA,PSOI,ORPSPKG)
"RTN","ORKCHK4",101,0)
 Q
"RTN","ORKCHK4",102,0)
 ;
"RTN","ORKCHK4",103,0)
PARAMS(ORKNAME,ORKNUM,ORKFLAG,ORKDNGR) ; get parameter values for an order chk
"RTN","ORKCHK4",104,0)
 S ORKNUM=0,ORKNUM=$O(^ORD(100.8,"B",ORKNAME,ORKNUM))
"RTN","ORKCHK4",105,0)
 S ORKFLAG=$$GET^XPAR(ORENT,"ORK PROCESSING FLAG",ORKNUM,"I")
"RTN","ORKCHK4",106,0)
 S ORKDNGR=$$GET^XPAR("DIV^SYS^PKG","ORK CLINICAL DANGER LEVEL",ORKNUM,"I")
"RTN","ORKCHK4",107,0)
 Q
"RTN","ORKCHK6")
0^2^B26704586
"RTN","ORKCHK6",1,0)
ORKCHK6 ; slc/CLA - Support routine called by ORKCHK to do SESSION mode order checks ;3/6/97  9:35
"RTN","ORKCHK6",2,0)
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**6,32,74,87,94,123,162**;Dec 17, 1997
"RTN","ORKCHK6",3,0)
 Q
"RTN","ORKCHK6",4,0)
 ;
"RTN","ORKCHK6",5,0)
EN(ORKS,ORKDFN,ORKA,ORENT,ORKTMODE) ;perform order checking for entire ordering session
"RTN","ORKCHK6",6,0)
 Q:$$GET^XPAR("DIV^SYS^PKG","ORK SYSTEM ENABLE/DISABLE",1,"I")="D"
"RTN","ORKCHK6",7,0)
 ;
"RTN","ORKCHK6",8,0)
 N OI,ORKDG,HL7,ODT,ORNUM,HL7NPTR,HL7NTXT,HL7NCOD,HL7LPTR,HL7LTXT,HL7LCOD
"RTN","ORKCHK6",9,0)
 N ORKMSG,ORKDGI,ORKT,ORKTXT,ORKPDATA
"RTN","ORKCHK6",10,0)
 ;
"RTN","ORKCHK6",11,0)
 S OI=$P(ORKA,"|"),ORKDG=$P(ORKA,"|",2),HL7=$P(ORKA,"|",3)
"RTN","ORKCHK6",12,0)
 S ODT=$P(ORKA,"|",4),ORNUM=$P(ORKA,"|",5),ORKPDATA=$P(ORKA,"|",6)
"RTN","ORKCHK6",13,0)
 S HL7NPTR=$P(HL7,U),HL7NTXT=$P(HL7,U,2),HL7NCOD=$P(HL7,U,3)
"RTN","ORKCHK6",14,0)
 S HL7LPTR=$P(HL7,U,4),HL7LTXT=$P(HL7,U,5),HL7LCOD=$P(HL7,U,6)
"RTN","ORKCHK6",15,0)
 ;
"RTN","ORKCHK6",16,0)
 S:ORKDG="PSJ" ORKDG="PSI"
"RTN","ORKCHK6",17,0)
 I $E(ORKDG,1,2)="PS" D PHARM
"RTN","ORKCHK6",18,0)
 I $E(ORKDG,1,2)'="PS" D MLM^ORKCHK2(.ORKS,ORKDFN,ORKA,ORENT,"SESSION")
"RTN","ORKCHK6",19,0)
 Q
"RTN","ORKCHK6",20,0)
 ;
"RTN","ORKCHK6",21,0)
PHARM ;process pharmacy order checks:
"RTN","ORKCHK6",22,0)
 N ORPSPKG,ORPSA,ORKDD
"RTN","ORKCHK6",23,0)
 N ORCRITN,ORCRITF,ORCRITD,ORSIGN,ORSIGF,ORSIGD,ORDUPN,ORDUPF,ORDUPD,ORDUPC,ORDUPCF,ORDUPCD
"RTN","ORKCHK6",24,0)
 ;
"RTN","ORKCHK6",25,0)
 D PARAMS("CRITICAL DRUG INTERACTION",.ORCRITN,.ORCRITF,.ORCRITD)
"RTN","ORKCHK6",26,0)
 D PARAMS("SIGNIFICANT DRUG INTERACTION",.ORSIGN,.ORSIGF,.ORSIGD)
"RTN","ORKCHK6",27,0)
 D PARAMS("DUPLICATE DRUG ORDER",.ORDUPN,.ORDUPF,.ORDUPD)
"RTN","ORKCHK6",28,0)
 D PARAMS("DUPLICATE DRUG CLASS ORDER",.ORDUPCN,.ORDUPCF,.ORDUPCD)
"RTN","ORKCHK6",29,0)
 ;
"RTN","ORKCHK6",30,0)
 ;dispense drug selected:
"RTN","ORKCHK6",31,0)
 I $L($G(HL7LPTR)),($G(HL7LCOD)="99PSD") D
"RTN","ORKCHK6",32,0)
 .D RXOCS
"RTN","ORKCHK6",33,0)
 .D MLM^ORKCHK2(.ORKS,ORKDFN,ORKA,ORENT,"SESSION")
"RTN","ORKCHK6",34,0)
 ;
"RTN","ORKCHK6",35,0)
 ;dispense drug NOT selected, split OI into dispense drugs:
"RTN","ORKCHK6",36,0)
 I '$L($G(HL7LPTR)) D
"RTN","ORKCHK6",37,0)
 .S ORPSPKG=$E(ORKDG,3)
"RTN","ORKCHK6",38,0)
 .I "IO"[ORPSPKG D OI2DD(.ORPSA,OI,ORPSPKG)
"RTN","ORKCHK6",39,0)
 .S ORKDD=0 F  S ORKDD=$O(ORPSA(ORKDD)) Q:'ORKDD  D
"RTN","ORKCHK6",40,0)
 ..S HL7LTXT=ORPSA(ORKDD)
"RTN","ORKCHK6",41,0)
 ..S HL7NPTR=$P(ORKDD,";",2)
"RTN","ORKCHK6",42,0)
 ..S HL7LPTR=+ORKDD
"RTN","ORKCHK6",43,0)
 ..S HL7LCOD="99PSD",HL7NCOD="99NDF"
"RTN","ORKCHK6",44,0)
 ..S $P(HL7,U)=HL7NPTR,$P(HL7,U,3)=HL7NCOD
"RTN","ORKCHK6",45,0)
 ..S $P(HL7,U,4)=HL7LPTR,$P(HL7,U,5)=HL7LTXT,$P(HL7,U,6)=HL7LCOD
"RTN","ORKCHK6",46,0)
 ..S $P(ORKA,"|",3)=HL7  ;set these for MLM OCX call
"RTN","ORKCHK6",47,0)
 ..D RXOCS
"RTN","ORKCHK6",48,0)
 ..D MLM^ORKCHK2(.ORKS,ORKDFN,ORKA,ORENT,"SESSION")
"RTN","ORKCHK6",49,0)
 Q
"RTN","ORKCHK6",50,0)
 ;
"RTN","ORKCHK6",51,0)
RXOCS ;drug-drug interaction, duplicate drug order, duplicate drug class
"RTN","ORKCHK6",52,0)
 Q:ORCRITF_ORSIGF_ORDUPF_ORDUPCF'["E"  ;quit if none are "E"nabled
"RTN","ORKCHK6",53,0)
 N ORKRX,ORPSNUM
"RTN","ORKCHK6",54,0)
 I $L($G(HL7LPTR)),($G(HL7LCOD)="99PSD") D
"RTN","ORKCHK6",55,0)
 .D CHKSESS^ORKPS(.ORKRX,ORKDFN,HL7LPTR,OI,ORKPDATA,ORKDG)
"RTN","ORKCHK6",56,0)
 .N CHK,XX S CHK=0,XX=""
"RTN","ORKCHK6",57,0)
 .F  S CHK=$O(ORKRX(CHK)) Q:'CHK  D
"RTN","ORKCHK6",58,0)
 ..S XX=ORKRX(CHK)
"RTN","ORKCHK6",59,0)
 ..;
"RTN","ORKCHK6",60,0)
 ..;critical drug interaction:
"RTN","ORKCHK6",61,0)
 ..I $P(XX,U)="DI",$P(XX,U,5)="CRITICAL" D
"RTN","ORKCHK6",62,0)
 ...Q:ORCRITF="D"
"RTN","ORKCHK6",63,0)
 ...S ORPSNUM=$P(XX,U,8)  ;get the associated order number
"RTN","ORKCHK6",64,0)
 ...I $L(ORPSNUM),$G(^OR(100,+ORPSNUM,0)) S ORKT=$$FULLTEXT^ORQOR1(+ORPSNUM),ORKTXT=$P(ORKT,U)_" ["_$P(ORKT,U,2)_"]"
"RTN","ORKCHK6",65,0)
 ...E  S ORKTXT=$P(XX,U,3)
"RTN","ORKCHK6",66,0)
 ...S ORKMSG=$P(XX,U,5)_" drug-drug interaction: "_$P(XX,U,6)_" & "_$P(XX,U,7)
"RTN","ORKCHK6",67,0)
 ...S ORKS("ORK",ORCRITD_","_$G(ORNUM)_","_ORPSNUM_","_$E(ORKMSG,1,225))=ORNUM_U_ORCRITN_U_ORCRITD_U_ORKMSG_" ("_ORKTXT_")"_U_$G(ORPSNUM)
"RTN","ORKCHK6",68,0)
 ..;
"RTN","ORKCHK6",69,0)
 ..;significant drug interaction:
"RTN","ORKCHK6",70,0)
 ..I $P(XX,U)="DI",$P(XX,U,5)="SIGNIFICANT" D
"RTN","ORKCHK6",71,0)
 ...Q:ORSIGF="D"
"RTN","ORKCHK6",72,0)
 ...S ORPSNUM=$P(XX,U,8)  ;get the associated order number
"RTN","ORKCHK6",73,0)
 ...I $L(ORPSNUM),$G(^OR(100,+ORPSNUM,0)) S ORKT=$$FULLTEXT^ORQOR1(+ORPSNUM),ORKTXT=$P(ORKT,U)_" ["_$P(ORKT,U,2)_"]"
"RTN","ORKCHK6",74,0)
 ...E  S ORKTXT=$P(XX,U,3)
"RTN","ORKCHK6",75,0)
 ...S ORKMSG=$P(XX,U,5)_" drug-drug interaction: "_$P(XX,U,6)_" & "_$P(XX,U,7)
"RTN","ORKCHK6",76,0)
 ...S ORKS("ORK",ORSIGD_","_$G(ORNUM)_","_ORPSNUM_","_$E(ORKMSG,1,225))=ORNUM_U_ORSIGN_U_ORSIGD_U_ORKMSG_" ("_ORKTXT_")"_U_$G(ORPSNUM)
"RTN","ORKCHK6",77,0)
 ..;
"RTN","ORKCHK6",78,0)
 ..;duplicate drug:
"RTN","ORKCHK6",79,0)
 ..I $P(XX,U)="DD" D
"RTN","ORKCHK6",80,0)
 ...Q:ORDUPF="D"
"RTN","ORKCHK6",81,0)
 ...S ORPSNUM=$P(XX,U,4)  ;get the associated order number
"RTN","ORKCHK6",82,0)
 ...I $L(ORPSNUM),$G(^OR(100,+ORPSNUM,0)) S ORKT=$$FULLTEXT^ORQOR1(+ORPSNUM),ORKTXT=$P(ORKT,U)_" ["_$P(ORKT,U,2)_"]"
"RTN","ORKCHK6",83,0)
 ...E  S ORKTXT=$P(XX,U,3)
"RTN","ORKCHK6",84,0)
 ...S ORKMSG="Duplicate order: "_ORKTXT
"RTN","ORKCHK6",85,0)
 ...S ORKS("ORK",ORDUPD_","_$G(ORNUM)_","_ORPSNUM_",Duplicate order: "_$P(XX,U,3))=ORNUM_U_ORDUPN_U_ORDUPD_U_ORKMSG_U_$G(ORPSNUM)
"RTN","ORKCHK6",86,0)
 ..;
"RTN","ORKCHK6",87,0)
 ..;duplicate class:
"RTN","ORKCHK6",88,0)
 ..I $P(XX,U)="DC" D
"RTN","ORKCHK6",89,0)
 ...Q:ORDUPCF="D"
"RTN","ORKCHK6",90,0)
 ...S ORPSNUM=$P(XX,U,6)  ;get the associated order number
"RTN","ORKCHK6",91,0)
 ...I $L(ORPSNUM),$G(^OR(100,+ORPSNUM,0)) S ORKT=$$FULLTEXT^ORQOR1(+ORPSNUM),ORKTXT=$P(ORKT,U)_" ["_$P(ORKT,U,2)_"]"
"RTN","ORKCHK6",92,0)
 ...E  S ORKTXT=$P(XX,U,5)
"RTN","ORKCHK6",93,0)
 ...S ORKMSG="Duplicate drug class order: "_$P(XX,U,3)
"RTN","ORKCHK6",94,0)
 ...S ORKS("ORK",ORDUPCD_","_$G(ORNUM)_","_ORPSNUM_","_$E(ORKMSG,1,225))=ORNUM_U_ORDUPCN_U_ORDUPCD_U_ORKMSG_" ("_ORKTXT_")"_U_$G(ORPSNUM)
"RTN","ORKCHK6",95,0)
 Q
"RTN","ORKCHK6",96,0)
 ;
"RTN","ORKCHK6",97,0)
OI2DD(ORPSA,OROI,ORPSPKG)       ;rtn dispense drugs for a PS OI
"RTN","ORKCHK6",98,0)
 N PSOI
"RTN","ORKCHK6",99,0)
 Q:'$D(^ORD(101.43,OROI,0))
"RTN","ORKCHK6",100,0)
 S PSOI=$P($P(^ORD(101.43,OROI,0),U,2),";")
"RTN","ORKCHK6",101,0)
 Q:+$G(PSOI)<1
"RTN","ORKCHK6",102,0)
 D DRG^PSSUTIL1(.ORPSA,PSOI,ORPSPKG)
"RTN","ORKCHK6",103,0)
 Q
"RTN","ORKCHK6",104,0)
 ;
"RTN","ORKCHK6",105,0)
PARAMS(ORKNAME,ORKNUM,ORKFLAG,ORKDNGR) ; get parameter values for an order chk
"RTN","ORKCHK6",106,0)
 S ORKNUM=0,ORKNUM=$O(^ORD(100.8,"B",ORKNAME,ORKNUM))
"RTN","ORKCHK6",107,0)
 S ORKFLAG=$$GET^XPAR(ORENT,"ORK PROCESSING FLAG",ORKNUM,"I")
"RTN","ORKCHK6",108,0)
 S ORKDNGR=$$GET^XPAR("DIV^SYS^PKG","ORK CLINICAL DANGER LEVEL",ORKNUM,"I")
"RTN","ORKCHK6",109,0)
 Q
"RTN","ORQQAL")
0^3^B21002381
"RTN","ORQQAL",1,0)
ORQQAL ; slc/CLA,JFR - Functions which return patient allergy data ;9/18/97 [ 04/02/97  3:43 PM ]
"RTN","ORQQAL",2,0)
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**9,85,162**;Dec 17, 1997
"RTN","ORQQAL",3,0)
LIST(ORAY,ORPT) ; RETURN PATIENT'S ALLERGY/ADVERSE REACTION INFO:
"RTN","ORQQAL",4,0)
 ; null:no allergy assessment, 0:no known allergies, 1:pt has allergies
"RTN","ORQQAL",5,0)
 ; if 1 also get: allergen/reactant^reaction/symptom^severity^allergy ien
"RTN","ORQQAL",6,0)
 N I,J,K
"RTN","ORQQAL",7,0)
 S I=1,J=0,K=0
"RTN","ORQQAL",8,0)
 D EN1^GMRAOR1(ORPT,"GMRARXN")
"RTN","ORQQAL",9,0)
 I $G(GMRARXN)="" S ORAY(I)="^No Allergy Assessment"
"RTN","ORQQAL",10,0)
 I $G(GMRARXN)=0 S ORAY(I)="^No Known Allergies"
"RTN","ORQQAL",11,0)
 I $G(GMRARXN)=1 F  S J=$O(GMRARXN(J)) Q:J=""  S ORAY(I)=$P(GMRARXN(J),"^",3)_"^"_$P(GMRARXN(J),"^")_"^"_$P(GMRARXN(J),"^",2) D SIGNS S I=I+1
"RTN","ORQQAL",12,0)
 S:'$D(ORAY(1)) ORAY(1)="^No allergies found."
"RTN","ORQQAL",13,0)
 K GMRARXN
"RTN","ORQQAL",14,0)
 Q
"RTN","ORQQAL",15,0)
SIGNS S K=0,N=0 F  S K=$O(GMRARXN(J,"S",K)) Q:K'>0  D
"RTN","ORQQAL",16,0)
 .I N=0 S ORAY(I)=ORAY(I)_"^"_$P(GMRARXN(J,"S",K),";")
"RTN","ORQQAL",17,0)
 .E  S ORAY(I)=ORAY(I)_";"_$P(GMRARXN(J,"S",K),";")
"RTN","ORQQAL",18,0)
 .S N=N+1
"RTN","ORQQAL",19,0)
 Q
"RTN","ORQQAL",20,0)
LRPT(ORAY,ORPT) ; RETURN PT'S ALLERGY/ADVERSE REACTION INFO IN REPORT FORMAT:
"RTN","ORQQAL",21,0)
 ; null:no allergy assessment, 0:no known allergies, 1:pt has allergies
"RTN","ORQQAL",22,0)
 ; if 1 also get: allergen/reactant^reaction/symptom^severity^allergy ien
"RTN","ORQQAL",23,0)
 N I,J,K,SEVER,CR
"RTN","ORQQAL",24,0)
 S CR=$CHAR(13)
"RTN","ORQQAL",25,0)
 S I=1,J=0,K=0,SEVER=""
"RTN","ORQQAL",26,0)
 D EN1^GMRAOR1(ORPT,"GMRARXN")
"RTN","ORQQAL",27,0)
 I $G(GMRARXN)="" S ORAY(I)="No Allergy Assessment"
"RTN","ORQQAL",28,0)
 I $G(GMRARXN)=0 S ORAY(I)="No Known Allergies"
"RTN","ORQQAL",29,0)
 I $G(GMRARXN)=1 F  S J=$O(GMRARXN(J)) Q:J=""  D
"RTN","ORQQAL",30,0)
 .S SEVER=$P(GMRARXN(J),U,2)
"RTN","ORQQAL",31,0)
 .S ORAY(I)=$P(GMRARXN(J),U)_"     [Severity: "_$S($L($G(SEVER)):SEVER,1:"UNKNOWN")_"]",I=I+1
"RTN","ORQQAL",32,0)
 .S K=0,N=0 F  S K=$O(GMRARXN(J,"S",K)) Q:K'>0  D
"RTN","ORQQAL",33,0)
 ..I N=0 S ORAY(I)="    Signs/symptoms: "_$P(GMRARXN(J,"S",K),";")
"RTN","ORQQAL",34,0)
 ..E     S ORAY(I)="                    "_$P(GMRARXN(J,"S",K),";")
"RTN","ORQQAL",35,0)
 ..S N=N+1,I=I+1
"RTN","ORQQAL",36,0)
 .S ORAY(I)=" ",I=I+1
"RTN","ORQQAL",37,0)
 S:'$D(ORAY(1)) ORAY(1)="No allergies found."
"RTN","ORQQAL",38,0)
 K GMRARXN
"RTN","ORQQAL",39,0)
 Q
"RTN","ORQQAL",40,0)
RXN(ORAY,ORPT,SRC,NDF,PSDRUG) ; RETURN TRUE OR FALSE IF PATIENT IS ALLERGIC TO AGENT
"RTN","ORQQAL",41,0)
 ; SRC: ALLERGEN SOURCE (CM=CONTRAST MEDIA, DR=DRUG)
"RTN","ORQQAL",42,0)
 ; NDF: IF SRC=DR, NDF=Nat'l Drug File ien ELSE NDF=""
"RTN","ORQQAL",43,0)
 ; PSDRUG:IF SRC=DR, PSDRUG=(local) Drug file ien ELSE PSDRUG=""
"RTN","ORQQAL",44,0)
 S ORAY=$$ORCHK^GMRAOR(ORPT,SRC,NDF)
"RTN","ORQQAL",45,0)
 I SRC="DR",ORAY=1 D  ;drug ingredient allergy found
"RTN","ORQQAL",46,0)
 .S I=1,J=0 F  S J=$O(GMRAING(J)) Q:J=""  D
"RTN","ORQQAL",47,0)
 ..I I=1 S ORAY=ORAY_U_GMRAING(J)
"RTN","ORQQAL",48,0)
 ..E  S ORAY=ORAY_";"_GMRAING(J)
"RTN","ORQQAL",49,0)
 ..S I=I+1
"RTN","ORQQAL",50,0)
 I SRC="DR",ORAY=2 D  ;drug class allergy found
"RTN","ORQQAL",51,0)
 .S CL="",I=1,J=0 F  S J=$O(GMRADRCL(J)) Q:J=""  D
"RTN","ORQQAL",52,0)
 ..I I=1 S ORAY=ORAY_U_$P(GMRADRCL(J),U,2)
"RTN","ORQQAL",53,0)
 ..E  S CL=$P(GMRADRCL(J),U,2) I ORAY'[CL S ORAY=ORAY_";"_CL
"RTN","ORQQAL",54,0)
 ..S I=I+1
"RTN","ORQQAL",55,0)
 I SRC="DR",(+$G(ORAY)<1) D MEDCLASS(.ORAY,ORPT,PSDRUG)
"RTN","ORQQAL",56,0)
 K I,J,GMRADRCL,GMRAING,CL
"RTN","ORQQAL",57,0)
 Q
"RTN","ORQQAL",58,0)
MEDCLASS(ORAY,DFN,PSDRUG) ;check for allergens with medications in same VA drug class
"RTN","ORQQAL",59,0)
 N ORVACLS,ALLR,K,CL
"RTN","ORQQAL",60,0)
 Q:+$G(PSDRUG)<1
"RTN","ORQQAL",61,0)
 S ORVACLS=$P(^PSDRUG(PSDRUG,0),U,2)
"RTN","ORQQAL",62,0)
 Q:$L(ORVACLS)<4
"RTN","ORQQAL",63,0)
 S CL=$S($E(ORVACLS,1,4)="CN10":5,1:4) ;look at 5 chars if ANALGESICS
"RTN","ORQQAL",64,0)
 S GMRA="0^0^001",ALLR=""
"RTN","ORQQAL",65,0)
 D EN1^GMRADPT F  S ALLR=$O(GMRAL(ALLR)) Q:'ALLR!(+ORAY=2)  D
"RTN","ORQQAL",66,0)
 .K GMRACT D EN1^GMRAOR2(ALLR,"GMRACT") I $D(GMRACT("V")) D
"RTN","ORQQAL",67,0)
 ..S K=0 F  S K=$O(GMRACT("V",K)) Q:K'>0!(+ORAY=2)  D
"RTN","ORQQAL",68,0)
 ...I $E($P(GMRACT("V",K),U),1,CL)=$E(ORVACLS,1,CL) D
"RTN","ORQQAL",69,0)
 ....S ORAY="2"_U_$P(GMRACT("V",K),U,2)
"RTN","ORQQAL",70,0)
 K GMRA,GMRAL,GMRACT
"RTN","ORQQAL",71,0)
 Q
"RTN","ORQQAL",72,0)
DETAIL(ORAY,DFN,ALLR,ID) ; RETURN DETAILED ALLERGY INFO FOR SPECIFIED ALLERGIC REACTION:
"RTN","ORQQAL",73,0)
 D EN1^GMRAOR2(ALLR,"GMRACT")
"RTN","ORQQAL",74,0)
 N CR,OX,OH S CR=$CHAR(13),I=1
"RTN","ORQQAL",75,0)
 S ORAY(I)="    Causative agent: "_$P(GMRACT,U),I=I+1
"RTN","ORQQAL",76,0)
 S ORAY(I)=" ",I=I+1
"RTN","ORQQAL",77,0)
 I $D(GMRACT("S",1)) D SYMP
"RTN","ORQQAL",78,0)
 I $D(GMRACT("V",1)) D CLAS
"RTN","ORQQAL",79,0)
 S ORAY(I)="         Originated: "_$P(GMRACT,U,2)_"  "_$P(GMRACT,U,3),I=I+1
"RTN","ORQQAL",80,0)
 I $D(GMRACT("O",1)) D OBS
"RTN","ORQQAL",81,0)
 S ORAY(I)="           Verified: "_$S($P(GMRACT,U,4)="VERIFIED":"Yes",1:"No"),I=I+1
"RTN","ORQQAL",82,0)
 S ORAY(I)="Observed/Historical: "_$S($P(GMRACT,U,5)="OBSERVED":"Observed",$P(GMRACT,U,5)="HISTORICAL":"Historical",1:""),I=I+1
"RTN","ORQQAL",83,0)
 I $D(GMRACT("C",1)) D COM
"RTN","ORQQAL",84,0)
 K GMRACT
"RTN","ORQQAL",85,0)
 Q
"RTN","ORQQAL",86,0)
SYMP S K=0,N=0 F  S K=$O(GMRACT("S",K)) Q:K'>0  D
"RTN","ORQQAL",87,0)
 .I N=0 S ORAY(I)="     Signs/symptoms: "_GMRACT("S",K),I=I+1
"RTN","ORQQAL",88,0)
 .E  S ORAY(I)="                     "_GMRACT("S",K),I=I+1
"RTN","ORQQAL",89,0)
 .S N=N+1
"RTN","ORQQAL",90,0)
 S ORAY(I)=" ",I=I+1
"RTN","ORQQAL",91,0)
 K N,K
"RTN","ORQQAL",92,0)
 Q
"RTN","ORQQAL",93,0)
CLAS S K=0,N=0 F  S K=$O(GMRACT("V",K)) Q:K'>0  D
"RTN","ORQQAL",94,0)
 .I N=0 S ORAY(I)="       Drug Classes: "_$P(GMRACT("V",K),U,2),I=I+1
"RTN","ORQQAL",95,0)
 .E  S ORAY(I)="                     "_$P(GMRACT("V",K),U,2),I=I+1
"RTN","ORQQAL",96,0)
 .S N=N+1
"RTN","ORQQAL",97,0)
 S ORAY(I)=" ",I=I+1
"RTN","ORQQAL",98,0)
 K N,K
"RTN","ORQQAL",99,0)
 Q
"RTN","ORQQAL",100,0)
OBS S K=0,N=0 F  S K=$O(GMRACT("O",K)) Q:K'>0  D
"RTN","ORQQAL",101,0)
 .I N=0 D
"RTN","ORQQAL",102,0)
 ..S Y=$P(GMRACT("O",K),U) D DD^%DT
"RTN","ORQQAL",103,0)
 ..S ORAY(I)=" Obs dates/severity: "_Y_" "_$P(GMRACT("O",K),U,2),I=I+1
"RTN","ORQQAL",104,0)
 .E  D
"RTN","ORQQAL",105,0)
 ..S Y=$P(GMRACT("O",K),U) D DD^%DT
"RTN","ORQQAL",106,0)
 ..S ORAY(I)="                     "_Y_" "_$P(GMRACT("O",K),U,2),I=I+1
"RTN","ORQQAL",107,0)
 .S N=N+1
"RTN","ORQQAL",108,0)
 S ORAY(I)=" ",I=I+1
"RTN","ORQQAL",109,0)
 K N,K,Y
"RTN","ORQQAL",110,0)
 Q
"RTN","ORQQAL",111,0)
COM S K=0,N=0,ORAY(I)=" ",I=I+1
"RTN","ORQQAL",112,0)
 F  S K=$O(GMRACT("C",K)) Q:K'>0  D
"RTN","ORQQAL",113,0)
 .I N=0 S ORAY(I)="Comments:",I=I+1
"RTN","ORQQAL",114,0)
 .S Y=$P(GMRACT("C",K),U) D DD^%DT
"RTN","ORQQAL",115,0)
 .S ORAY(I)="   "_Y_" by "_$P(GMRACT("C",K),U,2),I=I+1
"RTN","ORQQAL",116,0)
 .I $D(GMRACT("C",K,1,0)) S L=0 F  S L=$O(GMRACT("C",K,L)) Q:L'>0  D
"RTN","ORQQAL",117,0)
 ..S ORAY(I)=GMRACT("C",K,L,0),I=I+1
"RTN","ORQQAL",118,0)
 .S N=N+1
"RTN","ORQQAL",119,0)
 S ORAY(I)=" ",I=I+1
"RTN","ORQQAL",120,0)
 K N,K,L,Y
"RTN","ORQQAL",121,0)
 Q
"VER")
8.0^22.0
**END**
**END**
