Released OR*3*143 SEQ #143
Extracted from mail message
**KIDS**:OR*3.0*143^

**INSTALL NAME**
OR*3.0*143
"BLD",3606,0)
OR*3.0*143^ORDER ENTRY/RESULTS REPORTING^0^3020916^y
"BLD",3606,4,0)
^9.64PA^^
"BLD",3606,"KRN",0)
^9.67PA^8989.52^19
"BLD",3606,"KRN",.4,0)
.4
"BLD",3606,"KRN",.401,0)
.401
"BLD",3606,"KRN",.402,0)
.402
"BLD",3606,"KRN",.403,0)
.403
"BLD",3606,"KRN",.5,0)
.5
"BLD",3606,"KRN",.84,0)
.84
"BLD",3606,"KRN",3.6,0)
3.6
"BLD",3606,"KRN",3.8,0)
3.8
"BLD",3606,"KRN",9.2,0)
9.2
"BLD",3606,"KRN",9.8,0)
9.8
"BLD",3606,"KRN",9.8,"NM",0)
^9.68A^8^7
"BLD",3606,"KRN",9.8,"NM",2,0)
OCXOPURG^^0^B9246604
"BLD",3606,"KRN",9.8,"NM",3,0)
ORQQLR^^0^B19085376
"BLD",3606,"KRN",9.8,"NM",4,0)
ORQQLR1^^0^B15053517
"BLD",3606,"KRN",9.8,"NM",5,0)
OCXCACHE^^0^B3193778
"BLD",3606,"KRN",9.8,"NM",6,0)
OCXSENDA^^0^B19170708
"BLD",3606,"KRN",9.8,"NM",7,0)
OCXSENDB^^0^B44498394
"BLD",3606,"KRN",9.8,"NM",8,0)
ORB3TIM1^^0^B22870825
"BLD",3606,"KRN",9.8,"NM","B","OCXCACHE",5)

"BLD",3606,"KRN",9.8,"NM","B","OCXOPURG",2)

"BLD",3606,"KRN",9.8,"NM","B","OCXSENDA",6)

"BLD",3606,"KRN",9.8,"NM","B","OCXSENDB",7)

"BLD",3606,"KRN",9.8,"NM","B","ORB3TIM1",8)

"BLD",3606,"KRN",9.8,"NM","B","ORQQLR",3)

"BLD",3606,"KRN",9.8,"NM","B","ORQQLR1",4)

"BLD",3606,"KRN",19,0)
19
"BLD",3606,"KRN",19.1,0)
19.1
"BLD",3606,"KRN",101,0)
101
"BLD",3606,"KRN",409.61,0)
409.61
"BLD",3606,"KRN",771,0)
771
"BLD",3606,"KRN",870,0)
870
"BLD",3606,"KRN",8989.51,0)
8989.51
"BLD",3606,"KRN",8989.52,0)
8989.52
"BLD",3606,"KRN",8994,0)
8994
"BLD",3606,"KRN","B",.4,.4)

"BLD",3606,"KRN","B",.401,.401)

"BLD",3606,"KRN","B",.402,.402)

"BLD",3606,"KRN","B",.403,.403)

"BLD",3606,"KRN","B",.5,.5)

"BLD",3606,"KRN","B",.84,.84)

"BLD",3606,"KRN","B",3.6,3.6)

"BLD",3606,"KRN","B",3.8,3.8)

"BLD",3606,"KRN","B",9.2,9.2)

"BLD",3606,"KRN","B",9.8,9.8)

"BLD",3606,"KRN","B",19,19)

"BLD",3606,"KRN","B",19.1,19.1)

"BLD",3606,"KRN","B",101,101)

"BLD",3606,"KRN","B",409.61,409.61)

"BLD",3606,"KRN","B",771,771)

"BLD",3606,"KRN","B",870,870)

"BLD",3606,"KRN","B",8989.51,8989.51)

"BLD",3606,"KRN","B",8989.52,8989.52)

"BLD",3606,"KRN","B",8994,8994)

"BLD",3606,"QUES",0)
^9.62^^
"BLD",3606,"REQB",0)
^9.611^1^1
"BLD",3606,"REQB",1,0)
OR*3.0*105^2
"BLD",3606,"REQB","B","OR*3.0*105",1)

"MBREQ")
0
"PKG",110,-1)
1^1
"PKG",110,0)
ORDER ENTRY/RESULTS REPORTING^OR^Order Entry/Results Reporting
"PKG",110,20,0)
^9.402P^^
"PKG",110,22,0)
^9.49I^1^1
"PKG",110,22,1,0)
3.0^2971217
"PKG",110,22,1,"PAH",1,0)
143^3020916
"QUES","XPF1",0)
Y
"QUES","XPF1","??")
^D REP^XPDH
"QUES","XPF1","A")
Shall I write over your |FLAG| File
"QUES","XPF1","B")
YES
"QUES","XPF1","M")
D XPF1^XPDIQ
"QUES","XPF2",0)
Y
"QUES","XPF2","??")
^D DTA^XPDH
"QUES","XPF2","A")
Want my data |FLAG| yours
"QUES","XPF2","B")
YES
"QUES","XPF2","M")
D XPF2^XPDIQ
"QUES","XPI1",0)
YO
"QUES","XPI1","??")
^D INHIBIT^XPDH
"QUES","XPI1","A")
Want KIDS to INHIBIT LOGONs during the install
"QUES","XPI1","B")
YES
"QUES","XPI1","M")
D XPI1^XPDIQ
"QUES","XPM1",0)
PO^VA(200,:EM
"QUES","XPM1","??")
^D MG^XPDH
"QUES","XPM1","A")
Enter the Coordinator for Mail Group '|FLAG|'
"QUES","XPM1","B")

"QUES","XPM1","M")
D XPM1^XPDIQ
"QUES","XPO1",0)
Y
"QUES","XPO1","??")
^D MENU^XPDH
"QUES","XPO1","A")
Want KIDS to Rebuild Menu Trees Upon Completion of Install
"QUES","XPO1","B")
YES
"QUES","XPO1","M")
D XPO1^XPDIQ
"QUES","XPZ1",0)
Y
"QUES","XPZ1","??")
^D OPT^XPDH
"QUES","XPZ1","A")
Want to DISABLE Scheduled Options, Menu Options, and Protocols
"QUES","XPZ1","B")
YES
"QUES","XPZ1","M")
D XPZ1^XPDIQ
"QUES","XPZ2",0)
Y
"QUES","XPZ2","??")
^D RTN^XPDH
"QUES","XPZ2","A")
Want to MOVE routines to other CPUs
"QUES","XPZ2","B")
NO
"QUES","XPZ2","M")
D XPZ2^XPDIQ
"RTN")
7
"RTN","OCXCACHE")
0^5^B3193778
"RTN","OCXCACHE",1,0)
OCXCACHE ;SLC/RJS,CLA - ORDER CHECK CACHE CONTROLLER ;4/16/02  16:28
"RTN","OCXCACHE",2,0)
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**143**;Dec 17,1997
"RTN","OCXCACHE",3,0)
 ;;  ;;ORDER CHECK EXPERT version 1.01 released OCT 29,1998
"RTN","OCXCACHE",4,0)
 ;
"RTN","OCXCACHE",5,0)
GETDATA(OCXRES,OCXCALL,OCXDFN,OCXTIME) ;
"RTN","OCXCACHE",6,0)
 ;
"RTN","OCXCACHE",7,0)
 ;
"RTN","OCXCACHE",8,0)
 N OCXDATA K OCXRES S OCXRES=""
"RTN","OCXCACHE",9,0)
 ;
"RTN","OCXCACHE",10,0)
 Q:'$L($G(OCXCALL)) 1
"RTN","OCXCACHE",11,0)
 Q:'$L($G(OCXDFN)) 2
"RTN","OCXCACHE",12,0)
 S ^XTMP("OCXCACHE",0)=$$FMADD^XLFDT($$NOW^XLFDT,1,"","","")_"^"_$$NOW^XLFDT
"RTN","OCXCACHE",13,0)
 S:'$G(OCXTIME) OCXTIME=300
"RTN","OCXCACHE",14,0)
 ;
"RTN","OCXCACHE",15,0)
 K:($G(^XTMP("OCXCACHE",OCXDFN,OCXCALL,"TIME"))<$$NOW) ^XTMP("OCXCACHE",OCXDFN,OCXCALL)
"RTN","OCXCACHE",16,0)
 ;
"RTN","OCXCACHE",17,0)
 I '$D(^XTMP("OCXCACHE",OCXDFN,OCXCALL)) D
"RTN","OCXCACHE",18,0)
 .I OCXCALL["$$" X "S OCXDATA="_OCXCALL
"RTN","OCXCACHE",19,0)
 .E  S OCXDATA="" D @OCXCALL
"RTN","OCXCACHE",20,0)
 .M ^XTMP("OCXCACHE",OCXDFN,OCXCALL,"DATA")=OCXDATA
"RTN","OCXCACHE",21,0)
 .S ^XTMP("OCXCACHE",OCXDFN,OCXCALL,"TIME")=$$NOW+OCXTIME
"RTN","OCXCACHE",22,0)
 ;
"RTN","OCXCACHE",23,0)
 M:$D(^XTMP("OCXCACHE",OCXDFN,OCXCALL,"DATA")) OCXRES=^XTMP("OCXCACHE",OCXDFN,OCXCALL,"DATA")
"RTN","OCXCACHE",24,0)
 Q:'$D(^XTMP("OCXCACHE",OCXDFN,OCXCALL,"DATA")) 3
"RTN","OCXCACHE",25,0)
 ;
"RTN","OCXCACHE",26,0)
 Q 0
"RTN","OCXCACHE",27,0)
 ;
"RTN","OCXCACHE",28,0)
NOW() Q $P($H,",",2)+($H*86400)
"RTN","OCXCACHE",29,0)
 ;
"RTN","OCXCACHE",30,0)
PURGE ;   Purge OCX namespaced entries in ^XTMP (Cache) that have expired.
"RTN","OCXCACHE",31,0)
 ;
"RTN","OCXCACHE",32,0)
 N OCXE0,OCXE1,OCXS
"RTN","OCXCACHE",33,0)
 ;
"RTN","OCXCACHE",34,0)
 ;S OCXS="OCX" F  S OCXS=$O(^XTMP(OCXS)) Q:'$L(OCXS)  Q:'($E(OCXS,1,3)="OCX")  D
"RTN","OCXCACHE",35,0)
 S OCXS="OCXCACHE" D
"RTN","OCXCACHE",36,0)
 .S OCXE0=0 F  S OCXE0=$O(^XTMP(OCXS,OCXE0)) Q:'$L(OCXE0)  D
"RTN","OCXCACHE",37,0)
 ..S OCXE1="" F  S OCXE1=$O(^XTMP(OCXS,OCXE0,OCXE1)) Q:'$L(OCXE1)  D
"RTN","OCXCACHE",38,0)
 ...K:($G(^XTMP(OCXS,OCXE0,OCXE1,"TIME"))<$$NOW) ^XTMP(OCXS,OCXE0,OCXE1)
"RTN","OCXCACHE",39,0)
 ;
"RTN","OCXCACHE",40,0)
 Q
"RTN","OCXCACHE",41,0)
 ;
"RTN","OCXCACHE",42,0)
 ;Sample External Call
"RTN","OCXCACHE",43,0)
 ;
"RTN","OCXCACHE",44,0)
 ;       S ORZ=$$LOCL^ORQQLR1(ORDFN,TEST,SPECIMEN)
"RTN","OCXCACHE",45,0)
 ;
"RTN","OCXCACHE",46,0)
 ;               Changes to:
"RTN","OCXCACHE",47,0)
 ;
"RTN","OCXCACHE",48,0)
 ;S TEMP=$$GETDATA^OCXCACHE(.ORZ,"$$LOCL^ORQQLR1("_ORDFN_","_TEST_","_SPECIMEN_")",ORDFN,300)
"RTN","OCXCACHE",49,0)
 ;
"RTN","OCXCACHE",50,0)
 ;$$GETDATA^OCXCACHE(RESULTS,EXTERNAL CALL,PATIENT ID,TIMEOUT) ----> returns either a 1, 2, 3, or 0
"RTN","OCXCACHE",51,0)
 ;                                                                     0 -> No Errors
"RTN","OCXCACHE",52,0)
 ;                                                                     1 -> Missing External Call.
"RTN","OCXCACHE",53,0)
 ;                                                                     2 -> Missing Patient ID.
"RTN","OCXCACHE",54,0)
 ;                                                                     3 -> Cache Data Missing.
"RTN","OCXCACHE",55,0)
 ;***Results = Data Value Returned,
"RTN","OCXCACHE",56,0)
 ;            Either Scalar or Array.
"RTN","OCXCACHE",57,0)
 ;
"RTN","OCXCACHE",58,0)
 ;***External Call = Routine call in a 'resolved parameter' format to
"RTN","OCXCACHE",59,0)
 ;                  reduce the chances of cache returning the wrong values.
"RTN","OCXCACHE",60,0)
 ;
"RTN","OCXCACHE",61,0)
 ;        If ORDFN=1234 and TEST=110 and SPECIMEN=119
"RTN","OCXCACHE",62,0)
 ;
"RTN","OCXCACHE",63,0)
 ;            Then        If this parameter is: "$$LOCL^ORQQLR1("_ORDFN_","_TEST_","_SPECIMEN_")"
"RTN","OCXCACHE",64,0)
 ;  then the value will be stored in subscript: "$$LOCL^ORQQLR1(1234,110,119)"
"RTN","OCXCACHE",65,0)
 ;
"RTN","OCXCACHE",66,0)
 ;                        If this parameter is: "$$LOCL^ORQQLR1(ORDFN,TEST,SPECIMEN)"
"RTN","OCXCACHE",67,0)
 ;  then the value will be stored in subscript: "$$LOCL^ORQQLR1(ORDFN,TEST,SPECIMEN)"
"RTN","OCXCACHE",68,0)
 ;
"RTN","OCXCACHE",69,0)
 ;***Object ID = If this is patient data then this will be the patient's DFN.
"RTN","OCXCACHE",70,0)
 ;               If this is user data then this will be the user's DUZ.
"RTN","OCXCACHE",71,0)
 ;               etc...
"RTN","OCXCACHE",72,0)
 ;
"RTN","OCXCACHE",73,0)
 ;***Timeout = (Optional  Default = 300 (5 Minutes)) How long, in seconds, the data has to live in the cache.
"RTN","OCXCACHE",74,0)
 ;
"RTN","OCXCACHE",75,0)
 ;^XTMP("OCXCACHE",DFN,"$$LOCL^ORQQLR1(1234,110,119)","DATA")= Data
"RTN","OCXCACHE",76,0)
 ;
"RTN","OCXCACHE",77,0)
 ;^XTMP("OCXCACHE",DFN,"$$LOCL^ORQQLR1(1234,110,119)","TIME")= When the data will be deleted from the cache.
"RTN","OCXCACHE",78,0)
 ;
"RTN","OCXCACHE",79,0)
 ; $$NOW^OCXCACHE  =  The number of seconds since the "beginning of time". Used to determine if the data
"RTN","OCXCACHE",80,0)
 ;                    node in the cache is past its expiration date or not.
"RTN","OCXCACHE",81,0)
 ;
"RTN","OCXCACHE",82,0)
 ;                     It is very important that ORMTIME is running if this routine is being used.
"RTN","OCXCACHE",83,0)
 ;                    ORMTIME calls OCXOPURG which calls PURGE^OCXCACHE that cleans out expired data
"RTN","OCXCACHE",84,0)
 ;                    in the cache. This will keep the cache from using up all the available diskspace
"RTN","OCXCACHE",85,0)
 ;                    in the Volume Set or directory that ^XTMP resides in. PURGE^OCXCACHE can be run
"RTN","OCXCACHE",86,0)
 ;                    manually from a programmer's prompt if needed.
"RTN","OCXCACHE",87,0)
 ;
"RTN","OCXOPURG")
0^2^B9246604
"RTN","OCXOPURG",1,0)
OCXOPURG ;SLC/RJS,CLA - Purge old Log and Patient Data ;4/02/02  08:38
"RTN","OCXOPURG",2,0)
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**32,143**;Dec 17,1997
"RTN","OCXOPURG",3,0)
 ;;  ;;ORDER CHECK EXPERT version 1.01 released OCT 29,1998
"RTN","OCXOPURG",4,0)
 ;
"RTN","OCXOPURG",5,0)
EN ;
"RTN","OCXOPURG",6,0)
 ;
"RTN","OCXOPURG",7,0)
 N OCXE0,OCXE1,OCXE2,OCXS,OCXDFN,OCXCNT,OCXDATE,OCXRUL,OCXKEEP,OCXFILE
"RTN","OCXOPURG",8,0)
 N OCXFIRST,OCXLAST,OCXOVER
"RTN","OCXOPURG",9,0)
 ;
"RTN","OCXOPURG",10,0)
 ;   Purge OCX namespaced entries in ^TMP that have expired.
"RTN","OCXOPURG",11,0)
 ;
"RTN","OCXOPURG",12,0)
 S OCXS="OCX" F  S OCXS=$O(^TMP(OCXS)) Q:'$L(OCXS)  Q:'($E(OCXS,1,3)="OCX")  D
"RTN","OCXOPURG",13,0)
 .S OCXE0=0 F  S OCXE0=$O(^TMP(OCXS,OCXE0)) Q:'$L(OCXE0)  D
"RTN","OCXOPURG",14,0)
 ..K:($G(^TMP(OCXS,OCXE0))<($P($H,",",2)+($H*86400))) ^TMP(OCXS,OCXE0)
"RTN","OCXOPURG",15,0)
 ;
"RTN","OCXOPURG",16,0)
 D PURGE^OCXCACHE
"RTN","OCXOPURG",17,0)
 ;
"RTN","OCXOPURG",18,0)
 S OCXDATE=0 F  S OCXDATE=$O(^OCXD(860.7,"AT",OCXDATE)) Q:'OCXDATE  I (OCXDATE<($H-5)) D
"RTN","OCXOPURG",19,0)
 .S OCXDFN=0 F  S OCXDFN=$O(^OCXD(860.7,"AT",OCXDATE,OCXDFN)) Q:'OCXDFN  D
"RTN","OCXOPURG",20,0)
 ..S OCXRUL=0 F  S OCXRUL=$O(^OCXD(860.7,"AT",OCXDATE,OCXDFN,OCXRUL)) Q:'OCXRUL  D
"RTN","OCXOPURG",21,0)
 ...N OCXNODE
"RTN","OCXOPURG",22,0)
 ...S OCXNODE=$G(^OCXD(860.7,OCXDFN,1,OCXRUL,0))
"RTN","OCXOPURG",23,0)
 ...I ($P(OCXNODE,U,2)=OCXDATE) D
"RTN","OCXOPURG",24,0)
 ....K ^OCXD(860.7,OCXDFN,1,OCXRUL)
"RTN","OCXOPURG",25,0)
 ....K ^OCXD(860.7,OCXDFN,"B",OCXRUL,OCXRUL)
"RTN","OCXOPURG",26,0)
 ....I '$O(^OCXD(860.7,OCXDFN,1,0)) D
"RTN","OCXOPURG",27,0)
 .....K ^OCXD(860.7,OCXDFN)
"RTN","OCXOPURG",28,0)
 .....K ^OCXD(860.7,"B",OCXDFN,OCXDFN)
"RTN","OCXOPURG",29,0)
 ...K ^OCXD(860.7,"AT",OCXDATE,OCXDFN,OCXRUL)
"RTN","OCXOPURG",30,0)
 ;
"RTN","OCXOPURG",31,0)
 I '($P($G(^OCXD(861,1,0)),U,1)="SITE PREFERENCES") K ^OCXD(861,1) S ^OCXD(861,1,0)="SITE PREFERENCES"
"RTN","OCXOPURG",32,0)
 ;
"RTN","OCXOPURG",33,0)
 I '($P($G(^OCXD(861,1,0)),U,2)=(+$H)) D
"RTN","OCXOPURG",34,0)
 .I $L($T(LOG^OCXOZ01)),$$LOG^OCXOZ01 S OCXKEEP=$$DT("TODAY-"_(+$$LOG^OCXOZ01)) I 1
"RTN","OCXOPURG",35,0)
 .E  S OCXKEEP=$$DT("TODAY-3")
"RTN","OCXOPURG",36,0)
 .K ^OCXD(861,"B")
"RTN","OCXOPURG",37,0)
 .S OCXE1=0,OCXE0=1 F  S OCXE0=$O(^OCXD(861,OCXE0)) Q:'OCXE0  D
"RTN","OCXOPURG",38,0)
 ..S OCXDATE=+$G(^OCXD(861,OCXE0,0))
"RTN","OCXOPURG",39,0)
 ..I 'OCXDATE K ^OCXD(861,OCXE0) Q
"RTN","OCXOPURG",40,0)
 ..I (OCXDATE<OCXKEEP) K ^OCXD(861,OCXE0) Q
"RTN","OCXOPURG",41,0)
 ..S ^OCXD(861,"B",OCXDATE,OCXE0)="",OCXE1=$G(OCXE1)+1
"RTN","OCXOPURG",42,0)
 .S $P(^OCXD(861,1,0),U,2)=(+$H)
"RTN","OCXOPURG",43,0)
 ;
"RTN","OCXOPURG",44,0)
 S OCXFIRST=$O(^OCXD(861,1))
"RTN","OCXOPURG",45,0)
 S OCXLAST=$O(^OCXD(861," "),-1)
"RTN","OCXOPURG",46,0)
 S OCXOVER=((OCXLAST-OCXFIRST)-200000)
"RTN","OCXOPURG",47,0)
 ;
"RTN","OCXOPURG",48,0)
 I (OCXOVER>0) D
"RTN","OCXOPURG",49,0)
 .S OCXE0=1 F OCXE1=1:1:OCXOVER S OCXE0=$O(^OCXD(861,OCXE0)) Q:'OCXE0  D
"RTN","OCXOPURG",50,0)
 ..S OCXDATE=$G(^OCXD(861,OCXE0,0))
"RTN","OCXOPURG",51,0)
 ..K ^OCXD(861,OCXE0)
"RTN","OCXOPURG",52,0)
 ..K ^OCXD(861,"B",OCXDATE,OCXE0)
"RTN","OCXOPURG",53,0)
 ;
"RTN","OCXOPURG",54,0)
 F OCXFILE=860.7,861 I $L($G(^OCXD(OCXFILE,0))) D
"RTN","OCXOPURG",55,0)
 .S OCXE0=0 F OCXCNT=0:1 S OCXE1=OCXE0,OCXE0=$O(^OCXD(OCXFILE,OCXE0)) Q:'OCXE0
"RTN","OCXOPURG",56,0)
 .S ^OCXD(OCXFILE,0)=$P(^OCXD(OCXFILE,0),U,1,2)_U_OCXE1_U_OCXCNT
"RTN","OCXOPURG",57,0)
 ;
"RTN","OCXOPURG",58,0)
 I '$O(^OCXD(860.7,0)) S ^OCXD(860.7,0)=$P(^OCXD(860.7,0),U,1,2)
"RTN","OCXOPURG",59,0)
 I '$O(^OCXD(861,0)) S ^OCXD(861,0)=$P(^OCXD(861,0),U,1,2)
"RTN","OCXOPURG",60,0)
 I $G(OCXE1),$O(^OCXD(861,0)) S ^OCXD(861,0)=$P(^OCXD(861,0),U,1,2)_U_$O(^OCXD(861," "),-1)_U_OCXE1
"RTN","OCXOPURG",61,0)
 ;
"RTN","OCXOPURG",62,0)
 Q
"RTN","OCXOPURG",63,0)
 ;
"RTN","OCXOPURG",64,0)
DATE() ;
"RTN","OCXOPURG",65,0)
 ;
"RTN","OCXOPURG",66,0)
 N X,Y,%DT
"RTN","OCXOPURG",67,0)
 S X="N",%DT="T" D ^%DT X ^DD("DD") S:(Y["@") Y=$P(Y,"@",1)_" at "_$P(Y,"@",2)
"RTN","OCXOPURG",68,0)
 Q Y
"RTN","OCXOPURG",69,0)
 ;
"RTN","OCXOPURG",70,0)
DT(X) N Y,%DT S %DT="" D ^%DT Q Y+17000000
"RTN","OCXOPURG",71,0)
 ;
"RTN","OCXSENDA")
0^6^B19170708
"RTN","OCXSENDA",1,0)
OCXSENDA ;SLC/RJS,CLA - BUILD RULE TRANSPORTER ROUTINES (Build Main Routine) ;6/12/02  12:03
"RTN","OCXSENDA",2,0)
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**32,74,96,105,143**;Dec 17,1997
"RTN","OCXSENDA",3,0)
 ;;  ;;ORDER CHECK EXPERT version 1.01 released OCT 29,1998
"RTN","OCXSENDA",4,0)
 ;
"RTN","OCXSENDA",5,0)
EN() ;
"RTN","OCXSENDA",6,0)
 ;
"RTN","OCXSENDA",7,0)
 N R,LINE,TEXT,NOW,RUCI,XCM
"RTN","OCXSENDA",8,0)
 S NOW=$$NOW^OCXSEND3,RUCI=$$NETNAME^OCXSEND,CVER=$$VERSION^OCXOCMP
"RTN","OCXSENDA",9,0)
 F LINE=1:1:999 S TEXT=$P($T(TEXT+LINE),";",2,999) Q:TEXT  S TEXT=$P(TEXT,";",2,999) S R(LINE,0)=$$CONV^OCXSEND3(TEXT)
"RTN","OCXSENDA",10,0)
 ;
"RTN","OCXSENDA",11,0)
 M ^TMP("OCXSEND",$J,"RTN")=R
"RTN","OCXSENDA",12,0)
 ;
"RTN","OCXSENDA",13,0)
 S DIE="^TMP(""OCXSEND"","_$J_",""RTN"",",XCN=0,X=$$RNAME^OCXSEND3(0,0)
"RTN","OCXSENDA",14,0)
 W !,X X ^%ZOSF("SAVE") W "  ... ",XCM," Lines filed" K ^TMP("OCXSEND",$J,"RTN")
"RTN","OCXSENDA",15,0)
 ;
"RTN","OCXSENDA",16,0)
 Q XCM
"RTN","OCXSENDA",17,0)
 ;
"RTN","OCXSENDA",18,0)
 ;
"RTN","OCXSENDA",19,0)
TEXT ;
"RTN","OCXSENDA",20,0)
 ;;|$$RNAME^OCXSEND3(0,0)| ;SLC/RJS,CLA - OCX PACKAGE RULE TRANSPORT ROUTINE |OCXPATCH| ;|NOW|
"RTN","OCXSENDA",21,0)
 ;;|OCXLIN2|
"RTN","OCXSENDA",22,0)
 ;;|OCXLIN3|
"RTN","OCXSENDA",23,0)
 ;; ;
"RTN","OCXSENDA",24,0)
 ;;S ;
"RTN","OCXSENDA",25,0)
 ;; ;
"RTN","OCXSENDA",26,0)
 ;; N OCXDIER,QUIT,LINE,TEXT,REMOTE,LOCAL,D0,OPCODE,REF,OCXFLAG S QUIT=0
"RTN","OCXSENDA",27,0)
 ;; N OCXAUTO,OCZSCR
"RTN","OCXSENDA",28,0)
 ;; ;
"RTN","OCXSENDA",29,0)
 ;; D DOT
"RTN","OCXSENDA",30,0)
 ;; I $L($T(VERSION^OCXOCMP)),($$VERSION^OCXOCMP="|CVER|"),1
"RTN","OCXSENDA",31,0)
 ;; E  D  Q
"RTN","OCXSENDA",32,0)
 ;; .W !
"RTN","OCXSENDA",33,0)
 ;; .W !,"Rule Transport aborted, version mismatch."
"RTN","OCXSENDA",34,0)
 ;; .W !,"Current Local version: ",$$VERSION^OCXOCMP
"RTN","OCXSENDA",35,0)
 ;; .W !,"   Rule Transport Version: |CVER|"
"RTN","OCXSENDA",36,0)
 ;; I '$D(DTIME) W !!,"DTIME not defined !!",!! Q
"RTN","OCXSENDA",37,0)
 ;; W !!,"Order Check Expert System Rule Transporter"
"RTN","OCXSENDA",38,0)
 ;; W !," Created: |NOW|  at  |RUCI|"
"RTN","OCXSENDA",39,0)
 ;; W !," Current Date: ",$$NOW^|$$RNAME^OCXSEND3(0,1)|,"  at  ",$$NETNAME^OCXSEND,!!
"RTN","OCXSENDA",40,0)
 ;; S LASTFILE=0 K ^TMP("OCXRULE",$J)
"RTN","OCXSENDA",41,0)
 ;; S ^TMP("OCXRULE",$J)=($P($H,",",2)+($H*86400)+(1*60*60))_" <- ^TMP ENTRY EXPIRATION DATE FOR ^OCXOPURG"
"RTN","OCXSENDA",42,0)
 ;; S OCXFLAG="|OCXASK|"
"RTN","OCXSENDA",43,0)
 ;; ;
"RTN","OCXSENDA",44,0)
 ;;RUN ;
"RTN","OCXSENDA",45,0)
 ;; ;
"RTN","OCXSENDA",46,0)
 ;; W !,"Loading Data " D ^|$$RNAME^OCXSEND3(1,2)|
"RTN","OCXSENDA",47,0)
 ;; ;
"RTN","OCXSENDA",48,0)
 ;; S LINE=0 F  S LINE=$O(^TMP("OCXRULE",$J,LINE)) Q:'LINE   D  Q:QUIT
"RTN","OCXSENDA",49,0)
 ;; .D:'(LINE#50) STATUS^OCXOPOST(LINE,$O(^TMP("OCXRULE",$J," "),-1))
"RTN","OCXSENDA",50,0)
 ;; .S TEXT=$G(^TMP("OCXRULE",$J,LINE)) I $L(TEXT) D  Q:QUIT
"RTN","OCXSENDA",51,0)
 ;; ..S TEXT=$P(TEXT,";",2,999),OPCODE=$P(TEXT,U,1),TEXT=$P(TEXT,U,2,999)
"RTN","OCXSENDA",52,0)
 ;; ..;
"RTN","OCXSENDA",53,0)
 ;; ..I OPCODE="KEY" D DOT S LOCAL="",D0=$$GETFILE^|$$RNAME^OCXSEND3(0,1)|(+$P(TEXT,U,1),$P(TEXT,U,2),.LOCAL) S QUIT=(D0=(-10)) Q
"RTN","OCXSENDA",54,0)
 ;; ..I OPCODE="R" S REF="REMOTE("_$P(TEXT,":",1)_":"_D0_$P(TEXT,":",2,99)_")" Q
"RTN","OCXSENDA",55,0)
 ;; ..I OPCODE="D",$D(REF) S @REF=$P(TEXT,U,1,999) K REF Q
"RTN","OCXSENDA",56,0)
 ;; ..;
"RTN","OCXSENDA",57,0)
 ;; ..I OPCODE="EOR" S QUIT=$$COMPARE^|$$RNAME^OCXSEND3(1,1)|(.LOCAL,.REMOTE) K LOCAL,REMOTE Q
"RTN","OCXSENDA",58,0)
 ;; ..I OPCODE="EOF" K LOCAL,REMOTE Q
"RTN","OCXSENDA",59,0)
 ;; ..I OPCODE="SOF" W !,"  Installing '",TEXT,"' records... " Q
"RTN","OCXSENDA",60,0)
 ;; ..I OPCODE="ROOT" D  Q
"RTN","OCXSENDA",61,0)
 ;; ...N FILE,DATA
"RTN","OCXSENDA",62,0)
 ;; ...S FILE=U_$P(TEXT,U,1),DATA=$P(TEXT,U,2,3)
"RTN","OCXSENDA",63,0)
 ;; ...I ($P($G(@FILE),U,1,2)=DATA) Q
"RTN","OCXSENDA",64,0)
 ;; ...S $P(@FILE,U,1,2)=DATA
"RTN","OCXSENDA",65,0)
 ;; ...W !,"  Restoring file #",(+$P(DATA,U,2))," zero node"
"RTN","OCXSENDA",66,0)
 ;; ..;
"RTN","OCXSENDA",67,0)
 ;; ..W !,"Unknown OpCode: ",OPCODE,"  in: ",TEXT S QUIT=$$PAUSE^|$$RNAME^OCXSEND3(0,1)| W !
"RTN","OCXSENDA",68,0)
 ;; ;
"RTN","OCXSENDA",69,0)
 ;; K ^TMP("OCXRULE",$J)
"RTN","OCXSENDA",70,0)
 ;; ;
"RTN","OCXSENDA",71,0)
 ;; I $D(^OCXS) D
"RTN","OCXSENDA",72,0)
 ;; .N FILE,DO,PD0,CNT
"RTN","OCXSENDA",73,0)
 ;; .S FILE=0 F  S FILE=$O(^OCXS(FILE)) Q:'FILE  D
"RTN","OCXSENDA",74,0)
 ;; ..S D0=0 F CNT=0:1 S PD0=D0,D0=$O(^OCXS(FILE,D0)) Q:'D0
"RTN","OCXSENDA",75,0)
 ;; ..S $P(^OCXS(FILE,0),U,3,4)=CNT_U_PD0
"RTN","OCXSENDA",76,0)
 ;; ;
"RTN","OCXSENDA",77,0)
 ;; I $G(OCXDIER) D
"RTN","OCXSENDA",78,0)
 ;; .W !!!!!!!
"RTN","OCXSENDA",79,0)
 ;; .W !,?5,"******************** Warning ******************** "
"RTN","OCXSENDA",80,0)
 ;; .W !,?7,+$G(OCXDIER)," data filing error",$S(($G(OCXDIER)=1):"",1:"s"),"."
"RTN","OCXSENDA",81,0)
 ;; .W !,?7,"Some expert system rules may be incomplete."
"RTN","OCXSENDA",82,0)
 ;; .W !,?5,"******************** Warning ******************** "
"RTN","OCXSENDA",83,0)
 ;; I '$G(OCXDIER) W !!,?5," No data filing errors."
"RTN","OCXSENDA",84,0)
 ;; W !!,"Transport Finished..."
"RTN","OCXSENDA",85,0)
 ;; ;
"RTN","OCXSENDA",86,0)
 ;; D
"RTN","OCXSENDA",87,0)
 ;; .N OCXOETIM
"RTN","OCXSENDA",88,0)
 ;; .D BMES^XPDUTL("---Creating Order Check Routines-----------------------------------")
"RTN","OCXSENDA",89,0)
 ;; .D AUTO^OCXOCMP
"RTN","OCXSENDA",90,0)
 ;; ;
"RTN","OCXSENDA",91,0)
 ;; Q
"RTN","OCXSENDA",92,0)
 ;; ;
"RTN","OCXSENDA",93,0)
 ;;DOT Q:$G(OCXAUTO)  W:($X>70) ! W " ." Q
"RTN","OCXSENDA",94,0)
 ;; ;
"RTN","OCXSENDA",95,0)
 ;;READ(OCXZ0,OCXZA,OCXZB,OCXZL) ;
"RTN","OCXSENDA",96,0)
 ;; N OCXLINE,DIR,DTOUT,DUOUT,DIRUT,DIROUT
"RTN","OCXSENDA",97,0)
 ;; Q:'$L($G(OCXZ0)) U
"RTN","OCXSENDA",98,0)
 ;; S DIR(0)=OCXZ0
"RTN","OCXSENDA",99,0)
 ;; S:$L($G(OCXZA)) DIR("A")=OCXZA
"RTN","OCXSENDA",100,0)
 ;; S:$L($G(OCXZB)) DIR("B")=OCXZB
"RTN","OCXSENDA",101,0)
 ;; F OCXLINE=1:1:($G(OCXZL)-1) W !
"RTN","OCXSENDA",102,0)
 ;; D ^DIR
"RTN","OCXSENDA",103,0)
 ;; I $D(DTOUT)!$D(DUOUT)!$D(DIRUT)!$D(DIROUT) Q U
"RTN","OCXSENDA",104,0)
 ;; Q Y
"RTN","OCXSENDA",105,0)
 ;; ;
"RTN","OCXSENDA",106,0)
 ;;$
"RTN","OCXSENDA",107,0)
 ;1;
"RTN","OCXSENDB")
0^7^B44498394
"RTN","OCXSENDB",1,0)
OCXSENDB ;SLC/RJS,CLA - BUILD RULE TRANSPORTER ROUTINES (Get List of Objects to Transport  continued) ;8/04/98  13:21
"RTN","OCXSENDB",2,0)
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**32,105,143**;Dec 17,1997
"RTN","OCXSENDB",3,0)
 ;;  ;;ORDER CHECK EXPERT version 1.01 released OCT 29,1998
"RTN","OCXSENDB",4,0)
 ;
"RTN","OCXSENDB",5,0)
 ;
"RTN","OCXSENDB",6,0)
DIC(OCXDIC,OCXDIC0,OCXDICA,OCXX,OCXDICS,OCXW) ;
"RTN","OCXSENDB",7,0)
 ;
"RTN","OCXSENDB",8,0)
 N DIC,X,Y
"RTN","OCXSENDB",9,0)
 S DIC=$G(OCXDIC) Q:'$L(DIC) -1
"RTN","OCXSENDB",10,0)
 S DIC(0)=$G(OCXDIC0) S:$L($G(OCXX)) X=OCXX
"RTN","OCXSENDB",11,0)
 S:$L($G(OCXDICS)) DIC("S")=OCXDICS
"RTN","OCXSENDB",12,0)
 S:$L($G(OCXDICA)) DIC("A")=OCXDICA
"RTN","OCXSENDB",13,0)
 S:$L($G(OCXW)) DIC("W")=OCXW
"RTN","OCXSENDB",14,0)
 D ^DIC Q:(Y<1) 0 Q Y
"RTN","OCXSENDB",15,0)
 ;
"RTN","OCXSENDB",16,0)
CHECK(FILE,VALUE) ;
"RTN","OCXSENDB",17,0)
 ;
"RTN","OCXSENDB",18,0)
 N IEN,OCXID
"RTN","OCXSENDB",19,0)
 Q:'$L(VALUE)
"RTN","OCXSENDB",20,0)
 I (VALUE[U),VALUE S VALUE=+VALUE
"RTN","OCXSENDB",21,0)
 I (VALUE=+VALUE) S IEN=VALUE
"RTN","OCXSENDB",22,0)
 E  S IEN=+$$DIC(FILE,"XM","",VALUE)
"RTN","OCXSENDB",23,0)
 I 'IEN W !!,$P(^OCXS(FILE,0),U,1)," -1-> ",VALUE,"  [",IEN,"]  ERROR - RECORD NOT FOUND" Q
"RTN","OCXSENDB",24,0)
 I '$D(^OCXS(FILE,IEN)) W !!,$P(^OCXS(FILE,0),U,1)," -2-> ",VALUE," [",IEN,"]  ERROR - RECORD NOT FOUND" Q
"RTN","OCXSENDB",25,0)
 D ADDREC^OCXSEND1(FILE,IEN)
"RTN","OCXSENDB",26,0)
 Q
"RTN","OCXSENDB",27,0)
 ;
"RTN","OCXSENDB",28,0)
8602 ; ORDER CHECK RULE
"RTN","OCXSENDB",29,0)
 ;
"RTN","OCXSENDB",30,0)
 N D0,MSG,PIEC
"RTN","OCXSENDB",31,0)
 ;
"RTN","OCXSENDB",32,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"C",D0)) Q:'D0  D  ; TRUTH ELEMENTS multiple
"RTN","OCXSENDB",33,0)
 .D CHECK(860.3,$P($G(^OCXS(FILE,REC,"C",D0,0)),U,2)) ; ELEMENT NAME
"RTN","OCXSENDB",34,0)
 ;
"RTN","OCXSENDB",35,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"R",D0)) Q:'D0  D  ; RELATION ACTIONS multiple
"RTN","OCXSENDB",36,0)
 .S MSG=$G(^OCXS(FILE,REC,"R",D0,"MSG"))
"RTN","OCXSENDB",37,0)
 .I (MSG["|") F PIEC=2:2:$L(MSG,"|")  D CHECK(860.4,$P(MSG,"|",PIEC))
"RTN","OCXSENDB",38,0)
 .S MSG=$G(^OCXS(FILE,REC,"R",D0,"OCMSG"))
"RTN","OCXSENDB",39,0)
 .I (MSG["|") F PIEC=2:2:$L(MSG,"|")  D CHECK(860.4,$P(MSG,"|",PIEC))
"RTN","OCXSENDB",40,0)
 ;
"RTN","OCXSENDB",41,0)
 Q
"RTN","OCXSENDB",42,0)
 ;
"RTN","OCXSENDB",43,0)
8603 ; ORDER CHECK ELEMENT
"RTN","OCXSENDB",44,0)
 ;
"RTN","OCXSENDB",45,0)
 N D0,OPER,TERM
"RTN","OCXSENDB",46,0)
 ;
"RTN","OCXSENDB",47,0)
 D CHECK(860.6,$P($G(^OCXS(FILE,REC,0)),U,2)) ; ELEMENT CONTEXT
"RTN","OCXSENDB",48,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"COND",D0)) Q:'D0  D  ; CONDITIONAL EXPRESSION multiple
"RTN","OCXSENDB",49,0)
 .D CHECK(860.4,$P($G(^OCXS(FILE,REC,"COND",D0,"DFLD1")),U,1)) ; DATA FIELD 1
"RTN","OCXSENDB",50,0)
 .D CHECK(863.9,$G(^OCXS(FILE,REC,"COND",D0,"OPER"))) ; OPERATOR/FUNCTION
"RTN","OCXSENDB",51,0)
 .D CHECK(860.4,$G(^OCXS(FILE,REC,"COND",D0,"DFLD2"))) ; DATA FIELD 2
"RTN","OCXSENDB",52,0)
 .D CHECK(860.4,$P($G(^OCXS(FILE,REC,"COND",D0,"DFLD3")),U,1)) ; DATA FIELD 3
"RTN","OCXSENDB",53,0)
 .;
"RTN","OCXSENDB",54,0)
 .S OPER=$G(^OCXS(FILE,REC,"COND",D0,"OPER")) Q:'OPER
"RTN","OCXSENDB",55,0)
 .S OPER=$P($G(^OCXS(863.9,+OPER,0)),U,1) Q:'(OPER["TERM")
"RTN","OCXSENDB",56,0)
 .S TERM=$G(^OCXS(FILE,REC,"COND",D0,"VAL1"))
"RTN","OCXSENDB",57,0)
 .D CHECK(860.9,TERM)
"RTN","OCXSENDB",58,0)
 ;
"RTN","OCXSENDB",59,0)
 Q
"RTN","OCXSENDB",60,0)
 ;
"RTN","OCXSENDB",61,0)
8604 ; ORDER CHECK DATA FIELD
"RTN","OCXSENDB",62,0)
 ;
"RTN","OCXSENDB",63,0)
 N D0
"RTN","OCXSENDB",64,0)
 ;
"RTN","OCXSENDB",65,0)
 D CHECK(864.1,$P($G(^OCXS(FILE,REC,0)),U,3)) ; DATATYPE
"RTN","OCXSENDB",66,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"LINK",D0)) Q:'D0  D  ; DATA SOURCES multiple
"RTN","OCXSENDB",67,0)
 .D CHECK(860.6,$P($G(^OCXS(FILE,REC,"LINK",D0,0)),U,1)) ; DATA CONTEXT
"RTN","OCXSENDB",68,0)
 .D CHECK(860.5,$P($G(^OCXS(FILE,REC,"LINK",D0,0)),U,2)) ; DATA SOURCE
"RTN","OCXSENDB",69,0)
 .D CHECK(863.3,$G(^OCXS(FILE,REC,"LINK",D0,"DATAPATH"))) ; LINK
"RTN","OCXSENDB",70,0)
 ;
"RTN","OCXSENDB",71,0)
 Q
"RTN","OCXSENDB",72,0)
 ;
"RTN","OCXSENDB",73,0)
8605 ; ORDER CHECK DATA SOURCE
"RTN","OCXSENDB",74,0)
 ;
"RTN","OCXSENDB",75,0)
 N D0
"RTN","OCXSENDB",76,0)
 ;
"RTN","OCXSENDB",77,0)
 D CHECK(860.6,$P($G(^OCXS(FILE,REC,0)),U,2)) ; CONTEXT
"RTN","OCXSENDB",78,0)
 Q
"RTN","OCXSENDB",79,0)
 ;
"RTN","OCXSENDB",80,0)
8608 ; ORDER CHECK COMPILER FUNCTIONS
"RTN","OCXSENDB",81,0)
 ;
"RTN","OCXSENDB",82,0)
 N D0,TEXT,PIEC,CALL
"RTN","OCXSENDB",83,0)
 ;
"RTN","OCXSENDB",84,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"CODE",D0)) Q:'D0  D  ; CODE multiple
"RTN","OCXSENDB",85,0)
 .S TEXT=$G(^OCXS(FILE,REC,"CODE",D0,0))
"RTN","OCXSENDB",86,0)
 .;
"RTN","OCXSENDB",87,0)
 .I (TEXT["$$") F PIEC=2:1:$L(TEXT,"$$")  D
"RTN","OCXSENDB",88,0)
 ..S CALL=$P($P(TEXT,"$$",PIEC),"(",1) Q:'$L(CALL)  Q:(CALL[U)
"RTN","OCXSENDB",89,0)
 ..D CHECK(860.8,CALL)
"RTN","OCXSENDB",90,0)
 ;
"RTN","OCXSENDB",91,0)
 Q
"RTN","OCXSENDB",92,0)
 ;
"RTN","OCXSENDB",93,0)
863 ; OCX MDD CLASS
"RTN","OCXSENDB",94,0)
 ;
"RTN","OCXSENDB",95,0)
 N D0
"RTN","OCXSENDB",96,0)
 ;
"RTN","OCXSENDB",97,0)
 D CHECK(863,$P($G(^OCXS(FILE,REC,0)),U,3)) ; PARENT CLASS
"RTN","OCXSENDB",98,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"PAR",D0)) Q:'D0  D  ; PARAMETER multiple
"RTN","OCXSENDB",99,0)
 .D CHECK(863.8,$P($G(^OCXS(FILE,REC,"PAR",D0,0)),U,1)) ; PARAMETER
"RTN","OCXSENDB",100,0)
 ;
"RTN","OCXSENDB",101,0)
 Q
"RTN","OCXSENDB",102,0)
 ;
"RTN","OCXSENDB",103,0)
8631 ; OCX MDD APPLICATION
"RTN","OCXSENDB",104,0)
 ;
"RTN","OCXSENDB",105,0)
 N D0
"RTN","OCXSENDB",106,0)
 ;
"RTN","OCXSENDB",107,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"PAR",D0)) Q:'D0  D  ; PARAMETER multiple
"RTN","OCXSENDB",108,0)
 .D CHECK(863.8,$P($G(^OCXS(FILE,REC,"PAR",D0,0)),U,1)) ; PARAMETER NAME
"RTN","OCXSENDB",109,0)
 ;
"RTN","OCXSENDB",110,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"SUBJ",D0)) Q:'D0  D  ; PRIMARY SUBJECT multiple
"RTN","OCXSENDB",111,0)
 .D CHECK(863.2,$P($G(^OCXS(FILE,REC,"SUBJ",D0,0)),U,1)) ; PRIMARY SUBJECT
"RTN","OCXSENDB",112,0)
 ;
"RTN","OCXSENDB",113,0)
 Q
"RTN","OCXSENDB",114,0)
 ;
"RTN","OCXSENDB",115,0)
8632 ; OCX MDD SUBJECT
"RTN","OCXSENDB",116,0)
 ;
"RTN","OCXSENDB",117,0)
 N D0
"RTN","OCXSENDB",118,0)
 ;
"RTN","OCXSENDB",119,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"PAR",D0)) Q:'D0  D  ; PARAMETER multiple
"RTN","OCXSENDB",120,0)
 .D CHECK(863.8,$P($G(^OCXS(FILE,REC,"PAR",D0,0)),U,1)) ; PARAMETER NAME
"RTN","OCXSENDB",121,0)
 ;
"RTN","OCXSENDB",122,0)
 Q
"RTN","OCXSENDB",123,0)
 ;
"RTN","OCXSENDB",124,0)
8633 ; OCX MDD LINK
"RTN","OCXSENDB",125,0)
 ;
"RTN","OCXSENDB",126,0)
 N D0
"RTN","OCXSENDB",127,0)
 ;
"RTN","OCXSENDB",128,0)
 D CHECK(863.2,$P($G(^OCXS(FILE,REC,0)),U,2)) ; PARENT SUBJECT
"RTN","OCXSENDB",129,0)
 D CHECK(863.2,$P($G(^OCXS(FILE,REC,0)),U,3)) ; DESCENDANT SUBJECT
"RTN","OCXSENDB",130,0)
 D CHECK(863.4,$P($G(^OCXS(FILE,REC,0)),U,5)) ; ATTRIBUTE
"RTN","OCXSENDB",131,0)
 ;
"RTN","OCXSENDB",132,0)
 S FCPARM=$O(^OCXS(863.8,"B","OCXO EXTERNAL FUNCTION CALL",0))
"RTN","OCXSENDB",133,0)
 ;
"RTN","OCXSENDB",134,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"PAR",D0)) Q:'D0  D  ; PARAMETER multiple
"RTN","OCXSENDB",135,0)
 .N PARM,PIEC
"RTN","OCXSENDB",136,0)
 .S PARM=$P($G(^OCXS(FILE,REC,"PAR",D0,0)),U,1) ; PARAMETER NAME
"RTN","OCXSENDB",137,0)
 .D CHECK(863.8,PARM) ; PARAMETER NAME
"RTN","OCXSENDB",138,0)
 .S PARMV=$G(^OCXS(FILE,REC,"PAR",D0,"VAL")) ; PARAMETER NAME
"RTN","OCXSENDB",139,0)
 .Q:'(PARM=FCPARM)
"RTN","OCXSENDB",140,0)
 .I '($P(PARMV,"(")[U) D CHECK(860.8,$P(PARMV,"(",1))
"RTN","OCXSENDB",141,0)
 .I (PARMV["|") F PIEC=2:2:$L(PARMV,"|")  D CHECK(860.4,$P(PARMV,"|",PIEC))
"RTN","OCXSENDB",142,0)
 ;
"RTN","OCXSENDB",143,0)
 Q
"RTN","OCXSENDB",144,0)
 ;
"RTN","OCXSENDB",145,0)
8634 ; OCX MDD ATTRIBUTE
"RTN","OCXSENDB",146,0)
 ;
"RTN","OCXSENDB",147,0)
 N D0
"RTN","OCXSENDB",148,0)
 ;
"RTN","OCXSENDB",149,0)
 D CHECK(863.4,$P($G(^OCXS(FILE,REC,"MOM")),U,1)) ; PARENT ATTRIBUTE
"RTN","OCXSENDB",150,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"PAR",D0)) Q:'D0  D  ; PARAMETER multiple
"RTN","OCXSENDB",151,0)
 .D CHECK(863.8,$P($G(^OCXS(FILE,REC,"PAR",D0,0)),U,1)) ; PARAMETER NAME
"RTN","OCXSENDB",152,0)
 ;
"RTN","OCXSENDB",153,0)
 Q
"RTN","OCXSENDB",154,0)
 ;
"RTN","OCXSENDB",155,0)
8635 ; OCX MDD VALUES
"RTN","OCXSENDB",156,0)
 ;
"RTN","OCXSENDB",157,0)
 N D0
"RTN","OCXSENDB",158,0)
 ;
"RTN","OCXSENDB",159,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"PAR",D0)) Q:'D0  D  ; PARAMETER multiple
"RTN","OCXSENDB",160,0)
 .D CHECK(863.8,$P($G(^OCXS(FILE,REC,"PAR",D0,0)),U,1)) ; PARAMETER
"RTN","OCXSENDB",161,0)
 ;
"RTN","OCXSENDB",162,0)
 Q
"RTN","OCXSENDB",163,0)
 ;
"RTN","OCXSENDB",164,0)
8636 ; OCX MDD METHOD
"RTN","OCXSENDB",165,0)
 ;
"RTN","OCXSENDB",166,0)
 N D0
"RTN","OCXSENDB",167,0)
 ;
"RTN","OCXSENDB",168,0)
 D CHECK(863,$P($G(^OCXS(FILE,REC,0)),U,3)) ; CLASS FILE
"RTN","OCXSENDB",169,0)
 ;
"RTN","OCXSENDB",170,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"PAR",D0)) Q:'D0  D  ; PARAMETER multiple
"RTN","OCXSENDB",171,0)
 .D CHECK(863.8,$P($G(^OCXS(FILE,REC,"PAR",D0,0)),U,1)) ; PARAMETER NAME
"RTN","OCXSENDB",172,0)
 ;
"RTN","OCXSENDB",173,0)
 Q
"RTN","OCXSENDB",174,0)
 ;
"RTN","OCXSENDB",175,0)
8637 ; OCX MDD PUBLIC FUNCTION
"RTN","OCXSENDB",176,0)
 ;
"RTN","OCXSENDB",177,0)
 N D0
"RTN","OCXSENDB",178,0)
 ;
"RTN","OCXSENDB",179,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"PAR",D0)) Q:'D0  D  ; PARAMETER multiple
"RTN","OCXSENDB",180,0)
 .D CHECK(863.8,$P($G(^OCXS(FILE,REC,"PAR",D0,0)),U,1)) ; PARAMETERS
"RTN","OCXSENDB",181,0)
 ;
"RTN","OCXSENDB",182,0)
 Q
"RTN","OCXSENDB",183,0)
 ;
"RTN","OCXSENDB",184,0)
8638 ; OCX MDD PARAMETER
"RTN","OCXSENDB",185,0)
 ;
"RTN","OCXSENDB",186,0)
 N D0
"RTN","OCXSENDB",187,0)
 ;
"RTN","OCXSENDB",188,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"PAR",D0)) Q:'D0  D  ; PARAMETER ATTRIBUTE multiple
"RTN","OCXSENDB",189,0)
 .D CHECK(863.8,$P($G(^OCXS(FILE,REC,"PAR",D0,0)),U,1)) ; PARAMETER
"RTN","OCXSENDB",190,0)
 ;
"RTN","OCXSENDB",191,0)
 Q
"RTN","OCXSENDB",192,0)
 ;
"RTN","OCXSENDB",193,0)
8639 ; OCX MDD CONDITION/FUNCTION
"RTN","OCXSENDB",194,0)
 ;
"RTN","OCXSENDB",195,0)
 N D0
"RTN","OCXSENDB",196,0)
 ;
"RTN","OCXSENDB",197,0)
 D CHECK(864.1,$P($G(^OCXS(FILE,REC,0)),U,2)) ; DATATYPE
"RTN","OCXSENDB",198,0)
 D CHECK(863.7,$P($G(^OCXS(FILE,REC,0)),U,3)) ; CODE GENERATOR FUNCTION
"RTN","OCXSENDB",199,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"PAR",D0)) Q:'D0  D  ; PARAMETER multiple
"RTN","OCXSENDB",200,0)
 .S PARM=$P($G(^OCXS(FILE,REC,"PAR",D0,0)),U,1)
"RTN","OCXSENDB",201,0)
 .S PARMV=$G(^OCXS(FILE,REC,"PAR",D0,"VAL"))
"RTN","OCXSENDB",202,0)
 .D CHECK(863.8,PARM) ; PARAMETER
"RTN","OCXSENDB",203,0)
 .I (PARM="OCXO GENERATE CODE FUNCTION") D CHECK(863.7,PARMV)
"RTN","OCXSENDB",204,0)
 ;
"RTN","OCXSENDB",205,0)
 Q
"RTN","OCXSENDB",206,0)
 ;
"RTN","OCXSENDB",207,0)
8641 ; OCX MDD DATATYPE
"RTN","OCXSENDB",208,0)
 ;
"RTN","OCXSENDB",209,0)
 N D0
"RTN","OCXSENDB",210,0)
 ;
"RTN","OCXSENDB",211,0)
 D CHECK(864.1,$P($G(^OCXS(FILE,REC,"MOM")),U,1)) ; PARENT DATA TYPE
"RTN","OCXSENDB",212,0)
 S D0=0 F  S D0=$O(^OCXS(FILE,REC,"PAR",D0)) Q:'D0  D  ; PARAMETER multiple
"RTN","OCXSENDB",213,0)
 .D CHECK(863.8,$P($G(^OCXS(FILE,REC,"PAR",D0,0)),U,1)) ; PARAMETER NAME
"RTN","OCXSENDB",214,0)
 ;
"RTN","OCXSENDB",215,0)
 Q
"RTN","ORB3TIM1")
0^8^B22870825
"RTN","ORB3TIM1",1,0)
ORB3TIM1 ; slc/CLA - Routine to trigger time-related notifications ;6/28/00 12:00 [ 04/02/97  11:12 AM ]
"RTN","ORB3TIM1",2,0)
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**31,64,74,88,102,143**;Dec 17, 1997
"RTN","ORB3TIM1",3,0)
TNOTIFS ;process time-driven notifications - called by ORMTIM01
"RTN","ORB3TIM1",4,0)
 ;
"RTN","ORB3TIM1",5,0)
 ;Do not process DIV for param - ORMTIM01 is initiated by postmaster:
"RTN","ORB3TIM1",6,0)
 Q:$$GET^XPAR("SYS^PKG","ORB SYSTEM ENABLE/DISABLE",1,"I")="D"
"RTN","ORB3TIM1",7,0)
 N ORLASTQ,ORNOW,ORERR
"RTN","ORB3TIM1",8,0)
 S ORNOW=$$NOW^XLFDT
"RTN","ORB3TIM1",9,0)
 S ORLASTQ=$$GET^XPAR("SYS","ORB LAST QUEUE DATE",1,"I")
"RTN","ORB3TIM1",10,0)
 ;
"RTN","ORB3TIM1",11,0)
 D NPO
"RTN","ORB3TIM1",12,0)
 D UNVER
"RTN","ORB3TIM1",13,0)
 D UVMED
"RTN","ORB3TIM1",14,0)
 D EXPIR^ORB3TIM2
"RTN","ORB3TIM1",15,0)
 D PUT^XPAR("SYS","ORB LAST QUEUE DATE",1,ORNOW,.ORERR)
"RTN","ORB3TIM1",16,0)
 Q
"RTN","ORB3TIM1",17,0)
NPO ;trigger NPO diet > 72 hours notifications
"RTN","ORB3TIM1",18,0)
 N ORNPO,ORPT,INVDT,ORDG,ORNUM,ORBDT,OREDT
"RTN","ORB3TIM1",19,0)
 N OIFILE,ORBY,ORBI,ORST
"RTN","ORB3TIM1",20,0)
 ;
"RTN","ORB3TIM1",21,0)
 ;get NPO OIs:
"RTN","ORB3TIM1",22,0)
 S OIFILE=$$TERMLKUP^ORB31(.ORBY,"NPO")
"RTN","ORB3TIM1",23,0)
 ;
"RTN","ORB3TIM1",24,0)
 Q:'$D(ORBY)  ;quit if no link between NPO and local OI
"RTN","ORB3TIM1",25,0)
 S:'$G(ORLASTQ) ORLASTQ=$$FMADD^XLFDT(ORNOW,"","-96","","")
"RTN","ORB3TIM1",26,0)
 S ORBDT=$$FMADD^XLFDT(ORLASTQ,"","-72","","")
"RTN","ORB3TIM1",27,0)
 S OREDT=$$FMADD^XLFDT(ORNOW,"","-72","","")
"RTN","ORB3TIM1",28,0)
 F  S ORBDT=$O(^OR(100,"AF",ORBDT)) Q:(ORBDT="")!(ORBDT>OREDT)  D
"RTN","ORB3TIM1",29,0)
 .S ORNUM="" F  S ORNUM=$O(^OR(100,"AF",ORBDT,ORNUM)) Q:ORNUM=""  D
"RTN","ORB3TIM1",30,0)
 ..S ORPT=$P($G(^OR(100,ORNUM,0)),U,2) I ORPT]"" D
"RTN","ORB3TIM1",31,0)
 ...; determine if NPO order:
"RTN","ORB3TIM1",32,0)
 ...I +$G(OIFILE)=101.43 F ORBI=1:1:ORBY D
"RTN","ORB3TIM1",33,0)
 ....S ORNPO=$P(ORBY(ORBI),U) I ORNPO=$$OI^ORQOR2(ORNUM) D
"RTN","ORB3TIM1",34,0)
 .....S ORST=$P($$STATUS^ORQOR2(ORNUM),U,2)
"RTN","ORB3TIM1",35,0)
 .....I ORST'="DISCONTINUED",ORST'="COMPLETE",ORST'="EXPIRED",ORST'="UNRELEASED",ORST'="CHANGED",ORST'="CANCELLED",ORST'="LAPSED",ORST'="SCHEDULED" D
"RTN","ORB3TIM1",36,0)
 ......D EN^ORB3(31,+ORPT,ORNUM,"","",ORNUM_"@") ;trigger NPO>72 notif
"RTN","ORB3TIM1",37,0)
 Q
"RTN","ORB3TIM1",38,0)
UNVER ;trigger unverified order (by nurse) notif
"RTN","ORB3TIM1",39,0)
 N ORPT,INVDT,ORDG,ORNUM,ORBDT,OREDT,ORST,ORX,ORACT,ORDELAY
"RTN","ORB3TIM1",40,0)
 ;
"RTN","ORB3TIM1",41,0)
 ;if not queued via ORMTIM01 recently, look for past 48 hours:
"RTN","ORB3TIM1",42,0)
 S:'$G(ORLASTQ) ORLASTQ=$$FMADD^XLFDT(ORNOW,"","-48","","")
"RTN","ORB3TIM1",43,0)
 ;
"RTN","ORB3TIM1",44,0)
 ;get number of hours delay before trigger:
"RTN","ORB3TIM1",45,0)
 S ORDELAY=$$GET^XPAR("ALL","ORB UNVERIFIED ORDER",1,"I")
"RTN","ORB3TIM1",46,0)
 ;
"RTN","ORB3TIM1",47,0)
 ;look for orders unverified after <parameter value> hours:
"RTN","ORB3TIM1",48,0)
 S ORBDT=$$FMADD^XLFDT(ORLASTQ,"",-ORDELAY,"","")
"RTN","ORB3TIM1",49,0)
 S OREDT=$$FMADD^XLFDT(ORNOW,"",-ORDELAY,"","")
"RTN","ORB3TIM1",50,0)
 ;
"RTN","ORB3TIM1",51,0)
 F  S ORBDT=$O(^OR(100,"AF",ORBDT)) Q:(ORBDT="")!(ORBDT>OREDT)  D
"RTN","ORB3TIM1",52,0)
 .S ORNUM="" F  S ORNUM=$O(^OR(100,"AF",ORBDT,ORNUM)) Q:ORNUM=""  D
"RTN","ORB3TIM1",53,0)
 ..S ORPT=$P($G(^OR(100,ORNUM,0)),U,2) I ORPT]"" D
"RTN","ORB3TIM1",54,0)
 ...;The following filters match those in UVN1^ORQ11 so notif triggers
"RTN","ORB3TIM1",55,0)
 ...;and orders displayed via alert follow-up action are in sync:
"RTN","ORB3TIM1",56,0)
 ...S ORX=$G(^OR(100,ORNUM,0))
"RTN","ORB3TIM1",57,0)
 ...Q:'$L(ORX)
"RTN","ORB3TIM1",58,0)
 ...Q:$P(ORX,U,12)="O"  ;quit if outpatient order
"RTN","ORB3TIM1",59,0)
 ...Q:$L($P(ORX,U,17))  ;quit if someone has released order
"RTN","ORB3TIM1",60,0)
 ...S ORST=$P($$STATUS^ORQOR2(ORNUM),U,2)
"RTN","ORB3TIM1",61,0)
 ...I ORST'="DISCONTINUED",ORST'="COMPLETE",ORST'="EXPIRED",ORST'="UNRELEASED",ORST'="CHANGED",ORST'="CANCELLED",ORST'="LAPSED" D
"RTN","ORB3TIM1",62,0)
 ....Q:'$D(^OR(100,ORNUM,8))
"RTN","ORB3TIM1",63,0)
 ....Q:$P(^OR(100,ORNUM,8,$P(^OR(100,ORNUM,8,0),U,3),0),U,8)  ;quit if someone has verified order
"RTN","ORB3TIM1",64,0)
 ....D EN^ORB3(59,+ORPT,ORNUM,"","",ORNUM_"@")
"RTN","ORB3TIM1",65,0)
 Q
"RTN","ORB3TIM1",66,0)
UVMED ;trigger unverified med (by nurse) notif
"RTN","ORB3TIM1",67,0)
 N DG,ORGRP,ORPT,INVDT,ORNUM,ORBDT,OREDT,ORST,ORX,ORACT,ORDELAY
"RTN","ORB3TIM1",68,0)
 ;
"RTN","ORB3TIM1",69,0)
 ;if not queued via ORMTIM01 recently, look for past 48 hours:
"RTN","ORB3TIM1",70,0)
 S:'$G(ORLASTQ) ORLASTQ=$$FMADD^XLFDT(ORNOW,"","-48","","")
"RTN","ORB3TIM1",71,0)
 ;
"RTN","ORB3TIM1",72,0)
 ;get number of hours delay before trigger:
"RTN","ORB3TIM1",73,0)
 S ORDELAY=$$GET^XPAR("ALL","ORB UNVERIFIED MED ORDER",1,"I")
"RTN","ORB3TIM1",74,0)
 ;
"RTN","ORB3TIM1",75,0)
 ;look for meds unverified after <parameter value> hours:
"RTN","ORB3TIM1",76,0)
 S ORBDT=$$FMADD^XLFDT(ORLASTQ,"",-ORDELAY,"","")
"RTN","ORB3TIM1",77,0)
 S OREDT=$$FMADD^XLFDT(ORNOW,"",-ORDELAY,"","")
"RTN","ORB3TIM1",78,0)
 ;
"RTN","ORB3TIM1",79,0)
 F  S ORBDT=$O(^OR(100,"AF",ORBDT)) Q:(ORBDT="")!(ORBDT>OREDT)  D
"RTN","ORB3TIM1",80,0)
 .S ORNUM="" F  S ORNUM=$O(^OR(100,"AF",ORBDT,ORNUM)) Q:ORNUM=""  D
"RTN","ORB3TIM1",81,0)
 ..S ORPT=$P($G(^OR(100,ORNUM,0)),U,2) I ORPT]"" D
"RTN","ORB3TIM1",82,0)
 ...;The following filters match those in UVN1^ORQ11 so notif triggers
"RTN","ORB3TIM1",83,0)
 ...;and orders displayed via alert follow-up action are in sync:
"RTN","ORB3TIM1",84,0)
 ...S ORX=$G(^OR(100,ORNUM,0))
"RTN","ORB3TIM1",85,0)
 ...Q:'$L(ORX)
"RTN","ORB3TIM1",86,0)
 ...Q:'$L($$DGRX^ORQOR2(+ORNUM))  ;quit if not a pharmacy order
"RTN","ORB3TIM1",87,0)
 ...Q:$P(ORX,U,12)="O"  ;quit if outpatient order
"RTN","ORB3TIM1",88,0)
 ...Q:$L($P(ORX,U,17))  ;quit if someone has released order
"RTN","ORB3TIM1",89,0)
 ...S ORST=$P($$STATUS^ORQOR2(ORNUM),U,2)
"RTN","ORB3TIM1",90,0)
 ...I ORST'="DISCONTINUED",ORST'="COMPLETE",ORST'="EXPIRED",ORST'="UNRELEASED",ORST'="CHANGED",ORST'="CANCELLED",ORST'="LAPSED" D
"RTN","ORB3TIM1",91,0)
 ....Q:'$D(^OR(100,ORNUM,8))
"RTN","ORB3TIM1",92,0)
 ....Q:$P(^OR(100,ORNUM,8,$P(^OR(100,ORNUM,8,0),U,3),0),U,8)  ;quit if someone has verified order
"RTN","ORB3TIM1",93,0)
 ....D EN^ORB3(48,+ORPT,ORNUM,"","",ORNUM_"@")
"RTN","ORB3TIM1",94,0)
 Q
"RTN","ORB3TIM1",95,0)
GRP(DG) ;Setup display groups
"RTN","ORB3TIM1",96,0)
 ;DG=Display group to expand
"RTN","ORB3TIM1",97,0)
 N STK,MEM,I
"RTN","ORB3TIM1",98,0)
 S ORGRP(DG)="",STK=1,STK(STK)=DG_"^0",STK(0)=0,MEM=0
"RTN","ORB3TIM1",99,0)
 F I=0:0 S MEM=$O(^ORD(100.98,+STK(STK),1,MEM)) D @$S(+MEM'>0:"POP",1:"PROC") Q:STK<1
"RTN","ORB3TIM1",100,0)
 Q
"RTN","ORB3TIM1",101,0)
POP S STK=STK-1,MEM=$P(STK(STK),"^",2) Q
"RTN","ORB3TIM1",102,0)
PROC S $P(STK(STK),"^",2)=MEM,DG=$P(^ORD(100.98,+STK(STK),1,MEM,0),"^",1)
"RTN","ORB3TIM1",103,0)
 S ORGRP(DG)="",STK=STK+1,STK(STK)=DG_"^0",MEM=0
"RTN","ORB3TIM1",104,0)
 Q
"RTN","ORQQLR")
0^3^B19085376
"RTN","ORQQLR",1,0)
ORQQLR ; slc/CLA - Functions which return patient lab results ;12/15/97 [ 04/02/97  3:46 PM ]
"RTN","ORQQLR",2,0)
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**9,143**;Dec 17, 1997
"RTN","ORQQLR",3,0)
 ;
"RTN","ORQQLR",4,0)
LIST(Y,PT,SDT,EDT,SUBSECT) ; return patient's lab results between start date and stop date for the lab sub section:
"RTN","ORQQLR",5,0)
 N I,J,SUB,INVDT,SEQ,DIFF,X,EXTDT,ORSRV
"RTN","ORQQLR",6,0)
 S J=1,SUB=0,INVDT=0,SEQ=0
"RTN","ORQQLR",7,0)
 S ORSRV=$G(^VA(200,DUZ,5)) I +ORSRV>0 S ORSRV=$P(ORSRV,U)
"RTN","ORQQLR",8,0)
 I '$L($G(SDT))  S Y(1)="^Error in date range." Q
"RTN","ORQQLR",9,0)
 I '$L($G(EDT)) D NOW^%DTC S EDT=+% K %
"RTN","ORQQLR",10,0)
 S:'$L($G(SUBSECT)) SUBSECT="ALL"
"RTN","ORQQLR",11,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR",12,0)
 D RR^LR7OR1(PT,"",SDT,EDT,SUBSECT)
"RTN","ORQQLR",13,0)
 F  S SUB=$O(^TMP("LRRR",$J,PT,SUB)) Q:SUB=""  D
"RTN","ORQQLR",14,0)
 .S INVDT=0 F  S INVDT=$O(^TMP("LRRR",$J,PT,SUB,INVDT)) Q:INVDT=""  D
"RTN","ORQQLR",15,0)
 ..S SEQ=0 F  S SEQ=$O(^TMP("LRRR",$J,PT,SUB,INVDT,SEQ)) Q:SEQ=""!(SEQ<1)  D
"RTN","ORQQLR",16,0)
 ...S X=^(SEQ),Y(J)=$P(X,U)_U_$P(X,U,15)_U_$P(X,U,2)_U_$P(X,U,4)_U_$P(X,U,3)_U
"RTN","ORQQLR",17,0)
 ...S EXTDT=$$EXTERNAL^DILFD(4.302,.01,"",9999999-INVDT),Y(J)=Y(J)_EXTDT
"RTN","ORQQLR",18,0)
 ...S J=J+1
"RTN","ORQQLR",19,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR",20,0)
 S:+$G(Y(1))<1 Y(1)="^No results found."
"RTN","ORQQLR",21,0)
 Q
"RTN","ORQQLR",22,0)
 ;
"RTN","ORQQLR",23,0)
ORDER(Y,PATIENT,ORDER) ; return patient's lab results for an order:
"RTN","ORQQLR",24,0)
 N RSLT
"RTN","ORQQLR",25,0)
 S RSLT=$$GETDATA^OCXCACHE(.Y,"ORDERC^ORQQLR(.OCXDATA,"_PATIENT_","_ORDER_")",PATIENT,)
"RTN","ORQQLR",26,0)
 Q
"RTN","ORQQLR",27,0)
 ;
"RTN","ORQQLR",28,0)
ORDERC(Y,PATIENT,ORDER) ; return patient's lab results for an order:
"RTN","ORQQLR",29,0)
 N SUB,INVDT,SEQ,RESULT,J,LRORD S SUB="",INVDT=0,SEQ=0,J=1
"RTN","ORQQLR",30,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR",31,0)
 S LRORD=$G(^OR(100,+ORDER,4))
"RTN","ORQQLR",32,0)
 Q:'$L(LRORD)
"RTN","ORQQLR",33,0)
 D RR^LR7OR1(PATIENT,LRORD,"","","","","")
"RTN","ORQQLR",34,0)
 S SUB=$O(^TMP("LRRR",$J,PATIENT,SUB)) Q:SUB=""
"RTN","ORQQLR",35,0)
 S INVDT=$O(^TMP("LRRR",$J,PATIENT,SUB,INVDT)) Q:'INVDT
"RTN","ORQQLR",36,0)
 F  S SEQ=$O(^TMP("LRRR",$J,PATIENT,SUB,INVDT,SEQ)) Q:'SEQ  D
"RTN","ORQQLR",37,0)
 .S RESULT=^(SEQ),Y(J)=$P(RESULT,U)_U_$P(RESULT,U,15)_U_$P(RESULT,U,2)_U_$P(RESULT,U,4)_U_$P(RESULT,U,3)_U_$P(RESULT,U,5)_U_INVDT,J=J+1
"RTN","ORQQLR",38,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR",39,0)
 Q
"RTN","ORQQLR",40,0)
DETAIL(LST,DFN,ORDER) ; return lab results for an order
"RTN","ORQQLR",41,0)
 N LRORD,SUB,IDT,I,DATE,FLAG,REF,ILST
"RTN","ORQQLR",42,0)
 S LST(1)="No detailed information found.",ILST=0
"RTN","ORQQLR",43,0)
 S LRORD=$G(^OR(100,+ORDER,4))
"RTN","ORQQLR",44,0)
 Q:'$L(LRORD)
"RTN","ORQQLR",45,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR",46,0)
 D RR^LR7OR1(DFN,LRORD,"","","","","")
"RTN","ORQQLR",47,0)
 S SUB="" F  S SUB=$O(^TMP("LRRR",$J,DFN,SUB)) Q:SUB=""  D
"RTN","ORQQLR",48,0)
 . S IDT=0 F  S IDT=$O(^TMP("LRRR",$J,DFN,SUB,IDT)) Q:'IDT  D
"RTN","ORQQLR",49,0)
 . . S I=0 F  S I=$O(^TMP("LRRR",$J,DFN,SUB,IDT,I)) Q:'I  S X=^(I) D
"RTN","ORQQLR",50,0)
 . . . S DATE=$$FMTE^XLFDT(9999999-IDT),FLAG=$P(X,U,3)
"RTN","ORQQLR",51,0)
 . . . S REF=$P(X,U,5)
"RTN","ORQQLR",52,0)
 . . . S:$L(REF) REF="("_$P(X,U,5)_")"
"RTN","ORQQLR",53,0)
 . . . S X=$P(X,U,15)_U_$P(X,U,2)_U_$P(X,U,4)_U_FLAG_U_DATE_U_REF
"RTN","ORQQLR",54,0)
 . . . S X=$$TABPIECE(X,"1,2,3,4,5,6","9,18,24,27,50")
"RTN","ORQQLR",55,0)
 . . . S ILST=ILST+1,LST(ILST)=X
"RTN","ORQQLR",56,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR",57,0)
 Q
"RTN","ORQQLR",58,0)
TABPIECE(X,PIECES,TABS) ; return pieces with withspace between them
"RTN","ORQQLR",59,0)
 N I,J,Y,APIECE S Y=""
"RTN","ORQQLR",60,0)
 F I=1:1:$L(PIECES,",") S APIECE=+$P(PIECES,",",I) D
"RTN","ORQQLR",61,0)
 . S Y=Y_$P(X,U,APIECE)
"RTN","ORQQLR",62,0)
 . F J=$L(Y):1:+$P(TABS,",",I) S Y=Y_" "
"RTN","ORQQLR",63,0)
 Q Y
"RTN","ORQQLR",64,0)
ZDETAIL(Y,PATIENT,ORDER) ; return detailed, narrative results for an order:
"RTN","ORQQLR",65,0)
 N CR,J,SUB,INVDT,SEQ,RESULT,EXTDT,FLAG,LRORD
"RTN","ORQQLR",66,0)
 S CR=$CHAR(13),J=1,SUB="",INVDT=0,SEQ=0
"RTN","ORQQLR",67,0)
 S LRORD=$$OETOLAB^ORQQLR1(+ORDER)
"RTN","ORQQLR",68,0)
 I '$L($G(LRORD)) S Y(J)="No detailed information found." Q
"RTN","ORQQLR",69,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR",70,0)
 D RR^LR7OR1(PATIENT,LRORD,"","","","","")
"RTN","ORQQLR",71,0)
 S SUB=$O(^TMP("LRRR",$J,PATIENT,SUB))
"RTN","ORQQLR",72,0)
 I '$L($G(SUB)) S Y(J)="No detailed information found." Q
"RTN","ORQQLR",73,0)
 S INVDT=$O(^TMP("LRRR",$J,PATIENT,SUB,INVDT))
"RTN","ORQQLR",74,0)
 I '$L($G(INVDT)) S Y(J)="No detailed information found." Q
"RTN","ORQQLR",75,0)
 F  S SEQ=$O(^TMP("LRRR",$J,PATIENT,SUB,INVDT,SEQ)) Q:'SEQ  D
"RTN","ORQQLR",76,0)
 .S RESULT=^(SEQ),Y(J)=$P(RESULT,U,15)_" "_$P(RESULT,U,2)_" "_$P(RESULT,U,4),FLAG=$P(RESULT,U,3)
"RTN","ORQQLR",77,0)
 .S Y(J)=Y(J)_$S($L($G(FLAG)):" "_FLAG,1:"")
"RTN","ORQQLR",78,0)
 .S EXTDT=$$EXTERNAL^DILFD(4.302,.01,"",9999999-INVDT)
"RTN","ORQQLR",79,0)
 .S Y(J)=Y(J)_" "_EXTDT_" (ref. "_$P(RESULT,U,5)_")",J=J+1
"RTN","ORQQLR",80,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR",81,0)
 Q
"RTN","ORQQLR",82,0)
SROUT(ORY) ;return lab results search date range for an outpatient
"RTN","ORQQLR",83,0)
 N DIFF,SDT,EDT,ORSRV
"RTN","ORQQLR",84,0)
 S ORSRV=$G(^VA(200,DUZ,5)) I +ORSRV>0 S ORSRV=$P(ORSRV,U)
"RTN","ORQQLR",85,0)
 S DIFF=$$GET^XPAR("USR^SRV.`"_+$G(ORSRV)_"^DIV^SYS^PKG","ORQQLR SEARCH RANGE OUTPT",1,"E")
"RTN","ORQQLR",86,0)
 S:+$G(DIFF)<1 DIFF=14  ;if no default defined use 14 days
"RTN","ORQQLR",87,0)
 S ORY=DIFF
"RTN","ORQQLR",88,0)
 Q
"RTN","ORQQLR",89,0)
SRIN(ORY,ORPT) ;return lab results search date range for an inpatient
"RTN","ORQQLR",90,0)
 N DIFF,SDT,EDT,ORSRV,ORLOC
"RTN","ORQQLR",91,0)
 ;
"RTN","ORQQLR",92,0)
 ;get patient's location flag (INPATIENT ONLY - outpt locations cannot be
"RTN","ORQQLR",93,0)
 ;reliably determined, and many simultaneous outpt locations can occur):
"RTN","ORQQLR",94,0)
 I +$G(ORPT)>0 D
"RTN","ORQQLR",95,0)
 .N DFN S DFN=ORPT,VA200="" D OERR^VADPT
"RTN","ORQQLR",96,0)
 .I +$G(VAIN(4))>0 S ORLOC=+$G(^DIC(42,+$G(VAIN(4)),44))
"RTN","ORQQLR",97,0)
 .K VA200,VAIN
"RTN","ORQQLR",98,0)
 ;
"RTN","ORQQLR",99,0)
 S ORSRV=$G(^VA(200,DUZ,5)) I +ORSRV>0 S ORSRV=$P(ORSRV,U)
"RTN","ORQQLR",100,0)
 S DIFF=$$GET^XPAR("USR^LOC.`"_$G(ORLOC)_"^SRV.`"_+$G(ORSRV)_"^DIV^SYS^PKG","ORQQLR SEARCH RANGE INPT",1,"E")
"RTN","ORQQLR",101,0)
 S:+$G(DIFF)<1 DIFF=2  ;if no default defined use 2 days
"RTN","ORQQLR",102,0)
 S ORY=DIFF
"RTN","ORQQLR",103,0)
 Q
"RTN","ORQQLR1")
0^4^B15053517
"RTN","ORQQLR1",1,0)
ORQQLR1 ; slc/CLA - Extrinsic functions and procedures which return patient lab results ;7/23/96  12:47
"RTN","ORQQLR1",2,0)
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**6,51,74,143**;Dec 17, 1997
"RTN","ORQQLR1",3,0)
OETOLAB(ORNUM) ;extrinsic funct to get a lab order number from an oe/rr number
"RTN","ORQQLR1",4,0)
 N LRNUM
"RTN","ORQQLR1",5,0)
 S LRNUM=$G(^OR(100,ORNUM,4))
"RTN","ORQQLR1",6,0)
 Q +LRNUM
"RTN","ORQQLR1",7,0)
 ;
"RTN","ORQQLR1",8,0)
PRINTNAM(LRIEN) ;extrinsic function to return the print name for an entry in the Lab file [#60]
"RTN","ORQQLR1",9,0)
 Q:+$G(LRIEN)<1 ""
"RTN","ORQQLR1",10,0)
 N NODE,NAME
"RTN","ORQQLR1",11,0)
 S NODE=$G(^LAB(60,LRIEN,.1))
"RTN","ORQQLR1",12,0)
 Q:'$L(NODE) ""
"RTN","ORQQLR1",13,0)
 S NAME=$P(NODE,U)
"RTN","ORQQLR1",14,0)
 Q NAME
"RTN","ORQQLR1",15,0)
 ;
"RTN","ORQQLR1",16,0)
OIRES(PT,OILR,SPEC) ;extrinsic function to return pt's most recent lab results for a lab orderable item in the format:
"RTN","ORQQLR1",17,0)
 ; test id^abbrev test name^result^units^flag^collection d/t
"RTN","ORQQLR1",18,0)
 N RSLT,ORZ
"RTN","ORQQLR1",19,0)
 S ORZ=""
"RTN","ORQQLR1",20,0)
 S RSLT=$$GETDATA^OCXCACHE(.ORZ,"$$OIRESC^ORQQLR1("_PT_","_OILR_","_SPEC_")",PT,)
"RTN","ORQQLR1",21,0)
 Q ORZ
"RTN","ORQQLR1",22,0)
 ;
"RTN","ORQQLR1",23,0)
OIRESC(PT,OILR,SPEC) ;extrinsic function to return pt's most recent lab results for a lab orderable item in the format:
"RTN","ORQQLR1",24,0)
 ; test id^abbrev test name^result^units^flag^collection d/t
"RTN","ORQQLR1",25,0)
 N ORY,ORX,ORN,ORLR,SUB,INVDT,SEQ,ORDG,RESULT
"RTN","ORQQLR1",26,0)
 S SUB="",INVDT=0,SEQ=0,ORY=""
"RTN","ORQQLR1",27,0)
 ;check to make sure the OI is in DG lab
"RTN","ORQQLR1",28,0)
 Q:'$L($G(PT))!('$L($G(OILR))) ORY
"RTN","ORQQLR1",29,0)
 Q:'$L($G(^ORD(101.43,OILR,0))) ORY
"RTN","ORQQLR1",30,0)
 I +$G(SPEC)<1 S SPEC=""
"RTN","ORQQLR1",31,0)
 S ORDG=$$DG^ORQOR1("LAB")
"RTN","ORQQLR1",32,0)
 Q:'$L($G(ORDG)) ORY
"RTN","ORQQLR1",33,0)
 Q:$P(^ORD(101.43,OILR,0),U,5)'=ORDG ORY  ;quit if display grp is not lab
"RTN","ORQQLR1",34,0)
 ;get lab test ien
"RTN","ORQQLR1",35,0)
 S ORX=$P(^ORD(101.43,OILR,0),U,2)
"RTN","ORQQLR1",36,0)
 S ORLR=$S(ORX["~":$P(ORX,"~"),1:$P(ORX,";"))
"RTN","ORQQLR1",37,0)
 ;get lab results
"RTN","ORQQLR1",38,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR1",39,0)
 D RR^LR7OR1(PT,"","","","",ORLR,"L",1,SPEC) I $D(^TMP("LRRR",$J,PT)) D
"RTN","ORQQLR1",40,0)
 .S SUB=$O(^TMP("LRRR",$J,PT,SUB)) Q:SUB=""
"RTN","ORQQLR1",41,0)
 .S INVDT=$O(^TMP("LRRR",$J,PT,SUB,INVDT)) Q:'INVDT
"RTN","ORQQLR1",42,0)
 .S SEQ=$O(^TMP("LRRR",$J,PT,SUB,INVDT,SEQ)) Q:'SEQ  D
"RTN","ORQQLR1",43,0)
 ..S RESULT=^(SEQ),ORY=$P(RESULT,U)_U_$P(RESULT,U,15)_U_$P(RESULT,U,2)_U_$P(RESULT,U,4)_U_$P(RESULT,U,3)_U_$P(RESULT,U,5)_U_(9999999-INVDT)
"RTN","ORQQLR1",44,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR1",45,0)
 Q ORY
"RTN","ORQQLR1",46,0)
 ;
"RTN","ORQQLR1",47,0)
NATL(PT,NID,SPEC) ;extrinsic function to return pt's most recent lab results for a lab national id in the format:
"RTN","ORQQLR1",48,0)
 ; test id^abbrev test name^result^units^flag^collection d/t
"RTN","ORQQLR1",49,0)
 N RSLT,ORZ
"RTN","ORQQLR1",50,0)
 S ORZ=""
"RTN","ORQQLR1",51,0)
 S RSLT=$$GETDATA^OCXCACHE(.ORZ,"$$NATLC^ORQQLR1("_PT_","_NID_","_SPEC_")",PT,)
"RTN","ORQQLR1",52,0)
 Q ORZ
"RTN","ORQQLR1",53,0)
 ;
"RTN","ORQQLR1",54,0)
NATLC(PT,NID,SPEC) ;extrinsic function to return pt's most recent lab results for a lab national id in the format:
"RTN","ORQQLR1",55,0)
 ; test id^abbrev test name^result^units^flag^collection d/t
"RTN","ORQQLR1",56,0)
 N ORY,ORX,ORN,ORLR,SUB,INVDT,SEQ,ORDG
"RTN","ORQQLR1",57,0)
 S SUB="",INVDT=0,SEQ=0,ORY=""
"RTN","ORQQLR1",58,0)
 I +$G(SPEC)<1 S SPEC=""
"RTN","ORQQLR1",59,0)
 ;get lab results
"RTN","ORQQLR1",60,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR1",61,0)
 D RR^LR7OR1(PT,"","","","",NID,"N",1,SPEC) I $D(^TMP("LRRR",$J,PT)) D
"RTN","ORQQLR1",62,0)
 .S SUB=$O(^TMP("LRRR",$J,PT,SUB)) Q:SUB=""
"RTN","ORQQLR1",63,0)
 .S INVDT=$O(^TMP("LRRR",$J,PT,SUB,INVDT)) Q:'INVDT
"RTN","ORQQLR1",64,0)
 .S SEQ=$O(^TMP("LRRR",$J,PT,SUB,INVDT,SEQ)) Q:'SEQ  D
"RTN","ORQQLR1",65,0)
 ..S RESULT=^(SEQ),ORY=$P(RESULT,U)_U_$P(RESULT,U,15)_U_$P(RESULT,U,2)_U_$P(RESULT,U,4)_U_$P(RESULT,U,3)_U_$P(RESULT,U,5)_U_(9999999-INVDT)
"RTN","ORQQLR1",66,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR1",67,0)
 Q ORY
"RTN","ORQQLR1",68,0)
 ;
"RTN","ORQQLR1",69,0)
LOCL(PT,LID,SPEC) ;extrinsic function to return pt's most recent lab results for a lab local id in the format:
"RTN","ORQQLR1",70,0)
 ; test id^abbrev test name^result^units^flag^collection d/t
"RTN","ORQQLR1",71,0)
 N RSLT,ORZ
"RTN","ORQQLR1",72,0)
 S ORZ=""
"RTN","ORQQLR1",73,0)
 S RSLT=$$GETDATA^OCXCACHE(.ORZ,"$$LOCLC^ORQQLR1("_PT_","_LID_","_SPEC_")",PT,)
"RTN","ORQQLR1",74,0)
 Q ORZ
"RTN","ORQQLR1",75,0)
 ;
"RTN","ORQQLR1",76,0)
LOCLC(PT,LID,SPEC) ;extrinsic function to return pt's most recent lab results for a lab local id in the format:
"RTN","ORQQLR1",77,0)
 ; test id^abbrev test name^result^units^flag^collection d/t
"RTN","ORQQLR1",78,0)
 N ORY,ORX,SUB,INVDT,SEQ,RESULT
"RTN","ORQQLR1",79,0)
 S SUB="",INVDT=0,SEQ=0,ORY=""
"RTN","ORQQLR1",80,0)
 ;get lab results
"RTN","ORQQLR1",81,0)
 I +$G(SPEC)<1 S SPEC=""
"RTN","ORQQLR1",82,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR1",83,0)
 D RR^LR7OR1(PT,"","","","",LID,"L",1,SPEC) I $D(^TMP("LRRR",$J,PT)) D
"RTN","ORQQLR1",84,0)
 .S SUB=$O(^TMP("LRRR",$J,PT,SUB)) Q:SUB=""
"RTN","ORQQLR1",85,0)
 .S INVDT="" F  S INVDT=$O(^TMP("LRRR",$J,PT,SUB,INVDT)) Q:'INVDT  D
"RTN","ORQQLR1",86,0)
 ..S SEQ="" F  S SEQ=$O(^TMP("LRRR",$J,PT,SUB,INVDT,SEQ)) Q:'SEQ!(+$G(RESULT)>0)  D
"RTN","ORQQLR1",87,0)
 ...S ORX=^(SEQ)
"RTN","ORQQLR1",88,0)
 ...I $P(ORX,U,2)'="canc" D  ;if results were not cancelled in lab:
"RTN","ORQQLR1",89,0)
 ....S RESULT=$P(ORX,U,2)
"RTN","ORQQLR1",90,0)
 ....S ORY=$P(ORX,U)_U_$P(ORX,U,15)_U_$P(ORX,U,2)_U_$P(ORX,U,4)
"RTN","ORQQLR1",91,0)
 ....S ORY=ORY_U_$P(ORX,U,3)_U_$P(ORX,U,5)_U_(9999999-INVDT)
"RTN","ORQQLR1",92,0)
 K ^TMP("LRRR",$J)
"RTN","ORQQLR1",93,0)
 Q ORY
"RTN","ORQQLR1",94,0)
 ;
"RTN","ORQQLR1",95,0)
LOCLFORM(PT,LID,SPEC) ;extrinsic function to return formatted most recnt lab
"RTN","ORQQLR1",96,0)
 ;rtn format: 1 (if results)^<print name> <value> <units> <high/low flag>
"RTN","ORQQLR1",97,0)
 ;               (<reference range>) <collection date/time>
"RTN","ORQQLR1",98,0)
 N FRCNT,X
"RTN","ORQQLR1",99,0)
 S X=$$LOCL(PT,LID,SPEC)
"RTN","ORQQLR1",100,0)
 Q:'$L(X) "^No results found."
"RTN","ORQQLR1",101,0)
 S FRCNT="1^"_$P(X,U,2)_" "_$P(X,U,3)_" "_$P(X,U,4)_" "_$P(X,U,5)
"RTN","ORQQLR1",102,0)
 S FRCNT=FRCNT_" ("_$P(X,U,6)_") "_$$FMTE^XLFDT($P(X,U,7),"2P")
"RTN","ORQQLR1",103,0)
 Q FRCNT
"VER")
8.0^22.0
**END**
**END**
